import { css, cx } from '@emotion/css';
import { Children, type ReactNode, useCallback, useEffect, useMemo, useRef, useState } from 'react';

import { useAssistant } from '@grafana/assistant';
import { type DataSourceInstanceSettings, type GrafanaTheme2, type SelectableValue } from '@grafana/data';
import { Trans, t } from '@grafana/i18n';
import { getDataSourceSrv, locationService, reportInteraction } from '@grafana/runtime';
import {
  Alert,
  Badge,
  Button,
  CollapsableSection,
  Field,
  Icon,
  type IconName,
  Input,
  Modal,
  MultiSelect,
  RadioButtonGroup,
  Spinner,
  Stack,
  Text,
  TextArea,
  Tooltip,
  useStyles2,
} from '@grafana/ui';
import { useTemplateDashboardsAvailability } from 'app/features/dashboard/dashgrid/DashboardLibrary/hooks/useTemplateDashboardsAvailability';

import { analyzeDatasource } from './analysis';
import { buildCapabilityChips, type CapabilityChip } from './capabilityChips';
import { buildDomainGroups, type DomainGroup, domainGroupsFromCategories } from './domains';
import { useDashboardGenerator } from './generateDashboard';
import { useIntentSuggestions } from './generateIntents';
import { putGeneratedDashboard } from './generatedDashboardRegistry';
import { getIntentsForLabel } from './intents';
import {
  type AnalysisStatus,
  type CustomizationOptions,
  type DashboardIntent,
  type DashboardOrientation,
  type DatasourceAnalysis,
  type ExplorationOption,
  type IntentGenerationContext,
  type IntentSelection,
  type WizardMode,
} from './types';

/** Composite key uniquely identifying a (dimension, intent) pick across all groups. */
function selectionKey(option: ExplorationOption, intent: DashboardIntent): string {
  return `${option.labelKey}::${intent.id}`;
}

/**
 * Defaults applied when the user opens the modal — they can be overridden inline via
 * the "Advanced" section. Kept alongside the modal so the mapping stays visible.
 */
const DEFAULT_CUSTOMIZATION: CustomizationOptions = {
  additionalNotes: '',
};

/**
 * Default entry-path defaults. `beginner` keeps the surface small (curated top
 * picks, one-click); `expert` opens up multi-select and shows the full generated
 * intent list. `technical` mirrors the previous SRE-focused default.
 */
const DEFAULT_MODE: WizardMode = 'beginner';
const DEFAULT_ORIENTATION: DashboardOrientation = 'technical';

export interface GenerateDashboardModalProps {
  onDismiss: () => void;
}

/**
 * "Generate a dashboard" modal, launched from the header Plus menu.
 *
 * Design goals:
 * - Single scrollable screen — no wizard steps, no back button, no context loss.
 * - Data-driven: both the CATEGORIES and the INTENTS the user picks from are
 *   generated by the Assistant from the datasource's actual metrics / logs /
 *   labels ("Apps & services", "Databases", "Business KPIs" — never raw
 *   dimensions). Each card carries its own pivot label; each pick becomes a tab.
 * - Two entry paths: Beginner (curated top picks, single-click) vs Expert (full
 *   generated catalogue, multi-select). A Focus control (Technical / Business /
 *   Both) plus a free-form refinement input let the user steer what the LLM
 *   proposes without opening any hidden panel.
 * - Detected capabilities are visible up-front so the user can verify the wizard
 *   understood their stack before committing.
 * - "Advanced" (additional notes) stays always-available at the bottom of the
 *   same screen instead of being buried behind a step.
 *
 * The entire generation flow is headless: no Assistant sidebar. When the user
 * hits Generate (with one or more picks, or none for a default overview):
 * 1. `useDashboardGenerator` runs an inline LLM call producing a compact recipe.
 * 2. `composeRecipe` composes a strict `DashboardV2Spec` from that recipe locally.
 * 3. The spec is stashed in an in-memory registry.
 * 4. We route to `/dashboard/new?fromGenerator=<key>` and the dashboard scene
 *    picks the spec up as an unsaved dashboard the user can review and save.
 */
export function GenerateDashboardModal({ onDismiss }: GenerateDashboardModalProps) {
  const styles = useStyles2(getStyles);

  const [datasources, setDatasources] = useState<DataSourceInstanceSettings[]>(() => {
    const initial = getDataSourceSrv().getInstanceSettings();
    return initial ? [initial] : [];
  });
  const [analysis, setAnalysis] = useState<DatasourceAnalysis | undefined>();
  const [analysisStatus, setAnalysisStatus] = useState<AnalysisStatus>('idle');
  const [analysisError, setAnalysisError] = useState<string | undefined>();

  const [customization, setCustomization] = useState<CustomizationOptions>(DEFAULT_CUSTOMIZATION);
  const [generationErrorMessage, setGenerationErrorMessage] = useState<string | undefined>();
  // Multi-select state. Keys are `${labelKey}::${intentId}` so a pick is unique
  // across groups; we derive the ordered `selectedSelections` list from the union
  // of everything currently on screen.
  const [selectedKeys, setSelectedKeys] = useState<Set<string>>(() => new Set());

  // Wizard mode / orientation / refinement — the three inputs that shape which
  // categories and intents the data-driven generator proposes. `mode` also
  // drives the modal's UI density (beginner shrinks to a curated top set,
  // expert opens the full generated list with multi-select).
  const [mode, setMode] = useState<WizardMode>(DEFAULT_MODE);
  const [orientation, setOrientation] = useState<DashboardOrientation>(DEFAULT_ORIENTATION);
  const [refinement, setRefinement] = useState<string>('');

  const { isAvailable: isAssistantAvailable, isLoading: isAssistantLoading } = useAssistant();
  const { isAvailable: areTemplatesAvailable } = useTemplateDashboardsAvailability();
  const analysisAbortRef = useRef<AbortController | null>(null);
  const intentSuggestions = useIntentSuggestions();
  const dashboardGenerator = useDashboardGenerator();

  const primaryDatasource: DataSourceInstanceSettings | undefined = datasources[0];
  const isGenerating = dashboardGenerator.isLoading;

  useEffect(() => {
    reportInteraction('grafana_generate_dashboard_modal_opened');
  }, []);

  useEffect(() => {
    return () => {
      analysisAbortRef.current?.abort();
    };
  }, []);

  const runAnalysis = useCallback(async (ds: DataSourceInstanceSettings) => {
    analysisAbortRef.current?.abort();
    const controller = new AbortController();
    analysisAbortRef.current = controller;

    setAnalysisStatus('loading');
    setAnalysisError(undefined);
    setAnalysis(undefined);
    // A new datasource means a new set of dimensions/intents — drop any prior picks.
    setSelectedKeys(new Set());

    try {
      const analysed = await analyzeDatasource(ds);
      if (controller.signal.aborted) {
        return;
      }
      setAnalysis(analysed);
      setAnalysisStatus('ready');
    } catch (err) {
      if (controller.signal.aborted) {
        return;
      }
      setAnalysisError(
        err instanceof Error
          ? err.message
          : t('dashboard-generate.errors.analysis-failed', 'Failed to analyse the selected data source.')
      );
      setAnalysisStatus('error');
    }
  }, []);

  // Kick off analysis whenever the primary datasource changes (including the initial default).
  const analysedForUid = useRef<string | undefined>();
  useEffect(() => {
    if (!primaryDatasource) {
      setAnalysisStatus('idle');
      setAnalysis(undefined);
      return;
    }
    if (analysedForUid.current === primaryDatasource.uid) {
      return;
    }
    analysedForUid.current = primaryDatasource.uid;
    runAnalysis(primaryDatasource);
  }, [primaryDatasource, runAnalysis]);

  // Fire a single datasource-wide suggestions pass once analysis completes. The
  // suggestions call is now the primary source of categories AND intents (see
  // `generateIntents.ts`) — everything static in `intents.ts` / `domains.ts` is
  // fallback-only. We re-run when `mode`/`orientation`/`refinement` change since
  // those steer the LLM's output.
  //
  // Refinement is applied on request (only re-runs on submit) rather than every
  // keystroke, so a slow LLM call can't hold the UI hostage while the user is
  // still typing. That's handled by the "Update suggestions" button below.
  const runSuggestions = useCallback(() => {
    if (!primaryDatasource || !analysis || analysis.options.length === 0 || !isAssistantAvailable) {
      return;
    }
    intentSuggestions.request({
      primaryDatasource,
      analysis,
      existingTitles: [],
      context: { mode, orientation, refinement },
    });
    // Same rationale as the analysis effect: intentSuggestions has stable methods.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [primaryDatasource, analysis, isAssistantAvailable, mode, orientation, refinement]);

  useEffect(() => {
    if (!primaryDatasource || !analysis || analysis.options.length === 0 || !isAssistantAvailable) {
      return;
    }
    runSuggestions();
    // We intentionally exclude `intentSuggestions` and `refinement` from the dep array —
    // refinement is applied via the explicit "Update suggestions" button so a
    // slow LLM call can't fire on every keystroke.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [primaryDatasource, analysis, isAssistantAvailable, mode, orientation]);

  // Watch the headless generator. When a spec arrives, stash it and route the
  // user to `/dashboard/new`. On error, surface it inline (staying on the modal).
  useEffect(() => {
    if (dashboardGenerator.result) {
      const key = putGeneratedDashboard(dashboardGenerator.result.spec);
      const { recipe, source } = dashboardGenerator.result;
      // Engine builds don't emit a recipe — the plugin returns a V2 spec
      // directly. Fall back to zeros so the event still fires with meaningful
      // dimensions (source + spec presence) even when panel/section counts
      // aren't available.
      const flatPanelCount = recipe?.panels?.length ?? 0;
      const sectionPanelCount = (recipe?.sections ?? []).reduce((sum, section) => {
        const rowPanels = (section.rows ?? []).reduce((n, row) => n + (row.panels?.length ?? 0), 0);
        return sum + (section.panels?.length ?? 0) + rowPanels;
      }, 0);
      reportInteraction('grafana_generate_dashboard_spec_produced', {
        source,
        panelCount: sectionPanelCount + flatPanelCount,
        sectionCount: recipe?.sections?.length ?? 0,
        variableCount: recipe?.variables?.length ?? 0,
      });
      dashboardGenerator.reset();
      onDismiss();
      locationService.push({ pathname: '/dashboard/new', search: `?fromGenerator=${key}` });
      return;
    }
    if (dashboardGenerator.error) {
      setGenerationErrorMessage(
        dashboardGenerator.error.message ||
          t('dashboard-generate.errors.generation-failed', 'The Assistant could not generate a dashboard.')
      );
    }
  }, [dashboardGenerator, onDismiss]);

  const onDatasourcesChange = useCallback((selected: DataSourceInstanceSettings[]) => {
    setDatasources(selected);
    reportInteraction('grafana_generate_dashboard_datasources_changed', {
      count: selected.length,
      datasourceType: selected[0]?.type,
    });
  }, []);

  const runGeneration = useCallback(
    (selections: IntentSelection[], intentSource: 'overview' | 'single' | 'multi') => {
      if (!primaryDatasource || !analysis || selections.length === 0) {
        return;
      }
      setGenerationErrorMessage(undefined);

      const primary = selections[0];
      const context: IntentGenerationContext = { mode, orientation, refinement };
      reportInteraction('grafana_generate_dashboard_generation_started', {
        datasourceType: primaryDatasource.type,
        // Legacy scalar fields kept for backwards-compat — driven by the primary
        // (first-selected) pick so single-selection requests keep the old shape.
        labelKey: primary.option.labelKey,
        intentId: primary.intent.id,
        intentSource,
        intentCount: selections.length,
        intentIds: selections.map((s) => s.intent.id).join(','),
        dimensions: Array.from(new Set(selections.map((s) => s.option.labelKey))).join(','),
        hasAdditionalNotes: customization.additionalNotes.trim().length > 0,
        additionalDatasourceCount: Math.max(0, datasources.length - 1),
        mode,
        orientation,
        hasRefinement: refinement.trim().length > 0,
      });

      dashboardGenerator.generate({
        selections,
        primaryDatasource,
        additionalDatasources: datasources.slice(1),
        analysis,
        customization,
        context,
      });
    },
    [analysis, customization, dashboardGenerator, datasources, mode, orientation, primaryDatasource, refinement]
  );

  const onToggleSelection = useCallback((selection: IntentSelection) => {
    const key = selectionKey(selection.option, selection.intent);
    setSelectedKeys((prev) => {
      const next = new Set(prev);
      if (next.has(key)) {
        next.delete(key);
      } else {
        next.add(key);
      }
      return next;
    });
    reportInteraction('grafana_generate_dashboard_intent_toggled', {
      intentId: selection.intent.id,
      labelKey: selection.option.labelKey,
    });
  }, []);

  const onClearSelection = useCallback(() => {
    setSelectedKeys(new Set());
  }, []);

  /**
   * Fallback overview pick used when the primary CTA fires without any selection.
   * We pick the top-ranked capability/category intent on the top-ranked dimension so
   * the user always gets a sensible default. The "Additional notes" field under
   * Advanced options is the intended place for freeform steering — the LLM prompt
   * already layers notes on top of the intent's guidance.
   */
  const buildOverviewFallback = useCallback((): IntentSelection | undefined => {
    if (!primaryDatasource || !analysis) {
      return undefined;
    }
    const option: ExplorationOption = analysis.options[0] ?? {
      id: analysis.labelKeys[0] ?? 'service',
      labelKey: analysis.labelKeys[0] ?? 'service',
      title: t('dashboard-generate.scratch.fallback-title', 'Overview'),
      description: t('dashboard-generate.scratch.fallback-description', 'General-purpose overview'),
    };

    const intent: DashboardIntent = getIntentsForLabel(option.labelKey, analysis.capabilities)[0] ?? {
      id: 'overview',
      title: t('dashboard-generate.scratch.fallback-intent-title', 'Overview'),
      description: t(
        'dashboard-generate.scratch.fallback-intent-description',
        'A general-purpose starting point for this data source.'
      ),
      // Prompt for the LLM — technical guidance string, never rendered.
      guidance:
        'Pick 6–10 signals from the datasource covering activity rates, error indicators, latencies, and resource usage. Add one template variable for the primary label. Do not invent metric names.',
      icon: 'chart-line',
    };

    return { intent, option };
  }, [analysis, primaryDatasource]);

  const onUseTemplate = useCallback(() => {
    reportInteraction('grafana_generate_dashboard_use_template');
    locationService.push('/dashboards?templateDashboards=true&source=generateDashboardModal');
    onDismiss();
  }, [onDismiss]);

  const onRetryGeneration = useCallback(() => {
    setGenerationErrorMessage(undefined);
    dashboardGenerator.reset();
  }, [dashboardGenerator]);

  const onRetryAnalysis = useCallback(() => {
    if (primaryDatasource) {
      runAnalysis(primaryDatasource);
    }
  }, [primaryDatasource, runAnalysis]);

  const chips = useMemo<CapabilityChip[]>(
    () => (analysis?.capabilities ? buildCapabilityChips(analysis.capabilities) : []),
    [analysis?.capabilities]
  );

  // Primary path: use the LLM-generated categories. Falls back to the static
  // domain builder (capabilities + label heuristics) only when the LLM couldn't
  // deliver anything — that keeps the modal useful even when the Assistant is
  // off or the generation errored out.
  const generatedCategoryGroups = useMemo<DomainGroup[]>(() => {
    return domainGroupsFromCategories(intentSuggestions.categories);
  }, [intentSuggestions.categories]);

  const fallbackDomainGroups = useMemo<DomainGroup[]>(() => {
    if (!analysis) {
      return [];
    }
    return buildDomainGroups(analysis);
  }, [analysis]);

  // Use generated categories when available, otherwise fall back to the static
  // domain builder. Beginner mode further trims the surface (top curated picks)
  // vs. expert mode (the full generated list).
  const domainGroups = useMemo<DomainGroup[]>(() => {
    const groups = generatedCategoryGroups.length > 0 ? generatedCategoryGroups : fallbackDomainGroups;
    if (mode === 'beginner') {
      // Beginner mode shows a smaller, curated set — the first 3 groups and up
      // to 3 selections per group so the modal reads as a shortlist.
      return groups.slice(0, 3).map((group) => ({ ...group, selections: group.selections.slice(0, 3) }));
    }
    return groups;
  }, [generatedCategoryGroups, fallbackDomainGroups, mode]);

  // Flattened union of everything selectable, in display order. Used to derive
  // the ordered selection and to prune stale keys.
  const allSelections = useMemo<IntentSelection[]>(() => {
    const flat: IntentSelection[] = [];
    for (const group of domainGroups) {
      flat.push(...group.selections);
    }
    return flat;
  }, [domainGroups]);

  // Drop any selected key that's no longer on screen (e.g. suggestions reloaded).
  useEffect(() => {
    const availableKeys = new Set(allSelections.map((s) => selectionKey(s.option, s.intent)));
    setSelectedKeys((prev) => {
      if (prev.size === 0) {
        return prev;
      }
      let changed = false;
      const next = new Set<string>();
      for (const key of prev) {
        if (availableKeys.has(key)) {
          next.add(key);
        } else {
          changed = true;
        }
      }
      return changed ? next : prev;
    });
  }, [allSelections]);

  const selectedSelections = useMemo<IntentSelection[]>(
    () => allSelections.filter((s) => selectedKeys.has(selectionKey(s.option, s.intent))),
    [allSelections, selectedKeys]
  );

  const suggestionsFinished = intentSuggestions.status === 'ready' || intentSuggestions.status === 'error';
  const hasAnyIntents = domainGroups.length > 0;

  const canGenerate = isAssistantAvailable && !isGenerating && !!primaryDatasource && analysisStatus === 'ready';

  /**
   * Primary CTA handler. If the user picked one or more intents we honour their
   * selection; otherwise we fall back to a sensible overview so the button always
   * "does something useful".
   */
  const onGenerate = useCallback(() => {
    if (selectedSelections.length > 0) {
      runGeneration(selectedSelections, selectedSelections.length > 1 ? 'multi' : 'single');
      return;
    }
    const fallback = buildOverviewFallback();
    if (fallback) {
      runGeneration([fallback], 'overview');
    }
  }, [buildOverviewFallback, runGeneration, selectedSelections]);

  return (
    <Modal
      isOpen
      onDismiss={onDismiss}
      ariaLabel={t('dashboard-generate.title', 'Generate a dashboard')}
      title={
        <Stack direction="row" alignItems="center" gap={1}>
          <Icon name="ai-sparkle" size="lg" />
          <span>{t('dashboard-generate.title', 'Generate a dashboard')}</span>
        </Stack>
      }
      className={styles.modal}
    >
      <div className={cx(styles.body, isGenerating && styles.bodyBusy)}>
        <Field
          noMargin
          label={t('dashboard-generate.datasource-label', 'Data source')}
          description={t(
            'dashboard-generate.datasource-description',
            'The Assistant will read labels and metric names from these to shape the dashboard.'
          )}
        >
          <DatasourcesPicker selected={datasources} onChange={onDatasourcesChange} disabled={isGenerating} />
        </Field>

        {chips.length > 0 && (
          <div className={styles.chipsRow} data-testid="generate-dashboard-detected-chips">
            <Text variant="bodySmall" color="secondary">
              <Trans i18nKey="dashboard-generate.chips.detected-prefix">Detected in this data source</Trans>
            </Text>
            <div className={styles.chips}>
              {chips.map((chip) => (
                <Badge key={chip.id} icon={chip.icon} color="blue" text={chip.label} />
              ))}
            </div>
          </div>
        )}

        {!isAssistantLoading && !isAssistantAvailable && (
          <Alert severity="warning" title={t('dashboard-generate.no-assistant.title', 'Assistant is unavailable')}>
            <Trans i18nKey="dashboard-generate.no-assistant.body">
              The Grafana Assistant is not configured, so this wizard cannot generate dashboards. Ask an admin to enable
              the Assistant plugin, then try again.
            </Trans>
          </Alert>
        )}

        {analysisStatus === 'loading' && (
          <div className={styles.inlineLoader}>
            <Spinner />
            <Text color="secondary">
              <Trans i18nKey="dashboard-generate.analyzing">Analysing labels on the selected data source…</Trans>
            </Text>
          </div>
        )}

        {analysisStatus === 'error' && (
          <Alert
            severity="warning"
            title={t('dashboard-generate.errors.analysis-title', 'Could not analyse data source')}
          >
            <Stack direction="column" gap={1}>
              <Text>
                {analysisError ??
                  t('dashboard-generate.errors.analysis-generic', 'The wizard could not read from this data source.')}
              </Text>
              <div>
                <Button size="sm" variant="secondary" onClick={onRetryAnalysis}>
                  <Trans i18nKey="dashboard-generate.retry">Try again</Trans>
                </Button>
              </div>
            </Stack>
          </Alert>
        )}

        {analysisStatus === 'ready' && analysis && (
          <>
            {/*
             * Entry-path controls: mode (beginner vs expert) drives the modal's
             * density; orientation (technical/business/both) plus refinement
             * drive which categories + intents the LLM proposes.
             */}
            <WizardControls
              mode={mode}
              orientation={orientation}
              refinement={refinement}
              onModeChange={setMode}
              onOrientationChange={setOrientation}
              onRefinementChange={setRefinement}
              onApplyRefinement={runSuggestions}
              suggestionsLoading={intentSuggestions.isLoading}
              disabled={isGenerating}
              styles={styles}
            />

            <div className={styles.section}>
              <div className={styles.sectionHeader}>
                <Text element="h3" variant="h6">
                  <Trans i18nKey="dashboard-generate.intents.starting-points">Starting points</Trans>
                </Text>
                <Text variant="bodySmall" color="secondary">
                  {mode === 'expert' ? (
                    <Trans i18nKey="dashboard-generate.intents.multi-hint-expert">
                      Pick one or more — each becomes its own tab
                    </Trans>
                  ) : (
                    <Trans i18nKey="dashboard-generate.intents.multi-hint-beginner">
                      Pick a starting point to generate a dashboard
                    </Trans>
                  )}
                </Text>
              </div>

              {/*
               * The LLM-generated categories (or the static fallback groups) are
               * rendered directly. A single "Suggested" bucket no longer exists —
               * everything is grouped by the semantic categories the LLM proposed
               * for THIS datasource ("Apps & services", "Databases", "Business
               * KPIs", …).
               */}
              {intentSuggestions.isLoading && domainGroups.length === 0 && (
                <div className={styles.inlineLoader}>
                  <Spinner size="sm" />
                  <Text color="secondary">
                    <Trans i18nKey="dashboard-generate.intents.tailoring-loader">
                      Finding starting points tailored to your data…
                    </Trans>
                  </Text>
                </div>
              )}

              {domainGroups.map((group, index) => {
                // Only label each card with its pivot when a group actually mixes
                // dimensions (e.g. Kubernetes spans clusters/pods/nodes); when
                // every card shares one pivot the pill is just noise.
                const mixedPivots = new Set(group.selections.map((s) => s.option.labelKey)).size > 1;
                // Open the first group by default so beginners see something
                // populated; the rest stay collapsed so the modal stays scannable.
                const defaultOpen = index === 0;
                return (
                  <IntentGroup
                    key={group.id}
                    title={group.title}
                    icon={group.icon}
                    styles={styles}
                    defaultOpen={defaultOpen}
                    hint={group.samplePreview}
                  >
                    {group.selections.map((selection) => {
                      const key = selectionKey(selection.option, selection.intent);
                      return (
                        <IntentCard
                          key={key}
                          intent={selection.intent}
                          isSuggested={generatedCategoryGroups.length > 0}
                          dimensionTitle={mixedPivots ? selection.option.title : undefined}
                          selected={selectedKeys.has(key)}
                          onToggle={() => onToggleSelection(selection)}
                          disabled={
                            isGenerating ||
                            !isAssistantAvailable ||
                            (mode === 'beginner' && selectedKeys.size >= 1 && !selectedKeys.has(key))
                          }
                          styles={styles}
                        />
                      );
                    })}
                  </IntentGroup>
                );
              })}

              {/*
               * Nothing-to-show state — reached only when suggestions completed but
               * yielded nothing AND there are no curated groups. The primary
               * "Generate an overview" button in the footer still works.
               */}
              {suggestionsFinished && !hasAnyIntents && (
                <Text color="secondary" variant="bodySmall">
                  <Trans i18nKey="dashboard-generate.intents.empty">
                    No curated starting points for this data source yet — hit Generate to get a default overview.
                  </Trans>
                </Text>
              )}
            </div>
          </>
        )}

        <AdvancedOptions value={customization} onChange={setCustomization} styles={styles} />

        {generationErrorMessage && (
          <Alert severity="error" title={t('dashboard-generate.errors.title', 'Something went wrong')}>
            <Stack direction="column" gap={1}>
              <Text>{generationErrorMessage}</Text>
              <div>
                <Button size="sm" variant="secondary" onClick={onRetryGeneration}>
                  <Trans i18nKey="dashboard-generate.dismiss-error">Dismiss</Trans>
                </Button>
              </div>
            </Stack>
          </Alert>
        )}

        {isGenerating && (
          <div className={styles.generatingBanner}>
            <Spinner size="sm" />
            <Stack direction="column" gap={0}>
              <Text weight="medium">
                <Trans i18nKey="dashboard-generate.generating.title">Generating your dashboard…</Trans>
              </Text>
              <Text color="secondary" variant="bodySmall">
                <Trans i18nKey="dashboard-generate.generating.body">
                  This usually takes a few seconds. You&apos;ll land on the new dashboard once it&apos;s ready.
                </Trans>
              </Text>
            </Stack>
          </div>
        )}
      </div>

      <Modal.ButtonRow
        leftItems={
          <Stack direction="row" alignItems="center" gap={1}>
            {areTemplatesAvailable && (
              <Button variant="secondary" fill="text" icon="apps" onClick={onUseTemplate} disabled={isGenerating}>
                <Trans i18nKey="dashboard-generate.footer.template">Start from a template</Trans>
              </Button>
            )}
            {selectedSelections.length > 0 && (
              <div className={styles.selectionSummary} data-testid="generate-dashboard-selection-summary">
                <Text variant="bodySmall" color="secondary">
                  {t('dashboard-generate.footer.selected-count', '', {
                    count: selectedSelections.length,
                    defaultValue_one: '{{count}} selected',
                    defaultValue_other: '{{count}} selected',
                  })}
                </Text>
                <Button variant="secondary" fill="text" size="sm" onClick={onClearSelection} disabled={isGenerating}>
                  <Trans i18nKey="dashboard-generate.footer.clear-selection">Clear</Trans>
                </Button>
              </div>
            )}
          </Stack>
        }
      >
        <Button variant="secondary" onClick={onDismiss}>
          <Trans i18nKey="dashboard-generate.footer.cancel">Cancel</Trans>
        </Button>
        <Button
          variant="primary"
          icon={isGenerating ? undefined : 'ai-sparkle'}
          onClick={onGenerate}
          disabled={!canGenerate}
        >
          {isGenerating ? (
            <Trans i18nKey="dashboard-generate.footer.generating">Generating…</Trans>
          ) : selectedSelections.length > 1 ? (
            t('dashboard-generate.footer.generate-selected', '', {
              count: selectedSelections.length,
              defaultValue_one: 'Generate dashboard ({{count}})',
              defaultValue_other: 'Generate dashboard ({{count}})',
            })
          ) : selectedSelections.length === 1 ? (
            <Trans i18nKey="dashboard-generate.footer.generate-single">Generate dashboard</Trans>
          ) : (
            <Trans i18nKey="dashboard-generate.footer.generate-overview">Generate an overview</Trans>
          )}
        </Button>
      </Modal.ButtonRow>
    </Modal>
  );
}

interface IntentGroupProps {
  title: string;
  /** Optional leading icon (e.g. the sparkle on the AI suggestions group). */
  icon?: IconName;
  /** Optional muted hint shown next to the title (e.g. sample values, "PostgreSQL, Redis"). */
  hint?: string;
  /** Show a spinner in the header + a placeholder while the group is still loading. */
  loading?: boolean;
  /** Whether this group opens expanded on first mount. */
  defaultOpen?: boolean;
  styles: ReturnType<typeof getStyles>;
  children: ReactNode;
}

/**
 * A titled group of intent cards, one per LLM-generated category (or, on the
 * fallback path, one per detected domain). Groups are collapsible; the first
 * one opens by default so beginners see immediately-useful content, and the
 * rest stay collapsed so the modal is scannable.
 */
function IntentGroup({ title, icon, hint, loading, defaultOpen = false, styles, children }: IntentGroupProps) {
  const isEmpty = Children.count(children) === 0;

  return (
    <CollapsableSection
      isOpen={defaultOpen}
      label={
        <div className={styles.groupHeader}>
          {icon && <Icon name={icon} size="sm" />}
          <Text weight="medium" variant="body">
            {title}
          </Text>
          {hint && (
            <Text color="secondary" variant="bodySmall">
              {hint}
            </Text>
          )}
        </div>
      }
      loading={loading}
    >
      {isEmpty && loading ? (
        <Text color="secondary" variant="bodySmall">
          <Trans i18nKey="dashboard-generate.intents.tailoring">Finding starting points tailored to your data…</Trans>
        </Text>
      ) : (
        <div className={styles.intentGrid}>{children}</div>
      )}
    </CollapsableSection>
  );
}

interface WizardControlsProps {
  mode: WizardMode;
  orientation: DashboardOrientation;
  refinement: string;
  onModeChange: (mode: WizardMode) => void;
  onOrientationChange: (orientation: DashboardOrientation) => void;
  onRefinementChange: (refinement: string) => void;
  onApplyRefinement: () => void;
  suggestionsLoading: boolean;
  disabled?: boolean;
  styles: ReturnType<typeof getStyles>;
}

/**
 * Top-of-modal controls: entry path (beginner/expert), focus (technical/business/both),
 * and a refinement text input where the user describes what they want the
 * dashboard to be about. `mode` and `orientation` re-run the LLM suggestions
 * automatically; `refinement` is applied on the "Update suggestions" button
 * because it changes on every keystroke and refetching per keystroke would be
 * expensive and annoying.
 */
function WizardControls({
  mode,
  orientation,
  refinement,
  onModeChange,
  onOrientationChange,
  onRefinementChange,
  onApplyRefinement,
  suggestionsLoading,
  disabled,
  styles,
}: WizardControlsProps) {
  const modeOptions = useMemo<Array<SelectableValue<WizardMode>>>(
    () => [
      {
        value: 'beginner',
        label: t('dashboard-generate.mode.beginner', 'Beginner'),
        description: t(
          'dashboard-generate.mode.beginner-description',
          "Show curated top picks — good if you're new to Grafana or unsure what to build."
        ),
      },
      {
        value: 'expert',
        label: t('dashboard-generate.mode.expert', 'Expert'),
        description: t(
          'dashboard-generate.mode.expert-description',
          'Show the full generated catalogue and allow multi-select.'
        ),
      },
    ],
    []
  );

  const orientationOptions = useMemo<Array<SelectableValue<DashboardOrientation>>>(
    () => [
      { value: 'technical', label: t('dashboard-generate.focus.technical', 'Technical') },
      { value: 'business', label: t('dashboard-generate.focus.business', 'Business') },
      { value: 'both', label: t('dashboard-generate.focus.both', 'Both') },
    ],
    []
  );

  return (
    <div className={styles.controlsRow}>
      <div className={styles.controlColumn}>
        <Field
          noMargin
          label={t('dashboard-generate.controls.mode-label', 'I want to')}
          description={
            mode === 'beginner'
              ? t(
                  'dashboard-generate.controls.mode-hint-beginner',
                  'The wizard picks a small set of high-signal starting points and generates on a single click.'
                )
              : t(
                  'dashboard-generate.controls.mode-hint-expert',
                  'You know what you want — pick one or more categories and intents; each becomes a tab.'
                )
          }
        >
          <RadioButtonGroup options={modeOptions} value={mode} onChange={onModeChange} disabled={disabled} fullWidth />
        </Field>
      </div>

      <div className={styles.controlColumn}>
        <Field
          noMargin
          label={t('dashboard-generate.controls.focus-label', 'Focus')}
          description={t(
            'dashboard-generate.controls.focus-hint',
            'Technical dashboards emphasise RED/USE, latency and reliability; business dashboards emphasise outcome KPIs.'
          )}
        >
          <RadioButtonGroup
            options={orientationOptions}
            value={orientation}
            onChange={onOrientationChange}
            disabled={disabled}
            fullWidth
          />
        </Field>
      </div>

      <div className={styles.refinementRow}>
        <Field
          noMargin
          label={t('dashboard-generate.controls.refinement-label', 'What should this dashboard analyse?')}
          description={t(
            'dashboard-generate.controls.refinement-hint',
            "Optional. Describe the subject in a few words. Leave empty for a general overview of what's on the data source."
          )}
        >
          <div className={styles.refinementInputRow}>
            <Input
              value={refinement}
              onChange={(e) => onRefinementChange(e.currentTarget.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  e.preventDefault();
                  onApplyRefinement();
                }
              }}
              placeholder={t(
                'dashboard-generate.controls.refinement-placeholder',
                'e.g. "checkout errors and latency", "revenue and signups by region"'
              )}
              disabled={disabled}
              className={styles.refinementInput}
            />
            <Button
              variant="secondary"
              size="md"
              icon={suggestionsLoading ? undefined : 'sync'}
              onClick={onApplyRefinement}
              disabled={disabled || suggestionsLoading}
            >
              {suggestionsLoading ? (
                <Trans i18nKey="dashboard-generate.controls.refinement-loading">Updating…</Trans>
              ) : (
                <Trans i18nKey="dashboard-generate.controls.refinement-apply">Update suggestions</Trans>
              )}
            </Button>
          </div>
        </Field>
      </div>
    </div>
  );
}

interface IntentCardProps {
  intent: DashboardIntent;
  isSuggested: boolean;
  /** For AI suggestions: the dimension this shape pivots on, shown as a pill. */
  dimensionTitle?: string;
  selected: boolean;
  disabled?: boolean;
  onToggle: () => void;
  styles: ReturnType<typeof getStyles>;
}

/**
 * Toggleable card representing a single dashboard intent.
 *
 * A click flips the card between selected / unselected states — the actual
 * generation runs from the footer's primary button using the current
 * selection. This keeps single-click generation snappy for one-intent picks
 * (one card + button) while letting users assemble multiple intents into a
 * single dashboard (each one becomes its own tab).
 *
 * Rendered as a `role="checkbox"` button so screen-readers announce the
 * toggle semantics correctly and keyboard focus lands on the whole card.
 */
function IntentCard({ intent, isSuggested, dimensionTitle, selected, disabled, onToggle, styles }: IntentCardProps) {
  return (
    <button
      type="button"
      role="checkbox"
      aria-checked={selected}
      className={cx(styles.intentCard, selected && styles.intentCardSelected)}
      onClick={onToggle}
      disabled={disabled}
      // Show the LLM guidance on hover so users can preview roughly what will
      // be built before committing.
      title={intent.description}
    >
      <div className={cx(styles.selectionIndicator, selected && styles.selectionIndicatorActive)} aria-hidden>
        <Icon name={selected ? 'check-square' : 'square-shape'} size="lg" />
      </div>
      <div className={styles.intentCardIcon}>
        <Icon name={intent.icon} size="xl" />
      </div>
      <div className={styles.intentCardBody}>
        <div className={styles.intentCardTitleRow}>
          <Text weight="medium">{intent.title}</Text>
          {isSuggested && (
            <Tooltip
              content={t(
                'dashboard-generate.intents.suggested-tooltip',
                'Suggested by the Assistant based on the metrics and labels in this data source.'
              )}
            >
              <span className={styles.suggestedBadge}>
                <Icon name="ai-sparkle" size="sm" />
              </span>
            </Tooltip>
          )}
          {dimensionTitle && <span className={styles.dimensionPill}>{dimensionTitle}</span>}
        </div>
        <Text color="secondary" variant="bodySmall">
          {intent.description}
        </Text>
      </div>
    </button>
  );
}

interface DatasourcesPickerProps {
  selected: DataSourceInstanceSettings[];
  onChange: (datasources: DataSourceInstanceSettings[]) => void;
  disabled?: boolean;
}

/**
 * Multi-select picker so the modal can accept several data sources (metrics + logs,
 * for example) without pulling in the alerting-specific `MultipleDataSourcePicker`,
 * which has alerting-oriented grouping baked in.
 */
function DatasourcesPicker({ selected, onChange, disabled }: DatasourcesPickerProps) {
  const options = useMemo<Array<SelectableValue<string>>>(() => {
    return getDataSourceSrv()
      .getList({ metrics: true, logs: true, tracing: true })
      .map((ds) => ({
        value: ds.uid,
        label: `${ds.name}${ds.isDefault ? ' (default)' : ''}`,
        imgUrl: ds.meta?.info?.logos?.small,
      }));
  }, []);

  const value = useMemo<Array<SelectableValue<string>>>(
    () =>
      selected.map((ds) => ({
        value: ds.uid,
        label: ds.name,
        imgUrl: ds.meta?.info?.logos?.small,
      })),
    [selected]
  );

  return (
    <MultiSelect
      disabled={disabled}
      options={options}
      value={value}
      placeholder={t('dashboard-generate.datasource-placeholder', 'Add data source…')}
      onChange={(items) => {
        const nextUids = (items ?? []).map((item) => item.value).filter((uid): uid is string => Boolean(uid));
        const srv = getDataSourceSrv();
        const nextDatasources = nextUids
          .map((uid) => srv.getInstanceSettings(uid))
          .filter((ds): ds is DataSourceInstanceSettings => Boolean(ds));
        onChange(nextDatasources);
      }}
    />
  );
}

interface AdvancedOptionsProps {
  value: CustomizationOptions;
  onChange: (next: CustomizationOptions) => void;
  styles: ReturnType<typeof getStyles>;
}

/**
 * "Advanced" collapsable shown at the bottom of the modal. Everything here is
 * layered on top of the intent's baseline guidance — leave the defaults alone and
 * the wizard behaves like it did before the panel existed.
 */
function AdvancedOptions({ value, onChange, styles }: AdvancedOptionsProps) {
  return (
    <div className={styles.advancedPanel}>
      <Stack direction="column" gap={2}>
        <Field
          noMargin
          label={t('dashboard-generate.customize.notes-label', 'Additional notes for the Assistant')}
          description={t(
            'dashboard-generate.customize.notes-description',
            'Free-form guidance layered on top of the starting point — focus areas, cardinality caveats, tone.'
          )}
        >
          <TextArea
            rows={3}
            value={value.additionalNotes}
            onChange={(e) => onChange({ ...value, additionalNotes: e.currentTarget.value })}
            placeholder={t(
              'dashboard-generate.customize.notes-placeholder',
              'e.g. "Focus on the checkout services", "We have ~500 pods so use topk aggregations"'
            )}
          />
        </Field>
      </Stack>
    </div>
  );
}

function getStyles(theme: GrafanaTheme2) {
  return {
    modal: css({
      width: '760px',
      maxWidth: '95vw',
    }),
    body: css({
      display: 'flex',
      flexDirection: 'column',
      gap: theme.spacing(2),
    }),
    bodyBusy: css({
      // Fade non-primary controls while the generator is producing a spec so the
      // user's focus lands on the "Generating…" banner + primary button.
      opacity: 0.85,
    }),
    chipsRow: css({
      display: 'flex',
      flexDirection: 'column',
      gap: theme.spacing(0.75),
      padding: theme.spacing(1, 1.5),
      borderRadius: theme.shape.radius.default,
      background: theme.colors.background.canvas,
      border: `1px solid ${theme.colors.border.weak}`,
    }),
    controlsRow: css({
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: theme.spacing(2),
      padding: theme.spacing(1.5),
      borderRadius: theme.shape.radius.default,
      background: theme.colors.background.canvas,
      border: `1px solid ${theme.colors.border.weak}`,
      [theme.breakpoints.down('sm')]: {
        gridTemplateColumns: '1fr',
      },
    }),
    controlColumn: css({
      display: 'flex',
      flexDirection: 'column',
      gap: theme.spacing(0.5),
      minWidth: 0,
    }),
    refinementRow: css({
      gridColumn: '1 / -1',
      display: 'flex',
      flexDirection: 'column',
      gap: theme.spacing(0.5),
      minWidth: 0,
    }),
    refinementInputRow: css({
      display: 'flex',
      alignItems: 'stretch',
      gap: theme.spacing(1),
      minWidth: 0,
    }),
    refinementInput: css({
      flex: 1,
      minWidth: 0,
    }),
    chips: css({
      display: 'flex',
      flexWrap: 'wrap',
      gap: theme.spacing(0.5),
    }),
    section: css({
      display: 'flex',
      flexDirection: 'column',
      gap: theme.spacing(1.5),
    }),
    sectionHeader: css({
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: theme.spacing(2),
      flexWrap: 'wrap',
    }),
    groupBlock: css({
      display: 'flex',
      flexDirection: 'column',
      gap: theme.spacing(1),
    }),
    groupHeader: css({
      display: 'flex',
      alignItems: 'center',
      gap: theme.spacing(1),
      minWidth: 0,
      color: theme.colors.text.primary,
    }),
    intentGrid: css({
      display: 'grid',
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
      gap: theme.spacing(1),
      [theme.breakpoints.down('sm')]: {
        gridTemplateColumns: '1fr',
      },
    }),
    intentCard: css({
      display: 'flex',
      alignItems: 'flex-start',
      gap: theme.spacing(1.5),
      minWidth: 0,
      width: '100%',
      padding: theme.spacing(1.5),
      borderRadius: theme.shape.radius.default,
      border: `1px solid ${theme.colors.border.weak}`,
      background: theme.colors.background.secondary,
      textAlign: 'left',
      cursor: 'pointer',
      [theme.transitions.handleMotion('no-preference', 'reduce')]: {
        transition: theme.transitions.create(['background-color', 'border-color', 'transform'], {
          duration: theme.transitions.duration.short,
        }),
      },
      '&:hover:not(:disabled)': {
        background: theme.colors.emphasize(theme.colors.background.secondary, 0.04),
        borderColor: theme.colors.primary.border,
      },
      '&:focus-visible': {
        outline: `2px solid ${theme.colors.primary.border}`,
        outlineOffset: 2,
      },
      '&:disabled': {
        cursor: 'not-allowed',
        opacity: 0.5,
      },
    }),
    intentCardSelected: css({
      // Give selected cards a filled primary tint + primary border so it's obvious
      // they'll ship in the next generation. The `!important`-free `&&` hover
      // override keeps the tint stable when the pointer moves across the card.
      background: theme.colors.action.selected,
      borderColor: theme.colors.primary.border,
      '&:hover:not(:disabled)': {
        background: theme.colors.emphasize(theme.colors.action.selected, 0.04),
        borderColor: theme.colors.primary.border,
      },
    }),
    selectionIndicator: css({
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      flex: '0 0 auto',
      width: 20,
      height: 20,
      color: theme.colors.text.secondary,
      marginTop: theme.spacing(0.5),
    }),
    selectionIndicatorActive: css({
      // The Icon inside inherits `currentColor`, so shifting the wrapper colour
      // is enough to tint the tick with the brand primary.
      color: theme.colors.primary.text,
    }),
    intentCardIcon: css({
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      flex: '0 0 auto',
      width: 40,
      height: 40,
      borderRadius: theme.shape.radius.default,
      background: theme.colors.background.canvas,
      color: theme.colors.text.secondary,
    }),
    intentCardBody: css({
      display: 'flex',
      flexDirection: 'column',
      gap: theme.spacing(0.25),
      flex: 1,
      minWidth: 0,
    }),
    intentCardTitleRow: css({
      display: 'flex',
      alignItems: 'center',
      gap: theme.spacing(0.75),
    }),
    suggestedBadge: css({
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      color: theme.colors.primary.text,
    }),
    dimensionPill: css({
      // Marks which dimension an AI suggestion pivots on, since suggestions from
      // different dimensions share the one "Suggested for your data" group.
      marginLeft: 'auto',
      flex: '0 0 auto',
      padding: theme.spacing(0, 0.75),
      borderRadius: theme.shape.radius.pill,
      background: theme.colors.background.canvas,
      border: `1px solid ${theme.colors.border.weak}`,
      color: theme.colors.text.secondary,
      fontSize: theme.typography.bodySmall.fontSize,
      lineHeight: `${theme.spacing(2.5)}`,
      whiteSpace: 'nowrap',
    }),
    inlineLoader: css({
      display: 'flex',
      alignItems: 'center',
      gap: theme.spacing(1),
      padding: theme.spacing(1.5),
      borderRadius: theme.shape.radius.default,
      background: theme.colors.background.secondary,
      border: `1px dashed ${theme.colors.border.weak}`,
    }),
    generatingBanner: css({
      display: 'flex',
      alignItems: 'center',
      gap: theme.spacing(1.5),
      padding: theme.spacing(1.5),
      borderRadius: theme.shape.radius.default,
      background: theme.colors.background.canvas,
      border: `1px solid ${theme.colors.primary.border}`,
    }),
    advancedPanel: css({
      // A subtle separator so the accordion visually detaches from the card grid
      // without pretending to be another selectable row.
      marginTop: theme.spacing(0.5),
      paddingTop: theme.spacing(0.5),
      borderTop: `1px solid ${theme.colors.border.weak}`,
    }),
    halfField: css({
      flex: 1,
      minWidth: 0,
    }),
    selectionSummary: css({
      display: 'inline-flex',
      alignItems: 'center',
      gap: theme.spacing(0.5),
      padding: theme.spacing(0.25, 1),
      borderRadius: theme.shape.radius.pill,
      background: theme.colors.background.canvas,
      border: `1px solid ${theme.colors.border.weak}`,
    }),
  };
}

export default GenerateDashboardModal;
