import { useMemo } from 'react';

import { contextSrv as ctx } from 'app/core/services/context_srv';
import { PERMISSIONS_CONTACT_POINTS_READ } from 'app/features/alerting/unified/components/contact-points/permissions';
import {
  PERMISSIONS_TIME_INTERVALS_MODIFY,
  PERMISSIONS_TIME_INTERVALS_READ,
} from 'app/features/alerting/unified/components/mute-timings/permissions';
import {
  PERMISSIONS_NOTIFICATION_POLICIES_MODIFY,
  PERMISSIONS_NOTIFICATION_POLICIES_READ,
} from 'app/features/alerting/unified/components/notification-policies/permissions';
import { AccessControlAction } from 'app/types/accessControl';

import { useAlertmanager } from '../../state/AlertmanagerContext';
import { getInstancesPermissions, getNotificationsPermissions } from '../../utils/access-control';
import { isAdmin } from '../../utils/misc';

import {
  type Abilities,
  type Ability,
  AlertmanagerAction,
  ExternalAlertmanagerAction,
  Granted,
  InsufficientPermissions,
  NotSupported,
} from './types';

// ── Internal helper ───────────────────────────────────────────────────────────

// TODO: Per-entity ability hooks for alertmanager resources
//
// Three mechanisms currently live outside the ability system and should be
// integrated as focused per-entity hooks in a future iteration:
//
// 1. K8s annotation-based (contact points — Grafana AM k8s API only)
//    canEditEntity / canDeleteEntity / canAdminEntity / canModifyProtectedEntity / canTestEntity
//    → proposed: useContactPointAbility(cp) returning { edit, delete, test, admin, editProtected }
//    Files: ContactPointHeader.tsx, GrafanaReceiverForm.tsx, useTestContactPoint.ts, contact-points/utils.ts
//
// 2. Silence accessControl response field
//    silence.accessControl.create / .write (populated when API is called with accesscontrol=true)
//    → proposed: useSilenceAbility(silence) returning { edit, recreate }
//    Files: SilencesTable.tsx, SilencesEditor.tsx
//
// 3. Provisioning-only gating (templates, mute timings, notification policies)
//    isProvisionedResource(entity.provenance) checked inline in every component
//    → proposed: useTemplateAbility(template), useMuteTimingAbility(muteTiming)
//    Files: TemplatesTable.tsx, TemplateForm.tsx, MuteTimingActionsButtons.tsx, MuteTimingForm.tsx,
//           ActionButtons.tsx, Policy.tsx

/**
 * Builds an `Ability` from a supported flag and an explicit list of `AccessControlActions`.
 * The user is considered allowed if they hold ANY of the listed permissions.
 */
function makeAbility(supported: boolean, anyOfPermissions: AccessControlAction[]): Ability {
  if (!supported) {
    return NotSupported;
  }
  const hasAny = anyOfPermissions.some((p) => p && ctx.hasPermission(p));
  return hasAny ? Granted : InsufficientPermissions(anyOfPermissions);
}

// ── Alertmanager abilities ────────────────────────────────────────────────────

export function useAllAlertmanagerAbilities(): Abilities<AlertmanagerAction> {
  const {
    selectedAlertmanager,
    hasConfigurationAPI,
    isGrafanaAlertmanager: isGrafanaFlavoredAlertmanager,
  } = useAlertmanager();

  const notificationsPermissions = getNotificationsPermissions(selectedAlertmanager!);
  const instancePermissions = getInstancesPermissions(selectedAlertmanager!);
  const admin = isAdmin();

  // Memoize on the values that determine all permission checks so downstream
  // useMemo([all, action]) calls aren't defeated by a new object reference each render.
  return useMemo<Abilities<AlertmanagerAction>>(() => {
    // Export contact point: only supported for Grafana-flavored AM; view implies export permission.
    const exportContact: Ability = isGrafanaFlavoredAlertmanager ? Granted : NotSupported;

    // Autogenerated policy tree: Grafana AM only, admin-only.
    let autogenerated: Ability;
    if (!isGrafanaFlavoredAlertmanager) {
      autogenerated = NotSupported;
    } else if (admin) {
      autogenerated = Granted;
    } else {
      autogenerated = InsufficientPermissions([]);
    }

    return {
      // -- contact points --
      [AlertmanagerAction.CreateContactPoint]: makeAbility(hasConfigurationAPI, [
        notificationsPermissions.create,
        // TODO: Move this into the permissions config and generalise that code to allow for an array of permissions
        ...(isGrafanaFlavoredAlertmanager ? [AccessControlAction.AlertingReceiversCreate] : []),
      ]),
      [AlertmanagerAction.ViewContactPoint]: makeAbility(true, [
        notificationsPermissions.read,
        ...(isGrafanaFlavoredAlertmanager ? PERMISSIONS_CONTACT_POINTS_READ : []),
      ]),
      [AlertmanagerAction.UpdateContactPoint]: makeAbility(hasConfigurationAPI, [
        notificationsPermissions.update,
        ...(isGrafanaFlavoredAlertmanager ? [AccessControlAction.AlertingReceiversWrite] : []),
      ]),
      [AlertmanagerAction.DeleteContactPoint]: makeAbility(hasConfigurationAPI, [
        notificationsPermissions.delete,
        ...(isGrafanaFlavoredAlertmanager ? [AccessControlAction.AlertingReceiversWrite] : []),
      ]),
      // At the time of writing, only Grafana flavored alertmanager supports exporting,
      // and if a user can view the contact point, then they can also export it.
      [AlertmanagerAction.ExportContactPoint]: exportContact,
      // -- notification templates --
      [AlertmanagerAction.CreateNotificationTemplate]: makeAbility(hasConfigurationAPI, [
        notificationsPermissions.create,
        ...(isGrafanaFlavoredAlertmanager ? [AccessControlAction.AlertingTemplatesWrite] : []),
      ]),
      [AlertmanagerAction.ViewNotificationTemplate]: makeAbility(true, [
        notificationsPermissions.read,
        ...(isGrafanaFlavoredAlertmanager ? [AccessControlAction.AlertingTemplatesRead] : []),
      ]),
      [AlertmanagerAction.UpdateNotificationTemplate]: makeAbility(hasConfigurationAPI, [
        notificationsPermissions.update,
        ...(isGrafanaFlavoredAlertmanager ? [AccessControlAction.AlertingTemplatesWrite] : []),
      ]),
      [AlertmanagerAction.DeleteNotificationTemplate]: makeAbility(hasConfigurationAPI, [
        notificationsPermissions.delete,
      ]),
      // -- notification policies --
      [AlertmanagerAction.CreateNotificationPolicy]: makeAbility(hasConfigurationAPI, [
        notificationsPermissions.create,
        ...(isGrafanaFlavoredAlertmanager ? PERMISSIONS_NOTIFICATION_POLICIES_MODIFY : []),
      ]),
      [AlertmanagerAction.ViewNotificationPolicyTree]: makeAbility(true, [
        notificationsPermissions.read,
        ...(isGrafanaFlavoredAlertmanager ? PERMISSIONS_NOTIFICATION_POLICIES_READ : []),
      ]),
      [AlertmanagerAction.UpdateNotificationPolicyTree]: makeAbility(hasConfigurationAPI, [
        notificationsPermissions.update,
        ...(isGrafanaFlavoredAlertmanager ? PERMISSIONS_NOTIFICATION_POLICIES_MODIFY : []),
      ]),
      [AlertmanagerAction.DeleteNotificationPolicy]: makeAbility(hasConfigurationAPI, [
        notificationsPermissions.delete,
        ...(isGrafanaFlavoredAlertmanager ? PERMISSIONS_NOTIFICATION_POLICIES_MODIFY : []),
      ]),
      [AlertmanagerAction.ExportNotificationPolicies]: makeAbility(isGrafanaFlavoredAlertmanager, [
        notificationsPermissions.read,
      ]),
      [AlertmanagerAction.DecryptSecrets]: makeAbility(isGrafanaFlavoredAlertmanager, [
        notificationsPermissions.provisioning.readSecrets,
      ]),
      [AlertmanagerAction.ViewAutogeneratedPolicyTree]: autogenerated,
      // -- silences --
      [AlertmanagerAction.CreateSilence]: makeAbility(true, [instancePermissions.create]),
      [AlertmanagerAction.ViewSilence]: makeAbility(true, [instancePermissions.read]),
      [AlertmanagerAction.UpdateSilence]: makeAbility(true, [instancePermissions.update]),
      [AlertmanagerAction.PreviewSilencedInstances]: makeAbility(true, [instancePermissions.read]),
      // -- time intervals --
      [AlertmanagerAction.CreateTimeInterval]: makeAbility(hasConfigurationAPI, [
        notificationsPermissions.create,
        ...(isGrafanaFlavoredAlertmanager ? PERMISSIONS_TIME_INTERVALS_MODIFY : []),
      ]),
      [AlertmanagerAction.ViewTimeInterval]: makeAbility(true, [
        notificationsPermissions.read,
        ...(isGrafanaFlavoredAlertmanager ? PERMISSIONS_TIME_INTERVALS_READ : []),
      ]),
      [AlertmanagerAction.UpdateTimeInterval]: makeAbility(hasConfigurationAPI, [
        notificationsPermissions.update,
        ...(isGrafanaFlavoredAlertmanager ? PERMISSIONS_TIME_INTERVALS_MODIFY : []),
      ]),
      [AlertmanagerAction.DeleteTimeInterval]: makeAbility(hasConfigurationAPI, [
        notificationsPermissions.delete,
        ...(isGrafanaFlavoredAlertmanager ? PERMISSIONS_TIME_INTERVALS_MODIFY : []),
      ]),
      [AlertmanagerAction.ExportTimeIntervals]: makeAbility(isGrafanaFlavoredAlertmanager, [
        notificationsPermissions.read,
      ]),
      [AlertmanagerAction.ViewAlertGroups]: makeAbility(true, [instancePermissions.read]),
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedAlertmanager, hasConfigurationAPI, isGrafanaFlavoredAlertmanager, admin]);
}

export function useAlertmanagerAbility(action: AlertmanagerAction): Ability {
  const all = useAllAlertmanagerAbilities();
  return useMemo(() => all[action], [all, action]);
}

export function useAlertmanagerAbilities(actions: AlertmanagerAction[]): Ability[] {
  const all = useAllAlertmanagerAbilities();
  return useMemo(() => actions.map((action) => all[action]), [all, actions]);
}

// ── External alertmanager abilities ──────────────────────────────────────────

export function useAllExternalAlertmanagerAbilities(): Abilities<ExternalAlertmanagerAction> {
  const { hasConfigurationAPI } = useAlertmanager();

  return useMemo<Abilities<ExternalAlertmanagerAction>>(
    () => ({
      [ExternalAlertmanagerAction.ViewExternalConfiguration]: makeAbility(true, [
        AccessControlAction.AlertingNotificationsExternalRead,
      ]),
      [ExternalAlertmanagerAction.UpdateExternalConfiguration]: makeAbility(hasConfigurationAPI, [
        AccessControlAction.AlertingNotificationsExternalWrite,
      ]),
    }),
    [hasConfigurationAPI]
  );
}

export function useExternalAlertmanagerAbility(action: ExternalAlertmanagerAction): Ability {
  const all = useAllExternalAlertmanagerAbilities();
  return useMemo(() => all[action], [all, action]);
}
