== Configuration
config.js is where you will find the core Kibana configuration. This file contains parameter that
must be set before kibana is run for the first time.
// src/config.js:1

=== Parameters
// src/config.js:10

==== elasticsearch

The URL to your elasticsearch server. You almost certainly don't
want +http://localhost:9200+ here. Even if Kibana and Elasticsearch are on
the same host. By default this will attempt to reach ES at the same host you have
kibana installed on. You probably want to set it to the FQDN of your
elasticsearch host
// src/config.js:15

==== default_route

This is the default landing page when you don't specify a dashboard to load. You can specify
files, scripts or saved dashboards here. For example, if you had saved a dashboard called
`WebLogs' to elasticsearch you might use:

+default_route: '/dashboard/elasticsearch/WebLogs',+
// src/config.js:26

==== kibana-int

The default ES index to use for storing Kibana specific object
such as stored dashboards
// src/config.js:37

==== panel_name

An array of panel modules available. Panels will only be loaded when they are defined in the
dashboard, but this list is used in the "add panel" interface.
// src/config.js:45

