define([
  './arrayJoin',
  './dashUpload',
  './grafanaPanel',
  './grafanaSimplePanel',
  './ngBlur',
  './ngModelOnBlur',
  './tip',
  './confirmClick',
  './configModal',
  './spectrumPicker',
  './grafanaGraph',
  './bootstrap-tagsinput',
  './bodyClass',
  './addGraphiteFunc',
  './graphiteFuncEditor',
  './grafanaVersionCheck',
  './influxdbFuncEditor'
], function () {});
