import { AchievementId, AchievementLevel } from './types';

// These are just hard coded for now loosely based on current available achievements
export const achievementLevelThresholds = {
  [AchievementLevel.Novice]: 3,
  [AchievementLevel.Beginner]: 9,
  [AchievementLevel.Experienced]: 16,
  [AchievementLevel.Expert]: 30,
  [AchievementLevel.Wizard]: 40,
};

export const achievements = [
  {
    id: AchievementId.NavigateToDashboard,
    title: 'Navigate to the dashboard page',
    description: '',
    level: AchievementLevel.Novice,
    link: 'https://grafana.com/docs/grafana/latest/dashboards/use-dashboards/',
    video: '',
  },
  {
    id: AchievementId.NavigateToExplore,
    title: 'Navigate to the explore page',
    description: '',
    level: AchievementLevel.Novice,
    link: 'https://grafana.com/docs/grafana/latest/explore/',
    video: '',
  },
  {
    id: AchievementId.WatchIntroToGrafanaVideo,
    title: 'Watch intro to Grafana video',
    description: '',
    level: AchievementLevel.Novice,
    link: '',
    video: 'https://www.youtube.com/embed/k3RQVyeYdO8?si=96JCRzMkuo6fjn4O',
  },
  {
    id: AchievementId.ConnectYourFirstDatasource,
    title: 'Connect your first datasource',
    description: '',
    level: AchievementLevel.Beginner,
    link: '',
    video: '',
  },
  {
    id: AchievementId.UseExploreToMakeAQuery,
    title: 'Use explore to make a query',
    description: 'Make a query in Explore and see the results in a table or graph',
    level: AchievementLevel.Beginner,
    link: '',
    video: '',
  },
  {
    id: AchievementId.AddExplorePanelToADashboard,
    title: 'Add explore panel to a dashboard',
    description: '',
    level: AchievementLevel.Beginner,
    link: '',
    video: '',
  },
  {
    id: AchievementId.AddATitleToAPanelInADashboard,
    title: 'Add a title to a panel in a dashboard',
    description: '',
    level: AchievementLevel.Beginner,
    link: '',
    video: '',
  },
  {
    id: AchievementId.AddADescriptionToAPanelInADashboard,
    title: 'Add a description to a panel in a dashboard',
    description: '',
    level: AchievementLevel.Beginner,
    link: '',
    video: '',
  },
  {
    id: AchievementId.ChangeTheTheme,
    title: 'Change the theme',
    description: 'Change the theme using the keyboard shortcut `ct`',
    level: AchievementLevel.Beginner,
    link: '',
    video: '',
  },
  {
    id: AchievementId.ExploreKeyboardShortcuts,
    title: 'Explore keyboard shortcuts',
    description: 'Use the keyboard shortcut `?` or `h` to see a list of keyboard shortcuts',
    level: AchievementLevel.Experienced,
    link: '',
    video: '',
  },
  {
    id: AchievementId.ChangePanelSettings,
    title: 'Change panel settings',
    description: 'Modify the visualization type, change the unit, change the legend position etc',
    level: AchievementLevel.Experienced,
    link: '',
    video: '',
  },
  {
    id: AchievementId.ImplementDataLink,
    title: 'Implement a data link',
    description: 'Create a data link that opens a new tab to a URL',
    level: AchievementLevel.Experienced,
    link: '',
    video: '',
  },
  {
    id: AchievementId.AddTemplateVariable,
    title: 'Add a template variable',
    description: 'Add a template variable to a dashboard',
    level: AchievementLevel.Experienced,
    link: '',
    video: '',
  },
  {
    id: AchievementId.BrowseDataTransformations,
    title: 'Browse data transformations that you can add to your panel',
    description: '',
    level: AchievementLevel.Experienced,
    link: '',
    video: '',
  },
  {
    id: AchievementId.AddCanvasVisualization,
    title: 'Add a canvas visualization',
    description: '',
    level: AchievementLevel.Experienced,
    link: '',
    video: '',
  },
  {
    id: AchievementId.SetMetricValueElement,
    title: 'Set a metric value element',
    description: 'Set a metric value element in a canvas visualization',
    level: AchievementLevel.Experienced,
    link: '',
    video: '',
  },
  {
    id: AchievementId.EnableSharedCrosshairOrTooltip,
    title: 'Enable shared crosshair or tooltip in a dashboard',
    description: '',
    level: AchievementLevel.Experienced,
    link: '',
    video: '',
  },
  {
    id: AchievementId.LegendChangeSeriesColor,
    title: 'Change color of series by clicking on time series legend',
    description: '',
    level: AchievementLevel.Experienced,
    link: '',
    video: '',
  },
  {
    id: AchievementId.LegendShowSeries,
    title: 'Click on series in the legend to display it by itself',
    description: '',
    level: AchievementLevel.Experienced,
    link: '',
    video: '',
  },
  {
    id: AchievementId.LegendHideSeries,
    title: 'Command + click on series in the legend to exclude it',
    description: '',
    level: AchievementLevel.Experienced,
    link: '',
    video: '',
  },
  {
    id: AchievementId.AddCustomThresholds,
    title: 'Add custom thresholds',
    description: '',
    level: AchievementLevel.Expert,
    link: '',
    video: '',
  },
  {
    id: AchievementId.AddValueMapping,
    title: 'Add a value mapping',
    description: '',
    level: AchievementLevel.Expert,
    link: '',
    video: '',
  },
  {
    id: AchievementId.AddAdvancedDataLink,
    title: 'Implement a data link using a template variable / panel data',
    description: '',
    level: AchievementLevel.Expert,
    link: '',
    video: '',
  },
  {
    id: AchievementId.UseJoinByFieldTransformation,
    title: 'Use a join by field transformation',
    description: '',
    level: AchievementLevel.Expert,
    link: '',
    video: '',
  },
  {
    id: AchievementId.MakePublicDashboard,
    title: 'Make a public dashboard',
    description: '',
    level: AchievementLevel.Expert,
    link: '',
    video: '',
  },
  {
    id: AchievementId.StreamDataToGrafana,
    title: 'Stream data to Grafana',
    description: '',
    level: AchievementLevel.Wizard,
    link: '',
    video: '',
  },
];
