// This webpack config is used during development to split out the compilation and caching
// of node_module dependencies

const path = require('path');
const { DllPlugin } = require('webpack');

// TODO: create a blacklist from package.json rather than this hardcoded array.
// This list cannot contain @grafana workspaces, jquery (due to bootstrap) or monaco
const vendorDeps = [
  '@emotion/css',
  '@emotion/react',
  '@grafana/slate-react',
  '@opentelemetry/api',
  '@opentelemetry/exporter-collector',
  '@opentelemetry/semantic-conventions',
  '@popperjs/core',
  '@reduxjs/toolkit',
  '@sentry/browser',
  '@sentry/types',
  '@sentry/utils',
  '@visx/event',
  '@visx/gradient',
  '@visx/scale',
  '@visx/shape',
  '@visx/tooltip',
  '@welldone-software/why-did-you-render',
  'abortcontroller-polyfill',
  'angular',
  'angular-bindonce',
  'angular-route',
  'angular-sanitize',
  'baron',
  'brace',
  'calculate-size',
  'centrifuge',
  'classnames',
  'clipboard',
  'common-tags',
  'core-js',
  'd3',
  'd3-force',
  'd3-scale-chromatic',
  'dangerously-set-html-content',
  'debounce-promise',
  'eventemitter3',
  'fast-deep-equal',
  'fast-json-patch',
  'fast-text-encoding',
  'file-saver',
  'history',
  'hoist-non-react-statics',
  'immer',
  'json-source-map',
  'jsurl',
  'lezer',
  'lezer-promql',
  'lezer-tree',
  'lodash',
  'logfmt',
  'lru-cache',
  'memoize-one',
  'moment',
  'moment-timezone',
  'mousetrap',
  'mousetrap-global-bind',
  'moveable',
  'ol',
  'papaparse',
  'pluralize',
  'prismjs',
  'prop-types',
  'rc-cascader',
  'rc-drawer',
  'rc-slider',
  'rc-time-picker',
  're-resizable',
  'react',
  'react-beautiful-dnd',
  'react-diff-viewer',
  'react-dom',
  'react-grid-layout',
  'react-highlight-words',
  'react-hook-form',
  'react-inlinesvg',
  'react-loadable',
  'react-popper',
  'react-redux',
  'react-reverse-portal',
  'react-router-dom',
  'react-select',
  'react-split-pane',
  'react-transition-group',
  'react-use',
  'react-virtualized-auto-sizer',
  'react-window',
  'redux',
  'redux-thunk',
  'regenerator-runtime',
  'reselect',
  'rst2html',
  'rxjs',
  'search-query-parser',
  'selecto',
  'semver',
  'slate',
  'slate-plain-serializer',
  'tether',
  'tether-drop',
  'tinycolor2',
  'uplot',
  'uuid',
  'visjs-network',
  'whatwg-fetch',
];

module.exports = {
  mode: 'development',
  entry: {
    vendor: vendorDeps,
  },
  devtool: false,
  resolve: {
    fallback: {
      stream: false,
    },
  },

  // enable persistent cache for faster cold starts
  cache: {
    type: 'filesystem',
    name: 'vendor-default-development',
    buildDependencies: {
      config: [__filename],
    },
  },

  // https://webpack.js.org/guides/build-performance/#output-without-path-info
  output: {
    filename: '[name].dll.js',
    pathinfo: false,
    path: path.join(__dirname, '../../public/build'),
    library: '[name]_dll',
  },

  // https://webpack.js.org/guides/build-performance/#avoid-extra-optimization-steps
  optimization: {
    runtimeChunk: true,
    removeAvailableModules: false,
    removeEmptyChunks: false,
    splitChunks: false,
  },
  plugins: [
    new DllPlugin({
      name: '[name]_dll',
      path: path.join(__dirname, '../../public/build', '[name].json'),
      entryOnly: true,
    }),
  ],
};
