// THIS FILE IS GENERATED. EDITING IS FUTILE.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     GoTypesJenny
//     LatestJenny
//
// Run 'make gen-cue' from repository root to regenerate.

package team

// Defines values for Permission.
const (
	PermissionN1 Permission = 1

	PermissionN2 Permission = 2

	PermissionN4 Permission = 4
)

// Team defines model for team.
type Team struct {
	// TODO: probably needs a better description
	// AccessControl metadata associated with a given resource.
	AccessControl map[string]interface{} `json:"accessControl"`

	// AvatarUrl is the team's avatar URL.
	AvatarUrl string `json:"avatarUrl"`

	// Email of the team.
	Email *string `json:"email,omitempty"`

	// MemberCount is the number of the team members.
	MemberCount int64 `json:"memberCount"`

	// Name of the team.
	Name string `json:"name"`

	// OrgId is the ID of an organisation the team belongs to.
	OrgId *int64 `json:"orgId,omitempty"`

	// TODO - check if it's used in the code
	Permission Permission `json:"permission"`
}

// TODO - check if it's used in the code
type Permission int
