name: Setup Node.js
description: Sets up a node.js environment with presets for the Grafana repository. Use .github/actions/yarn-install to install and cache dependencies.

inputs:
  cwd:
    description: "Changes node's process.cwd() if the project is not located on the root. Default to process.cwd()"
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version-file: '${{ inputs.cwd }}/.nvmrc'
        package-manager-cache: false
