version: 2
updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: deps(actions)
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "no-changelog"
  - package-ecosystem: "gomod"
    commit-message:
      prefix: deps(go)
    directories:
      - "/"
      - "/apps/advisor"
      - "/apps/alerting/alertenrichment"
      - "/apps/alerting/historian"
      - "/apps/alerting/notifications"
      - "/apps/alerting/rules"
      - "/apps/annotation"
      - "/apps/collections"
      - "/apps/correlations"
      - "/apps/dashboard"
      - "/apps/dashvalidator"
      - "/apps/example"
      - "/apps/folder"
      - "/apps/iam"
      - "/apps/logsdrilldown"
      - "/apps/playlist"
      - "/apps/plugins"
      - "/apps/preferences"
      - "/apps/provisioning"
      - "/apps/quotas"
      - "/apps/scope"
      - "/apps/secret"
      - "/apps/shorturl"
      - "/hack"
      - "/pkg/aggregator"
      - "/pkg/apimachinery"
      - "/pkg/apiserver"
      - "/pkg/build"
      - "/pkg/build/wire"
      - "/pkg/codegen"
      - "/pkg/infra/features"
      - "/pkg/plugins"
      - "/pkg/plugins/codegen"
      - "/pkg/semconv"
      - "/pkg/storage/unified/resource/kv"
      - "/pkg/util/xorm"
      - "/scripts/go-workspace"
      - "/scripts/modowners"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 20
    # group some updates together for easier review
    groups:
      go.opentelemetry.io:
        patterns:
          - "go.opentelemetry.io/*"
      k8s.io:
        patterns:
          - "k8s.io/*"
      aws-sdk-go:
        patterns:
          - "github.com/aws/aws-sdk-go*"
          - "github.com/aws/smithy-go"
      grafana-app-sdk:
        patterns:
          - "github.com/grafana/grafana-app-sdk*"
    labels:
      - "no-changelog"
  - package-ecosystem: "docker"
    commit-message:
      prefix: deps(docker)
    directories:
      - "/"
      - "/packaging/docker/custom"
      - "/scripts/verify-repo-update"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: Etc/UTC
    labels:
      - "no-changelog"
    open-pull-requests-limit: 20
