version: 2
updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: deps(actions)
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    groups:
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    commit-message:
      prefix: deps(go)
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    groups:
      go-security:
        applies-to: security-updates
        patterns:
          - "*"
