define([
  './grafanaCtrl',
  './dashboardCtrl',
  './dashboardNavCtrl',
  './row',
  './submenuCtrl',
  './pulldown',
  './search',
  './metricKeys',
  './graphiteImport',
  './playlistCtrl',
  './inspectCtrl',
  './templateEditorCtrl',
  './sharePanelCtrl',
  './jsonEditorCtrl',
], function () {});
