compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  croact-css-styled@1.1.9:
    dependencies:
      croact: 1.0.4
  doctrine@3.0.0:
    dependencies:
      assert: 2.0.0
  rc-trigger@2.6.5:
    peerDependencies:
      react: 17.0.1
      react-dom: 17.0.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"
  - checksum: 374f735053958b77583ef7b70e56a59540d1d9c681f04b8ab7a600f4325301d2e1fb67c51d34ba75bbbc4e71f8c003fbc52b1f22d7daa30dca655f1a1bf205a1
    path: .yarn/plugins/@yarnpkg/plugin-licenses.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-licenses/v0.15.0/bundles/@yarnpkg/plugin-licenses.js"

yarnPath: .yarn/releases/yarn-4.11.0.cjs

enableScripts: false

catalog:
  "@arethetypeswrong/cli": "^0.18.2"
  "@axe-core/playwright": "^4.11.1"
  "@babel/core": "7.28.0"
  "@babel/preset-env": "7.28.0"
  "@babel/preset-react": "7.27.1"
  "@babel/runtime": "7.28.2"
  "@braintree/sanitize-url": "7.0.1"
  "@bsull/augurs": "^0.10.0"
  "@crowdin/crowdin-api-client": "^1.42.0"
  "@cypress/webpack-preprocessor": "6.0.4"
  "@emotion/css": "11.13.5"
  "@emotion/eslint-plugin": "11.12.0"
  "@emotion/react": "11.14.0"
  "@emotion/serialize": "1.3.3"
  "@faker-js/faker": "^9.8.0"
  "@fingerprintjs/fingerprintjs": "^3.4.2"
  "@floating-ui/react": "0.27.16"
  "@formatjs/intl-durationformat": "^0.7.0"
  "@grafana/api-clients": "13.0.0-pre"
  "@grafana/assistant": "^0.1.1"
  "@grafana/aws-sdk": "^0.10.1"
  "@grafana/azure-sdk": "0.1.0"
  "@grafana/data": "13.0.0-pre"
  "@grafana/e2e-selectors": "13.0.0-pre"
  "@grafana/eslint-config": "8.2.0"
  "@grafana/faro-core": "^2.2.4"
  "@grafana/faro-instrumentation-replay": "^2.2.4"
  "@grafana/faro-web-sdk": "^2.2.4"
  "@grafana/faro-web-tracing": "^2.2.4"
  "@grafana/google-sdk": "0.3.5"
  "@grafana/i18n": "13.0.0-pre"
  "@grafana/lezer-logql": "0.2.9"
  "@grafana/lezer-traceql": "0.0.25"
  "@grafana/llm": "1.0.3"
  "@grafana/monaco-logql": "^0.0.8"
  "@grafana/plugin-configs": "13.0.0-pre"
  "@grafana/plugin-e2e": "3.4.0"
  "@grafana/plugin-ui": "^0.13.1"
  "@grafana/runtime": "*"
  "@grafana/scenes": "7.1.7"
  "@grafana/scenes-react": "7.1.7"
  "@grafana/schema": "13.0.0-pre"
  "@grafana/sql": "13.0.0-pre"
  "@grafana/tsconfig": "^2.0.0"
  "@grafana/ui": "13.0.0-pre"
  "@hello-pangea/dnd": "18.0.1"
  "@kusto/monaco-kusto": "^10.0.0"
  "@leeoniya/ufuzzy": "1.0.19"
  "@lezer/common": "1.3.0"
  "@lezer/highlight": "1.2.3"
  "@lezer/lr": "1.4.3"
  "@locker/near-membrane-dom": "0.14.0"
  "@locker/near-membrane-shared": "0.14.0"
  "@locker/near-membrane-shared-dom": "0.14.0"
  "@manypkg/get-packages": "^3.0.0"
  "@monaco-editor/react": "4.7.0"
  "@msagl/core": "^1.1.19"
  "@msagl/parser": "^1.1.19"
  "@npmcli/package-json": "^6.0.0"
  "@openfeature/core": "^1.9.0"
  "@openfeature/ofrep-web-provider": "^0.3.3"
  "@openfeature/react-sdk": "^1.2.0"
  "@openfeature/web-sdk": "^1.6.1"
  "@opentelemetry/api": "1.9.0"
  "@opentelemetry/exporter-collector": "0.25.0"
  "@opentelemetry/semantic-conventions": "1.38.0"
  "@playwright/test": "1.56.1"
  "@pmmmwh/react-refresh-webpack-plugin": "0.6.1"
  "@popperjs/core": "2.11.8"
  "@prometheus-io/lezer-promql": "0.307.3"
  "@rc-component/cascader": "1.9.0"
  "@rc-component/drawer": "1.3.0"
  "@rc-component/picker": "1.7.1"
  "@rc-component/slider": "1.0.1"
  "@rc-component/tooltip": "1.4.0"
  "@rc-component/tree": "1.1.0"
  "@react-aria/dialog": "3.5.31"
  "@react-aria/focus": "3.21.2"
  "@react-aria/overlays": "3.30.0"
  "@react-aria/utils": "3.31.0"
  "@react-awesome-query-builder/ui": "6.6.15"
  "@react-types/button": "3.13.0"
  "@react-types/menu": "3.10.3"
  "@react-types/overlays": "3.9.0"
  "@react-types/shared": "3.31.0"
  "@reduxjs/toolkit": "2.10.1"
  "@rollup/plugin-dynamic-import-vars": "2.1.5"
  "@rollup/plugin-image": "3.0.3"
  "@rollup/plugin-json": "6.1.0"
  "@rollup/plugin-node-resolve": "16.0.1"
  "@rollup/plugin-terser": "0.4.4"
  "@rsdoctor/webpack-plugin": "^1.0.0"
  "@rtk-query/codegen-openapi": "^2.0.0"
  "@rtsao/plugin-proposal-class-properties": "7.0.1-patch.1"
  "@storybook/addon-a11y": "^8.6.15"
  "@storybook/addon-actions": "^8.6.15"
  "@storybook/addon-docs": "^8.6.15"
  "@storybook/addon-essentials": "^8.6.15"
  "@storybook/addon-storysource": "^8.6.15"
  "@storybook/addon-webpack5-compiler-swc": "^4.0.2"
  "@storybook/blocks": "^8.6.15"
  "@storybook/components": "^8.6.15"
  "@storybook/core-events": "^8.6.15"
  "@storybook/manager-api": "^8.6.15"
  "@storybook/mdx2-csf": "1.1.0"
  "@storybook/preset-scss": "1.0.3"
  "@storybook/preview-api": "^8.6.15"
  "@storybook/react": "^10.0.8"
  "@storybook/react-webpack5": "^10.0.8"
  "@storybook/test-runner": "^0.23.0"
  "@storybook/theming": "^8.6.15"
  "@stylistic/eslint-plugin-ts": "^4.0.0"
  "@swc/core": "1.13.3"
  "@swc/helpers": "0.5.17"
  "@swc/jest": "^0.2.26"
  "@tanstack/react-virtual": "^3.5.1"
  "@testing-library/dom": "10.4.1"
  "@testing-library/jest-dom": "6.6.4"
  "@testing-library/react": "16.3.0"
  "@testing-library/user-event": "14.6.1"
  "@types/babel__core": "^7"
  "@types/babel__preset-env": "^7"
  "@types/chance": "^1.1.7"
  "@types/common-tags": "^1.8.0"
  "@types/confusing-browser-globals": "^1"
  "@types/d3": "7.4.3"
  "@types/d3-force": "^3.0.0"
  "@types/d3-interpolate": "^3.0.0"
  "@types/d3-random": "^3.0.2"
  "@types/d3-scale-chromatic": "3.1.0"
  "@types/debounce-promise": "3.1.9"
  "@types/eslint": "9.6.1"
  "@types/eslint-scope": "^8.0.0"
  "@types/file-saver": "2.0.7"
  "@types/fs-extra": "^11"
  "@types/google.analytics": "^0.0.46"
  "@types/gtag.js": "^0.0.20"
  "@types/history": "4.7.11"
  "@types/hoist-non-react-statics": "3.3.7"
  "@types/ini": "^4"
  "@types/is-hotkey": "0.1.10"
  "@types/jest": "29.5.14"
  "@types/jquery": "3.5.33"
  "@types/js-yaml": "^4.0.5"
  "@types/jsurl": "^1.2.28"
  "@types/lodash": "4.17.20"
  "@types/logfmt": "^1.2.3"
  "@types/lucene": "^2"
  "@types/mock-raf": "1.0.6"
  "@types/node": "24.10.1"
  "@types/node-forge": "^1"
  "@types/papaparse": "5.3.16"
  "@types/pluralize": "^0.0.33"
  "@types/prismjs": "1.26.5"
  "@types/react": "18.3.18"
  "@types/react-color": "3.0.13"
  "@types/react-dom": "18.3.5"
  "@types/react-grid-layout": "1.3.5"
  "@types/react-highlight-words": "0.20.0"
  "@types/react-resizable": "3.0.8"
  "@types/react-router": "5.1.20"
  "@types/react-router-dom": "5.3.3"
  "@types/react-table": "7.7.20"
  "@types/react-transition-group": "4.4.12"
  "@types/react-virtualized-auto-sizer": "1.0.8"
  "@types/react-window": "1.8.8"
  "@types/react-window-infinite-loader": "^1"
  "@types/redux-mock-store": "1.5.0"
  "@types/semver": "7.7.1"
  "@types/slate": "0.47.11"
  "@types/slate-plain-serializer": "0.7.5"
  "@types/slate-react": "0.22.9"
  "@types/string-hash": "1.1.3"
  "@types/swagger-ui-react": "5.18.0"
  "@types/systemjs": "6.15.3"
  "@types/tinycolor2": "1.4.6"
  "@types/uuid": "10.0.0"
  "@types/webpack-assets-manifest": "^5"
  "@types/webpack-bundle-analyzer": "^4.7.0"
  "@types/webpack-env": "^1.18.4"
  "@types/yargs": "17.0.33"
  "@typescript-eslint/eslint-plugin": "8.56.0"
  "@typescript-eslint/parser": "8.56.0"
  "@typescript-eslint/types": "^8.54.0"
  "@typescript-eslint/utils": "^8.9.0"
  "@visx/event": "3.12.0"
  "@visx/gradient": "3.12.0"
  "@visx/group": "3.12.0"
  "@visx/shape": "3.12.0"
  "@visx/tooltip": "3.12.0"
  "@welldone-software/why-did-you-render": "8.0.3"
  ansicolor: "2.0.3"
  autoprefixer: "10.4.21"
  axe-core: "^4.11.1"
  babel-jest: "29.7.0"
  babel-loader: "10.0.0"
  baron: "3.0.3"
  blob-polyfill: "9.0.20240710"
  brace: "0.11.1"
  browserslist: "^4.21.4"
  buffer: "6.0.3"
  calculate-size: "1.1.1"
  centrifuge: "5.5.3"
  chance: "^1.1.13"
  chrome-remote-interface: "0.33.3"
  classnames: "2.5.1"
  clsx: "^2.1.1"
  codeowners: "^5.1.1"
  combokeys: "^3.0.0"
  comlink: "4.4.2"
  common-tags: "1.8.2"
  confusing-browser-globals: "^1.0.11"
  copy-webpack-plugin: "13.0.0"
  core-js: "3.44.0"
  crashme: "0.0.15"
  croner: "^9.0.0"
  css-loader: "7.1.2"
  css-minimizer-webpack-plugin: "7.0.2"
  csstype: "3.1.3"
  cypress: "14.3.2"
  cypress-file-upload: "5.0.8"
  cypress-recurse: "^1.35.3"
  d3: "7.9.0"
  d3-force: "3.0.0"
  d3-interpolate: "3.0.1"
  d3-random: "^3.0.1"
  d3-scale-chromatic: "3.1.0"
  dangerously-set-html-content: "1.1.0"
  date-fns: "4.1.0"
  debounce-promise: "3.1.2"
  diff: "^8.0.0"
  dompurify: "3.3.2"
  downsample: "1.4.0"
  downshift: "^9.0.6"
  enquirer: "^2.4.1"
  esbuild: "0.25.8"
  esbuild-loader: "4.3.0"
  esbuild-plugin-browserslist: "^1.0.0"
  eslint: "9.32.0"
  eslint-config-prettier: "10.1.8"
  eslint-plugin-import: "^2.31.0"
  eslint-plugin-jest: "29.0.1"
  eslint-plugin-jest-dom: "^5.4.0"
  eslint-plugin-jsdoc: "52.0.2"
  eslint-plugin-jsx-a11y: "6.10.2"
  eslint-plugin-lodash: "8.0.0"
  eslint-plugin-no-barrel-files: "^1.1.1"
  eslint-plugin-react: "7.37.5"
  eslint-plugin-react-hooks: "5.2.0"
  eslint-plugin-react-prefer-function-component: "4.0.1"
  eslint-plugin-testing-library: "^7.0.0"
  eslint-plugin-unicorn: "^56.0.0"
  eslint-scope: "^8.1.0"
  eslint-webpack-plugin: "5.0.2"
  eventemitter3: "5.0.1"
  events: "3.3.0"
  expose-loader: "5.0.1"
  fast-deep-equal: "^3.1.3"
  fast-json-patch: "3.1.1"
  fast_array_intersect: "1.1.0"
  file-saver: "2.0.5"
  fishery: "^2.2.2"
  fork-ts-checker-webpack-plugin: "9.1.0"
  fs-extra: "^11.3.2"
  github-codeowners: "^0.2.1"
  glob: "11.1.0"
  history: "4.10.1"
  hoist-non-react-statics: "3.3.2"
  html-loader: "5.1.0"
  html-tags: "^5.1.0"
  html-webpack-plugin: "5.6.3"
  http-server: "14.1.1"
  i18next: "^25.0.0"
  i18next-browser-languagedetector: "^8.0.0"
  i18next-cli: "^1.48.0"
  i18next-pseudo: "^2.2.1"
  identity-obj-proxy: "^3.0.0"
  immer: "10.2.0"
  immutable: "^5.1.5"
  imports-loader: "^5.0.0"
  infinite-viewer: "^0.29.1"
  ini: "^5.0.0"
  is-hotkey: "0.2.0"
  ix: "^7.0.0"
  jest: "29.7.0"
  jest-canvas-mock: "2.5.2"
  jest-date-mock: "1.0.10"
  jest-environment-jsdom: "29.7.0"
  jest-fail-on-console: "3.3.1"
  jest-junit: "16.0.0"
  jest-matcher-utils: "29.7.0"
  jest-monocart-coverage: "^1.1.1"
  jest-watch-typeahead: "^2.2.2"
  jimp: "^1.6.0"
  jquery: "3.7.1"
  js-yaml: "^4.1.0"
  jsdom-testing-mocks: "^1.13.1"
  json-markup: "^1.1.0"
  json-source-map: "0.6.1"
  jsurl: "^0.1.5"
  kbar: "0.1.0-beta.48"
  known-css-properties: "^0.37.0"
  lerna: "9.0.5"
  leven: "^4.0.0"
  lodash: "^4.17.23"
  logfmt: "^1.3.2"
  lossless-json: "^4.1.1"
  lru-cache: "11.2.2"
  lru-memoize: "^1.1.0"
  lucene: "^2.1.1"
  madge: "^8.0.0"
  marked: "16.3.0"
  marked-mangle: "1.1.12"
  memoize-one: "6.0.0"
  micro-memoize: "^4.1.2"
  mini-css-extract-plugin: "2.9.2"
  ml-regression-polynomial: "^3.0.0"
  ml-regression-simple-linear: "^3.0.0"
  mock-raf: "1.0.1"
  moment: "2.30.1"
  moment-timezone: "0.5.47"
  monaco-editor: "0.34.1"
  monaco-promql: "1.8.0"
  moveable: "0.53.0"
  msw: "2.10.4"
  msw-storybook-addon: "^2.0.5"
  mutationobserver-shim: "0.3.7"
  nanoid: "^5.0.9"
  node-forge: "^1.3.1"
  node-notifier: "10.0.1"
  nx: "22.5.4"
  ol: "10.7.0"
  ol-ext: "4.0.36"
  ol-mapbox-style: "^13.0.1"
  open: "^10.2.0"
  openapi-types: "^12.1.3"
  ora: "^9.0.0"
  papaparse: "5.5.3"
  pdf-parse: "^1.1.1"
  plop: "^4.0.1"
  pluralize: "^8.0.0"
  postcss: "8.5.6"
  postcss-loader: "8.1.1"
  postcss-reporter: "7.1.0"
  postcss-scss: "4.0.9"
  prettier: "3.6.2"
  prismjs: "1.30.0"
  process: "^0.11.10"
  prom-client: "^15.1.3"
  publint: "^0.3.12"
  re-resizable: "6.11.2"
  react: "18.3.1"
  react-calendar: "^6.0.0"
  react-colorful: "5.6.1"
  react-custom-scrollbars-2: "4.5.0"
  react-data-grid: "grafana/react-data-grid#a10c748f40edc538425b458af4e471a8262ec4ed"
  react-diff-viewer-continued: "^3.4.0"
  react-dom: "18.3.1"
  react-draggable: "4.5.0"
  react-dropzone: "^14.2.3"
  react-highlight-words: "0.21.0"
  react-hook-form: "^7.49.2"
  react-i18next: "^15.0.0"
  react-inlinesvg: "4.2.0"
  react-loading-skeleton: "3.5.0"
  react-moveable: "0.56.0"
  react-redux: "9.2.0"
  react-refresh: "0.14.0"
  react-resizable: "3.0.5"
  react-responsive-carousel: "^3.2.23"
  react-router: "5.3.4"
  react-router-dom: "^6.26.1"
  react-router-dom-v5-compat: "^6.26.1"
  react-select: "5.10.2"
  react-select-event: "5.5.1"
  react-split-pane: "patch:react-split-pane@npm%3A0.1.92#~/.yarn/patches/react-split-pane-npm-0.1.92-93dbf51dff.patch"
  react-table: "7.8.0"
  react-transition-group: "4.4.5"
  react-use: "17.6.0"
  react-virtual: "2.10.4"
  react-virtualized-auto-sizer: "1.0.26"
  react-window: "1.8.11"
  react-window-infinite-loader: "1.0.10"
  reduce-reducers: "^1.0.4"
  redux: "5.0.1"
  redux-mock-store: "1.5.5"
  redux-thunk: "3.1.0"
  regenerator-runtime: "0.14.1"
  replace-in-file-webpack-plugin: "1.0.6"
  reselect: "5.1.1"
  rimraf: "6.0.1"
  rollup: "^4.22.4"
  rollup-plugin-copy: "3.5.0"
  rollup-plugin-esbuild: "6.2.1"
  rollup-plugin-node-externals: "^8.0.0"
  rollup-plugin-sourcemaps: "0.6.3"
  rollup-plugin-svg-import: "3.0.0"
  rxjs: "7.8.2"
  sass: "1.89.2"
  sass-loader: "16.0.5"
  selecto: "1.26.3"
  semver: "7.7.3"
  slate: "0.47.9"
  slate-plain-serializer: "0.7.13"
  slate-react: "0.22.10"
  smtp-tester: "^2.1.0"
  sql-formatter-plus: "^1.3.6"
  storybook: "^10.1.11"
  stream-browserify: "3.0.0"
  string-hash: "^1.1.3"
  string_decoder: "1.3.0"
  style-loader: "4.0.0"
  stylelint: "16.23.0"
  stylelint-config-sass-guidelines: "12.1.0"
  swagger-ui-react: "5.31.1"
  swc-loader: "0.2.6"
  symbol-observable: "4.0.0"
  systemjs: "6.15.1"
  terser-webpack-plugin: "5.3.14"
  testing-library-selector: "0.3.1"
  tinycolor2: "1.6.0"
  tracelib: "1.0.1"
  ts-jest: "29.4.0"
  ts-node: "10.9.2"
  tslib: "2.8.1"
  tsx: "^4.21.0"
  tween-functions: "^1.2.0"
  type-fest: "^4.18.2"
  typescript: "5.9.2"
  uplot: "1.6.32"
  uuid: "11.1.0"
  uwrap: "0.1.2"
  vis-data: "^8.0.0"
  vis-network: "10.0.2"
  webpack: "^5.105.0"
  webpack-assets-manifest: "^5.1.0"
  webpack-bundle-analyzer: "^4.10.2"
  webpack-cli: "6.0.1"
  webpack-livereload-plugin: "3.0.2"
  webpack-manifest-plugin: "5.0.1"
  webpack-merge: "5.10.0"
  webpack-subresource-integrity: "^5.2.0-rc.1"
  webpack-virtual-modules: "^0.6.2"
  webpackbar: "^7.0.0"
  whatwg-fetch: "3.6.20"
  xss: "^1.0.14"
  yaml: "^2.0.0"
  yargs: "^18.0.0"
  zod: "^4.3.0"
