{
 "title": "review submission accurate - WIP",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "rollup_resolution_prod", "label": "Resolution (Prod)", "query": "aggregations.*" }
  ]
 },
 "panels": [
  {
   "title": "Per platform",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(transformNull(summarize(aggregations.[[rollup_resolution_prod]].reviews.submission.platform.*, '[[interval]]', 'sum', false), 0), 5)"
    }
   ]
  },
  {
   "title": "Contribution Per platform",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "aliasByNode(divideSeries(#A, #B), 0)"
    }
   ]
  },
  {
   "title": "Per source",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 2,
     "target": "aliasByNode(transformNull(summarize(aggregations.[[rollup_resolution_prod]].reviews.submission.source.*email_sum, '[[interval]]', 'sum', false), 0), 5)"
    },
    {
     "refCount": 2,
     "target": "aliasByNode(transformNull(summarize(sumSeriesWithWildcards(aggregations.[[rollup_resolution_prod]].mobile_apps.main_app.*.all.counters.ugc.reviewsource_invite*.email_invite_count, 8), '[[interval]]', 'sum', false), 0), 4, 8)"
    },
    {
     "refCount": 1,
     "target": "alias(diffSeries(#B, sumSeries(#D)), 'other web')"
    },
    {
     "refCount": 1,
     "target": "aliasSub(aliasByNode(diffSeriesLists(#D, #C), 0), '(.*)', '${1}.other')"
    }
   ]
  },
  {
   "title": "Contribution Per source",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "refCount": 3,
     "target": "aliasSub(aliasByMetric(divideSeries(#A, #G)), '(.*)', '${1}.web')"
    },
    {
     "refCount": 3,
     "target": "aliasSub(aliasByNode(divideSeries(#C, #G), 4), '(.*)', '$1.email')"
    },
    {
     "refCount": 3,
     "target": "aliasSub(aliasByNode(divideSeries(#F, #G), 4), '(.*)', '${1}.other')"
    },
    {
     "refCount": 3,
     "target": "alias(divideSeries(#E, #G), 'web.other')"
    }
   ]
  }
 ]
}