// Code generated by mockery v2.53.4. DO NOT EDIT.

package jobs

import (
	context "context"

	repository "github.com/grafana/grafana/apps/provisioning/pkg/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockRepoGetter is an autogenerated mock type for the RepoGetter type
type MockRepoGetter struct {
	mock.Mock
}

type MockRepoGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepoGetter) EXPECT() *MockRepoGetter_Expecter {
	return &MockRepoGetter_Expecter{mock: &_m.Mock}
}

// GetRepository provides a mock function with given fields: ctx, namespace, name
func (_m *MockRepoGetter) GetRepository(ctx context.Context, namespace string, name string) (repository.Repository, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetRepository")
	}

	var r0 repository.Repository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (repository.Repository, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) repository.Repository); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Repository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepoGetter_GetRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepository'
type MockRepoGetter_GetRepository_Call struct {
	*mock.Call
}

// GetRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockRepoGetter_Expecter) GetRepository(ctx interface{}, namespace interface{}, name interface{}) *MockRepoGetter_GetRepository_Call {
	return &MockRepoGetter_GetRepository_Call{Call: _e.mock.On("GetRepository", ctx, namespace, name)}
}

func (_c *MockRepoGetter_GetRepository_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockRepoGetter_GetRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepoGetter_GetRepository_Call) Return(_a0 repository.Repository, _a1 error) *MockRepoGetter_GetRepository_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepoGetter_GetRepository_Call) RunAndReturn(run func(context.Context, string, string) (repository.Repository, error)) *MockRepoGetter_GetRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepoGetter creates a new instance of MockRepoGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepoGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepoGetter {
	mock := &MockRepoGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
