define([
  './panellinkeditor/module',
  './annotations/annotationsSrv',
  './templating/templateSrv',
  './graphite/datasource',
  './influxdb/datasource',
  './opentsdb/datasource',
  './elasticsearch/datasource',
  './dashboard/all',
  './account/accountCtrl',
  './account/collaboratorsCtrl',
  './account/datasourcesCtrl',
  './admin/accountsCtrl',
  './grafanaDatasource/datasource',
], function () {});
