define([
  './panellinkeditor/module',
  './annotations/annotationsSrv',
  './templating/templateSrv',
  './graphite/datasource',
  './influxdb/datasource',
  './opentsdb/datasource',
  './elasticsearch/datasource',
  './dashboard/all',
  './panel/all',
  './profile/profileCtrl',
  './profile/changePasswordCtrl',
  './account/all',
  './admin/all',
  './grafanaDatasource/datasource',
], function () {});
