/**
 * NOTE: This file was auto generated.  DO NOT EDIT DIRECTLY!
 * To change feature flags, edit:
 *  pkg/services/featuremgmt/registry.go
 * Then run:
 *  make gen-feature-toggles
 */

import "@openfeature/core";

declare module "@openfeature/core" {
  export type BooleanFlagKey =
    | "alertRuleRestore"
    | "alerting.dataSourceManagedRouteProxy"
    | "alerting.manualAssistantInvestigation"
    | "alerting.ruleQuality"
    | "alerting.syncExternalAlertmanager"
    | "alertingNavigationV2"
    | "alertingRuleRecoverDeleted"
    | "alertingTriage"
    | "analyticsFramework"
    | "assistant.dashboardPlanning"
    | "assistant.frontend.tools.dashboardTemplates"
    | "assistant.fullscreenWorkspace"
    | "awsAssumeRolePerDatasourceExternalId"
    | "canvasPanelNesting"
    | "canvasPanelPanZoom"
    | "dashboard.notebooks"
    | "dashboard.recentlyDeletedViaTrash"
    | "dashboard.vectorSearch"
    | "dashboardNewLayouts"
    | "dashboardTemplatesAssistantButton"
    | "dashboardUndoRedo"
    | "datasources.apiserver.useNewAPIsForDatasourceResources"
    | "datasources.azureMonitorBatchAPI"
    | "datasources.config.ui.useNewDatasourceCRUDAPIs"
    | "datasources.gatewayGuardrails"
    | "datasources.querier.newName"
    | "datasources.queryGateway"
    | "datasourcesApiServerEnableHealthEndpointFrontend"
    | "dataviz.experimentalColorSchemes"
    | "enableColorblindSafePanelOptions"
    | "enableExtensionsAdminPage"
    | "experimentRecentlyViewedDashboards"
    | "faroSessionReplay"
    | "feedbackButton"
    | "flameGraph.tableNg"
    | "foldersAppPlatformAPI"
    | "globalDashboardVariables"
    | "grafana.cmdkHybridSearch"
    | "grafana.customDashboardTemplates"
    | "grafana.customizableMegaMenu"
    | "grafana.dashboardAutoGridDefault"
    | "grafana.dashboardGlobalVariables"
    | "grafana.dashboardSettingsRedesign"
    | "grafana.dashboardsAutoHeightPanels"
    | "grafana.dynamicTraceToLogs"
    | "grafana.enableScopesFirstMode"
    | "grafana.exploreMetricsSidebar"
    | "grafana.filterablePanels"
    | "grafana.growthHomepage"
    | "grafana.kubernetesAnnotationsClient"
    | "grafana.logDetailsDisplayedFieldControls"
    | "grafana.logLevelInference"
    | "grafana.multiTenantNavTree"
    | "grafana.multiTenantUserPermissions"
    | "grafana.newPanelQueryErrorsUI"
    | "grafana.newTextPanel"
    | "grafana.onDemandDiagnostics"
    | "grafana.panelEditNextFeedbackEvent"
    | "grafana.panelPluginTransformations"
    | "grafana.pluginExtensionReactElementProps"
    | "grafana.pluginPathNesting"
    | "grafana.queryVarEditorRedesign"
    | "grafana.savedQueriesPage"
    | "grafana.scenesFlickeringFix"
    | "grafana.secretsReferenceValueUI"
    | "grafana.starredFolders"
    | "grafana.thresholdsInterpolation"
    | "grafana.unifiedDataSourcePicker"
    | "grafana.useDefaultScopesEndpoint"
    | "grafana.vectorSearchCmdk"
    | "grafana.viewPanelPane"
    | "grafana.visualDesignRefresh"
    | "inlineLogDetailsNoScrolls"
    | "kubernetesTeamsApi"
    | "libraryelements.kubernetesLibraryPanels"
    | "logsTablePanelNG"
    | "lokiShardSplitting"
    | "managedPluginsV2"
    | "newSavedQueriesExperience"
    | "otelLogsFormatting"
    | "paneledit.buttonLabels"
    | "perPanelNonApplicableDrilldowns"
    | "pieChartGradientColorScheme"
    | "playlistsRBAC"
    | "plugins.initDataSourcesAsync"
    | "plugins.useMTPluginSettings"
    | "plugins.useMTPlugins"
    | "provisioning.gitConventions"
    | "provisioning.readmes"
    | "provisioning.userAttribution"
    | "provisioningExport"
    | "provisioningFolderMetadata"
    | "queryEditorNext"
    | "queryHistory.localOnly"
    | "queryHistory.recentQueriesUI"
    | "queryLibrary"
    | "queryeditor.coauthoringUi"
    | "rawPrometheus.tableNg"
    | "recentlyViewedDashboards"
    | "reporting.anyPageReporting"
    | "reportingFooterSettings"
    | "reportingHeaderSettings"
    | "savedQueriesRBAC"
    | "secretsManagementAppPlatformUI"
    | "snapshots.kubernetesSnapshots"
    | "splashScreen"
    | "sqlExpressionsCodeMirror"
    | "sqlExpressionsColumnAutoComplete"
    | "stateTimeline.nameAboveBars"
    | "suggestedDashboardsAssistantButton"
    | "table.autoColumnWidths"
    | "table.inspectDataTableNG"
    | "table.paginationPageSize"
    | "table.refresh"
    | "table.refreshNewFeatures"
    | "tableSharedCrosshair"
    | "text.newFeatures"
    | "useKubernetesShortURLsAPI"
    | "vizActionsAuth";
  export type NumberFlagKey = never;
  export type StringFlagKey = never;
  export type ObjectFlagKey =
    | "grafana.mtFallback";
}
