/**
 * NOTE: This file was auto generated.  DO NOT EDIT DIRECTLY!
 * To change feature flags, edit:
 *  pkg/services/featuremgmt/registry.go
 * Then run:
 *  make gen-feature-toggles
 */

import "@openfeature/core";

declare module "@openfeature/core" {
  export type BooleanFlagKey =
    | "lokiShardSplitting"
    | "faroSessionReplay"
    | "queryHistory.localOnly"
    | "queryHistory.recentQueriesUI"
    | "awsAssumeRolePerDatasourceExternalId"
    | "provisioningFolderMetadata"
    | "provisioningExport"
    | "provisioning.readmes"
    | "provisioning.gitConventions"
    | "provisioning.userAttribution"
    | "snapshots.kubernetesSnapshots"
    | "libraryelements.kubernetesLibraryPanels"
    | "grafana.kubernetesAnnotationsClient"
    | "grafana.newPanelQueryErrorsUI"
    | "useKubernetesShortURLsAPI"
    | "dashboard.notebooks"
    | "feedbackButton"
    | "stateTimeline.nameAboveBars"
    | "grafana.secretsReferenceValueUI"
    | "sqlExpressionsColumnAutoComplete"
    | "sqlExpressionsCodeMirror"
    | "grafana.filterablePanels"
    | "grafana.savedQueriesPage"
    | "playlistsRBAC"
    | "newSavedQueriesExperience"
    | "grafana.customDashboardTemplates"
    | "dashboardTemplatesAssistantButton"
    | "suggestedDashboardsAssistantButton"
    | "alerting.manualAssistantInvestigation"
    | "alerting.ruleQuality"
    | "datasources.azureMonitorBatchAPI"
    | "recentlyViewedDashboards"
    | "experimentRecentlyViewedDashboards"
    | "otelLogsFormatting"
    | "grafana.starredFolders"
    | "grafana.newTextPanel"
    | "text.newFeatures"
    | "plugins.useMTPlugins"
    | "globalDashboardVariables"
    | "grafana.dashboardGlobalVariables"
    | "queryEditorNext"
    | "queryeditor.coauthoringUi"
    | "kubernetesTeamsApi"
    | "dashboard.recentlyDeletedViaTrash"
    | "managedPluginsV2"
    | "analyticsFramework"
    | "grafana.scenesFlickeringFix"
    | "grafana.viewPanelPane"
    | "datasourcesApiServerEnableHealthEndpointFrontend"
    | "flameGraphWithCallTree"
    | "flameGraph.tableNg"
    | "inlineLogDetailsNoScrolls"
    | "logsTablePanelNG"
    | "plugins.useMTPluginSettings"
    | "splashScreen"
    | "datasources.config.ui.useNewDatasourceCRUDAPIs"
    | "datasources.apiserver.useNewAPIsForDatasourceResources"
    | "reporting.anyPageReporting"
    | "assistant.frontend.tools.dashboardTemplates"
    | "alerting.syncExternalAlertmanager"
    | "grafana.enableScopesFirstMode"
    | "grafana.useDefaultScopesEndpoint"
    | "grafana.logLevelInference"
    | "plugins.initDataSourcesAsync"
    | "paneledit.buttonLabels"
    | "grafana.panelEditNextFeedbackEvent"
    | "grafana.visualDesignRefresh"
    | "dashboard.vectorSearch"
    | "grafana.vectorSearchCmdk"
    | "grafana.cmdkHybridSearch"
    | "assistant.fullscreenWorkspace"
    | "grafana.queryVarEditorRedesign"
    | "table.paginationPageSize"
    | "table.autoColumnWidths"
    | "table.refresh"
    | "table.inspectDataTableNG"
    | "dataviz.experimentalColorSchemes"
    | "grafana.customizableMegaMenu"
    | "grafana.dashboardSettingsRedesign"
    | "grafana.growthHomepage"
    | "grafana.onDemandDiagnostics"
    | "assistant.dashboardPlanning"
    | "grafana.multiTenantNavTree"
    | "grafana.exploreMetricsSidebar"
    | "grafana.dynamicTraceToLogs"
    | "grafana.thresholdsInterpolation"
    | "grafana.unifiedDataSourcePicker"
    | "rawPrometheus.tableNg"
    | "datasources.queryGateway"
    | "grafana.panelPluginTransformations"
    | "grafana.dashboardsAutoHeightPanels"
    | "grafana.dashboardAutoGridDefault";
  export type NumberFlagKey = never;
  export type StringFlagKey = never;
  export type ObjectFlagKey = never;
}
