{
 "title": "Azure App monitoring - Application Insights",
 "description": "Overview of different metrics for app monitoring through Application Insights.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "sub", "label": "Subscription", "query": "Subscriptions()" },
   { "name": "rg", "label": "Resource Group", "query": "ResourceGroups($sub)" },
   {
    "name": "res",
    "label": "Resource",
    "query": "ResourceNames($sub, $rg, microsoft.insights/components)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "<a style=\"color: inherit;\" href=\"https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/${sub}/resourceGroups/${rg}/providers/microsoft.insights/components/${res}/overview\" target=\"_blank\">\n  <div>\n    <h1> ${res} </h1>\n    <h5 style=\"margin-bottom: 0px;\"> Application Insights </h5>\n    <img src=\"https://cdn-images-1.medium.com/max/1600/0*m7zHr9EvegDjx8Si.png\" style=\"width:50px; height:25px; margin-left:140px;margin-bottom:35px\"/>\n  </div>\n</a>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": {
    "content": "<a style=\"color: inherit;\" href=\"https://ms.portal.azure.com/#blade/AppInsightsExtension/ProactiveDetectionFeedBlade/ComponentId/%7B%22Name%22%3A%22${res}%22%2C%22SubscriptionId%22%3A%22${sub}%22%2C%22ResourceGroup%22%3A%22${rg}%22%7D/TimeContext/%7B%22durationMs%22%3A604800000%2C%22endTime%22%3Anull%2C%22createdTime%22%3A%222021-10-18T19%3A26%3A58.876Z%22%2C%22isInitialTime%22%3Atrue%2C%22grain%22%3A1%2C%22useDashboardTimeRange%22%3Afalse%7D\" target=\"_blank\">\n<div style=\"padding-top: 20px\">\n  <center><h3 style=\"color: #4d99b8;\">Smart detection</h3></center>\n  <center><h4>${res}</h4></center>\n</div>\n</a>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": {
    "content": "<a style=\"color: inherit;\" href=\"https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/${sub}/resourceGroups/${rg}/providers/microsoft.insights/components/${res}/quickPulse\" target=\"_blank\">\n<div style=\"padding-top: 20px\">\n  <center><h3 style=\"color: #2272b9;\">Live Metrics</h3></center>\n  <center><h4>${res}</h4></center>\n</div>\n</a>\n           \n           "
   },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "alias": "Servers",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "requests/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc",
      "263177d8-32b8-465a-b939-be00c75e88c5"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "availabilityResults/availabilityPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc",
      "263177d8-32b8-465a-b939-be00c75e88c5"
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": {
    "content": "<a style=\"color: inherit;\" href=\"https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/${sub}/resourceGroups/${rg}/providers/microsoft.insights/components/${res}/applicationMap\" target=\"_blank\">\n<div>\n  <center><h2 style=\"position:center; padding-top: 10px; color: #ff8c00;\">App map</h2></center>\n  <center><h3>${res}</h3></center>\n</div>\n</a>\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": {
    "content": "<h1 style=\"font-size: 35px; color:#73bf69;\"> Usage </h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "requests/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc",
      "263177d8-32b8-465a-b939-be00c75e88c5"
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 4 },
   "options": {
    "content": "<h1 style=\"font-size:35px; color:#ec008c;\">Reliability</h1>"
   },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 1, "x": 10, "y": 4 },
   "options": {
    "content": "<a style=\"color: #ffffff;\"href=\"https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/${sub}/resourceGroups/${rg}/providers/microsoft.insights/components/${res}/failures\" target=\"_blank\">\n<div>\n  <img src=\"https://images.vexels.com/media/users/3/153978/isolated/preview/483ef8b10a46e28d02293a31570c8c56-warning-sign-colored-stroke-icon-by-vexels.png\" width=\"40px\"/>\n  <h5> Failures </h5>\n  <h6>${res}</h6>\n</div>\n</a>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 4 },
   "options": {
    "content": "<h1 style=\"font-size:35px; color:#7e58ff;\">Responsiveness</h1>"
   },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "options": {
    "content": "<a style=\"color: #ffffff;\"href=\"https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/${sub}/resourceGroups/${rg}/providers/microsoft.insights/components/${res}/performance\" target=\"_blank\">\n<div>\n  <img src=\"https://44s3b94691sl3smgmb1y936e-wpengine.netdna-ssl.com/wp-content/uploads/2016/12/performance-icon-png-6.png\" width=\"40px\" style=\"margin-bottom:10px\"/>\n  <h5> Performance </h5>\n  <h6>${res}</h6>\n</div>\n</a>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 4 },
   "options": {
    "content": "<h1 style=\"font-size:35px; color:#3274d9;\">Browser</h1>"
   },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 1, "x": 23, "y": 4 },
   "options": {
    "content": "<a style=\"color: #ffffff;\" href=\"https://ms.portal.azure.com/#blade/Microsoft_Azure_MonitoringMetrics/Metrics.ReactView/ResourceId/%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}/id/%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}/detailBlade/MetricsExplorerBlade/sourceExtension/AppInsightsExtension/TimeContext/%7B%22relative%22%3A%7B%22duration%22%3A86400000%7D%2C%22grain%22%3A1%2C%22options%22%3A%7B%22grain%22%3A1%2C%22showUTCTime%22%3Afalse%7D%7D/Chart/%7B%22v2charts%22%3A%5B%7B%22metrics%22%3A%5B%7B%22resourceMetadata%22%3A%7B%22id%22%3A%22%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}%22%2C%22sku%22%3A%7B%22name%22%3A%22${res}%22%7D%7D%2C%22metricVisualization%22%3A%7B%22resourceDisplayName%22%3A%22pageViews%2Fduration%22%2C%22color%22%3A%22msportalfx-bgcolor-g2%22%7D%2C%22name%22%3A%22pageViews%2Fduration%22%2C%22namespace%22%3A%22microsoft.insights%2Fcomponents%2Fkusto%22%2C%22aggregationType%22%3A4%7D%5D%2C%22visualization%22%3A%7B%22chartType%22%3A2%2C%22axisVisualization%22%3A%7B%22y%22%3A%7B%22isVisible%22%3Atrue%7D%7D%7D%2C%22grouping%22%3A%7B%22dimension%22%3A%22operation%2Fname%22%7D%2C%22filterCollection%22%3A%7B%22filters%22%3A%5B%7B%22key%22%3A%22client%2Ftype%22%2C%22operator%22%3A0%2C%22values%22%3A%5B%22Browser%22%5D%7D%5D%7D%2C%22title%22%3A%22Browsers%22%2C%22timespan%22%3A%7B%22relative%22%3A%7B%22duration%22%3A86400000%7D%2C%22grain%22%3A1%2C%22options%22%3A%7B%22grain%22%3A1%2C%22showUTCTime%22%3Afalse%7D%7D%7D%2C%7B%22metrics%22%3A%5B%7B%22resourceMetadata%22%3A%7B%22id%22%3A%22%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}%22%2C%22sku%22%3A%7B%22name%22%3A%22${res}%22%7D%7D%2C%22metricVisualization%22%3A%7B%22resourceDisplayName%22%3A%22dependencies%2Fduration%22%2C%22color%22%3A%22msportalfx-bgcolor-g2%22%7D%2C%22name%22%3A%22dependencies%2Fduration%22%2C%22namespace%22%3A%22microsoft.insights%2Fcomponents%2Fkusto%22%2C%22aggregationType%22%3A4%7D%5D%2C%22visualization%22%3A%7B%22chartType%22%3A2%2C%22axisVisualization%22%3A%7B%22y%22%3A%7B%22isVisible%22%3Atrue%7D%7D%7D%2C%22grouping%22%3A%7B%22dimension%22%3A%22dependency%2Fname%22%7D%2C%22filterCollection%22%3A%7B%22filters%22%3A%5B%7B%22key%22%3A%22client%2Ftype%22%2C%22operator%22%3A0%2C%22values%22%3A%5B%22Browser%22%5D%7D%5D%7D%2C%22title%22%3A%22Have%20AJAX%20calls%20been%20slow%3F%22%2C%22timespan%22%3A%7B%22relative%22%3A%7B%22duration%22%3A86400000%7D%2C%22grain%22%3A1%2C%22options%22%3A%7B%22grain%22%3A1%2C%22showUTCTime%22%3Afalse%7D%7D%7D%2C%7B%22metrics%22%3A%5B%7B%22resourceMetadata%22%3A%7B%22id%22%3A%22%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}%22%2C%22sku%22%3A%7B%22name%22%3A%22${res}%22%7D%7D%2C%22metricVisualization%22%3A%7B%22resourceDisplayName%22%3A%22pageViews%2Fcount%22%2C%22color%22%3A%22msportalfx-bgcolor-g2%22%7D%2C%22name%22%3A%22pageViews%2Fcount%22%2C%22namespace%22%3A%22microsoft.insights%2Fcomponents%2Fkusto%22%2C%22aggregationType%22%3A1%7D%5D%2C%22visualization%22%3A%7B%22chartType%22%3A2%2C%22axisVisualization%22%3A%7B%22y%22%3A%7B%22isVisible%22%3Atrue%7D%7D%7D%2C%22grouping%22%3A%7B%22dimension%22%3A%22operation%2Fname%22%7D%2C%22filterCollection%22%3A%7B%22filters%22%3A%5B%7B%22key%22%3A%22client%2Ftype%22%2C%22operator%22%3A0%2C%22values%22%3A%5B%22Browser%22%5D%7D%5D%7D%2C%22title%22%3A%22Has%20page%20view%20traffic%20changed%3F%22%2C%22timespan%22%3A%7B%22relative%22%3A%7B%22duration%22%3A86400000%7D%2C%22grain%22%3A1%2C%22options%22%3A%7B%22grain%22%3A1%2C%22showUTCTime%22%3Afalse%7D%7D%7D%2C%7B%22metrics%22%3A%5B%7B%22resourceMetadata%22%3A%7B%22id%22%3A%22%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}%22%2C%22sku%22%3A%7B%22name%22%3A%22${res}%22%7D%7D%2C%22metricVisualization%22%3A%7B%22resourceDisplayName%22%3A%22exceptions%2Fbrowser%22%2C%22color%22%3A%22msportalfx-bgcolor-g2%22%7D%2C%22name%22%3A%22exceptions%2Fbrowser%22%2C%22namespace%22%3A%22microsoft.insights%2Fcomponents%2Fkusto%22%2C%22aggregationType%22%3A1%7D%5D%2C%22visualization%22%3A%7B%22chartType%22%3A2%2C%22axisVisualization%22%3A%7B%22y%22%3A%7B%22isVisible%22%3Atrue%7D%7D%7D%2C%22grouping%22%3A%7B%22dimension%22%3A%22exception%2FproblemId%22%7D%2C%22filterCollection%22%3A%7B%22filters%22%3A%5B%7B%22key%22%3A%22client%2Ftype%22%2C%22operator%22%3A0%2C%22values%22%3A%5B%22Browser%22%5D%7D%5D%7D%2C%22title%22%3A%22When%20are%20script%20errors%20occurring%3F%22%2C%22timespan%22%3A%7B%22relative%22%3A%7B%22duration%22%3A86400000%7D%2C%22grain%22%3A1%2C%22options%22%3A%7B%22grain%22%3A1%2C%22showUTCTime%22%3Afalse%7D%7D%7D%2C%7B%22metrics%22%3A%5B%7B%22resourceMetadata%22%3A%7B%22id%22%3A%22%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}%22%2C%22sku%22%3A%7B%22name%22%3A%22${res}%22%7D%7D%2C%22metricVisualization%22%3A%7B%22resourceDisplayName%22%3A%22pageViews%2Fduration%22%2C%22color%22%3A%22msportalfx-bgcolor-g0%22%7D%2C%22name%22%3A%22pageViews%2Fduration%22%2C%22namespace%22%3A%22microsoft.insights%2Fcomponents%2Fkusto%22%2C%22aggregationType%22%3A4%7D%5D%2C%22visualization%22%3A%7B%22chartType%22%3A5%2C%22axisVisualization%22%3A%7B%22y%22%3A%7B%22isVisible%22%3Atrue%7D%7D%7D%2C%22grouping%22%3A%7B%22dimension%22%3Afalse%7D%2C%22filterCollection%22%3A%7B%22filters%22%3A%5B%7B%22key%22%3A%22client%2Ftype%22%2C%22operator%22%3A0%2C%22values%22%3A%5B%22Browser%22%5D%7D%5D%7D%2C%22title%22%3A%22What%20are%20my%20slowest%20pages%3F%22%7D%2C%7B%22metrics%22%3A%5B%7B%22resourceMetadata%22%3A%7B%22id%22%3A%22%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}%22%2C%22sku%22%3A%7B%22name%22%3A%22${res}%22%7D%7D%2C%22metricVisualization%22%3A%7B%22resourceDisplayName%22%3A%22pageViews%2Fduration%22%7D%2C%22name%22%3A%22pageViews%2Fduration%22%2C%22namespace%22%3A%22microsoft.insights%2Fcomponents%2Fkusto%22%2C%22aggregationType%22%3A4%7D%5D%2C%22visualization%22%3A%7B%22chartType%22%3A5%2C%22axisVisualization%22%3A%7B%22y%22%3A%7B%22isVisible%22%3Atrue%7D%7D%7D%2C%22grouping%22%3A%7B%22dimension%22%3Afalse%7D%2C%22filterCollection%22%3A%7B%22filters%22%3A%5B%7B%22key%22%3A%22client%2Ftype%22%2C%22operator%22%3A0%2C%22values%22%3A%5B%22Browser%22%5D%7D%5D%7D%2C%22title%22%3A%22What%20are%20my%20slowest%20pages%3F%22%7D%2C%7B%22metrics%22%3A%5B%7B%22resourceMetadata%22%3A%7B%22id%22%3A%22%2Fsubscriptions%2F${sub}%2FresourceGroups%2F${rg}%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2F${res}%22%2C%22sku%22%3A%7B%22name%22%3A%22${res}%22%7D%7D%2C%22metricVisualization%22%3A%7B%22resourceDisplayName%22%3A%22exceptions%2Fbrowser%22%2C%22color%22%3A%22msportalfx-bgcolor-d0%22%7D%2C%22name%22%3A%22exceptions%2Fbrowser%22%2C%22namespace%22%3A%22microsoft.insights%2Fcomponents%2Fkusto%22%2C%22aggregationType%22%3A1%7D%5D%2C%22visualization%22%3A%7B%22chartType%22%3A5%2C%22axisVisualization%22%3A%7B%22y%22%3A%7B%22isVisible%22%3Atrue%7D%7D%7D%2C%22grouping%22%3A%7B%22dimension%22%3A%22exception%2FproblemId%22%7D%2C%22filterCollection%22%3A%7B%22filters%22%3A%5B%7B%22key%22%3A%22client%2Ftype%22%2C%22operator%22%3A0%2C%22values%22%3A%5B%22Browser%22%5D%7D%5D%7D%2C%22title%22%3A%22What%20are%20my%20most%20common%20script%20errors%3F%22%2C%22timespan%22%3A%7B%22relative%22%3A%7B%22duration%22%3A86400000%7D%2C%22grain%22%3A1%2C%22options%22%3A%7B%22grain%22%3A1%2C%22showUTCTime%22%3Afalse%7D%7D%7D%5D%7D/openInEditMode/\" target=\"_blank\">\n<div style=\"padding-top: 35px; background-color: #3274d9; width: 100%; height: 100%\">\n  <center><h5> Browsers </h5></center>\n</div>\n</a>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "requests/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc",
      "263177d8-32b8-465a-b939-be00c75e88c5"
     ]
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 7 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    }
   ]
  },
  {
   "title": "Server response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 7 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "requests/duration",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    }
   ]
  },
  {
   "title": "Page Views",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "pageViews/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    }
   ]
  },
  {
   "title": "Average availability",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "availabilityResults/availabilityPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    }
   ]
  },
  {
   "title": "Server exceptions and Dependency failures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 6, "y": 16 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "exceptions/server",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "alias": "Dependency failures",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "dependencies/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    }
   ]
  },
  {
   "title": "Average processor and process CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 11, "y": 16 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "performanceCounters/processorCpuPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "performanceCounters/processCpuPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    }
   ]
  },
  {
   "title": "Average page load time breakdown",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "browserTimings/networkDuration",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "browserTimings/processingDuration",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "browserTimings/sendDuration",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "browserTimings/receiveDuration",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    }
   ]
  },
  {
   "title": "Availability test results count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "availabilityResults/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    }
   ]
  },
  {
   "title": "Average process I/O rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 6, "y": 26 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "performanceCounters/processIOBytesPerSecond",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    }
   ]
  },
  {
   "title": "Average available memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 11, "y": 26 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "performanceCounters/memoryAvailableBytes",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    }
   ]
  },
  {
   "title": "Browser exceptions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 26 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Insights/components",
      "metricName": "exceptions/browser",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "$rg",
      "resourceName": "$res",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "50"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub",
     "subscriptions": [
      "4dc2cd39-7a89-43d8-bebe-8bb501359891",
      "39a6a513-91ca-4958-aa57-8374048b16ab",
      "f7152080-b4e8-47ee-9c85-7f1d0e6b72dc"
     ]
    }
   ]
  }
 ]
}