// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     kinds/cog_gen.go
// Using jennies:
//     GoRuntime
//
// Run 'make gen-cue' from repository root to regenerate.

// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Using jennies:
//     GoRuntime

package cog

func ToPtr[T any](v T) *T {
	return &v
}
