/* eslint-disable @grafana/no-restricted-img-srcs */
import { isIconName, type NavLinkDTO } from '@grafana/data';

type PrototypeNavLink = Omit<NavLinkDTO, 'children' | 'icon'> & {
  children?: PrototypeNavLink[];
  icon?: string;
};

const prototypeTree: PrototypeNavLink[] = [
  {
    id: 'home',
    text: 'Home',
    icon: 'home-alt',
    url: '/a/grafana-setupguide-app/home',
    sortWeight: -4000,
  },
  {
    id: 'bookmarks',
    text: 'Bookmarks',
    icon: 'bookmark',
    url: '/bookmarks',
    sortWeight: -3900,
    emptyMessageId: 'bookmarks-empty',
  },
  {
    id: 'starred',
    text: 'Starred',
    icon: 'star',
    url: '/dashboards?starred',
    sortWeight: -3800,
    children: [
      {
        id: 'starred/da7a9aec-536e-4fe6-ac09-435795eede35',
        text: 'Rolling Release Channels Overview',
        url: '/d/da7a9aec-536e-4fe6-ac09-435795eede35/rolling-release-channels-overview',
      },
    ],
    emptyMessageId: 'starred-empty',
  },
  {
    id: 'dashboards/browse',
    text: 'Dashboards',
    subTitle: 'Create and manage dashboards to visualize your data',
    icon: 'apps',
    url: '/dashboards',
    sortWeight: -3700,
    children: [
      {
        id: 'dashboards/playlists',
        text: 'Playlists',
        subTitle: 'Groups of dashboards that are displayed in a sequence',
        icon: 'presentation-play',
        url: '/playlists',
      },
      {
        id: 'dashboards/snapshots',
        text: 'Snapshots',
        subTitle: 'Interactive, publicly available, point-in-time representations of dashboards',
        icon: 'camera',
        url: '/dashboard/snapshots',
      },
      {
        id: 'dashboards/library-panels',
        text: 'Library panels',
        subTitle: 'Reusable panels that can be added to multiple dashboards',
        icon: 'library-panel',
        url: '/library-panels',
      },
      {
        id: 'dashboards/public',
        text: 'Public dashboards',
        icon: 'library-panel',
        url: '/dashboard/public',
      },
      {
        id: 'dashboards/recently-deleted',
        text: 'Recently deleted',
        subTitle: 'Any items listed here for more than 30 days will be automatically deleted.',
        url: '/dashboard/recently-deleted',
      },
      {
        id: 'dashboards/new',
        text: 'New dashboard',
        icon: 'plus',
        url: '/dashboard/new',
        hideFromTabs: true,
        isCreateAction: true,
      },
      {
        id: 'dashboards/import',
        text: 'Import dashboard',
        subTitle: 'Import dashboard from file or Grafana.com',
        icon: 'plus',
        url: '/dashboard/import',
        hideFromTabs: true,
        isCreateAction: true,
      },
      {
        id: 'reports',
        text: 'Reporting',
        subTitle: 'Create and manage PDF reports distributed via e-mail',
        icon: 'file-alt',
        url: '/reports',
      },
    ],
  },
  {
    id: 'explore',
    text: 'Explore',
    subTitle: 'Explore your data',
    icon: 'compass',
    url: '/explore',
    sortWeight: -3600,
  },
  {
    id: 'drilldown',
    text: 'Drilldown',
    subTitle: "Drill down into your data using Grafana's powerful queryless apps",
    icon: 'drilldown',
    url: '/drilldown',
    sortWeight: -3500,
    children: [
      {
        id: 'plugin-page-grafana-metricsdrilldown-app',
        text: 'Metrics',
        subTitle:
          'Quickly find related metrics with a few clicks, without needing to write PromQL queries to retrieve metrics.',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-metricsdrilldown-app/2.0.7+d3e65954e6b610c13241e5c04e8a18559112fa84/public/plugins/grafana-metricsdrilldown-app/img/logo.svg',
        url: '/a/grafana-metricsdrilldown-app/drilldown',
        sortWeight: 1,
        isSection: true,
        pluginId: 'grafana-metricsdrilldown-app',
      },
      {
        id: 'plugin-page-grafana-lokiexplore-app',
        text: 'Logs',
        subTitle:
          'Visualize log volumes to easily detect anomalies or significant changes over time, without needing to compose LogQL queries.',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-lokiexplore-app/2.0.4+7d4f55fc501dacc3e5c13927889312ed5eab50cb/public/plugins/grafana-lokiexplore-app/img/logo.svg',
        url: '/a/grafana-lokiexplore-app/explore',
        sortWeight: 2,
        isSection: true,
        pluginId: 'grafana-lokiexplore-app',
      },
      {
        id: 'plugin-page-grafana-exploretraces-app',
        text: 'Traces',
        subTitle:
          'Use Rate, Errors, and Duration (RED) metrics derived from traces to investigate errors within complex distributed systems.',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-exploretraces-app/2.0.3+8426e7a8bef19aa677a3b5c269fca468426bb6a6/public/plugins/grafana-exploretraces-app/img/logo.svg',
        url: '/a/grafana-exploretraces-app/',
        sortWeight: 3,
        isSection: true,
        pluginId: 'grafana-exploretraces-app',
      },
      {
        id: 'plugin-page-grafana-pyroscope-app',
        text: 'Profiles',
        subTitle:
          'View and analyze high-level service performance, identify problem processes for optimization, and diagnose issues to determine root causes.',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-pyroscope-app/2.0.6/public/plugins/grafana-pyroscope-app/img/logo.svg',
        url: '/a/grafana-pyroscope-app/explore',
        sortWeight: 4,
        isSection: true,
        pluginId: 'grafana-pyroscope-app',
      },
      {
        id: 'plugin-page-grafana-sqldrilldown-app',
        text: 'SQL',
        subTitle:
          'Explore SQL databases from Grafana with a visual builder, schema-aware table explorer, and breakdown charts. No raw SQL required to get started.',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-sqldrilldown-app/1.0.1+cea9ea484ebd5d7bb673d2d87c004034956eca8b/public/plugins/grafana-sqldrilldown-app/img/logo.svg',
        url: '/a/grafana-sqldrilldown-app/explore',
        sortWeight: 5,
        isSection: true,
        pluginId: 'grafana-sqldrilldown-app',
      },
    ],
  },
  {
    id: 'plugin-page-grafana-assistant-app',
    text: 'Assistant',
    subTitle: 'AI-powered assistant for Grafana',
    icon: 'ai-sparkle',
    img: 'https://plugins-cdn.grafana-ops.net/grafana-assistant-app/2.0.19+003d8c69a1284ba6c39758c24b55f05226dbc085/public/plugins/grafana-assistant-app/img/logo.svg',
    url: '/a/grafana-assistant-app',
    sortWeight: -3400,
    isSection: true,
    children: [
      {
        text: 'Workspace',
        url: '/a/grafana-assistant-app/workspace',
        pluginId: 'grafana-assistant-app',
      },
      {
        text: 'Investigations',
        url: '/a/grafana-assistant-app/investigations',
        pluginId: 'grafana-assistant-app',
      },
      {
        text: 'Settings',
        url: '/a/grafana-assistant-app/settings',
        pluginId: 'grafana-assistant-app',
      },
    ],
    pluginId: 'grafana-assistant-app',
  },
  {
    id: 'alerts-and-incidents',
    text: 'Alerts & IRM',
    subTitle: 'Alerting and incident management apps',
    icon: 'bell',
    url: '/alerts-and-incidents',
    sortWeight: -3100,
    children: [
      {
        id: 'plugin-page-grafana-servicecenter-app',
        text: 'Service center',
        subTitle: 'Create and manage your services',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-servicecenter-app/1.3.0/public/plugins/grafana-servicecenter-app/img/logo.svg',
        url: '/a/grafana-servicecenter-app/services',
        sortWeight: 1,
        isSection: true,
        pluginId: 'grafana-servicecenter-app',
      },
      {
        id: 'alerting',
        text: 'Alerting',
        subTitle: 'Learn about problems in your systems moments after they occur',
        icon: 'bell',
        url: '/alerting',
        sortWeight: 2,
        children: [
          {
            id: 'alert-activity',
            text: 'Alert activity',
            subTitle: 'View alerts and active notifications',
            icon: 'bell',
            url: '/alerting/alerts',
            isNew: true,
          },
          {
            id: 'alert-rules',
            text: 'Alert rules',
            subTitle: 'Rules that determine whether an alert will fire',
            icon: 'list-ul',
            url: '/alerting/list',
          },
          {
            id: 'notification-config',
            text: 'Notification configuration',
            subTitle: 'Manage contact points, notification policies, templates, and time intervals',
            icon: 'comment-alt-share',
            url: '/alerting/notifications',
          },
          {
            id: 'silences',
            text: 'Silences',
            subTitle: 'Stop notifications from one or more alerting rules',
            icon: 'bell-slash',
            url: '/alerting/silences',
          },
          {
            id: 'alerts-history',
            text: 'History',
            icon: 'history',
            url: '/alerting/history',
          },
          {
            id: 'alert',
            text: 'Create alert rule',
            subTitle: 'Create an alert rule',
            icon: 'plus',
            url: '/alerting/new',
            hideFromTabs: true,
            isCreateAction: true,
          },
        ],
      },
      {
        id: 'plugin-page-grafana-irm-app',
        text: 'IRM',
        subTitle: 'Incident response and management',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-irm-app/0.96.0/public/plugins/grafana-irm-app/img/logo.svg',
        url: '/a/grafana-irm-app',
        sortWeight: 3,
        isSection: true,
        children: [
          {
            text: 'Alert groups',
            url: '/a/grafana-irm-app/alert-groups',
            pluginId: 'grafana-irm-app',
          },
          {
            text: 'Incidents',
            icon: 'columns',
            url: '/a/grafana-irm-app/incidents',
            pluginId: 'grafana-irm-app',
          },
          {
            text: 'Tasks',
            icon: 'check-circle',
            url: '/a/grafana-irm-app/tasks',
            pluginId: 'grafana-irm-app',
          },
          {
            text: 'Schedules',
            url: '/a/grafana-irm-app/schedules',
            pluginId: 'grafana-irm-app',
          },
          {
            text: 'Escalation chains',
            url: '/a/grafana-irm-app/escalations',
            pluginId: 'grafana-irm-app',
          },
          {
            text: 'Integrations',
            url: '/a/grafana-irm-app/integrations',
            pluginId: 'grafana-irm-app',
          },
          {
            text: 'Users',
            url: '/a/grafana-irm-app/users',
            pluginId: 'grafana-irm-app',
          },
          {
            text: 'Insights',
            url: '/a/grafana-irm-app/insights',
            pluginId: 'grafana-irm-app',
          },
          {
            text: 'Settings',
            url: '/a/grafana-irm-app/settings',
            pluginId: 'grafana-irm-app',
          },
        ],
        pluginId: 'grafana-irm-app',
      },
      {
        id: 'plugin-page-grafana-slo-app',
        text: 'SLO',
        subTitle: 'Create and manage Service Level Objectives',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-slo-app/1.86.0/public/plugins/grafana-slo-app/img/logo.svg',
        url: '/a/grafana-slo-app/home/insights',
        sortWeight: 4,
        isSection: true,
        children: [
          {
            text: 'Manage SLOs',
            url: '/a/grafana-slo-app/manage-slos',
            pluginId: 'grafana-slo-app',
          },
          {
            text: 'SLO performance',
            url: '/a/grafana-slo-app/slo-performance',
            pluginId: 'grafana-slo-app',
          },
          {
            text: 'Reports',
            url: '/a/grafana-slo-app/reports',
            pluginId: 'grafana-slo-app',
          },
        ],
        pluginId: 'grafana-slo-app',
      },
      {
        id: 'plugin-page-grafana-labelmanagement-app',
        text: 'Label management',
        subTitle: 'Manage labels across Grafana',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-labelmanagement-app/1.3.4/public/plugins/grafana-labelmanagement-app/img/logo.svg',
        url: '/a/grafana-labelmanagement-app',
        sortWeight: 5,
        isSection: true,
        pluginId: 'grafana-labelmanagement-app',
      },
    ],
  },
  {
    id: 'plugin-page-grafana-ml-app',
    text: 'Machine Learning',
    subTitle: 'Explore AI and machine learning features',
    icon: 'gf-ml-alt',
    img: 'https://plugins-cdn.grafana-ops.net/grafana-ml-app/1.35.4+d06774e8cbd65b787709adf1e2226cca82f9d844/public/plugins/grafana-ml-app/assets/logo.svg',
    url: '/a/grafana-ml-app/home',
    sortWeight: -3000,
    isSection: true,
    children: [
      {
        text: 'Metric forecasts',
        url: '/a/grafana-ml-app/metric-forecast',
        pluginId: 'grafana-ml-app',
      },
      {
        text: 'Outlier detection',
        url: '/a/grafana-ml-app/outlier-detector',
        pluginId: 'grafana-ml-app',
      },
      {
        text: 'Sift investigations',
        url: '/a/grafana-ml-app/investigations',
        pluginId: 'grafana-ml-app',
      },
    ],
    pluginId: 'grafana-ml-app',
  },
  {
    id: 'adaptive-telemetry',
    text: 'Adaptive Telemetry',
    subTitle:
      'Reduce noise, cut costs, and accelerate troubleshooting by intelligently ingesting only the telemetry data that matters most.',
    icon: 'adaptive-telemetry',
    img: 'https://plugins-cdn.grafana-ops.net/grafana-adaptive-metrics-app/1.8.0/public/plugins/grafana-adaptive-metrics-app/img/logo.svg',
    url: 'adaptive-telemetry',
    sortWeight: -2900,
    children: [
      {
        id: 'plugin-page-grafana-adaptive-metrics-app',
        text: 'Adaptive Metrics',
        subTitle:
          'Analyzes and reduces unused metrics and cardinality to help you focus on your most valuable performance data.',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-adaptive-metrics-app/1.8.0/public/plugins/grafana-adaptive-metrics-app/img/logo.svg',
        url: '/a/grafana-adaptive-metrics-app/overview',
        sortWeight: 1,
        isSection: true,
        children: [
          {
            text: 'Configuration',
            url: '/a/grafana-adaptive-metrics-app/configuration',
            pluginId: 'grafana-adaptive-metrics-app',
          },
          {
            text: 'Metrics',
            url: '/a/grafana-adaptive-metrics-app/rule-management',
            pluginId: 'grafana-adaptive-metrics-app',
          },
          {
            text: 'Segments',
            url: '/a/grafana-adaptive-metrics-app/segments',
            pluginId: 'grafana-adaptive-metrics-app',
          },
        ],
        pluginId: 'grafana-adaptive-metrics-app',
      },
      {
        id: 'plugin-page-grafana-adaptivelogs-app',
        text: 'Adaptive Logs',
        subTitle: 'Analyzes log patterns to drop repetitive lines and accelerate troubleshooting.',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-adaptivelogs-app/1.18.0/public/plugins/grafana-adaptivelogs-app/img/logo.svg',
        url: '/a/grafana-adaptivelogs-app/overview',
        sortWeight: 2,
        isSection: true,
        children: [
          {
            text: 'Drop rules',
            url: '/a/grafana-adaptivelogs-app/drop-rules',
            pluginId: 'grafana-adaptivelogs-app',
          },
          {
            text: 'Segments',
            url: '/a/grafana-adaptivelogs-app/segments',
            pluginId: 'grafana-adaptivelogs-app',
          },
          {
            text: 'Patterns',
            url: '/a/grafana-adaptivelogs-app/patterns',
            pluginId: 'grafana-adaptivelogs-app',
          },
          {
            text: 'Exemptions',
            url: '/a/grafana-adaptivelogs-app/exemptions',
            pluginId: 'grafana-adaptivelogs-app',
          },
        ],
        pluginId: 'grafana-adaptivelogs-app',
      },
      {
        id: 'plugin-page-grafana-adaptivetraces-app',
        text: 'Adaptive Traces',
        subTitle:
          'Analyzes and retains the most valuable traces, providing the performance insights needed to resolve issues faster.',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-adaptivetraces-app/1.14.0/public/plugins/grafana-adaptivetraces-app/img/logo.svg',
        url: '/a/grafana-adaptivetraces-app/overview',
        sortWeight: 3,
        isSection: true,
        children: [
          {
            text: 'Policies',
            url: '/a/grafana-adaptivetraces-app/policies',
            pluginId: 'grafana-adaptivetraces-app',
          },
        ],
        pluginId: 'grafana-adaptivetraces-app',
      },
      {
        id: 'plugin-page-grafana-adaptiveprofiles-app',
        text: 'Adaptive Profiles',
        subTitle:
          'Analyzes application profiles to pinpoint the root cause of performance issues and accelerate resolution.',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-adaptiveprofiles-app/0.15.2/public/plugins/grafana-adaptiveprofiles-app/img/logo.svg',
        url: '/a/grafana-adaptiveprofiles-app/overview',
        sortWeight: 4,
        isSection: true,
        children: [
          {
            text: 'Boosted Services',
            url: '/a/grafana-adaptiveprofiles-app/boosted-services',
            pluginId: 'grafana-adaptiveprofiles-app',
          },
        ],
        pluginId: 'grafana-adaptiveprofiles-app',
      },
    ],
    isNew: true,
  },
  {
    id: 'plugin-page-grafana-cmab-app',
    text: 'Cost Management and Billing',
    icon: 'cmab-logo',
    img: 'https://plugins-cdn.grafana-ops.net/grafana-cmab-app/1.16.0+3f97f07c/public/plugins/grafana-cmab-app/img/logo.svg',
    url: '/a/grafana-cmab-app/',
    sortWeight: -2800,
    isSection: true,
    children: [
      {
        text: 'Usage',
        url: '/a/grafana-cmab-app/usage',
        pluginId: 'grafana-cmab-app',
      },
      {
        text: 'Attributions',
        url: '/a/grafana-cmab-app/attributions',
        pluginId: 'grafana-cmab-app',
      },
      {
        text: 'Usage Alerts',
        url: '/a/grafana-cmab-app/usage-alerts',
        pluginId: 'grafana-cmab-app',
      },
      {
        text: 'Invoices',
        url: '/a/grafana-cmab-app/invoices',
        pluginId: 'grafana-cmab-app',
      },
      {
        text: 'Settings',
        url: '/a/grafana-cmab-app/settings',
        pluginId: 'grafana-cmab-app',
      },
      {
        text: 'Resources',
        url: '/a/grafana-cmab-app/resources',
        pluginId: 'grafana-cmab-app',
      },
    ],
    pluginId: 'grafana-cmab-app',
    isNew: true,
  },
  {
    id: 'testing-and-synthetics',
    text: 'Testing & synthetics',
    subTitle: 'Optimize performance with k6 and Synthetic Monitoring insights',
    icon: 'k6',
    url: '/testing-and-synthetics',
    sortWeight: -2700,
    children: [
      {
        id: 'plugin-page-k6-app',
        text: 'Performance',
        subTitle: 'Identify and analyze performance and reliability issues in your applications by executing k6 tests',
        img: 'https://plugins-cdn.grafana-ops.net/k6-app/0.112.1/public/plugins/k6-app/img/logo.svg',
        url: '/a/k6-app',
        sortWeight: 2,
        isSection: true,
        children: [
          {
            text: 'Projects',
            url: '/a/k6-app/projects',
            pluginId: 'k6-app',
          },
          {
            text: 'Settings',
            url: '/a/k6-app/settings',
            pluginId: 'k6-app',
          },
          {
            text: 'Learn',
            url: '/a/k6-app/learn',
            pluginId: 'k6-app',
          },
        ],
        pluginId: 'k6-app',
      },
      {
        id: 'plugin-page-grafana-synthetic-monitoring-app',
        text: 'Synthetics',
        subTitle: 'Worldwide black box monitoring for services and applications',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-synthetic-monitoring-app/1.52.0/public/plugins/grafana-synthetic-monitoring-app/img/logo.svg',
        url: '/a/grafana-synthetic-monitoring-app/home',
        sortWeight: 3,
        isSection: true,
        children: [
          {
            text: 'Checks',
            url: '/a/grafana-synthetic-monitoring-app/checks',
            pluginId: 'grafana-synthetic-monitoring-app',
          },
          {
            text: 'Probes',
            url: '/a/grafana-synthetic-monitoring-app/probes',
            pluginId: 'grafana-synthetic-monitoring-app',
          },
          {
            text: 'Alerts (Legacy)',
            url: '/a/grafana-synthetic-monitoring-app/alerts',
            pluginId: 'grafana-synthetic-monitoring-app',
          },
          {
            text: 'Config',
            url: '/a/grafana-synthetic-monitoring-app/config',
            pluginId: 'grafana-synthetic-monitoring-app',
          },
        ],
        pluginId: 'grafana-synthetic-monitoring-app',
      },
    ],
  },
  {
    id: 'observability',
    text: 'Observability',
    subTitle:
      "Monitor infrastructure and applications in real time with Grafana Cloud's fully managed observability suite",
    icon: 'heart-rate',
    url: '/observability',
    sortWeight: -2600,
    children: [
      {
        id: 'standalone-plugin-page-entity-graph',
        text: 'Entity graph',
        url: '/a/grafana-asserts-app/entities',
        sortWeight: -100,
        pluginId: 'grafana-asserts-app',
      },
      {
        id: 'standalone-plugin-page-entity-catalog',
        text: 'Entity catalog',
        url: '/a/grafana-asserts-app/catalog',
        sortWeight: -100,
        pluginId: 'grafana-asserts-app',
      },
      {
        id: 'standalone-plugin-page-rca-workbench',
        text: 'RCA workbench',
        url: '/a/grafana-asserts-app/assertions',
        sortWeight: -100,
        pluginId: 'grafana-asserts-app',
      },
      {
        id: 'standalone-plugin-page-health-target',
        text: 'Health target',
        url: '/a/grafana-asserts-app/slo',
        sortWeight: -100,
        pluginId: 'grafana-asserts-app',
      },
      {
        id: 'standalone-plugin-page-rules',
        text: 'Rules',
        url: '/a/grafana-asserts-app/rules',
        sortWeight: -100,
        pluginId: 'grafana-asserts-app',
      },
      {
        id: 'standalone-plugin-page-configuration',
        text: 'Configuration',
        url: '/a/grafana-asserts-app/configuration',
        sortWeight: -100,
        pluginId: 'grafana-asserts-app',
      },
      {
        id: 'plugin-page-grafana-kowalski-app',
        text: 'Frontend',
        subTitle: 'Real user monitoring for availability, performance, and correctness',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-kowalski-app/1.56.0+792d1c78/public/plugins/grafana-kowalski-app/logo.svg',
        url: '/a/grafana-kowalski-app',
        sortWeight: 3,
        isSection: true,
        children: [
          {
            text: 'Errors',
            url: '/a/grafana-kowalski-app/errors',
            pluginId: 'grafana-kowalski-app',
          },
          {
            text: 'Learn',
            url: '/a/grafana-kowalski-app/learn',
            pluginId: 'grafana-kowalski-app',
          },
        ],
        pluginId: 'grafana-kowalski-app',
      },
      {
        id: 'plugin-page-grafana-app-observability-app',
        text: 'Application',
        subTitle: 'Application Performance Monitoring based on OpenTelemetry and Prometheus',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-app-observability-app/1.75.3-b13ccf9-nightly/public/plugins/grafana-app-observability-app/img/logos/applicationObservability.svg',
        url: '/a/grafana-app-observability-app',
        sortWeight: 4,
        isSection: true,
        pluginId: 'grafana-app-observability-app',
      },
      {
        id: 'plugin-page-grafana-dbo11y-app',
        text: 'Database',
        subTitle: 'Gain insight into query performance and database health',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-dbo11y-app/2.23.0/public/plugins/grafana-dbo11y-app/img/dbo11y-logo.svg',
        url: '/a/grafana-dbo11y-app/',
        sortWeight: 5,
        isSection: true,
        children: [
          {
            text: 'Queries Overview',
            url: '/a/grafana-dbo11y-app/overview',
            pluginId: 'grafana-dbo11y-app',
          },
          {
            text: 'Configuration',
            url: '/a/grafana-dbo11y-app/configuration',
            pluginId: 'grafana-dbo11y-app',
          },
        ],
        pluginId: 'grafana-dbo11y-app',
        isNew: true,
      },
      {
        id: 'plugin-page-grafana-k8s-app',
        text: 'Kubernetes',
        subTitle: 'Observability for Kubernetes',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-k8s-app/2.33.0/public/plugins/grafana-k8s-app/img/k8s.png',
        url: '/a/grafana-k8s-app/home',
        sortWeight: 6,
        isSection: true,
        children: [
          {
            text: 'Search',
            url: '/a/grafana-k8s-app/search',
            pluginId: 'grafana-k8s-app',
          },
          {
            text: 'Clusters',
            url: '/a/grafana-k8s-app/navigation/cluster',
            pluginId: 'grafana-k8s-app',
          },
          {
            text: 'Namespaces',
            url: '/a/grafana-k8s-app/navigation/namespace',
            pluginId: 'grafana-k8s-app',
          },
          {
            text: 'Workloads',
            url: '/a/grafana-k8s-app/navigation/workload',
            pluginId: 'grafana-k8s-app',
          },
          {
            text: 'Nodes',
            url: '/a/grafana-k8s-app/navigation/nodes',
            pluginId: 'grafana-k8s-app',
          },
          {
            text: 'All jobs',
            url: '/a/grafana-k8s-app/navigation/all-jobs',
            pluginId: 'grafana-k8s-app',
          },
          {
            text: 'Cost',
            url: '/a/grafana-k8s-app/cost',
            pluginId: 'grafana-k8s-app',
          },
          {
            text: 'Alerts',
            url: '/a/grafana-k8s-app/alerts',
            pluginId: 'grafana-k8s-app',
          },
          {
            text: 'Configuration',
            url: '/a/grafana-k8s-app/configuration',
            pluginId: 'grafana-k8s-app',
          },
        ],
        pluginId: 'grafana-k8s-app',
      },
      {
        id: 'plugin-page-grafana-csp-app',
        text: 'Cloud provider',
        subTitle: 'Observability for cloud environments and services, including AWS, Azure, and GCP',
        icon: 'cloud-provider',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-csp-app/3.34.0/public/plugins/grafana-csp-app/img/CP-logo.svg',
        url: '/a/grafana-csp-app',
        sortWeight: 7,
        isSection: true,
        children: [
          {
            text: 'AWS',
            url: '/a/grafana-csp-app/aws',
            pluginId: 'grafana-csp-app',
          },
          {
            text: 'Azure',
            url: '/a/grafana-csp-app/azure',
            pluginId: 'grafana-csp-app',
          },
          {
            text: 'GCP',
            url: '/a/grafana-csp-app/gcp',
            pluginId: 'grafana-csp-app',
          },
        ],
        pluginId: 'grafana-csp-app',
      },
    ],
  },
  {
    id: 'connections',
    text: 'Connections',
    icon: 'adjust-circle',
    url: '/connections',
    sortWeight: -2100,
    children: [
      {
        id: 'standalone-plugin-page-/connections/infrastructure',
        text: 'Manage Integrations',
        url: '/connections/infrastructure',
        pluginId: 'grafana-easystart-app',
      },
      {
        id: 'standalone-plugin-page-/a/grafana-collector-app/fleet-management',
        text: 'Fleet Management',
        url: '/a/grafana-collector-app/fleet-management',
        sortWeight: 3,
        pluginId: 'grafana-collector-app',
      },
      {
        id: 'standalone-plugin-page-/connections/add-new-connection',
        text: 'Add new connection',
        url: '/connections/add-new-connection',
        sortWeight: 4,
        pluginId: 'grafana-easystart-app',
      },
      {
        id: 'standalone-plugin-page-/connections/private-data-source-connections',
        text: 'Private data source connect',
        url: '/connections/private-data-source-connections',
        pluginId: 'grafana-pdc-app',
      },
    ],
  },
  {
    id: 'apps',
    text: 'More apps',
    subTitle: 'App plugins that extend the Grafana experience',
    icon: 'layer-group',
    url: '/apps',
    sortWeight: -2000,
    children: [
      {
        id: 'plugin-page-grafana-dssql-app',
        text: 'Grafana Data Sources SQL',
        subTitle: 'SQL datasource and schema browser for cross-datasource SQL querying.',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-dssql-app/1.0.0+1ae7f3a30b233dfc06288faccab1078b57133a85/public/plugins/grafana-dssql-app/img/logo.svg',
        url: '/a/grafana-dssql-app/schema',
        sortWeight: -1900,
        isSection: true,
        pluginId: 'grafana-dssql-app',
      },
      {
        id: 'plugin-page-grafana-extensionsdependencygraph-app',
        text: 'Extensions Dependency Graph',
        subTitle:
          'The graph shows how the installed plugins depend on one another through the Plugin Extensions framework. The information is derived from the extension settings specified in each plugin’s plugin.json file.',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-extensionsdependencygraph-app/1.0.6/public/plugins/grafana-extensionsdependencygraph-app/img/logo.svg',
        url: '/a/grafana-extensionsdependencygraph-app/dependency-graph',
        sortWeight: -1900,
        isSection: true,
        pluginId: 'grafana-extensionsdependencygraph-app',
      },
      {
        id: 'plugin-page-grafana-logvolumeexplorer-app',
        text: 'Log Volume Explorer',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-logvolumeexplorer-app/0.17.3/public/plugins/grafana-logvolumeexplorer-app/img/logsVolExp.svg',
        url: '/a/grafana-logvolumeexplorer-app',
        sortWeight: -1900,
        isSection: true,
        children: [
          {
            text: 'Overview',
            icon: 'question-circle',
            url: '/a/grafana-logvolumeexplorer-app/overview',
            pluginId: 'grafana-logvolumeexplorer-app',
          },
          {
            text: 'Explorer',
            url: '/a/grafana-logvolumeexplorer-app/log-volume-explorer',
            pluginId: 'grafana-logvolumeexplorer-app',
          },
        ],
        pluginId: 'grafana-logvolumeexplorer-app',
      },
      {
        id: 'plugin-page-grafana-odin-app',
        text: 'Grafana Experiments',
        subTitle: 'Experiment orchestration with Grafana',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-odin-app/1.0.0+74f762d609097e2e124020eb728ea1631bc6639a/public/plugins/grafana-odin-app/img/logo.svg',
        url: '/a/grafana-odin-app/experiments',
        sortWeight: -1900,
        isSection: true,
        pluginId: 'grafana-odin-app',
      },
      {
        id: 'plugin-page-grafana-profilingworkbench-app',
        text: 'Profiling Workbench',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-profilingworkbench-app/1.0.8/public/plugins/grafana-profilingworkbench-app/img/logo.svg',
        url: '/a/grafana-profilingworkbench-app/home',
        sortWeight: -1900,
        isSection: true,
        pluginId: 'grafana-profilingworkbench-app',
      },
      {
        id: 'plugin-page-grafana-sessionreplay-app',
        text: 'Session Replay',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-sessionreplay-app/0.0.8/public/plugins/grafana-sessionreplay-app/img/logo.svg',
        url: '/a/grafana-sessionreplay-app',
        sortWeight: -1900,
        isSection: true,
        pluginId: 'grafana-sessionreplay-app',
      },
      {
        id: 'plugin-page-grafana-vulnerabilityobs-app',
        text: 'Vulnerability Observability',
        subTitle: 'Security',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-vulnerabilityobs-app/0.6.51/public/plugins/grafana-vulnerabilityobs-app/img/logo.svg',
        url: '/a/grafana-vulnerabilityobs-app',
        sortWeight: -1900,
        isSection: true,
        children: [
          {
            text: 'Projects',
            icon: 'folder',
            url: '/a/grafana-vulnerabilityobs-app/projects',
            pluginId: 'grafana-vulnerabilityobs-app',
          },
          {
            text: 'Kubernetes',
            icon: 'columns',
            url: '/a/grafana-vulnerabilityobs-app/k8s',
            pluginId: 'grafana-vulnerabilityobs-app',
          },
          {
            text: 'CVEs',
            icon: 'bug',
            url: '/a/grafana-vulnerabilityobs-app/cves',
            pluginId: 'grafana-vulnerabilityobs-app',
          },
          {
            text: 'Bug Bounty',
            icon: 'columns',
            url: '/a/grafana-vulnerabilityobs-app/bug-bounty',
            pluginId: 'grafana-vulnerabilityobs-app',
          },
          {
            text: 'Integrations',
            icon: 'columns',
            url: '/a/grafana-vulnerabilityobs-app/integrations',
            pluginId: 'grafana-vulnerabilityobs-app',
          },
          {
            text: 'First Party',
            icon: 'search',
            url: '/a/grafana-vulnerabilityobs-app/first-party',
            pluginId: 'grafana-vulnerabilityobs-app',
          },
          {
            text: 'Settings',
            icon: 'columns',
            url: '/a/grafana-vulnerabilityobs-app/settings',
            pluginId: 'grafana-vulnerabilityobs-app',
          },
        ],
        pluginId: 'grafana-vulnerabilityobs-app',
      },
      {
        id: 'plugin-page-grafana-workflows-app',
        text: 'Workflows',
        img: 'https://plugins-cdn.grafana-ops.net/grafana-workflows-app/1.2.0/public/plugins/grafana-workflows-app/img/logo.svg',
        url: '/a/grafana-workflows-app',
        sortWeight: -1900,
        isSection: true,
        children: [
          {
            text: 'Workflows List',
            url: '/a/grafana-workflows-app/workflows',
            pluginId: 'grafana-workflows-app',
          },
          {
            text: 'Secrets',
            url: '/a/grafana-workflows-app/secrets',
            pluginId: 'grafana-workflows-app',
          },
        ],
        pluginId: 'grafana-workflows-app',
      },
    ],
  },
  {
    id: 'cfg',
    text: 'Administration',
    subTitle: 'Organization: Main Org.',
    icon: 'cog',
    url: '/admin',
    sortWeight: -1800,
    children: [
      {
        id: 'cfg/plugins',
        text: 'Plugins and data',
        subTitle: 'Install plugins and define the relationships between data',
        icon: 'shield',
        url: '/admin/plugins',
        children: [
          {
            id: 'correlations',
            text: 'Correlations',
            subTitle: 'Add and configure correlations',
            icon: 'gf-glue',
            url: '/datasources/correlations',
          },
        ],
      },
      {
        id: 'cfg/access',
        text: 'Users and access',
        subTitle: 'Configure access for individual users, teams, and service accounts',
        icon: 'shield',
        url: '/admin/access',
        children: [
          {
            id: 'global-users',
            text: 'Users',
            subTitle: 'Manage users in Grafana',
            icon: 'user',
            url: '/admin/users',
          },
          {
            id: 'teams',
            text: 'Teams',
            subTitle: 'Groups of users that have common dashboard and permission needs',
            icon: 'users-alt',
            url: '/org/teams',
          },
          {
            id: 'serviceaccounts',
            text: 'Service accounts',
            subTitle: 'Use service accounts to run automated workloads in Grafana',
            icon: 'gf-service-account',
            url: '/org/serviceaccounts',
          },
        ],
      },
    ],
  },
  {
    id: 'profile',
    text: 'Sean Griffin',
    subTitle: 'sean.griffin@grafana.com',
    img: '/avatar/28a6bb7e109710ac0c95c5f55523fd6b333cb09be60a866e7dab138967a39e53',
    url: '/profile',
    sortWeight: -1700,
    roundIcon: true,
    children: [
      {
        id: 'profile/settings',
        text: 'Profile',
        icon: 'sliders-v-alt',
        url: '/profile',
      },
      {
        id: 'profile/notifications',
        text: 'Notification history',
        icon: 'bell',
        url: '/profile/notifications',
      },
    ],
  },
  {
    id: 'help',
    text: 'Help',
    icon: 'question-circle',
    url: '#',
    sortWeight: -1600,
    hideFromTabs: true,
  },
];

export const tree: NavLinkDTO[] = prototypeTree.map(toNavLinkDTO);

function toNavLinkDTO(item: PrototypeNavLink): NavLinkDTO {
  const { children, icon, ...navItem } = item;

  return {
    ...navItem,
    children: children?.map(toNavLinkDTO),
    icon: isIconName(icon) ? icon : undefined,
  };
}
