{
 "title": "EBS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "statistic", "label": "Statistic", "query": "statistics()" },
   {
    "name": "volume",
    "label": "Volume",
    "query": "dimension_values($region, AWS/EBS, , VolumeId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume Read Bytes $statistic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "VolumeId": "$volume" },
     "metricName": "VolumeReadBytes",
     "namespace": "AWS/EBS",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Volume Write Bytes $statistic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "VolumeId": "$volume" },
     "metricName": "VolumeWriteBytes",
     "namespace": "AWS/EBS",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Volume Total Read Time $statistic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "VolumeId": "$volume" },
     "metricName": "VolumeTotalReadTime",
     "namespace": "AWS/EBS",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Volume Total Write Time $statistic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "VolumeId": "$volume" },
     "metricName": "VolumeTotalWriteTime",
     "namespace": "AWS/EBS",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Volume Read Ops $statistic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "VolumeId": "$volume" },
     "metricName": "VolumeReadOps",
     "namespace": "AWS/EBS",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Volume Write Ops $statistic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "VolumeId": "$volume" },
     "metricName": "VolumeWriteOps",
     "namespace": "AWS/EBS",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Volume Idle Time $statistic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "VolumeId": "$volume" },
     "metricName": "VolumeIdleTime",
     "namespace": "AWS/EBS",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Volume Queue Length $statistic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "VolumeId": "$volume" },
     "metricName": "VolumeQueueLength",
     "namespace": "AWS/EBS",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Burst Balance Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "VolumeId": "$volume" },
     "metricName": "BurstBalance",
     "namespace": "AWS/EBS",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}