{
 "title": "EC2",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "query": "regions()" },
   { "name": "statistic", "query": "statistics()" },
   {
    "name": "instance",
    "query": "dimension_values($region, AWS/EC2, , InstanceId)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance" },
     "metricName": "DiskReadBytes",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Disk Read Ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance" },
     "metricName": "DiskReadOps",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Disk Write Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance" },
     "metricName": "DiskWriteOps",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Disk Write Ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance" },
     "metricName": "DiskWriteOps",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Network In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance" },
     "metricName": "Network In",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance" },
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Network Packets In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance" },
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Status Check Failed sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance" },
     "metricName": "StatusCheckFailed",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Status Check Failed Instance sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance" },
     "metricName": "StatusCheckFailed_Instance",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Status Check Failed System sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance" },
     "metricName": "StatusCheckFailed_System",
     "namespace": "AWS/EC2",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  }
 ]
}