{
 "title": "Lambda",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "statistic", "label": "Statistic", "query": "statistics()" },
   {
    "name": "function",
    "label": "FunctionName",
    "query": "dimension_values($region, AWS/Lambda, , FunctionName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Invocations $statistic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "FunctionName": "$function" },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "region": "$region",
     "statistics": [ "$statistic" ]
    }
   ]
  },
  {
   "title": "Duration Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "FunctionName": "$function" },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Errors $statistic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "FunctionName": "$function" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Throttles $statistic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "FunctionName": "$function" },
     "metricName": "Throttles",
     "namespace": "AWS/Lambda",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}