###
# create parent folder
# @name createParent
POST http://admin:admin@localhost:3000/api/folders
content-type: application/json

{
    "title": "Parent folder",
    "description": "Folder with sub-folders"
}

###
# list folders under root
GET http://admin:admin@localhost:3000/api/folders
content-type: application/json

###
@parentUID = {{createParent.response.body.uid}}
{{parentUID}}

###
GET http://admin:admin@localhost:3000/api/folders/{{parentUID}}


###
# create subfolder
# @name createSubFolder
POST http://admin:admin@localhost:3000/api/folders
content-type: application/json

{
    "title": "Subfolder",
    "description": "Folder with parent",
    "parentUid": "{{parentUID}}"
}

###
# get created subfolder
GET http://admin:admin@localhost:3000/api/folders/{{subfolderUID}}
content-type: application/json


###
@subfolderUID = {{createSubFolder.response.body.uid}}
{{subfolderUID}}

###
# update subfolder title and description
PUT http://admin:admin@localhost:3000/api/folders/{{subfolderUID}}
content-type: application/json

{
    "title": "Subfolder 1",
    "description": "Folder with parent 1",
    "overwrite": true
}

###
# get updated subfolder
GET http://admin:admin@localhost:3000/api/folders/{{subfolderUID}}
content-type: application/json

###
# update subfolder UID
PUT http://admin:admin@localhost:3000/api/folders/{{subfolderUID}}
content-type: application/json

{
    "uid": "42",
    "overwrite": true
}

###
# get updated subfolder
GET http://admin:admin@localhost:3000/api/folders/42
content-type: application/json

###
# delete parent folder; it should delete also subfolders
DELETE http://admin:admin@localhost:3000/api/folders/{{parentUID}}

###
# attempt to delete the subfolder should fail since it should have been deleted by the previous request
DELETE http://admin:admin@localhost:3000/api/folders/42