#!/usr/bin/env bash
set -eo pipefail

. scripts/grafana-server/variables

HOST=${HOST:-$DEFAULT_HOST}
PORT=${PORT:-$DEFAULT_PORT}

printf "Waiting for grafana-server to finish starting, host=%s, port=%s" "$HOST" "$PORT"

while ! curl -s -f http://$HOST:$PORT/health > /dev/null 2>&1; do
  printf "."
  sleep 1
done

printf "\n"
