// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     CRDWireSetJenny
//
// Run 'make gen-cue' from repository root to regenerate.

package preferences

import (
	"github.com/google/wire"
)

var GeneratedWireSet = wire.NewSet(
	ProvideWatcher,
	wire.Bind(new(Watcher), new(*watcher)),
)
