/* eslint-disable @typescript-eslint/consistent-type-assertions */
import {
  PluginIncludeType,
  PluginLoadingStrategy,
  type PluginMeta,
  PluginSignatureStatus,
  PluginSignatureType,
  type PluginState,
  PluginType,
} from '@grafana/data';

export const legacyMyOrgTestAppSettings: PluginMeta = structuredClone({
  name: 'Test',
  type: PluginType.app,
  id: 'myorg-test-app',
  enabled: true,
  pinned: false,
  autoEnabled: false,
  module: 'public/plugins/myorg-test-app/module.js',
  baseUrl: 'public/plugins/myorg-test-app',
  info: {
    author: {
      name: 'Myorg',
      url: '',
    },
    description: '',
    links: [],
    logos: {
      small: 'public/plugins/myorg-test-app/img/logo.svg',
      large: 'public/plugins/myorg-test-app/img/logo.svg',
    },
    build: {},
    screenshots: [],
    version: '1.0.0',
    updated: '2026-04-20',
    keywords: ['app'],
  },
  includes: [
    {
      name: 'Page One',
      path: '/a/myorg-test-app/one',
      type: PluginIncludeType.page,
      component: '',
      role: 'Viewer',
      action: 'plugins.app:access',
      addToNav: true,
      defaultNav: true,
      slug: 'page-one',
      icon: '',
      uid: '',
    },
    {
      name: 'Page Two',
      path: '/a/myorg-test-app/two',
      type: PluginIncludeType.page,
      component: '',
      role: 'Viewer',
      action: 'plugins.app:access',
      addToNav: true,
      defaultNav: false,
      slug: 'page-two',
      icon: '',
      uid: '',
    },
    {
      name: 'Page Three',
      path: '/a/myorg-test-app/three',
      type: PluginIncludeType.page,
      component: '',
      role: 'Viewer',
      action: 'plugins.app:access',
      addToNav: true,
      defaultNav: false,
      slug: 'page-three',
      icon: '',
      uid: '',
    },
    {
      name: 'Page Four',
      path: '/a/myorg-test-app/four',
      type: PluginIncludeType.page,
      component: '',
      role: 'Viewer',
      action: 'plugins.app:access',
      addToNav: true,
      defaultNav: false,
      slug: 'page-four',
      icon: '',
      uid: '',
    },
    {
      name: 'Configuration',
      path: '/plugins/myorg-test-app',
      type: PluginIncludeType.page,
      component: '',
      role: 'Admin',
      addToNav: true,
      defaultNav: false,
      slug: 'configuration',
      icon: 'cog',
      uid: '',
    },
  ],
  dependencies: {
    grafanaDependency: '\u003e=12.3.0',
    grafanaVersion: '*',
    plugins: [],
    extensions: {
      exposedComponents: [],
    },
  },
  extensions: {
    addedLinks: [],
    addedComponents: [],
    exposedComponents: [],
    extensionPoints: [],
    addedFunctions: [],
  },
  jsonData: {
    apiUrl: 'http://api-url.com',
  },
  secureJsonFields: {
    apiKey: true,
    password: true,
  },
  defaultNavUrl: '/plugins/myorg-test-app/page/page-one',
  latestVersion: '',
  hasUpdate: false,
  state: '' as PluginState,
  signature: 'unsigned' as PluginSignatureStatus,
  signatureType: '' as PluginSignatureType,
  signatureOrg: '',
  angularDetected: false,
  loadingStrategy: PluginLoadingStrategy.script,
});

export const legacyClockPanelOnPrem: PluginMeta = structuredClone({
  name: 'Clock',
  type: PluginType.panel,
  id: 'grafana-clock-panel',
  enabled: false,
  pinned: false,
  autoEnabled: false,
  module: 'public/plugins/grafana-clock-panel/module.js',
  baseUrl: 'public/plugins/grafana-clock-panel',
  info: {
    author: {
      name: 'Grafana Labs',
      url: 'https://grafana.com',
    },
    description: 'Clock panel for grafana',
    links: [
      {
        name: 'Project site',
        url: 'https://github.com/grafana/clock-panel',
      },
      {
        name: 'MIT License',
        url: 'https://github.com/grafana/clock-panel/blob/master/LICENSE',
      },
    ],
    logos: {
      small: 'public/plugins/grafana-clock-panel/img/clock.svg',
      large: 'public/plugins/grafana-clock-panel/img/clock.svg',
    },
    build: {},
    screenshots: [
      {
        name: 'Showcase',
        path: 'public/plugins/grafana-clock-panel/img/screenshot-showcase.png',
      },
      {
        name: 'Options',
        path: 'public/plugins/grafana-clock-panel/img/screenshot-clock-options.png',
      },
    ],
    version: '3.2.2',
    updated: '2026-02-17',
    keywords: ['clock', 'panel'],
  },
  includes: [],
  dependencies: {
    grafanaDependency: '>=11.0.0',
    grafanaVersion: '*',
    plugins: [],
    extensions: {
      exposedComponents: [],
    },
  },
  extensions: {
    addedLinks: [],
    addedComponents: [],
    exposedComponents: [],
    extensionPoints: [],
    addedFunctions: [],
  },
  jsonData: {},
  secureJsonFields: {},
  defaultNavUrl: '',
  latestVersion: '',
  hasUpdate: false,
  state: '' as PluginState,
  signature: PluginSignatureStatus.valid,
  signatureType: PluginSignatureType.grafana,
  signatureOrg: 'Grafana Labs',
  angularDetected: false,
  loadingStrategy: PluginLoadingStrategy.script,
  translations: {
    'cs-CZ': 'public/plugins/grafana-clock-panel/locales/cs-CZ/grafana-clock-panel.json',
    'de-DE': 'public/plugins/grafana-clock-panel/locales/de-DE/grafana-clock-panel.json',
    'en-US': 'public/plugins/grafana-clock-panel/locales/en-US/grafana-clock-panel.json',
    'es-ES': 'public/plugins/grafana-clock-panel/locales/es-ES/grafana-clock-panel.json',
    'fr-FR': 'public/plugins/grafana-clock-panel/locales/fr-FR/grafana-clock-panel.json',
    'hu-HU': 'public/plugins/grafana-clock-panel/locales/hu-HU/grafana-clock-panel.json',
    'id-ID': 'public/plugins/grafana-clock-panel/locales/id-ID/grafana-clock-panel.json',
    'it-IT': 'public/plugins/grafana-clock-panel/locales/it-IT/grafana-clock-panel.json',
    'ja-JP': 'public/plugins/grafana-clock-panel/locales/ja-JP/grafana-clock-panel.json',
    'ko-KR': 'public/plugins/grafana-clock-panel/locales/ko-KR/grafana-clock-panel.json',
    'nl-NL': 'public/plugins/grafana-clock-panel/locales/nl-NL/grafana-clock-panel.json',
    'pl-PL': 'public/plugins/grafana-clock-panel/locales/pl-PL/grafana-clock-panel.json',
    'pt-BR': 'public/plugins/grafana-clock-panel/locales/pt-BR/grafana-clock-panel.json',
    'pt-PT': 'public/plugins/grafana-clock-panel/locales/pt-PT/grafana-clock-panel.json',
    'ru-RU': 'public/plugins/grafana-clock-panel/locales/ru-RU/grafana-clock-panel.json',
    'sv-SE': 'public/plugins/grafana-clock-panel/locales/sv-SE/grafana-clock-panel.json',
    'tr-TR': 'public/plugins/grafana-clock-panel/locales/tr-TR/grafana-clock-panel.json',
    'zh-Hans': 'public/plugins/grafana-clock-panel/locales/zh-Hans/grafana-clock-panel.json',
    'zh-Hant': 'public/plugins/grafana-clock-panel/locales/zh-Hant/grafana-clock-panel.json',
  },
});
