import { type Settings } from '../types';

export const myOrgTestAppSettings: Settings = structuredClone({
  kind: 'Settings',
  apiVersion: 'myorg-test-app.grafana.app/v0alpha1',
  metadata: {
    name: 'myorg-test-app',
    namespace: 'default',
    uid: '',
    resourceVersion: '',
  },
  spec: {
    enabled: true,
    pinned: false,
    jsonData: {
      apiUrl: 'http://api-url.com',
    },
  },
  secure: {
    apiKey: {
      name: 'lps-sv-48fe6a860af4f72f3eefd0032e207ea1f942fcc88693411993ff778462867d27',
    },
    password: {
      name: 'lps-sv-58d8e08c33cf0bd6d7545df6d7957333f5604371ff87ca294e4572e6d9bedb04',
    },
  },
});

export const clockPanelOnPremPluginMeta = structuredClone({
  angular: { detected: false },
  angularDetected: false,
  autoEnabled: false,
  baseUrl: 'public/plugins/grafana-clock-panel',
  dependencies: {
    extensions: { exposedComponents: [] },
    grafanaDependency: '>=11.0.0',
    grafanaVersion: '*',
    plugins: [],
  },
  enabled: false,
  extensions: {
    addedComponents: [],
    addedFunctions: [],
    addedLinks: [],
    exposedComponents: [],
    extensionPoints: [],
  },
  hasUpdate: false,
  id: 'grafana-clock-panel',
  includes: [],
  info: {
    author: { name: 'Grafana Labs', url: 'https://grafana.com' },
    build: {},
    description: 'Clock panel for grafana',
    keywords: ['clock', 'panel'],
    links: [
      { name: 'Project site', url: 'https://github.com/grafana/clock-panel' },
      { name: 'MIT License', url: 'https://github.com/grafana/clock-panel/blob/master/LICENSE' },
    ],
    logos: {
      large: 'public/plugins/grafana-clock-panel/img/clock.svg',
      small: 'public/plugins/grafana-clock-panel/img/clock.svg',
    },
    screenshots: [
      { name: 'Showcase', path: 'public/plugins/grafana-clock-panel/img/screenshot-showcase.png' },
      { name: 'Options', path: 'public/plugins/grafana-clock-panel/img/screenshot-clock-options.png' },
    ],
    updated: '2025-12-10',
    version: '3.2.0',
  },
  jsonData: {},
  latestVersion: '',
  loadingStrategy: 'script',
  module: 'public/plugins/grafana-clock-panel/module.js',
  name: 'Clock',
  pinned: false,
  secureJsonFields: {},
  signature: 'valid',
  signatureOrg: 'Grafana Labs',
  signatureType: 'grafana',
  state: '',
  type: 'panel',
});

export const cloudwatchPluginMeta = structuredClone({
  aliasIDs: undefined,
  angular: { detected: false },
  angularDetected: false,
  autoEnabled: false,
  baseUrl: 'app/plugins/datasource/cloudwatch',
  defaultNavUrl: undefined,
  dependencies: {
    extensions: { exposedComponents: [] },
    grafanaDependency: '',
    grafanaVersion: '*',
    plugins: [],
  },
  enabled: false,
  extensions: {
    addedComponents: [],
    addedFunctions: [],
    addedLinks: [],
    exposedComponents: [],
    extensionPoints: [],
  },
  hasUpdate: false,
  id: 'cloudwatch',
  includes: [
    {
      addToNav: false,
      component: '',
      defaultNav: false,
      icon: '',
      name: 'EC2',
      path: 'dashboards/ec2.json',
      role: 'Viewer',
      slug: 'ec2',
      type: 'dashboard',
      uid: '',
    },
    {
      addToNav: false,
      component: '',
      defaultNav: false,
      icon: '',
      name: 'EBS',
      path: 'dashboards/EBS.json',
      role: 'Viewer',
      slug: 'ebs',
      type: 'dashboard',
      uid: '',
    },
    {
      addToNav: false,
      component: '',
      defaultNav: false,
      icon: '',
      name: 'Lambda',
      path: 'dashboards/Lambda.json',
      role: 'Viewer',
      slug: 'lambda',
      type: 'dashboard',
      uid: '',
    },
    {
      addToNav: false,
      component: '',
      defaultNav: false,
      icon: '',
      name: 'Logs',
      path: 'dashboards/Logs.json',
      role: 'Viewer',
      slug: 'logs',
      type: 'dashboard',
      uid: '',
    },
    {
      addToNav: false,
      component: '',
      defaultNav: false,
      icon: '',
      name: 'RDS',
      path: 'dashboards/RDS.json',
      role: 'Viewer',
      slug: 'rds',
      type: 'dashboard',
      uid: '',
    },
  ],
  info: {
    author: { name: 'Grafana Labs', url: 'https://grafana.com' },
    build: {},
    description: 'Data source for Amazon AWS monitoring service',
    keywords: ['aws', 'amazon'],
    links: [
      { name: 'Raise issue', url: 'https://github.com/grafana/grafana/issues/new' },
      { name: 'Documentation', url: 'https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/' },
    ],
    logos: {
      large: 'app/plugins/datasource/cloudwatch/dist/img/amazon-web-services.png',
      small: 'app/plugins/datasource/cloudwatch/dist/img/amazon-web-services.png',
    },
    screenshots: [],
    updated: '',
    version: '',
  },
  jsonData: {},
  latestVersion: '',
  loadingStrategy: 'script',
  module: 'core:plugin/cloudwatch',
  moduleHash: undefined,
  name: 'CloudWatch',
  pinned: false,
  secureJsonFields: {},
  signature: 'internal',
  signatureOrg: '',
  signatureType: '',
  state: '',
  type: 'datasource',
});
