{
 "title": "ES集群数据(apps)",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "请求总访问量 PV",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "销售额",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "action.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "price", "id": "1", "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "各应用的访问流量",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "action.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "vip用户占比图",
   "type": "piechart",
   "gridPos": { "h": 19, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "svip",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "svip : \"2\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "svip",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "svip : \"1\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "svip",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "svip : \"0\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "请求访问流量",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "各应用访问请求数量",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "action.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ES原始数据",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1000" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}