name: 'Setup Grafana Bench'
description: 'Sets up and installs Grafana Bench'

inputs:
  github-app-name:
    description: 'GitHub token for cloning grafana-bench'
    required: true
  branch:
    description: 'The branch to install from'
    required: false
    default: 'main'

runs:
  using: "composite"
  steps:
    - name: Generate GitHub App token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ env.APP_ID }}
        private-key: ${{ env.PRIVATE_KEY }}
        repositories: "grafana-bench"
        owner: "grafana"

    - name: Setup Bench
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.branch }}
        BRANCH: ${{ inputs.branch }}
      run: |
        git clone https://x-access-token:${GH_TOKEN}@github.com/grafana/grafana-bench.git ../grafana-bench

        cd ../grafana-bench
        git switch "$BRANCH"
        go install .
