name: 'Setup Grafana Bench'
description: 'Sets up and installs Grafana Bench'

inputs:
  branch:
    description: 'The branch to install from'
    required: false
    default: 'main'

runs:
  using: "composite"
  steps:
    - name: Get GitHub App token
      id: get-github-app-token
      uses: grafana/shared-workflows/actions/create-github-app-token@259ba21cb3ff07724f331e26d926d655d24b317b # create-github-app-token (github-script/v9)
      with:
        github_app: grafana-ci-bot

    - name: Setup Bench
      shell: bash
      env:
        GH_TOKEN: ${{ steps.get-github-app-token.outputs.token }}
        BRANCH: ${{ inputs.branch }}
      run: |
        git clone https://x-access-token:${GH_TOKEN}@github.com/grafana/grafana-bench.git ../grafana-bench

        cd ../grafana-bench
        git switch "$BRANCH"
        go install .
