// Code generated by mockery v2.53.5. DO NOT EDIT.

package quotas

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockNamespaceLimitsProvider is an autogenerated mock type for the NamespaceLimitsProvider type
type MockNamespaceLimitsProvider struct {
	mock.Mock
}

type MockNamespaceLimitsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNamespaceLimitsProvider) EXPECT() *MockNamespaceLimitsProvider_Expecter {
	return &MockNamespaceLimitsProvider_Expecter{mock: &_m.Mock}
}

// GetMaxRepositories provides a mock function with given fields: ctx, namespace
func (_m *MockNamespaceLimitsProvider) GetMaxRepositories(ctx context.Context, namespace string) (int, error) {
	ret := _m.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetMaxRepositories")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, namespace)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNamespaceLimitsProvider_GetMaxRepositories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxRepositories'
type MockNamespaceLimitsProvider_GetMaxRepositories_Call struct {
	*mock.Call
}

// GetMaxRepositories is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *MockNamespaceLimitsProvider_Expecter) GetMaxRepositories(ctx interface{}, namespace interface{}) *MockNamespaceLimitsProvider_GetMaxRepositories_Call {
	return &MockNamespaceLimitsProvider_GetMaxRepositories_Call{Call: _e.mock.On("GetMaxRepositories", ctx, namespace)}
}

func (_c *MockNamespaceLimitsProvider_GetMaxRepositories_Call) Run(run func(ctx context.Context, namespace string)) *MockNamespaceLimitsProvider_GetMaxRepositories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockNamespaceLimitsProvider_GetMaxRepositories_Call) Return(_a0 int, _a1 error) *MockNamespaceLimitsProvider_GetMaxRepositories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNamespaceLimitsProvider_GetMaxRepositories_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockNamespaceLimitsProvider_GetMaxRepositories_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNamespaceLimitsProvider creates a new instance of MockNamespaceLimitsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNamespaceLimitsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNamespaceLimitsProvider {
	mock := &MockNamespaceLimitsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
