#! /usr/bin/env bash

if ! command -v grafana >/dev/null 2>&1; then
  echo "grafana command not installed or not executable"
  exit 5
fi

echo "Deprecation warning: 'grafana-cli' is deprecated and will be removed in a future release. Use 'grafana' instead." >&2
exec grafana cli "$@"
