import { locale, scaledUnits, simpleCountUnit, toFixedUnit, ValueFormatCategory } from './valueFormats';
import {
  dateTimeAsIso,
  dateTimeAsUS,
  dateTimeFromNow,
  toClockMilliseconds,
  toClockSeconds,
  toDays,
  toDurationInHoursMinutesSeconds,
  toDurationInMilliseconds,
  toDurationInSeconds,
  toHours,
  toMicroSeconds,
  toMilliSeconds,
  toMinutes,
  toNanoSeconds,
  toSeconds,
  toTimeTicks,
} from './dateTimeFormatters';
import { toHex, sci, toHex0x, toPercent, toPercentUnit } from './arithmeticFormatters';
import { binarySIPrefix, currency, decimalSIPrefix } from './symbolFormatters';

export const getCategories = (): ValueFormatCategory[] => [
  {
    name: 'Misc',
    formats: [
      { name: 'none', id: 'none', fn: toFixedUnit('') },
      {
        name: 'short',
        id: 'short',
        fn: scaledUnits(1000, ['', ' K', ' Mil', ' Bil', ' Tri', ' Quadr', ' Quint', ' Sext', ' Sept']),
      },
      { name: 'percent (0-100)', id: 'percent', fn: toPercent },
      { name: 'percent (0.0-1.0)', id: 'percentunit', fn: toPercentUnit },
      { name: 'Humidity (%H)', id: 'humidity', fn: toFixedUnit('%H') },
      { name: 'decibel', id: 'dB', fn: toFixedUnit('dB') },
      { name: 'hexadecimal (0x)', id: 'hex0x', fn: toHex0x },
      { name: 'hexadecimal', id: 'hex', fn: toHex },
      { name: 'scientific notation', id: 'sci', fn: sci },
      { name: 'locale format', id: 'locale', fn: locale },
      { name: 'Pixels', id: 'pixel', fn: toFixedUnit('px') },
    ],
  },
  {
    name: 'Acceleration',
    formats: [
      { name: 'Meters/sec²', id: 'accMS2', fn: toFixedUnit('m/sec²') },
      { name: 'Feet/sec²', id: 'accFS2', fn: toFixedUnit('f/sec²') },
      { name: 'G unit', id: 'accG', fn: toFixedUnit('g') },
    ],
  },
  {
    name: 'Angle',
    formats: [
      { name: 'Degrees (°)', id: 'degree', fn: toFixedUnit('°') },
      { name: 'Radians', id: 'radian', fn: toFixedUnit('rad') },
      { name: 'Gradian', id: 'grad', fn: toFixedUnit('grad') },
      { name: 'Arc Minutes', id: 'arcmin', fn: toFixedUnit('arcmin') },
      { name: 'Arc Seconds', id: 'arcsec', fn: toFixedUnit('arcsec') },
    ],
  },
  {
    name: 'Area',
    formats: [
      { name: 'Square Meters (m²)', id: 'areaM2', fn: toFixedUnit('m²') },
      { name: 'Square Feet (ft²)', id: 'areaF2', fn: toFixedUnit('ft²') },
      { name: 'Square Miles (mi²)', id: 'areaMI2', fn: toFixedUnit('mi²') },
    ],
  },
  {
    name: 'Computation',
    formats: [
      { name: 'FLOP/s', id: 'flops', fn: decimalSIPrefix('FLOP/s') },
      { name: 'MFLOP/s', id: 'mflops', fn: decimalSIPrefix('FLOP/s', 2) },
      { name: 'GFLOP/s', id: 'gflops', fn: decimalSIPrefix('FLOP/s', 3) },
      { name: 'TFLOP/s', id: 'tflops', fn: decimalSIPrefix('FLOP/s', 4) },
      { name: 'PFLOP/s', id: 'pflops', fn: decimalSIPrefix('FLOP/s', 5) },
      { name: 'EFLOP/s', id: 'eflops', fn: decimalSIPrefix('FLOP/s', 6) },
      { name: 'ZFLOP/s', id: 'zflops', fn: decimalSIPrefix('FLOP/s', 7) },
      { name: 'YFLOP/s', id: 'yflops', fn: decimalSIPrefix('FLOP/s', 8) },
    ],
  },
  {
    name: 'Concentration',
    formats: [
      { name: 'parts-per-million (ppm)', id: 'ppm', fn: toFixedUnit('ppm') },
      { name: 'parts-per-billion (ppb)', id: 'conppb', fn: toFixedUnit('ppb') },
      { name: 'nanogram per cubic meter (ng/m³)', id: 'conngm3', fn: toFixedUnit('ng/m³') },
      { name: 'nanogram per normal cubic meter (ng/Nm³)', id: 'conngNm3', fn: toFixedUnit('ng/Nm³') },
      { name: 'microgram per cubic meter (μg/m³)', id: 'conμgm3', fn: toFixedUnit('μg/m³') },
      { name: 'microgram per normal cubic meter (μg/Nm³)', id: 'conμgNm3', fn: toFixedUnit('μg/Nm³') },
      { name: 'milligram per cubic meter (mg/m³)', id: 'conmgm3', fn: toFixedUnit('mg/m³') },
      { name: 'milligram per normal cubic meter (mg/Nm³)', id: 'conmgNm3', fn: toFixedUnit('mg/Nm³') },
      { name: 'gram per cubic meter (g/m³)', id: 'congm3', fn: toFixedUnit('g/m³') },
      { name: 'gram per normal cubic meter (g/Nm³)', id: 'congNm3', fn: toFixedUnit('g/Nm³') },
      { name: 'milligrams per decilitre (mg/dL)', id: 'conmgdL', fn: toFixedUnit('mg/dL') },
      { name: 'millimoles per litre (mmol/L)', id: 'conmmolL', fn: toFixedUnit('mmol/L') },
    ],
  },
  {
    name: 'Currency',
    formats: [
      { name: 'Dollars ($)', id: 'currencyUSD', fn: currency('$') },
      { name: 'Pounds (£)', id: 'currencyGBP', fn: currency('£') },
      { name: 'Euro (€)', id: 'currencyEUR', fn: currency('€') },
      { name: 'Yen (¥)', id: 'currencyJPY', fn: currency('¥') },
      { name: 'Rubles (₽)', id: 'currencyRUB', fn: currency('₽') },
      { name: 'Hryvnias (₴)', id: 'currencyUAH', fn: currency('₴') },
      { name: 'Real (R$)', id: 'currencyBRL', fn: currency('R$') },
      { name: 'Danish Krone (kr)', id: 'currencyDKK', fn: currency('kr', true) },
      { name: 'Icelandic Króna (kr)', id: 'currencyISK', fn: currency('kr', true) },
      { name: 'Norwegian Krone (kr)', id: 'currencyNOK', fn: currency('kr', true) },
      { name: 'Swedish Krona (kr)', id: 'currencySEK', fn: currency('kr', true) },
      { name: 'Czech koruna (czk)', id: 'currencyCZK', fn: currency('czk') },
      { name: 'Swiss franc (CHF)', id: 'currencyCHF', fn: currency('CHF') },
      { name: 'Polish Złoty (PLN)', id: 'currencyPLN', fn: currency('PLN') },
      { name: 'Bitcoin (฿)', id: 'currencyBTC', fn: currency('฿') },
      { name: 'South African Rand (R)', id: 'currencyZAR', fn: currency('R') },
      { name: 'Indian Rupee (₹)', id: 'currencyINR', fn: currency('₹') },
      { name: 'South Korean Won (₩)', id: 'currencyKRW', fn: currency('₩') },
      { name: 'Botswanan Pula (P)', id: 'currencyBWP', fn: currency('P') },
      { name: 'Barbadian Dollar ($)', id: 'currencyBBD', fn: currency('$') },
      { name: 'Moroccan Franc (MAF)', id: 'currencyMAF', fn: currency('MAF') },
      { name: 'Venezuelan Bolívar (1871–2008) (VEB)', id: 'currencyVEB', fn: currency('VEB') },
      { name: 'Slovak Koruna (SKK)', id: 'currencySKK', fn: currency('SKK') },
      { name: 'British Pound (£)', id: 'currencyGBP', fn: currency('£') },
      { name: 'Serbian Dinar (RSD)', id: 'currencyRSD', fn: currency('RSD') },
      { name: 'Turkmenistani Manat (TMT)', id: 'currencyTMT', fn: currency('TMT') },
      { name: 'Turkish Lira (₺)', id: 'currencyTRY', fn: currency('₺') },
      { name: 'Uruguayan Peso ($)', id: 'currencyUYU', fn: currency('$') },
      { name: 'Chilean Escudo (CLE)', id: 'currencyCLE', fn: currency('CLE') },
      { name: 'Albanian Lek (1946–1965) (ALK)', id: 'currencyALK', fn: currency('ALK') },
      { name: 'Saudi Riyal (SAR)', id: 'currencySAR', fn: currency('SAR') },
      { name: 'Philippine Peso (₱)', id: 'currencyPHP', fn: currency('₱') },
      { name: 'Dutch Guilder (NLG)', id: 'currencyNLG', fn: currency('NLG') },
      { name: 'Chilean Peso ($)', id: 'currencyCLP', fn: currency('$') },
      { name: 'Chinese People’s Bank Dollar (CNX)', id: 'currencyCNX', fn: currency('CNX') },
      { name: 'Romanian Leu (1952–2006) (ROL)', id: 'currencyROL', fn: currency('ROL') },
      { name: 'Angolan New Kwanza (1990–2000) (AON)', id: 'currencyAON', fn: currency('AON') },
      { name: 'North Korean Won (₩)', id: 'currencyKPW', fn: currency('₩') },
      { name: 'Kuwaiti Dinar (KWD)', id: 'currencyKWD', fn: currency('KWD') },
      { name: 'Ethiopian Birr (ETB)', id: 'currencyETB', fn: currency('ETB') },
      { name: 'Malian Franc (MLF)', id: 'currencyMLF', fn: currency('MLF') },
      { name: 'Malawian Kwacha (MWK)', id: 'currencyMWK', fn: currency('MWK') },
      { name: 'Bosnia-Herzegovina Convertible Mark (KM)', id: 'currencyBAM', fn: currency('KM') },
      { name: 'Israeli New Sheqel (₪)', id: 'currencyILS', fn: currency('₪') },
      { name: 'Burmese Kyat (BUK)', id: 'currencyBUK', fn: currency('BUK') },
      { name: 'Namibian Dollar ($)', id: 'currencyNAD', fn: currency('$') },
      { name: 'Platinum (XPT)', id: 'currencyXPT', fn: currency('XPT') },
      { name: 'French Gold Franc (XFO)', id: 'currencyXFO', fn: currency('XFO') },
      { name: 'Aruban Florin (AWG)', id: 'currencyAWG', fn: currency('AWG') },
      { name: 'Bulgarian Lev (BGN)', id: 'currencyBGN', fn: currency('BGN') },
      { name: 'New Zealand Dollar (NZ$)', id: 'currencyNZD', fn: currency('NZ$') },
      { name: 'Libyan Dinar (LYD)', id: 'currencyLYD', fn: currency('LYD') },
      { name: 'ADB Unit of Account (XUA)', id: 'currencyXUA', fn: currency('XUA') },
      { name: 'Mexican Silver Peso (1861–1992) (MXP)', id: 'currencyMXP', fn: currency('MXP') },
      { name: 'Tongan Paʻanga (T$)', id: 'currencyTOP', fn: currency('T$') },
      { name: 'Belgian Franc (BEF)', id: 'currencyBEF', fn: currency('BEF') },
      { name: 'Myanmar Kyat (K)', id: 'currencyMMK', fn: currency('K') },
      { name: 'Cuban Peso ($)', id: 'currencyCUP', fn: currency('$') },
      { name: 'Austrian Schilling (ATS)', id: 'currencyATS', fn: currency('ATS') },
      { name: 'Colombian Real Value Unit (COU)', id: 'currencyCOU', fn: currency('COU') },
      { name: 'Yemeni Dinar (YDD)', id: 'currencyYDD', fn: currency('YDD') },
      { name: 'European Composite Unit (XBA)', id: 'currencyXBA', fn: currency('XBA') },
      { name: 'Sierra Leonean Leone (SLL)', id: 'currencySLL', fn: currency('SLL') },
      { name: 'Nepalese Rupee (Rs)', id: 'currencyNPR', fn: currency('Rs') },
      { name: 'Liberian Dollar ($)', id: 'currencyLRD', fn: currency('$') },
      { name: 'Unknown Currency (XXX)', id: 'currencyXXX', fn: currency('XXX') },
      { name: 'European Unit of Account (XBC) (XBC)', id: 'currencyXBC', fn: currency('XBC') },
      { name: 'Afghan Afghani (AFN)', id: 'currencyAFN', fn: currency('AFN') },
      { name: 'Sudanese Pound (SDG)', id: 'currencySDG', fn: currency('SDG') },
      { name: 'Iraqi Dinar (IQD)', id: 'currencyIQD', fn: currency('IQD') },
      { name: 'Macedonian Denar (MKD)', id: 'currencyMKD', fn: currency('MKD') },
      { name: 'Israeli Pound (ILP)', id: 'currencyILP', fn: currency('ILP') },
      { name: 'Jordanian Dinar (JOD)', id: 'currencyJOD', fn: currency('JOD') },
      { name: 'Kenyan Shilling (KES)', id: 'currencyKES', fn: currency('KES') },
      { name: 'Greek Drachma (GRD)', id: 'currencyGRD', fn: currency('GRD') },
      { name: 'Vietnamese Dong (1978–1985) (VNN)', id: 'currencyVNN', fn: currency('VNN') },
      { name: 'Sudanese Dinar (1992–2007) (SDD)', id: 'currencySDD', fn: currency('SDD') },
      { name: 'Australian Dollar (A$)', id: 'currencyAUD', fn: currency('A$') },
      { name: 'Pakistani Rupee (Rs)', id: 'currencyPKR', fn: currency('Rs') },
      { name: 'Argentine Peso ($)', id: 'currencyARS', fn: currency('$') },
      { name: 'Gibraltar Pound (£)', id: 'currencyGIP', fn: currency('£') },
      { name: 'Lebanese Pound (L£)', id: 'currencyLBP', fn: currency('L£') },
      { name: 'Guinea-Bissau Peso (GWP)', id: 'currencyGWP', fn: currency('GWP') },
      { name: 'Polish Zloty (1950–1995) (PLZ)', id: 'currencyPLZ', fn: currency('PLZ') },
      { name: 'Equatorial Guinean Ekwele (GQE)', id: 'currencyGQE', fn: currency('GQE') },
      { name: 'Haitian Gourde (HTG)', id: 'currencyHTG', fn: currency('HTG') },
      { name: 'Mexican Peso (MX$)', id: 'currencyMXN', fn: currency('MX$') },
      { name: 'Icelandic Króna (1918–1981) (ISJ)', id: 'currencyISJ', fn: currency('ISJ') },
      { name: 'Angolan Kwanza (1977–1991) (AOK)', id: 'currencyAOK', fn: currency('AOK') },
      { name: 'Tunisian Dinar (TND)', id: 'currencyTND', fn: currency('TND') },
      { name: 'Bermudan Dollar ($)', id: 'currencyBMD', fn: currency('$') },
      { name: 'WIR Euro (CHE)', id: 'currencyCHE', fn: currency('CHE') },
      { name: 'Azerbaijani Manat (AZN)', id: 'currencyAZN', fn: currency('AZN') },
      { name: 'Brazilian New Cruzado (1989–1990) (BRN)', id: 'currencyBRN', fn: currency('BRN') },
      { name: 'Brunei Dollar ($)', id: 'currencyBND', fn: currency('$') },
      { name: 'German Mark (DEM)', id: 'currencyDEM', fn: currency('DEM') },
      { name: 'Angolan Readjusted Kwanza (1995–1999) (AOR)', id: 'currencyAOR', fn: currency('AOR') },
      { name: 'Czechoslovak Hard Koruna (CSK)', id: 'currencyCSK', fn: currency('CSK') },
      { name: 'Burundian Franc (BIF)', id: 'currencyBIF', fn: currency('BIF') },
      { name: 'French UIC-Franc (XFU)', id: 'currencyXFU', fn: currency('XFU') },
      { name: 'São Tomé & Príncipe Dobra (Db)', id: 'currencySTD', fn: currency('Db') },
      { name: 'Spanish Peseta (₧)', id: 'currencyESP', fn: currency('₧') },
      { name: 'Belarusian Ruble (р.)', id: 'currencyBYR', fn: currency('р.') },
      { name: 'Croatian Dinar (HRD)', id: 'currencyHRD', fn: currency('HRD') },
      { name: 'Ecuadorian Unit of Constant Value (ECV)', id: 'currencyECV', fn: currency('ECV') },
      { name: 'Nicaraguan Córdoba (C$)', id: 'currencyNIO', fn: currency('C$') },
      { name: 'Tajikistani Somoni (TJS)', id: 'currencyTJS', fn: currency('TJS') },
      { name: 'Mozambican Metical (MZN)', id: 'currencyMZN', fn: currency('MZN') },
      { name: 'Argentine Austral (ARA)', id: 'currencyARA', fn: currency('ARA') },
      { name: 'Ecuadorian Sucre (ECS)', id: 'currencyECS', fn: currency('ECS') },
      { name: 'Zambian Kwacha (1968–2012) (ZMK)', id: 'currencyZMK', fn: currency('ZMK') },
      { name: 'Yugoslavian Reformed Dinar (1992–1993) (YUR)', id: 'currencyYUR', fn: currency('YUR') },
      { name: 'Spanish Peseta (A account) (ESA)', id: 'currencyESA', fn: currency('ESA') },
      { name: 'Laotian Kip (₭)', id: 'currencyLAK', fn: currency('₭') },
      { name: 'West African CFA Franc (CFA)', id: 'currencyXOF', fn: currency('CFA') },
      { name: 'Guinean Franc (FG)', id: 'currencyGNF', fn: currency('FG') },
      { name: 'Egyptian Pound (E£)', id: 'currencyEGP', fn: currency('E£') },
      { name: 'Syrian Pound (£)', id: 'currencySYP', fn: currency('£') },
      { name: 'Bosnia-Herzegovina Dinar (1992–1994) (BAD)', id: 'currencyBAD', fn: currency('BAD') },
      { name: 'Malaysian Ringgit (RM)', id: 'currencyMYR', fn: currency('RM') },
      { name: 'Zimbabwean Dollar (1980–2008) (ZWD)', id: 'currencyZWD', fn: currency('ZWD') },
      { name: 'Sudanese Pound (1957–1998) (SDP)', id: 'currencySDP', fn: currency('SDP') },
      { name: 'Singapore Dollar ($)', id: 'currencySGD', fn: currency('$') },
      { name: 'Kazakhstani Tenge (₸)', id: 'currencyKZT', fn: currency('₸') },
      { name: 'Argentine Peso (1983–1985) (ARP)', id: 'currencyARP', fn: currency('ARP') },
      { name: 'Chinese Yuan (CN¥)', id: 'currencyCNY', fn: currency('CN¥') },
      { name: 'Estonian Kroon (EEK)', id: 'currencyEEK', fn: currency('EEK') },
      { name: 'South Korean Hwan (1953–1962) (KRH)', id: 'currencyKRH', fn: currency('KRH') },
      { name: 'Mauritanian Ouguiya (MRO)', id: 'currencyMRO', fn: currency('MRO') },
      { name: 'Luxembourg Financial Franc (LUL)', id: 'currencyLUL', fn: currency('LUL') },
      { name: 'Mongolian Tugrik (₮)', id: 'currencyMNT', fn: currency('₮') },
      { name: 'Yugoslavian Convertible Dinar (1990–1992) (YUN)', id: 'currencyYUN', fn: currency('YUN') },
      { name: 'Special Drawing Rights (XDR)', id: 'currencyXDR', fn: currency('XDR') },
      { name: 'Bosnia-Herzegovina New Dinar (1994–1997) (BAN)', id: 'currencyBAN', fn: currency('BAN') },
      { name: 'Papua New Guinean Kina (PGK)', id: 'currencyPGK', fn: currency('PGK') },
      { name: 'South Korean Won (1945–1953) (KRO)', id: 'currencyKRO', fn: currency('KRO') },
      { name: 'Timorese Escudo (TPE)', id: 'currencyTPE', fn: currency('TPE') },
      { name: 'Cypriot Pound (CYP)', id: 'currencyCYP', fn: currency('CYP') },
      { name: 'Zimbabwean Dollar (2009) (ZWL)', id: 'currencyZWL', fn: currency('ZWL') },
      { name: 'Cayman Islands Dollar ($)', id: 'currencyKYD', fn: currency('$') },
      { name: 'Samoan Tala (WST)', id: 'currencyWST', fn: currency('WST') },
      { name: 'Cambodian Riel (៛)', id: 'currencyKHR', fn: currency('៛') },
      { name: 'Bolivian Boliviano (Bs)', id: 'currencyBOB', fn: currency('Bs') },
      { name: 'Zimbabwean Dollar (2008) (ZWR)', id: 'currencyZWR', fn: currency('ZWR') },
      { name: 'Romanian Leu (RON)', id: 'currencyRON', fn: currency('RON') },
      { name: 'Silver (XAG)', id: 'currencyXAG', fn: currency('XAG') },
      { name: 'Latvian Lats (Ls)', id: 'currencyLVL', fn: currency('Ls') },
      { name: 'Belize Dollar ($)', id: 'currencyBZD', fn: currency('$') },
      { name: 'Bangladeshi Taka (৳)', id: 'currencyBDT', fn: currency('৳') },
      { name: 'Brazilian New Cruzeiro (1967–1986) (BRB)', id: 'currencyBRB', fn: currency('BRB') },
      { name: 'Malagasy Ariary (Ar)', id: 'currencyMGA', fn: currency('Ar') },
      { name: 'Central African CFA Franc (FCFA)', id: 'currencyXAF', fn: currency('FCFA') },
      { name: 'Mexican Investment Unit (MXV)', id: 'currencyMXV', fn: currency('MXV') },
      { name: 'Thai Baht (฿)', id: 'currencyTHB', fn: currency('฿') },
      { name: 'Seychellois Rupee (SCR)', id: 'currencySCR', fn: currency('SCR') },
      { name: 'Salvadoran Colón (SVC)', id: 'currencySVC', fn: currency('SVC') },
      { name: 'US Dollar (Next day) (USN)', id: 'currencyUSN', fn: currency('USN') },
      { name: 'Ghanaian Cedi (GHS)', id: 'currencyGHS', fn: currency('GHS') },
      { name: 'European Currency Unit (XEU)', id: 'currencyXEU', fn: currency('XEU') },
      { name: 'Surinamese Guilder (SRG)', id: 'currencySRG', fn: currency('SRG') },
      { name: 'Latvian Ruble (LVR)', id: 'currencyLVR', fn: currency('LVR') },
      { name: 'Nigerian Naira (₦)', id: 'currencyNGN', fn: currency('₦') },
      { name: 'Vanuatu Vatu (VUV)', id: 'currencyVUV', fn: currency('VUV') },
      { name: 'Bhutanese Ngultrum (BTN)', id: 'currencyBTN', fn: currency('BTN') },
      { name: 'Tanzanian Shilling (TZS)', id: 'currencyTZS', fn: currency('TZS') },
      { name: 'Gambian Dalasi (GMD)', id: 'currencyGMD', fn: currency('GMD') },
      { name: 'Bulgarian Lev (1879–1952) (BGO)', id: 'currencyBGO', fn: currency('BGO') },
      { name: 'Malagasy Franc (MGF)', id: 'currencyMGF', fn: currency('MGF') },
      { name: 'Argentine Peso Ley (1970–1983) (ARL)', id: 'currencyARL', fn: currency('ARL') },
      { name: 'Brazilian Cruzeiro (1990–1993) (BRE)', id: 'currencyBRE', fn: currency('BRE') },
      { name: 'Panamanian Balboa (PAB)', id: 'currencyPAB', fn: currency('PAB') },
      { name: 'Trinidad & Tobago Dollar ($)', id: 'currencyTTD', fn: currency('$') },
      { name: 'Bolivian Boliviano (1863–1963) (BOL)', id: 'currencyBOL', fn: currency('BOL') },
      { name: 'East Caribbean Dollar (EC$)', id: 'currencyXCD', fn: currency('EC$') },
      { name: 'European Unit of Account (XBD) (XBD)', id: 'currencyXBD', fn: currency('XBD') },
      { name: 'Belarusian New Ruble (1994–1999) (BYB)', id: 'currencyBYB', fn: currency('BYB') },
      { name: 'Bolivian Peso (BOP)', id: 'currencyBOP', fn: currency('BOP') },
      { name: 'Lithuanian Talonas (LTT)', id: 'currencyLTT', fn: currency('LTT') },
      { name: 'Maltese Pound (MTP)', id: 'currencyMTP', fn: currency('MTP') },
      { name: 'Somali Shilling (SOS)', id: 'currencySOS', fn: currency('SOS') },
      { name: 'Belgian Franc (financial) (BEL)', id: 'currencyBEL', fn: currency('BEL') },
      { name: 'Serbian Dinar (2002–2006) (CSD)', id: 'currencyCSD', fn: currency('CSD') },
      { name: 'Brazilian Cruzado (1986–1989) (BRC)', id: 'currencyBRC', fn: currency('BRC') },
      { name: 'Ghanaian Cedi (1979–2007) (GHC)', id: 'currencyGHC', fn: currency('GHC') },
      { name: 'Andorran Peseta (ADP)', id: 'currencyADP', fn: currency('ADP') },
      { name: 'Jamaican Dollar ($)', id: 'currencyJMD', fn: currency('$') },
      { name: 'Hong Kong Dollar (HK$)', id: 'currencyHKD', fn: currency('HK$') },
      { name: 'Moldovan Cupon (MDC)', id: 'currencyMDC', fn: currency('MDC') },
      { name: 'Mozambican Metical (1980–2006) (MZM)', id: 'currencyMZM', fn: currency('MZM') },
      { name: 'New Taiwan Dollar (NT$)', id: 'currencyTWD', fn: currency('NT$') },
      { name: 'Canadian Dollar (CA$)', id: 'currencyCAD', fn: currency('CA$') },
      { name: 'Yugoslavian Hard Dinar (1966–1990) (YUD)', id: 'currencyYUD', fn: currency('YUD') },
      { name: 'RINET Funds (XRE)', id: 'currencyXRE', fn: currency('XRE') },
      { name: 'Falkland Islands Pound (£)', id: 'currencyFKP', fn: currency('£') },
      { name: 'Slovenian Tolar (SIT)', id: 'currencySIT', fn: currency('SIT') },
      { name: 'Spanish Peseta (convertible account) (ESB)', id: 'currencyESB', fn: currency('ESB') },
      { name: 'Guinean Syli (GNS)', id: 'currencyGNS', fn: currency('GNS') },
      { name: 'Comorian Franc (CF)', id: 'currencyKMF', fn: currency('CF') },
      { name: 'Yugoslavian New Dinar (1994–2002) (YUM)', id: 'currencyYUM', fn: currency('YUM') },
      { name: 'Testing Currency Code (XTS)', id: 'currencyXTS', fn: currency('XTS') },
      { name: 'Fijian Dollar ($)', id: 'currencyFJD', fn: currency('$') },
      { name: 'Uruguayan Peso (1975–1993) (UYP)', id: 'currencyUYP', fn: currency('UYP') },
      { name: 'Soviet Rouble (SUR)', id: 'currencySUR', fn: currency('SUR') },
      { name: 'Rwandan Franc (RF)', id: 'currencyRWF', fn: currency('RF') },
      { name: 'Swazi Lilangeni (SZL)', id: 'currencySZL', fn: currency('SZL') },
      { name: 'Portuguese Escudo (PTE)', id: 'currencyPTE', fn: currency('PTE') },
      { name: 'WIR Franc (CHW)', id: 'currencyCHW', fn: currency('CHW') },
      { name: 'East German Mark (DDM)', id: 'currencyDDM', fn: currency('DDM') },
      { name: 'French Franc (FRF)', id: 'currencyFRF', fn: currency('FRF') },
      { name: 'Brazilian Cruzeiro (1942–1967) (BRZ)', id: 'currencyBRZ', fn: currency('BRZ') },
      { name: 'Zambian Kwacha (ZK)', id: 'currencyZMW', fn: currency('ZK') },
      { name: 'Afghan Afghani (1927–2002) (AFA)', id: 'currencyAFA', fn: currency('AFA') },
      { name: 'US Dollar (Same day) (USS)', id: 'currencyUSS', fn: currency('USS') },
      { name: 'South African Rand (financial) (ZAL)', id: 'currencyZAL', fn: currency('ZAL') },
      { name: 'Israeli Sheqel (1980–1985) (ILR)', id: 'currencyILR', fn: currency('ILR') },
      { name: 'CFP Franc (CFPF)', id: 'currencyXPF', fn: currency('CFPF') },
      { name: 'Russian Ruble (1991–1998) (р.)', id: 'currencyRUR', fn: currency('р.') },
      { name: 'Finnish Markka (FIM)', id: 'currencyFIM', fn: currency('FIM') },
      { name: 'Georgian Kupon Larit (GEK)', id: 'currencyGEK', fn: currency('GEK') },
      { name: 'Yemeni Rial (YER)', id: 'currencyYER', fn: currency('YER') },
      { name: 'Paraguayan Guarani (₲)', id: 'currencyPYG', fn: currency('₲') },
      { name: 'European Monetary Unit (XBB)', id: 'currencyXBB', fn: currency('XBB') },
      { name: 'Chilean Unit of Account (UF) (CLF)', id: 'currencyCLF', fn: currency('CLF') },
      { name: 'Rhodesian Dollar (RHD)', id: 'currencyRHD', fn: currency('RHD') },
      { name: 'Peruvian Sol (1863–1965) (PES)', id: 'currencyPES', fn: currency('PES') },
      { name: 'Netherlands Antillean Guilder (ANG)', id: 'currencyANG', fn: currency('ANG') },
      { name: 'Peruvian Nuevo Sol (PEN)', id: 'currencyPEN', fn: currency('PEN') },
      { name: 'Macanese Pataca (MOP)', id: 'currencyMOP', fn: currency('MOP') },
      { name: 'Moroccan Dirham (MAD)', id: 'currencyMAD', fn: currency('MAD') },
      { name: 'Brazilian Cruzeiro (1993–1994) (BRR)', id: 'currencyBRR', fn: currency('BRR') },
      { name: 'Maltese Lira (MTL)', id: 'currencyMTL', fn: currency('MTL') },
      { name: 'Bahraini Dinar (BHD)', id: 'currencyBHD', fn: currency('BHD') },
      { name: 'Lesotho Loti (LSL)', id: 'currencyLSL', fn: currency('LSL') },
      { name: 'Hungarian Forint (Ft)', id: 'currencyHUF', fn: currency('Ft') },
      { name: 'Angolan Kwanza (Kz)', id: 'currencyAOA', fn: currency('Kz') },
      { name: 'Iranian Rial (IRR)', id: 'currencyIRR', fn: currency('IRR') },
      { name: 'Qatari Rial (QAR)', id: 'currencyQAR', fn: currency('QAR') },
      { name: 'Gold (XAU)', id: 'currencyXAU', fn: currency('XAU') },
      { name: 'Luxembourgian Convertible Franc (LUC)', id: 'currencyLUC', fn: currency('LUC') },
      { name: 'Croatian Kuna (kn)', id: 'currencyHRK', fn: currency('kn') },
      { name: 'United Arab Emirates Dirham (AED)', id: 'currencyAED', fn: currency('AED') },
      { name: 'Guyanaese Dollar ($)', id: 'currencyGYD', fn: currency('$') },
      { name: 'Tajikistani Ruble (TJR)', id: 'currencyTJR', fn: currency('TJR') },
      { name: 'Belgian Franc (convertible) (BEC)', id: 'currencyBEC', fn: currency('BEC') },
      { name: 'Costa Rican Colón (₡)', id: 'currencyCRC', fn: currency('₡') },
      { name: 'Peruvian Inti (PEI)', id: 'currencyPEI', fn: currency('PEI') },
      { name: 'Bulgarian Hard Lev (BGL)', id: 'currencyBGL', fn: currency('BGL') },
      { name: 'Indonesian Rupiah (Rp)', id: 'currencyIDR', fn: currency('Rp') },
      { name: 'Vietnamese Dong (₫)', id: 'currencyVND', fn: currency('₫') },
      { name: 'Georgian Lari (₾)', id: 'currencyGEL', fn: currency('₾') },
      { name: 'Albanian Lek (ALL)', id: 'currencyALL', fn: currency('ALL') },
      { name: 'Congolese Franc (CDF)', id: 'currencyCDF', fn: currency('CDF') },
      { name: 'Guatemalan Quetzal (Q)', id: 'currencyGTQ', fn: currency('Q') },
      { name: 'Honduran Lempira (L)', id: 'currencyHNL', fn: currency('L') },
      { name: 'South Sudanese Pound (£)', id: 'currencySSP', fn: currency('£') },
      { name: 'Algerian Dinar (DZD)', id: 'currencyDZD', fn: currency('DZD') },
      { name: 'Solomon Islands Dollar ($)', id: 'currencySBD', fn: currency('$') },
      { name: 'Sri Lankan Rupee (Rs)', id: 'currencyLKR', fn: currency('Rs') },
      { name: 'Luxembourgian Franc (LUF)', id: 'currencyLUF', fn: currency('LUF') },
      { name: 'Mauritian Rupee (Rs)', id: 'currencyMUR', fn: currency('Rs') },
      { name: 'Maldivian Rufiyaa (MVR)', id: 'currencyMVR', fn: currency('MVR') },
      { name: 'Turkmenistani Manat (1993–2009) (TMM)', id: 'currencyTMM', fn: currency('TMM') },
      { name: 'Uzbekistani Som (UZS)', id: 'currencyUZS', fn: currency('UZS') },
      { name: 'Sucre (XSU)', id: 'currencyXSU', fn: currency('XSU') },
      { name: 'Dominican Peso ($)', id: 'currencyDOP', fn: currency('$') },
      { name: 'Bulgarian Socialist Lev (BGM)', id: 'currencyBGM', fn: currency('BGM') },
      { name: 'Djiboutian Franc (DJF)', id: 'currencyDJF', fn: currency('DJF') },
      { name: 'Italian Lira (ITL)', id: 'currencyITL', fn: currency('ITL') },
      { name: 'Palladium (XPD)', id: 'currencyXPD', fn: currency('XPD') },
      { name: 'Venezuelan Bolívar (Bs)', id: 'currencyVEF', fn: currency('Bs') },
      { name: 'Bahamian Dollar ($)', id: 'currencyBSD', fn: currency('$') },
      { name: 'Cuban Convertible Peso ($)', id: 'currencyCUC', fn: currency('$') },
      { name: 'Eritrean Nakfa (ERN)', id: 'currencyERN', fn: currency('ERN') },
      { name: 'Argentine Peso (1881–1970) (ARM)', id: 'currencyARM', fn: currency('ARM') },
      { name: 'Bolivian Mvdol (BOV)', id: 'currencyBOV', fn: currency('BOV') },
      { name: 'Nicaraguan Córdoba (1988–1991) (NIC)', id: 'currencyNIC', fn: currency('NIC') },
      { name: 'Lithuanian Litas (Lt)', id: 'currencyLTL', fn: currency('Lt') },
      { name: 'Ukrainian Karbovanets (UAK)', id: 'currencyUAK', fn: currency('UAK') },
      { name: 'St. Helena Pound (£)', id: 'currencySHP', fn: currency('£') },
      { name: 'Monegasque Franc (MCF)', id: 'currencyMCF', fn: currency('MCF') },
      { name: 'Uruguayan Peso (Indexed Units) (UYI)', id: 'currencyUYI', fn: currency('UYI') },
      { name: 'Surinamese Dollar ($)', id: 'currencySRD', fn: currency('$') },
      { name: 'Zairean Zaire (1971–1993) (ZRZ)', id: 'currencyZRZ', fn: currency('ZRZ') },
      { name: 'Kyrgystani Som (KGS)', id: 'currencyKGS', fn: currency('KGS') },
      { name: 'Colombian Peso ($)', id: 'currencyCOP', fn: currency('$') },
      { name: 'Macedonian Denar (1992–1993) (MKN)', id: 'currencyMKN', fn: currency('MKN') },
      { name: 'Zairean New Zaire (1993–1998) (ZRN)', id: 'currencyZRN', fn: currency('ZRN') },
      { name: 'Portuguese Guinea Escudo (GWE)', id: 'currencyGWE', fn: currency('GWE') },
      { name: 'Mozambican Escudo (MZE)', id: 'currencyMZE', fn: currency('MZE') },
      { name: 'Cape Verdean Escudo (CVE)', id: 'currencyCVE', fn: currency('CVE') },
      { name: 'Ugandan Shilling (1966–1987) (UGS)', id: 'currencyUGS', fn: currency('UGS') },
      { name: 'Armenian Dram (AMD)', id: 'currencyAMD', fn: currency('AMD') },
      { name: 'Omani Rial (OMR)', id: 'currencyOMR', fn: currency('OMR') },
      { name: 'Azerbaijani Manat (1993–2006) (AZM)', id: 'currencyAZM', fn: currency('AZM') },
      { name: 'Irish Pound (IEP)', id: 'currencyIEP', fn: currency('IEP') },
      { name: 'Turkish Lira (1922–2005) (TRL)', id: 'currencyTRL', fn: currency('TRL') },
      { name: 'Ugandan Shilling (UGX)', id: 'currencyUGX', fn: currency('UGX') },
      { name: 'Moldovan Leu (MDL)', id: 'currencyMDL', fn: currency('MDL') },
    ],
  },
  {
    name: 'Data (IEC)',
    formats: [
      { name: 'bits(IEC)', id: 'bits', fn: binarySIPrefix('b') },
      { name: 'bytes(IEC)', id: 'bytes', fn: binarySIPrefix('B') },
      { name: 'kibibytes', id: 'kbytes', fn: binarySIPrefix('B', 1) },
      { name: 'mebibytes', id: 'mbytes', fn: binarySIPrefix('B', 2) },
      { name: 'gibibytes', id: 'gbytes', fn: binarySIPrefix('B', 3) },
      { name: 'tebibytes', id: 'tbytes', fn: binarySIPrefix('B', 4) },
      { name: 'pebibytes', id: 'pbytes', fn: binarySIPrefix('B', 5) },
    ],
  },
  {
    name: 'Data (Metric)',
    formats: [
      { name: 'bits(Metric)', id: 'decbits', fn: decimalSIPrefix('b') },
      { name: 'bytes(Metric)', id: 'decbytes', fn: decimalSIPrefix('B') },
      { name: 'kilobytes', id: 'deckbytes', fn: decimalSIPrefix('B', 1) },
      { name: 'megabytes', id: 'decmbytes', fn: decimalSIPrefix('B', 2) },
      { name: 'gigabytes', id: 'decgbytes', fn: decimalSIPrefix('B', 3) },
      { name: 'terabytes', id: 'dectbytes', fn: decimalSIPrefix('B', 4) },
      { name: 'petabytes', id: 'decpbytes', fn: decimalSIPrefix('B', 5) },
    ],
  },
  {
    name: 'Data Rate',
    formats: [
      { name: 'packets/sec', id: 'pps', fn: decimalSIPrefix('pps') },
      { name: 'bits/sec', id: 'bps', fn: decimalSIPrefix('bps') },
      { name: 'bytes/sec', id: 'Bps', fn: decimalSIPrefix('Bs') },
      { name: 'kilobytes/sec', id: 'KBs', fn: decimalSIPrefix('Bs', 1) },
      { name: 'kilobits/sec', id: 'Kbits', fn: decimalSIPrefix('bps', 1) },
      { name: 'megabytes/sec', id: 'MBs', fn: decimalSIPrefix('Bs', 2) },
      { name: 'megabits/sec', id: 'Mbits', fn: decimalSIPrefix('bps', 2) },
      { name: 'gigabytes/sec', id: 'GBs', fn: decimalSIPrefix('Bs', 3) },
      { name: 'gigabits/sec', id: 'Gbits', fn: decimalSIPrefix('bps', 3) },
      { name: 'terabytes/sec', id: 'TBs', fn: decimalSIPrefix('Bs', 4) },
      { name: 'terabits/sec', id: 'Tbits', fn: decimalSIPrefix('bps', 4) },
      { name: 'petabytes/sec', id: 'PBs', fn: decimalSIPrefix('Bs', 5) },
      { name: 'petabits/sec', id: 'Pbits', fn: decimalSIPrefix('bps', 5) },
    ],
  },
  {
    name: 'Date & Time',
    formats: [
      { name: 'YYYY-MM-DD HH:mm:ss', id: 'dateTimeAsIso', fn: dateTimeAsIso },
      { name: 'MM/DD/YYYY h:mm:ss a', id: 'dateTimeAsUS', fn: dateTimeAsUS },
      { name: 'From Now', id: 'dateTimeFromNow', fn: dateTimeFromNow },
    ],
  },
  {
    name: 'Energy',
    formats: [
      { name: 'Watt (W)', id: 'watt', fn: decimalSIPrefix('W') },
      { name: 'Kilowatt (kW)', id: 'kwatt', fn: decimalSIPrefix('W', 1) },
      { name: 'Megawatt (MW)', id: 'megwatt', fn: decimalSIPrefix('W', 2) },
      { name: 'Gigawatt (GW)', id: 'gwatt', fn: decimalSIPrefix('W', 3) },
      { name: 'Milliwatt (mW)', id: 'mwatt', fn: decimalSIPrefix('W', -1) },
      { name: 'Watt per square meter (W/m²)', id: 'Wm2', fn: toFixedUnit('W/m²') },
      { name: 'Volt-ampere (VA)', id: 'voltamp', fn: decimalSIPrefix('VA') },
      { name: 'Kilovolt-ampere (kVA)', id: 'kvoltamp', fn: decimalSIPrefix('VA', 1) },
      { name: 'Volt-ampere reactive (var)', id: 'voltampreact', fn: decimalSIPrefix('var') },
      { name: 'Kilovolt-ampere reactive (kvar)', id: 'kvoltampreact', fn: decimalSIPrefix('var', 1) },
      { name: 'Watt-hour (Wh)', id: 'watth', fn: decimalSIPrefix('Wh') },
      { name: 'Watt-hour per Kilogram (Wh/kg)', id: 'watthperkg', fn: decimalSIPrefix('Wh/kg') },
      { name: 'Kilowatt-hour (kWh)', id: 'kwatth', fn: decimalSIPrefix('Wh', 1) },
      { name: 'Kilowatt-min (kWm)', id: 'kwattm', fn: decimalSIPrefix('W-Min', 1) },
      { name: 'Ampere-hour (Ah)', id: 'amph', fn: decimalSIPrefix('Ah') },
      { name: 'Kiloampere-hour (kAh)', id: 'kamph', fn: decimalSIPrefix('Ah', 1) },
      { name: 'Milliampere-hour (mAh)', id: 'mamph', fn: decimalSIPrefix('Ah', -1) },
      { name: 'Joule (J)', id: 'joule', fn: decimalSIPrefix('J') },
      { name: 'Electron volt (eV)', id: 'ev', fn: decimalSIPrefix('eV') },
      { name: 'Ampere (A)', id: 'amp', fn: decimalSIPrefix('A') },
      { name: 'Kiloampere (kA)', id: 'kamp', fn: decimalSIPrefix('A', 1) },
      { name: 'Milliampere (mA)', id: 'mamp', fn: decimalSIPrefix('A', -1) },
      { name: 'Volt (V)', id: 'volt', fn: decimalSIPrefix('V') },
      { name: 'Kilovolt (kV)', id: 'kvolt', fn: decimalSIPrefix('V', 1) },
      { name: 'Millivolt (mV)', id: 'mvolt', fn: decimalSIPrefix('V', -1) },
      { name: 'Decibel-milliwatt (dBm)', id: 'dBm', fn: decimalSIPrefix('dBm') },
      { name: 'Ohm (Ω)', id: 'ohm', fn: decimalSIPrefix('Ω') },
      { name: 'Kiloohm (kΩ)', id: 'kohm', fn: decimalSIPrefix('Ω', 1) },
      { name: 'Megaohm (MΩ)', id: 'Mohm', fn: decimalSIPrefix('Ω', 2) },
      { name: 'Farad (F)', id: 'farad', fn: decimalSIPrefix('F') },
      { name: 'Microfarad (µF)', id: 'µfarad', fn: decimalSIPrefix('F', -2) },
      { name: 'Nanofarad (nF)', id: 'nfarad', fn: decimalSIPrefix('F', -3) },
      { name: 'Picofarad (pF)', id: 'pfarad', fn: decimalSIPrefix('F', -4) },
      { name: 'Femtofarad (fF)', id: 'ffarad', fn: decimalSIPrefix('F', -5) },
      { name: 'Henry (H)', id: 'henry', fn: decimalSIPrefix('H') },
      { name: 'Millihenry (mH)', id: 'mhenry', fn: decimalSIPrefix('H', -1) },
      { name: 'Microhenry (µH)', id: 'µhenry', fn: decimalSIPrefix('H', -2) },
      { name: 'Lumens (Lm)', id: 'lumens', fn: decimalSIPrefix('Lm') },
    ],
  },
  {
    name: 'Flow',
    formats: [
      { name: 'Gallons/min (gpm)', id: 'flowgpm', fn: toFixedUnit('gpm') },
      { name: 'Cubic meters/sec (cms)', id: 'flowcms', fn: toFixedUnit('cms') },
      { name: 'Cubic feet/sec (cfs)', id: 'flowcfs', fn: toFixedUnit('cfs') },
      { name: 'Cubic feet/min (cfm)', id: 'flowcfm', fn: toFixedUnit('cfm') },
      { name: 'Litre/hour', id: 'litreh', fn: toFixedUnit('L/h') },
      { name: 'Litre/min (L/min)', id: 'flowlpm', fn: toFixedUnit('L/min') },
      { name: 'milliLitre/min (mL/min)', id: 'flowmlpm', fn: toFixedUnit('mL/min') },
      { name: 'Lux (lx)', id: 'lux', fn: toFixedUnit('lux') },
    ],
  },
  {
    name: 'Force',
    formats: [
      { name: 'Newton-meters (Nm)', id: 'forceNm', fn: decimalSIPrefix('Nm') },
      { name: 'Kilonewton-meters (kNm)', id: 'forcekNm', fn: decimalSIPrefix('Nm', 1) },
      { name: 'Newtons (N)', id: 'forceN', fn: decimalSIPrefix('N') },
      { name: 'Kilonewtons (kN)', id: 'forcekN', fn: decimalSIPrefix('N', 1) },
    ],
  },
  {
    name: 'Hash Rate',
    formats: [
      { name: 'hashes/sec', id: 'Hs', fn: decimalSIPrefix('H/s') },
      { name: 'kilohashes/sec', id: 'KHs', fn: decimalSIPrefix('H/s', 1) },
      { name: 'megahashes/sec', id: 'MHs', fn: decimalSIPrefix('H/s', 2) },
      { name: 'gigahashes/sec', id: 'GHs', fn: decimalSIPrefix('H/s', 3) },
      { name: 'terahashes/sec', id: 'THs', fn: decimalSIPrefix('H/s', 4) },
      { name: 'petahashes/sec', id: 'PHs', fn: decimalSIPrefix('H/s', 5) },
      { name: 'exahashes/sec', id: 'EHs', fn: decimalSIPrefix('H/s', 6) },
    ],
  },
  {
    name: 'Mass',
    formats: [
      { name: 'milligram (mg)', id: 'massmg', fn: decimalSIPrefix('g', -1) },
      { name: 'gram (g)', id: 'massg', fn: decimalSIPrefix('g') },
      { name: 'kilogram (kg)', id: 'masskg', fn: decimalSIPrefix('g', 1) },
      { name: 'metric ton (t)', id: 'masst', fn: toFixedUnit('t') },
    ],
  },
  {
    name: 'length',
    formats: [
      { name: 'millimeter (mm)', id: 'lengthmm', fn: decimalSIPrefix('m', -1) },
      { name: 'feet (ft)', id: 'lengthft', fn: toFixedUnit('ft') },
      { name: 'meter (m)', id: 'lengthm', fn: decimalSIPrefix('m') },
      { name: 'kilometer (km)', id: 'lengthkm', fn: decimalSIPrefix('m', 1) },
      { name: 'mile (mi)', id: 'lengthmi', fn: toFixedUnit('mi') },
    ],
  },
  {
    name: 'Pressure',
    formats: [
      { name: 'Millibars', id: 'pressurembar', fn: decimalSIPrefix('bar', -1) },
      { name: 'Bars', id: 'pressurebar', fn: decimalSIPrefix('bar') },
      { name: 'Kilobars', id: 'pressurekbar', fn: decimalSIPrefix('bar', 1) },
      { name: 'Hectopascals', id: 'pressurehpa', fn: toFixedUnit('hPa') },
      { name: 'Kilopascals', id: 'pressurekpa', fn: toFixedUnit('kPa') },
      { name: 'Inches of mercury', id: 'pressurehg', fn: toFixedUnit('"Hg') },
      { name: 'PSI', id: 'pressurepsi', fn: scaledUnits(1000, ['psi', 'ksi', 'Mpsi']) },
    ],
  },
  {
    name: 'Radiation',
    formats: [
      { name: 'Becquerel (Bq)', id: 'radbq', fn: decimalSIPrefix('Bq') },
      { name: 'curie (Ci)', id: 'radci', fn: decimalSIPrefix('Ci') },
      { name: 'Gray (Gy)', id: 'radgy', fn: decimalSIPrefix('Gy') },
      { name: 'rad', id: 'radrad', fn: decimalSIPrefix('rad') },
      { name: 'Sievert (Sv)', id: 'radsv', fn: decimalSIPrefix('Sv') },
      { name: 'milliSievert (mSv)', id: 'radmsv', fn: decimalSIPrefix('mSv', -1) },
      { name: 'microSievert (µSv)', id: 'radusv', fn: decimalSIPrefix('µSv', -2) },
      { name: 'rem', id: 'radrem', fn: decimalSIPrefix('rem') },
      { name: 'Exposure (C/kg)', id: 'radexpckg', fn: decimalSIPrefix('C/kg') },
      { name: 'roentgen (R)', id: 'radr', fn: decimalSIPrefix('R') },
      { name: 'Sievert/hour (Sv/h)', id: 'radsvh', fn: decimalSIPrefix('Sv/h') },
      { name: 'milliSievert/hour (mSv/h)', id: 'radmsvh', fn: decimalSIPrefix('Sv/h', -1) },
      { name: 'microSievert/hour (µSv/h)', id: 'radusvh', fn: decimalSIPrefix('Sv/h', -2) },
    ],
  },
  {
    name: 'Temperature',
    formats: [
      { name: 'Celsius (°C)', id: 'celsius', fn: toFixedUnit('°C') },
      { name: 'Fahrenheit (°F)', id: 'fahrenheit', fn: toFixedUnit('°F') },
      { name: 'Kelvin (K)', id: 'kelvin', fn: toFixedUnit('K') },
    ],
  },
  {
    name: 'Time',
    formats: [
      { name: 'Hertz (1/s)', id: 'hertz', fn: decimalSIPrefix('Hz') },
      { name: 'nanoseconds (ns)', id: 'ns', fn: toNanoSeconds },
      { name: 'microseconds (µs)', id: 'µs', fn: toMicroSeconds },
      { name: 'milliseconds (ms)', id: 'ms', fn: toMilliSeconds },
      { name: 'seconds (s)', id: 's', fn: toSeconds },
      { name: 'minutes (m)', id: 'm', fn: toMinutes },
      { name: 'hours (h)', id: 'h', fn: toHours },
      { name: 'days (d)', id: 'd', fn: toDays },
      { name: 'duration (ms)', id: 'dtdurationms', fn: toDurationInMilliseconds },
      { name: 'duration (s)', id: 'dtdurations', fn: toDurationInSeconds },
      { name: 'duration (hh:mm:ss)', id: 'dthms', fn: toDurationInHoursMinutesSeconds },
      { name: 'Timeticks (s/100)', id: 'timeticks', fn: toTimeTicks },
      { name: 'clock (ms)', id: 'clockms', fn: toClockMilliseconds },
      { name: 'clock (s)', id: 'clocks', fn: toClockSeconds },
    ],
  },
  {
    name: 'Throughput',
    formats: [
      { name: 'counts/sec (cps)', id: 'cps', fn: simpleCountUnit('cps') },
      { name: 'ops/sec (ops)', id: 'ops', fn: simpleCountUnit('ops') },
      { name: 'requests/sec (rps)', id: 'reqps', fn: simpleCountUnit('reqps') },
      { name: 'reads/sec (rps)', id: 'rps', fn: simpleCountUnit('rps') },
      { name: 'writes/sec (wps)', id: 'wps', fn: simpleCountUnit('wps') },
      { name: 'I/O ops/sec (iops)', id: 'iops', fn: simpleCountUnit('iops') },
      { name: 'counts/min (cpm)', id: 'cpm', fn: simpleCountUnit('cpm') },
      { name: 'ops/min (opm)', id: 'opm', fn: simpleCountUnit('opm') },
      { name: 'reads/min (rpm)', id: 'rpm', fn: simpleCountUnit('rpm') },
      { name: 'writes/min (wpm)', id: 'wpm', fn: simpleCountUnit('wpm') },
    ],
  },
  {
    name: 'Velocity',
    formats: [
      { name: 'meters/second (m/s)', id: 'velocityms', fn: toFixedUnit('m/s') },
      { name: 'kilometers/hour (km/h)', id: 'velocitykmh', fn: toFixedUnit('km/h') },
      { name: 'miles/hour (mph)', id: 'velocitymph', fn: toFixedUnit('mph') },
      { name: 'knot (kn)', id: 'velocityknot', fn: toFixedUnit('kn') },
    ],
  },
  {
    name: 'Volume',
    formats: [
      { name: 'millilitre (mL)', id: 'mlitre', fn: decimalSIPrefix('L', -1) },
      { name: 'litre (L)', id: 'litre', fn: decimalSIPrefix('L') },
      { name: 'cubic meter', id: 'm3', fn: toFixedUnit('m³') },
      { name: 'Normal cubic meter', id: 'Nm3', fn: toFixedUnit('Nm³') },
      { name: 'cubic decimeter', id: 'dm3', fn: toFixedUnit('dm³') },
      { name: 'gallons', id: 'gallons', fn: toFixedUnit('gal') },
    ],
  },
];
