/* eslint-disable @grafana/no-restricted-img-srcs */
/* eslint-disable @typescript-eslint/consistent-type-assertions */
import {
  type AngularMeta,
  type PanelPluginMeta,
  PluginLoadingStrategy,
  PluginSignatureStatus,
  PluginState,
  PluginType,
} from '@grafana/data';

import type { PanelPluginMetas } from '../types';

export const panel: PanelPluginMeta = structuredClone({
  id: 'grafana-test-panel',
  name: 'Test',
  info: {
    author: {
      name: 'Grafana',
      url: '',
    },
    description: '',
    links: [],
    logos: {
      small: 'public/plugins/grafana-test-panel/img/logo.svg',
      large: 'public/plugins/grafana-test-panel/img/logo.svg',
    },
    build: {},
    screenshots: [],
    version: '1.0.0',
    updated: '2026-01-26',
    keywords: ['panel'],
  },
  hideFromList: false,
  sort: 100,
  skipDataQuery: false,
  baseUrl: 'public/plugins/grafana-test-panel',
  signature: PluginSignatureStatus.valid,
  module: 'public/plugins/grafana-test-panel/module.js',
  angular: { detected: false } as AngularMeta,
  loadingStrategy: PluginLoadingStrategy.script,
  type: PluginType.panel,
});

export const clockPanelConfigCDN: PanelPluginMeta = structuredClone({
  id: 'grafana-clock-panel',
  name: 'Clock',
  info: {
    author: {
      name: 'Grafana Labs',
      url: 'https://grafana.com',
    },
    description: 'Clock panel for grafana',
    links: [
      {
        name: 'Project site',
        url: 'https://github.com/grafana/clock-panel',
      },
      {
        name: 'MIT License',
        url: 'https://github.com/grafana/clock-panel/blob/master/LICENSE',
      },
    ],
    logos: {
      small:
        'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/img/clock.svg',
      large:
        'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/img/clock.svg',
    },
    build: {},
    screenshots: [
      {
        name: 'Showcase',
        path: 'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/img/screenshot-showcase.png',
      },
      {
        name: 'Options',
        path: 'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/img/screenshot-clock-options.png',
      },
    ],
    version: '3.2.1',
    updated: '2026-01-12',
    keywords: ['clock', 'panel'],
  },
  hideFromList: false,
  sort: 100,
  skipDataQuery: false,
  state: '' as PluginState,
  baseUrl: 'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel',
  signature: 'valid' as PluginSignatureStatus,
  module: 'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/module.js',
  angular: { detected: false } as AngularMeta,
  loadingStrategy: 'script' as PluginLoadingStrategy,
  moduleHash: 'sha256-VWOd7WYQVvhfE36pnbvZHoIG25IkO9aaXYJwVKnH538=',
  translations: {
    'cs-CZ':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/cs-CZ/grafana-clock-panel.json',
    'de-DE':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/de-DE/grafana-clock-panel.json',
    'en-US':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/en-US/grafana-clock-panel.json',
    'es-ES':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/es-ES/grafana-clock-panel.json',
    'fr-FR':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/fr-FR/grafana-clock-panel.json',
    'hu-HU':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/hu-HU/grafana-clock-panel.json',
    'id-ID':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/id-ID/grafana-clock-panel.json',
    'it-IT':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/it-IT/grafana-clock-panel.json',
    'ja-JP':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/ja-JP/grafana-clock-panel.json',
    'ko-KR':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/ko-KR/grafana-clock-panel.json',
    'nl-NL':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/nl-NL/grafana-clock-panel.json',
    'pl-PL':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/pl-PL/grafana-clock-panel.json',
    'pt-BR':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/pt-BR/grafana-clock-panel.json',
    'pt-PT':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/pt-PT/grafana-clock-panel.json',
    'ru-RU':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/ru-RU/grafana-clock-panel.json',
    'sv-SE':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/sv-SE/grafana-clock-panel.json',
    'tr-TR':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/tr-TR/grafana-clock-panel.json',
    'zh-Hans':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/zh-Hans/grafana-clock-panel.json',
    'zh-Hant':
      'https://plugins-cdn.grafana-dev.net/grafana-clock-panel/3.2.1/public/plugins/grafana-clock-panel/locales/zh-Hant/grafana-clock-panel.json',
  },
  type: PluginType.panel,
});

export const clockPanelConfigOnPrem: PanelPluginMeta = structuredClone({
  id: 'grafana-clock-panel',
  name: 'Clock',
  info: {
    author: {
      name: 'Grafana Labs',
      url: 'https://grafana.com',
    },
    description: 'Clock panel for grafana',
    links: [
      {
        name: 'Project site',
        url: 'https://github.com/grafana/clock-panel',
      },
      {
        name: 'MIT License',
        url: 'https://github.com/grafana/clock-panel/blob/master/LICENSE',
      },
    ],
    logos: {
      small: 'public/plugins/grafana-clock-panel/img/clock.svg',
      large: 'public/plugins/grafana-clock-panel/img/clock.svg',
    },
    build: {},
    screenshots: [
      {
        name: 'Showcase',
        path: 'public/plugins/grafana-clock-panel/img/screenshot-showcase.png',
      },
      {
        name: 'Options',
        path: 'public/plugins/grafana-clock-panel/img/screenshot-clock-options.png',
      },
    ],
    version: '3.2.0',
    updated: '2025-12-10',
    keywords: ['clock', 'panel'],
  },
  hideFromList: false,
  sort: 100,
  skipDataQuery: false,
  state: '' as PluginState,
  baseUrl: 'public/plugins/grafana-clock-panel',
  signature: 'valid' as PluginSignatureStatus,
  module: 'public/plugins/grafana-clock-panel/module.js',
  angular: { detected: false } as AngularMeta,
  loadingStrategy: 'script' as PluginLoadingStrategy,
  translations: {
    'cs-CZ': 'public/plugins/grafana-clock-panel/locales/cs-CZ/grafana-clock-panel.json',
    'de-DE': 'public/plugins/grafana-clock-panel/locales/de-DE/grafana-clock-panel.json',
    'en-US': 'public/plugins/grafana-clock-panel/locales/en-US/grafana-clock-panel.json',
    'es-ES': 'public/plugins/grafana-clock-panel/locales/es-ES/grafana-clock-panel.json',
    'fr-FR': 'public/plugins/grafana-clock-panel/locales/fr-FR/grafana-clock-panel.json',
    'hu-HU': 'public/plugins/grafana-clock-panel/locales/hu-HU/grafana-clock-panel.json',
    'id-ID': 'public/plugins/grafana-clock-panel/locales/id-ID/grafana-clock-panel.json',
    'it-IT': 'public/plugins/grafana-clock-panel/locales/it-IT/grafana-clock-panel.json',
    'ja-JP': 'public/plugins/grafana-clock-panel/locales/ja-JP/grafana-clock-panel.json',
    'ko-KR': 'public/plugins/grafana-clock-panel/locales/ko-KR/grafana-clock-panel.json',
    'nl-NL': 'public/plugins/grafana-clock-panel/locales/nl-NL/grafana-clock-panel.json',
    'pl-PL': 'public/plugins/grafana-clock-panel/locales/pl-PL/grafana-clock-panel.json',
    'pt-BR': 'public/plugins/grafana-clock-panel/locales/pt-BR/grafana-clock-panel.json',
    'pt-PT': 'public/plugins/grafana-clock-panel/locales/pt-PT/grafana-clock-panel.json',
    'ru-RU': 'public/plugins/grafana-clock-panel/locales/ru-RU/grafana-clock-panel.json',
    'sv-SE': 'public/plugins/grafana-clock-panel/locales/sv-SE/grafana-clock-panel.json',
    'tr-TR': 'public/plugins/grafana-clock-panel/locales/tr-TR/grafana-clock-panel.json',
    'zh-Hans': 'public/plugins/grafana-clock-panel/locales/zh-Hans/grafana-clock-panel.json',
    'zh-Hant': 'public/plugins/grafana-clock-panel/locales/zh-Hant/grafana-clock-panel.json',
  },
  type: PluginType.panel,
});

export const panels: PanelPluginMetas = structuredClone({
  alertlist: {
    id: 'alertlist',
    name: 'Alert list',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Shows list of alerts and their current status',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/alert-list/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/alertlist/img/icn-singlestat-panel.svg',
        large: 'app/plugins/panel/alertlist/img/icn-singlestat-panel.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 15,
    skipDataQuery: true,
    baseUrl: 'app/plugins/panel/alertlist',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/alertlist',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  annolist: {
    id: 'annolist',
    name: 'Annotations list',
    aliasIds: ['ryantxu-annolist-panel'],
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'List annotations',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/annotations/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/annolist/img/icn-annolist-panel.svg',
        large: 'app/plugins/panel/annolist/img/icn-annolist-panel.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 100,
    skipDataQuery: true,
    baseUrl: 'app/plugins/panel/annolist',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/annolist',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  barchart: {
    id: 'barchart',
    name: 'Bar chart',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Categorical charts with group support',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/bar-chart/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/barchart/img/barchart.svg',
        large: 'app/plugins/panel/barchart/img/barchart.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 2,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/barchart',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/barchart',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  bargauge: {
    id: 'bargauge',
    name: 'Bar gauge',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Horizontal and vertical gauges',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/bar-gauge/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/bargauge/img/icon_bar_gauge.svg',
        large: 'app/plugins/panel/bargauge/img/icon_bar_gauge.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 5,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/bargauge',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/bargauge',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  candlestick: {
    id: 'candlestick',
    name: 'Candlestick',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Graphical representation of price movements of a security, derivative, or currency.',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/candlestick/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/candlestick/img/candlestick.svg',
        large: 'app/plugins/panel/candlestick/img/candlestick.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: ['financial', 'price', 'currency', 'k-line'],
    },
    hideFromList: false,
    sort: 100,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/candlestick',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/candlestick',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  canvas: {
    id: 'canvas',
    name: 'Canvas',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Explicit element placement',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/canvas/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/canvas/img/icn-canvas.svg',
        large: 'app/plugins/panel/canvas/img/icn-canvas.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 100,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/canvas',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/canvas',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  dashlist: {
    id: 'dashlist',
    name: 'Dashboard list',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'List of dynamic links to other dashboards',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/dashboard-list/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/dashlist/img/icn-dashlist-panel.svg',
        large: 'app/plugins/panel/dashlist/img/icn-dashlist-panel.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 16,
    skipDataQuery: true,
    baseUrl: 'app/plugins/panel/dashlist',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/dashlist',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  debug: {
    id: 'debug',
    name: 'Debug',
    aliasIDs: ['debugX'],
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Debug Panel for Grafana',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
      ],
      logos: {
        small: 'app/plugins/panel/debug/img/icn-debug.svg',
        large: 'app/plugins/panel/debug/img/icn-debug.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: null,
    },
    hideFromList: false,
    sort: 100,
    skipDataQuery: false,
    state: PluginState.alpha,
    baseUrl: 'app/plugins/panel/debug',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/debug',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  flamegraph: {
    id: 'flamegraph',
    name: 'Flame Graph',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: '',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/flame-graph/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/flamegraph/img/icn-flamegraph.svg',
        large: 'app/plugins/panel/flamegraph/img/icn-flamegraph.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 100,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/flamegraph',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/flamegraph',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  gauge: {
    id: 'gauge',
    name: 'Gauge',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Standard gauge visualization',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/gauge/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/gauge/img/icon_gauge.svg',
        large: 'app/plugins/panel/gauge/img/icon_gauge.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 4,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/gauge',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/gauge',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  geomap: {
    id: 'geomap',
    name: 'Geomap',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Geomap panel',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/geomap/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/geomap/img/icn-geomap.svg',
        large: 'app/plugins/panel/geomap/img/icn-geomap.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 100,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/geomap',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/geomap',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  gettingstarted: {
    id: 'gettingstarted',
    name: 'Getting Started',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: '',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
      ],
      logos: {
        small: 'app/plugins/panel/gettingstarted/img/icn-dashlist-panel.svg',
        large: 'app/plugins/panel/gettingstarted/img/icn-dashlist-panel.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: true,
    sort: 100,
    skipDataQuery: true,
    baseUrl: 'app/plugins/panel/gettingstarted',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/gettingstarted',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  heatmap: {
    id: 'heatmap',
    name: 'Heatmap',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Like a histogram over time',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/heatmap/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/heatmap/img/icn-heatmap-panel.svg',
        large: 'app/plugins/panel/heatmap/img/icn-heatmap-panel.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 10,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/heatmap',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/heatmap',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  histogram: {
    id: 'histogram',
    name: 'Histogram',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Distribution of values presented as a bar chart.',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/histogram/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/histogram/img/histogram.svg',
        large: 'app/plugins/panel/histogram/img/histogram.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: ['distribution', 'bar chart', 'frequency', 'proportional'],
    },
    hideFromList: false,
    sort: 12,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/histogram',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/histogram',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  logs: {
    id: 'logs',
    name: 'Logs',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: '',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/logs/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/logs/img/icn-logs-panel.svg',
        large: 'app/plugins/panel/logs/img/icn-logs-panel.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 100,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/logs',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/logs',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  news: {
    id: 'news',
    name: 'News',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'RSS feed reader',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/news/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/news/img/news.svg',
        large: 'app/plugins/panel/news/img/news.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 17,
    skipDataQuery: true,
    state: PluginState.beta,
    baseUrl: 'app/plugins/panel/news',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/news',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  nodeGraph: {
    id: 'nodeGraph',
    name: 'Node Graph',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: '',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/node-graph/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/nodeGraph/img/icn-node-graph.svg',
        large: 'app/plugins/panel/nodeGraph/img/icn-node-graph.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 100,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/nodeGraph',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/nodeGraph',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  piechart: {
    id: 'piechart',
    name: 'Pie chart',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'The new core pie chart visualization',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/pie-chart/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/piechart/img/icon_piechart.svg',
        large: 'app/plugins/panel/piechart/img/icon_piechart.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 8,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/piechart',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/piechart',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  stat: {
    id: 'stat',
    name: 'Stat',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Big stat values & sparklines',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/stat/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/stat/img/icn-singlestat-panel.svg',
        large: 'app/plugins/panel/stat/img/icn-singlestat-panel.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 3,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/stat',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/stat',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  'state-timeline': {
    id: 'state-timeline',
    name: 'State timeline',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'State changes and durations',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/state-timeline/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/state-timeline/img/timeline.svg',
        large: 'app/plugins/panel/state-timeline/img/timeline.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 9,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/state-timeline',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/state-timeline',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  'status-history': {
    id: 'status-history',
    name: 'Status history',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Periodic status history',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/status-history/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/status-history/img/status.svg',
        large: 'app/plugins/panel/status-history/img/status.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 11,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/status-history',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/status-history',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  table: {
    id: 'table',
    name: 'Table',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Supports many column styles',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/table/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/table/img/icn-table-panel.svg',
        large: 'app/plugins/panel/table/img/icn-table-panel.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 6,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/table',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/table',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  text: {
    id: 'text',
    name: 'Text',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Supports markdown and html content',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/text/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/text/img/icn-text-panel.svg',
        large: 'app/plugins/panel/text/img/icn-text-panel.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 14,
    skipDataQuery: true,
    baseUrl: 'app/plugins/panel/text',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/text',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  timeseries: {
    id: 'timeseries',
    name: 'Time series',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Time based line, area and bar charts',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/time-series/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/timeseries/img/icn-timeseries-panel.svg',
        large: 'app/plugins/panel/timeseries/img/icn-timeseries-panel.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 1,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/timeseries',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/timeseries',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  traces: {
    id: 'traces',
    name: 'Traces',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: '',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/traces/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/traces/img/traces-panel.svg',
        large: 'app/plugins/panel/traces/img/traces-panel.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 100,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/traces',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/traces',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  trend: {
    id: 'trend',
    name: 'Trend',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Like timeseries, but when x != time',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/trend/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/trend/img/trend.svg',
        large: 'app/plugins/panel/trend/img/trend.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: false,
    sort: 100,
    skipDataQuery: false,
    state: PluginState.beta,
    baseUrl: 'app/plugins/panel/trend',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/trend',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  welcome: {
    id: 'welcome',
    name: 'Welcome',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: '',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
      ],
      logos: {
        small: 'app/plugins/panel/welcome/img/icn-dashlist-panel.svg',
        large: 'app/plugins/panel/welcome/img/icn-dashlist-panel.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: [],
    },
    hideFromList: true,
    sort: 100,
    skipDataQuery: true,
    baseUrl: 'app/plugins/panel/welcome',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/welcome',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
  xychart: {
    id: 'xychart',
    name: 'XY Chart',
    info: {
      author: {
        name: 'Grafana Labs',
        url: 'https://grafana.com',
      },
      description: 'Supports arbitrary X vs Y in a graph to visualize the relationship between two variables.',
      links: [
        {
          name: 'Raise issue',
          url: 'https://github.com/grafana/grafana/issues/new',
        },
        {
          name: 'Documentation',
          url: 'https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/xy-chart/',
        },
      ],
      logos: {
        small: 'app/plugins/panel/xychart/img/icn-xychart.svg',
        large: 'app/plugins/panel/xychart/img/icn-xychart.svg',
      },
      build: {},
      screenshots: [],
      version: '',
      updated: '',
      keywords: ['scatter', 'plot'],
    },
    hideFromList: false,
    sort: 100,
    skipDataQuery: false,
    baseUrl: 'app/plugins/panel/xychart',
    signature: PluginSignatureStatus.internal,
    module: 'core:plugin/xychart',
    angular: { detected: false } as AngularMeta,
    loadingStrategy: PluginLoadingStrategy.script,
    type: PluginType.panel,
  },
});
