/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * API version: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type AlertNotification struct {
	Created               time.Time       `json:"created,omitempty"`
	DisableResolveMessage bool            `json:"disableResolveMessage,omitempty"`
	Frequency             string          `json:"frequency,omitempty"`
	Id                    int64           `json:"id,omitempty"`
	IsDefault             bool            `json:"isDefault,omitempty"`
	Name                  string          `json:"name,omitempty"`
	SecureFields          map[string]bool `json:"secureFields,omitempty"`
	SendReminder          bool            `json:"sendReminder,omitempty"`
	Settings              *Json           `json:"settings,omitempty"`
	Type_                 string          `json:"type,omitempty"`
	Uid                   string          `json:"uid,omitempty"`
	Updated               time.Time       `json:"updated,omitempty"`
}
