/*
 * Grafana HTTP API.
 *
 * The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.
 *
 * API version: 0.0.1
 * Contact: hello@grafana.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Silence silence
type Silence struct {
	// comment
	Comment string `json:"comment"`
	// created by
	CreatedBy string `json:"createdBy"`
	// ends at
	EndsAt   time.Time `json:"endsAt"`
	Matchers *Matchers `json:"matchers"`
	// starts at
	StartsAt time.Time `json:"startsAt"`
}
