// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify the template in templates/icon.js.
// Run "yarn generate" to update.
import { memo } from 'react';

import { IconBase, IconProps } from '../IconBase';
const SvgCloud = (props: IconProps) => (
  <IconBase xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" {...props}>
    <path d="M18.42,9.21a7,7,0,0,0-13.36,1.9A4,4,0,0,0,6,19H17a5,5,0,0,0,1.42-9.79ZM17,17H6a2,2,0,0,1,0-4,1,1,0,0,0,1-1,5,5,0,0,1,9.73-1.61,1,1,0,0,0,.78.66A3,3,0,0,1,17,17Z" />
  </IconBase>
);
const Memo = memo(SvgCloud);
export default Memo;
