import { TimeOption } from '@grafana/data';

import { ComboboxOption } from '../Combobox/types';

export const quickOptions: TimeOption[] = [
  { from: 'now-8h', to: 'now', display: '最近8小时' },
  { from: 'now/d+8h', to: 'now/d-8h', display: '白班' },
  { from: 'now/d+16h', to: 'now/d', display: '中班' },
  { from: 'now/d', to: 'now/d-16h', display: '晚班' },
  { from: 'now/d+8h', to: 'now', display: '今日整班' },
  { from: 'now-1d/d+8h', to: 'now-1d/d+8h', display: '昨日整班' },
  { from: 'now-2d/d+8h', to: 'now-2d/d+8h', display: '前日整班' },
  { from: 'now/d', to: 'now', display: '今天'},
  { from: 'now-1d/d', to: 'now-1d/d', display: '昨天' },
  { from: 'now-2d/d', to: 'now-2d/d', display: '前天' },
  { from: 'now/w', to: 'now', display: '本周' },
  { from: 'now-1w/w', to: 'now-1w/w', display: '上周' },
  { from: 'now/M', to: 'now', display: '本月' },
  { from: 'now-1M/M', to: 'now-1M/M', display: '上月' },
  { from: 'now/y', to: 'now', display: '今年' },
  { from: 'now-1y/y', to: 'now-1y/y', display: '去年' },
  { from: 'now-1y/fy', to: 'now-1y/fy', display: '去年的财政年' },

  { from: 'now-5m', to: 'now', display: '最近5分钟', splitter: true },
  { from: 'now-15m', to: 'now', display: '最近15分钟' },
  { from: 'now-30m', to: 'now', display: '最近30分钟' },
  { from: 'now-1h', to: 'now', display: '最近1小时' },
  { from: 'now-3h', to: 'now', display: '最近3小时' },
  { from: 'now-12h', to: 'now', display: '最近12小时' },
  { from: 'now-24h', to: 'now', display: '最近24小时' },
  { from: 'now-2d', to: 'now', display: '最近2天' },
  { from: 'now-7d', to: 'now', display: '最近7天' },
  { from: 'now-30d', to: 'now', display: '最近30天' },
  { from: 'now-90d', to: 'now', display: '最近90天' },
  { from: 'now-6M', to: 'now', display: '最近6个月' },
  { from: 'now-1y', to: 'now', display: '最近1年' },
  { from: 'now-2y', to: 'now', display: '最近2年' },
  { from: 'now-5y', to: 'now', display: '最近5年' },
  { from: 'now-1Q/fQ', to: 'now-1Q/fQ', display: '前季度' },
  { from: 'now-1y/y', to: 'now-1y/y', display: '前一年' },
  { from: 'now-1y/fy', to: 'now-1y/fy', display: '前财政年' },
  { from: 'now/d', to: 'now', display: '今天到目前' },
  { from: 'now/w', to: 'now', display: '本周到目前' },
  { from: 'now/M', to: 'now/M', display: '本月' },
  { from: 'now/M', to: 'now', display: '本月到目前' },
  { from: 'now/y', to: 'now/y', display: '今年' },
  { from: 'now/y', to: 'now', display: '今年到目前' },
  { from: 'now/fQ', to: 'now', display: '今年的季度到目前' },
  { from: 'now/fQ', to: 'now/fQ', display: '今年的季度' },
  { from: 'now/fy', to: 'now', display: '今年的财政年到目前' },
  { from: 'now/fy', to: 'now/fy', display: '今年的财政年' },
];

export const monthOptions: Array<ComboboxOption<number>> = [
  { label: '一月', value: 0 },
  { label: '二月', value: 1 },
  { label: '三月', value: 2 },
  { label: '四月', value: 3 },
  { label: '五月', value: 4 },
  { label: '六月', value: 5 },
  { label: '七月', value: 6 },
  { label: '八月', value: 7 },
  { label: '九月', value: 8 },
  { label: '十月', value: 9 },
  { label: '十一月', value: 10 },
  { label: '十二月', value: 11 },
];
