// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     public/app/plugins/gen.go
// Using jennies:
//     TSTypesJenny
//     PluginTSTypesJenny
//
// Run 'make gen-cue' from repository root to regenerate.

import * as common from '@grafana/schema';

export const PanelCfgModelVersion = Object.freeze([0, 0]);

export interface PanelOptions extends common.OptionsWithTimezones {
  legend: common.VizLegendOptions;
  tooltip: common.VizTooltipOptions;
}

export interface PanelFieldConfig extends common.GraphFieldConfig {}
