// This file was generated by lezer-generator. You probably shouldn't edit it.
export const AlertRuleSearch = 1,
  FilterExpression = 2,
  DataSourceFilter = 3,
  FilterValue = 4,
  NameSpaceFilter = 5,
  LabelFilter = 6,
  GroupFilter = 7,
  RuleFilter = 8,
  StateFilter = 9,
  TypeFilter = 10,
  FreeFormExpression = 11;
