package cloudwatch

var cloudwatchUnitMappings = map[string]string{
	"Seconds":      "s",
	"Microseconds": "µs",
	"Milliseconds": "ms",
	"Bytes":        "bytes",
	"Kilobytes":    "kbytes",
	"Megabytes":    "mbytes",
	"Gigabytes":    "gbytes",
	//"Terabytes":        "",
	"Bits": "bits",
	//"Kilobits":         "",
	//"Megabits":         "",
	//"Gigabits":         "",
	//"Terabits":         "",
	"Percent": "percent",
	//"Count":            "",
	"Bytes/Second":     "Bps",
	"Kilobytes/Second": "KBs",
	"Megabytes/Second": "MBs",
	"Gigabytes/Second": "GBs",
	//"Terabytes/Second": "",
	"Bits/Second":     "bps",
	"Kilobits/Second": "Kbits",
	"Megabits/Second": "Mbits",
	"Gigabits/Second": "Gbits",
	//"Terabits/Second":  "",
	//"Count/Second":     "",
}
