# Copyright 2011 The Graphics-Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=code.google.com/p/graphics-go/graphics/convolve
GOFILES=\
	convolve.go\

include $(GOROOT)/src/Make.pkg
