{
 "title": "Active Directory",
 "tags": [
  "Windows",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Active Directory",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 8 charts to display the metrics for the `Active directory servers`. Bule Medora needs to be [configured](https://bluemedora.com/monitoring-microsoft-active-directory-with-stackdriver-logging/). The metrics include resource utilization and service status."
   }
  },
  {
   "title": "Services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/microsoft_activedirectory/domain_controller/services",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Generic Node - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/microsoft_activedirectory/domain_controller/cpu/utilization",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "LDAP Client Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/microsoft_activedirectory/domain_controller/ldap_client_sessions",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Physical Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/microsoft_activedirectory/domain_controller/memory/usage",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Physical Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/microsoft_activedirectory/domain_controller/memory/physical_utilization",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Replication Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/microsoft_activedirectory/domain_controller/replication_throughput",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_COUNT_TRUE",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/microsoft_activedirectory/service/running",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/microsoft_activedirectory/service/status",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  }
 ]
}