{
 "title": "Istio Control Plane Dashboard",
 "tags": [
  "Servicemesh",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Proxy Clients by Pod Name, Revision",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [
       "resource.label.pod_name",
       "metric.label.revision"
      ],
      "metricKind": "GAUGE",
      "metricType": "istio.io/control/proxy_clients",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "XDS Configuration Pushes by Type, Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [
       "metric.label.type",
       "metric.label.success"
      ],
      "metricKind": "DELTA",
      "metricType": "istio.io/control/config_push_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "XDS Configuration Rejected by Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [ "metric.label.type" ],
      "metricKind": "DELTA",
      "metricType": "istio.io/control/rejected_config_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Configuration Event by Type, Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "metric.label.operation",
       "!=",
       "updatesame"
      ],
      "groupBys": [
       "metric.label.type",
       "metric.label.operation"
      ],
      "metricKind": "DELTA",
      "metricType": "istio.io/control/config_event_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Configuration Validation Count by Type, Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [
       "metric.label.type",
       "metric.label.success"
      ],
      "metricKind": "DELTA",
      "metricType": "istio.io/control/config_validation_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Sidecar Injection Count by Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [ "metric.label.success" ],
      "metricKind": "DELTA",
      "metricType": "istio.io/control/sidecar_injection_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "CPU Limit and Usage by Cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.container_name",
       "=",
       "discovery",
       "AND",
       "resource.label.pod_name",
       "=monitoring.regex.full_match(",
       "istio.*"
      ],
      "groupBys": [
       "resource.label.container_name",
       "resource.label.cluster_name"
      ],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/container/cpu/core_usage_time",
      "projectName": "$project",
      "unit": "s{CPU}",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.container_name",
       "=",
       "discovery",
       "AND",
       "resource.label.pod_name",
       "=monitoring.regex.full_match(",
       "istio-.*"
      ],
      "groupBys": [
       "resource.label.container_name",
       "resource.label.cluster_name"
      ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/limit_cores",
      "projectName": "$project",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Memory Usage and Limit by Cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.container_name",
       "=",
       "discovery",
       "AND",
       "resource.label.pod_name",
       "=monitoring.regex.full_match(",
       "istio.*"
      ],
      "groupBys": [
       "resource.label.container_name",
       "resource.label.cluster_name"
      ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/used_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.container_name",
       "=",
       "discovery",
       "AND",
       "resource.label.pod_name",
       "=monitoring.regex.full_match(",
       "istio.*"
      ],
      "groupBys": [
       "resource.label.container_name",
       "resource.label.cluster_name"
      ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/limit_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}