{
 "title": "BigQuery Query Monitoring",
 "tags": [
  "Bigdata",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "BigQuery Query Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 12 charts for the related [BigQuery metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-bigquery), including `uploaded bytes`, `scanned bytes`, `uploaded rows`, `query count`, and `query execution time` etc."
   }
  },
  {
   "title": "Uploaded bytes billed by label.project_id [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "bigquery_dataset"
      ],
      "groupBys": [ "resource.label.project_id" ],
      "metricKind": "DELTA",
      "metricType": "bigquery.googleapis.com/storage/uploaded_bytes_billed",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Scanned bytes, billed and uploaded by label.project_id [SUM], ...",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "global"
      ],
      "groupBys": [ "resource.label.project_id" ],
      "metricKind": "DELTA",
      "metricType": "bigquery.googleapis.com/query/scanned_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "global"
      ],
      "groupBys": [ "resource.label.project_id" ],
      "metricKind": "DELTA",
      "metricType": "bigquery.googleapis.com/query/scanned_bytes_billed",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "bigquery_dataset"
      ],
      "groupBys": [ "resource.label.project_id" ],
      "metricKind": "DELTA",
      "metricType": "bigquery.googleapis.com/storage/uploaded_bytes_billed",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Stored bytes by label.dataset_id [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "bigquery_dataset"
      ],
      "groupBys": [ "resource.label.dataset_id" ],
      "metricKind": "GAUGE",
      "metricType": "bigquery.googleapis.com/storage/stored_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Uploaded rows by label.project_id [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "bigquery_dataset"
      ],
      "groupBys": [ "resource.label.project_id" ],
      "metricKind": "DELTA",
      "metricType": "bigquery.googleapis.com/storage/uploaded_row_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Table count by label.project_id [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "bigquery_dataset"
      ],
      "groupBys": [ "resource.label.project_id" ],
      "metricKind": "GAUGE",
      "metricType": "bigquery.googleapis.com/storage/table_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Job count by label.project_id [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "bigquery_project"
      ],
      "groupBys": [ "resource.label.project_id" ],
      "metricKind": "GAUGE",
      "metricType": "bigquery.googleapis.com/job/num_in_flight",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Query execution times by label.project_id [99TH PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "perSeriesAligner": "ALIGN_NEXT_OLDER",
      "filters": [
       "resource.type",
       "=",
       "bigquery_project"
      ],
      "groupBys": [ "resource.label.project_id" ],
      "metricKind": "GAUGE",
      "metricType": "bigquery.googleapis.com/query/execution_times",
      "projectName": "$project",
      "unit": "s",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Query count by label.project_id [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "bigquery_project"
      ],
      "groupBys": [ "resource.label.project_id" ],
      "metricKind": "GAUGE",
      "metricType": "bigquery.googleapis.com/query/count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Slots used by project, reservation, and job type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "global"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "bigquery.googleapis.com/slots/allocated",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Slots used by project, reservation, and job type by label.project_id [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "bigquery_project"
      ],
      "groupBys": [ "resource.label.project_id" ],
      "metricKind": "GAUGE",
      "metricType": "bigquery.googleapis.com/slots/allocated",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Consumed API - Request latencies (filtered) (grouped) [99TH PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "perSeriesAligner": "ALIGN_SUM",
      "filters": [
       "resource.type",
       "=",
       "consumed_api",
       "AND",
       "resource.label.service",
       "=",
       "bigquery.googleapis.com"
      ],
      "groupBys": [ "resource.label.method" ],
      "metricKind": "DELTA",
      "metricType": "serviceruntime.googleapis.com/api/request_latencies",
      "projectName": "$project",
      "unit": "s",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Reservation total bytes by label.project_id [SUM], ...",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "bigquery_project"
      ],
      "groupBys": [ "resource.label.project_id" ],
      "metricKind": "GAUGE",
      "metricType": "bigquerybiengine.googleapis.com/reservation/total_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "bigquery_project"
      ],
      "groupBys": [ "resource.label.project_id" ],
      "metricKind": "GAUGE",
      "metricType": "bigquerybiengine.googleapis.com/reservation/used_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}