{
 "title": "Bigtable Monitoring",
 "tags": [
  "Storage",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Bigtable Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 13 charts for the related [Bigtable metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-bigtable), including `CPU load`, `Disk load`, `Request count`, `Error count`, and others."
   }
  },
  {
   "title": "Cluster - Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "bigtable_cluster"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "bigtable.googleapis.com/cluster/node_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Data stored",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "bigtable_table"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "bigtable.googleapis.com/table/bytes_used",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "bigtable_cluster"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "bigtable.googleapis.com/cluster/cpu_load",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "CPU load (hottest node)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "bigtable_cluster"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "bigtable.googleapis.com/cluster/cpu_load_hottest_node",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Disk load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "bigtable_cluster"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "bigtable.googleapis.com/cluster/disk_load",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Table - Error count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "bigtable_table"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "bigtable.googleapis.com/server/error_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Table - Received bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "bigtable_table"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "bigtable.googleapis.com/server/received_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Table - Sent bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "bigtable_table"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "bigtable.googleapis.com/server/sent_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Table - Request count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "bigtable_table"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "bigtable.googleapis.com/server/request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Returned rows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "bigtable_table"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "bigtable.googleapis.com/server/returned_rows_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Server Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "bigtable_table"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "bigtable.googleapis.com/server/latencies",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Storage capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "bigtable_cluster"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "bigtable.googleapis.com/disk/storage_capacity",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Cluster - Storage utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "bigtable_cluster"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "bigtable.googleapis.com/cluster/storage_utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  }
 ]
}