{
 "title": "CartService Monitoring",
 "tags": [
  "Microservices",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "CartService Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 7 charts to display the metrics for the `cart service` in our [demo application](https://github.com/GoogleCloudPlatform/microservices-demo). The metrics include resource utilization and bytes transmitted."
   }
  },
  {
   "title": "CPU limit utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "cartservice"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/limit_utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "CPU request utilization for demo, cartservice",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "cartservice"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/request_utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Limit cores for demo, cartservice",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "cartservice"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/limit_cores",
      "projectName": "$project",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Kubernetes Container - Memory usage for demo, cartservice",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "cartservice"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/used_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Kubernetes Pod - Bytes received for demo, cartservice",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "cartservice"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/pod/network/received_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Kubernetes Pod - Bytes transmitted for demo, cartservice",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "cartservice"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/pod/network/sent_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Pod volume capacity for demo, cartservice",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "cartservice"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/total_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "cartservice"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/used_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}