{
 "title": "Cloud SQL Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Instance state [COUNT]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.state}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_COUNT_TRUE",
      "filters": [],
      "groupBys": [ "metric.label.state" ],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/instance_state",
      "perSeriesAligner": "ALIGN_NEXT_OLDER",
      "projectName": "$project",
      "unit": "",
      "valueType": "BOOL"
     }
    }
   ]
  },
  {
   "title": "Server up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/up",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Total CPU reserved cores",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/cpu/reserved_cores",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "CPU utilization [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_95",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_50",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_05",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Total Memory quota, Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/memory/quota",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "{{metric.name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/memory/usage",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Memory utilization [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_05",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/memory/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_50",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/memory/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_95",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/memory/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Total Disk quota, Bytes used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/quota",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "{{metric.name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/bytes_used",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk utilization [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_05",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_50",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_95",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk read IO [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_05",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/read_ops_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_50",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/read_ops_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_95",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/read_ops_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk write IO [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_05",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/write_ops_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_50",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/write_ops_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_95",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/write_ops_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}