{
 "title": "VPN Monitoring",
 "tags": [
  "Networking",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "VPN Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 8 charts for the related [Cloud VPN metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-vpn), including `Number of connections`, `Tunnel established`, and metrics for incoming/outgoing network traffic."
   }
  },
  {
   "title": "Number of connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "vpn_gateway"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/gateway/connections",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Tunnel established",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "vpn_gateway"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "vpn.googleapis.com/tunnel_established",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Cloud VPN Gateway - Received bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "vpn_gateway"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Cloud VPN Gateway - Sent bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "vpn_gateway"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Cloud VPN Gateway - Received packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "vpn_gateway"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/received_packets_count",
      "projectName": "$project",
      "unit": "{packets}",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Cloud VPN Gateway - Sent packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "vpn_gateway"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/sent_packets_count",
      "projectName": "$project",
      "unit": "{packets}",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Incoming packets dropped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "vpn_gateway"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_received_packets_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Outgoing packets dropped",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "vpn_gateway"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpn.googleapis.com/network/dropped_sent_packets_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}