{
 "title": "Cloud Run Monitoring",
 "tags": [
  "Compute",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Cloud Run Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 7 charts for the related [Cloud Run metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-run), including `Request Count`, `Request Latency`, `Billable Instance Time`, `Container CPU Allocation`, `Container Memory Allocation`, `Container CPU Utilization`, and `Container Memory Utilization`."
   }
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_COUNT",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "cloud_run_revision"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "run.googleapis.com/request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "cloud_run_revision"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "run.googleapis.com/request_latencies",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "cloud_run_revision"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "run.googleapis.com/request_latencies",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "cloud_run_revision"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "run.googleapis.com/request_latencies",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MAX",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "cloud_run_revision"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "run.googleapis.com/request_latencies",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Billable Instance Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "cloud_run_revision"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "run.googleapis.com/container/billable_instance_time",
      "projectName": "$project",
      "unit": "s",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Container CPU Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "cloud_run_revision"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "run.googleapis.com/container/cpu/allocation_time",
      "projectName": "$project",
      "unit": "s{CPU}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Container Memory Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "cloud_run_revision"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "run.googleapis.com/container/memory/allocation_time",
      "projectName": "$project",
      "unit": "GiBy.s",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Container CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "cloud_run_revision"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "run.googleapis.com/container/cpu/utilizations",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "cloud_run_revision"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "run.googleapis.com/container/cpu/utilizations",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "cloud_run_revision"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "run.googleapis.com/container/cpu/utilizations",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MAX",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "cloud_run_revision"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "run.googleapis.com/container/cpu/utilizations",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Container Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "cloud_run_revision"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "run.googleapis.com/container/memory/utilizations",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "cloud_run_revision"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "run.googleapis.com/container/memory/utilizations",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "cloud_run_revision"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "run.googleapis.com/container/memory/utilizations",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MAX",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "cloud_run_revision"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "run.googleapis.com/container/memory/utilizations",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  }
 ]
}