{
 "title": "Datastore Monitoring",
 "tags": [
  "Storage",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Datastore Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 4 charts for the [Datastore metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-datastore), including `Index writes`, `Datastore requests`, `Sizes of read entities`, and `Sizes of written entities`."
   }
  },
  {
   "title": "Index writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "datastore_request"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "datastore.googleapis.com/index/write_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Datastore requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "datastore_request"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "datastore.googleapis.com/api/request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Sizes of read entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "datastore_request"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "datastore.googleapis.com/entity/read_sizes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Sizes of written entities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "datastore_request"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "datastore.googleapis.com/entity/write_sizes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  }
 ]
}