{
 "title": "GKE Cluster Monitoring",
 "tags": [
  "Compute",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "GKE Cluster Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 18 charts for the related [Kubernetes metrics](https://cloud.google.com/monitoring/api/metrics_kubernetes), including metrics for the worker nodes such as total allocatable CPU cores and memory; metrics for containers such as CPU and memory request utilization; metrics for Pods such as network bytes received and transmitted."
   }
  },
  {
   "title": "Node - Total, Request, Allocatable CPU cores",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/request_cores",
      "projectName": "$project",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_node"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/cpu/allocatable_cores",
      "projectName": "$project",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_node"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/cpu/total_cores",
      "projectName": "$project",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Node - Total memory, Memory usage, Allocatable memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_node"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/memory/total_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_node"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/memory/used_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_node"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/memory/allocatable_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Node - Bytes received [MEAN], Bytes received [MAX]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MEAN",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_node"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/node/network/received_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MAX",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_node"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/node/network/received_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Node - Bytes transmitted [MEAN], Bytes transmitted [MAX]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MEAN",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_node"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/node/network/sent_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MAX",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_node"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/node/network/sent_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Node - Total ephemeral storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_node"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/ephemeral_storage/total_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_node"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/ephemeral_storage/used_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_node"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/ephemeral_storage/allocatable_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Node - Total inodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_node"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/ephemeral_storage/inodes_total",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_node"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/ephemeral_storage/inodes_free",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Container - Total CPU Cores limit, Cores request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/limit_cores",
      "projectName": "$project",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/request_cores",
      "projectName": "$project",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Container - CPU cores limit utilization[95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/limit_utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/limit_utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/limit_utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Container - CPU request utilization [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/request_utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/request_utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/request_utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Container - Memory limit, Memory request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/limit_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/request_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Container - Memory limit utilization[90/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/limit_utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/limit_utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/limit_utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Container - Memory request utilization [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/request_utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/request_utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/request_utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Container - Restart count [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_container"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/container/restart_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Pod - Bytes received [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/pod/network/received_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/pod/network/received_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/pod/network/received_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Pod - Bytes transmitted [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/pod/network/sent_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/pod/network/sent_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/pod/network/sent_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Pod - Volume capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MIN",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/total_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MAX",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/total_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MEAN",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/total_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Pod - Volume usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MIN",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/used_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MAX",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/used_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MEAN",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/used_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Pod - Volume utilization [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/utilization",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  }
 ]
}