{
 "title": "GKE Cluster Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "stackdriver" },
   {
    "name": "project",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Node - Total, Request, Allocatable CPU cores",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/request_cores",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/cpu/allocatable_cores",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/cpu/total_cores",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Node - Total memory, Memory usage, Allocatable memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/memory/total_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/used_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/memory/allocatable_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Node - Bytes received [MEAN], Bytes received [MAX]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/node/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/node/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Node - Bytes transmitted [MEAN], Bytes transmitted [MAX]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/node/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/node/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Node - Total ephemeral storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/ephemeral_storage/total_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/ephemeral_storage/allocatable_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/ephemeral_storage/used_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Node - Total inodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/ephemeral_storage/inodes_total",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/node/ephemeral_storage/inodes_free",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/ephemeral_storage/used_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Container - Total CPU Cores limit, Cores request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/limit_cores",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/request_cores",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Container - CPU cores limit utilization[95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_95",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/limit_utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_05",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/request_cores",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_50",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/request_cores",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Container - CPU request utilization [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_95",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/request_utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_05",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/request_utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_50",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/request_utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Container - Memory limit, Memory request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/limit_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/request_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Container - Memory limit utilization[90/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_95",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/limit_utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_05",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/limit_utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_50",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/limit_utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Container - Memory request utilization [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_95",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/request_utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_05",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/request_utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_50",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/request_utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Container - Restart count [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/container/restart_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Pod - Bytes received [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_95",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/pod/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_50",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/pod/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_05",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/pod/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Pod - Bytes transmitted [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_95",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/pod/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_50",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/pod/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_05",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/pod/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Pod - Volume capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "REDUCE_MIN",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MIN",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/total_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_MAX",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/total_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_MEAN",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/total_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Pod - Volume capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "REDUCE_MIN",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MIN",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/used_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_MAX",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/used_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_MEAN",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/used_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Pod - Volume utilization [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_50",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_95",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "REDUCE_PERCENTILE_05",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/pod/volume/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}