{
 "title": "Host Monitoring using BindPlane",
 "tags": [
  "Bindplane",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Host Monitoring using BindPlane",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 10 charts to display the metrics ingested via [Bule Medora Bindplan](https://bluemedora.com/products/bindplane/bindplane-for-stackdriver/). The metrics include CPU utilization, Disk I/O, and network throughput etc."
   }
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/host/cpu/utilization",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "CPU Interrupts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/host/cpu/interrupts",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Disk Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/host/disk/operations",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/host/process/disk_io",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Usable Space Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/host/file_store/utilization",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Host Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/host/host/processes",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Host Thread Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/host/host/thread_count",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/host/network_interface/errors",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/host/network_interface/packets",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "generic_node"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "external.googleapis.com/bluemedora/generic_node/host/network_interface/throughput",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  }
 ]
}