{
 "title": "HTTP/S Load Balancer Monitoring",
 "tags": [
  "Networking",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP/S Load Balancer Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 9 charts for the related [HTTP/s load balancer metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-loadbalancing), including `Request Count`, `Total Latency`, `Request Bytes`, `Response Bytes`, `Frontend RTT`, `Backend Request Count`, `Backend Request Bytes`, and `Backend Response Bytes`."
   }
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Total Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/total_latencies",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Request Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/request_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Response Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/response_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Frontend RTT [95/50/5 PERCENTILE].",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/frontend_tcp_rtt",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/frontend_tcp_rtt",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/frontend_tcp_rtt",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Backend Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Backend Request Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Backend Response Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_response_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Backend Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_latencies",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_latencies",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_latencies",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  }
 ]
}