{
 "title": "Google Cloud HTTP(S) LB Backend Services",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "stackdriver" },
   {
    "name": "project",
    "query": {}
   },
   {
    "name": "backend",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Backend Request Count by Code Class",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.response_code_class}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [
       "metric.label.response_code_class"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "sloId": ""
     }
    }
   ]
  },
  {
   "title": "Backend Request Count by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.matched_url_path_rule}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [
       "resource.label.matched_url_path_rule"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Backend Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "P99",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "P95",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "P50",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Backend Latency by Path - P50",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.matched_url_path_rule}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [
       "resource.label.matched_url_path_rule"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Backend Latency by Path - P95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.matched_url_path_rule}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [
       "resource.label.matched_url_path_rule"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Backend Latency by Path - P99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.matched_url_path_rule}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [
       "resource.label.matched_url_path_rule"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "errors",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "$backend",
       "AND",
       "metric.label.response_code_class",
       "=",
       "500"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Error Count by Path and Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.matched_url_path_rule}} {{metric.label.response_code}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "$backend",
       "AND",
       "metric.label.response_code_class",
       "=",
       "500"
      ],
      "groupBys": [
       "resource.label.matched_url_path_rule",
       "metric.label.response_code"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Request Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "request bytes",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/request_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Response Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "response bytes",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/response_bytes_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Backend Request Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "backend request bytes",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Backend Response Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "backend response bytes",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_response_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}