{
 "title": "Memcache Monitoring",
 "tags": [
  "Storage",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Active connections by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "memcache_node"
      ],
      "groupBys": [ "resource.label.node_id" ],
      "metricKind": "GAUGE",
      "metricType": "memcache.googleapis.com/node/active_connections",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Memory usage by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "memcache_node"
      ],
      "groupBys": [ "resource.label.node_id" ],
      "metricKind": "GAUGE",
      "metricType": "memcache.googleapis.com/node/cache_memory",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "CPU usage time by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "memcache_node"
      ],
      "groupBys": [ "resource.label.node_id" ],
      "metricKind": "DELTA",
      "metricType": "memcache.googleapis.com/node/cpu/usage_time",
      "projectName": "$project",
      "unit": "s{CPU}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Eviction count by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "memcache_node"
      ],
      "groupBys": [ "resource.label.node_id" ],
      "metricKind": "DELTA",
      "metricType": "memcache.googleapis.com/node/eviction_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Hit ratio by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "memcache_node"
      ],
      "groupBys": [ "resource.label.node_id" ],
      "metricKind": "GAUGE",
      "metricType": "memcache.googleapis.com/node/hit_ratio",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Items by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "memcache_node"
      ],
      "groupBys": [ "resource.label.node_id" ],
      "metricKind": "GAUGE",
      "metricType": "memcache.googleapis.com/node/items",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Operation count by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "memcache_node"
      ],
      "groupBys": [ "resource.label.node_id" ],
      "metricKind": "DELTA",
      "metricType": "memcache.googleapis.com/node/operation_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Received bytes by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "memcache_node"
      ],
      "groupBys": [ "resource.label.node_id" ],
      "metricKind": "DELTA",
      "metricType": "memcache.googleapis.com/node/received_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Sent bytes by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "memcache_node"
      ],
      "groupBys": [ "resource.label.node_id" ],
      "metricKind": "DELTA",
      "metricType": "memcache.googleapis.com/node/sent_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Node - Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "memcache_node"
      ],
      "groupBys": [ "resource.label.node_id" ],
      "metricKind": "GAUGE",
      "metricType": "memcache.googleapis.com/node/uptime",
      "projectName": "$project",
      "unit": "s",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}