{
 "title": "Redis Ops Monitoring",
 "tags": [
  "Storage",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Redis Ops Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 10 charts for the operational metrics of [Memorystore for Redis](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-redis), including `Instance Uptime`, `Connected Clients`, `Blocked Clients`, `Calls`, `Time per Call`, and `Average TTL`, etc."
   }
  },
  {
   "title": "Redis Instance - Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "redis_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "redis.googleapis.com/server/uptime",
      "projectName": "$project",
      "unit": "s",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "redis_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "redis.googleapis.com/clients/connected",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Blocked Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "redis_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "redis.googleapis.com/clients/blocked",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_COUNT",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "redis_instance"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "redis.googleapis.com/commands/calls",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Total Time of Calls by cmd",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "redis_instance"
      ],
      "groupBys": [ "metric.label.cmd" ],
      "metricKind": "DELTA",
      "metricType": "redis.googleapis.com/commands/total_time",
      "projectName": "$project",
      "unit": "us",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Time per Call",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "redis_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "redis.googleapis.com/commands/usec_per_call",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "redis_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "redis.googleapis.com/keyspace/keys",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Expirable Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "redis_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "redis.googleapis.com/keyspace/keys_with_expiration",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Average TTL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "redis_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "redis.googleapis.com/keyspace/avg_ttl",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Persisting RDB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_COUNT",
      "perSeriesAligner": "ALIGN_COUNT_TRUE",
      "filters": [
       "resource.type",
       "=",
       "redis_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "redis.googleapis.com/persistence/rdb/bgsave_in_progress",
      "projectName": "$project",
      "unit": "1",
      "valueType": "BOOL"
     }
    }
   ]
  }
 ]
}