{
 "title": "Spanner Monitoring",
 "tags": [
  "Storage",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Count of queries by database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "spanner_instance"
      ],
      "groupBys": [ "metric.label.database" ],
      "metricKind": "DELTA",
      "metricType": "spanner.googleapis.com/query_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "API requests by method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "spanner_instance"
      ],
      "groupBys": [ "metric.label.method" ],
      "metricKind": "DELTA",
      "metricType": "spanner.googleapis.com/api/api_request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "API request rate by method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "spanner_instance"
      ],
      "groupBys": [ "metric.label.method" ],
      "metricKind": "GAUGE",
      "metricType": "spanner.googleapis.com/api/request_count",
      "projectName": "$project",
      "unit": "1/s",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "API Request latencies [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "spanner_instance"
      ],
      "groupBys": [ "metric.label.method" ],
      "metricKind": "DELTA",
      "metricType": "spanner.googleapis.com/api/request_latencies",
      "projectName": "$project",
      "unit": "s",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "spanner_instance"
      ],
      "groupBys": [ "metric.label.method" ],
      "metricKind": "DELTA",
      "metricType": "spanner.googleapis.com/api/request_latencies",
      "projectName": "$project",
      "unit": "s",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "spanner_instance"
      ],
      "groupBys": [ "metric.label.method" ],
      "metricKind": "DELTA",
      "metricType": "spanner.googleapis.com/api/request_latencies",
      "projectName": "$project",
      "unit": "s",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "API Bytes received by method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "spanner_instance"
      ],
      "groupBys": [ "metric.label.method" ],
      "metricKind": "DELTA",
      "metricType": "spanner.googleapis.com/api/received_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "API Bytes sent by method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "spanner_instance"
      ],
      "groupBys": [ "metric.label.method" ],
      "metricKind": "DELTA",
      "metricType": "spanner.googleapis.com/api/sent_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Cloud Spanner Instance - Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "spanner_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "spanner.googleapis.com/instance/node_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Cloud Spanner Instance - Sessions by label.database [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "spanner_instance"
      ],
      "groupBys": [ "metric.label.database" ],
      "metricKind": "GAUGE",
      "metricType": "spanner.googleapis.com/instance/session_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "CPU utilization by database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "spanner_instance"
      ],
      "groupBys": [ "metric.label.database" ],
      "metricKind": "GAUGE",
      "metricType": "spanner.googleapis.com/instance/cpu/utilization",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "CPU utilization by priority by database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "spanner_instance"
      ],
      "groupBys": [ "metric.label.database" ],
      "metricKind": "GAUGE",
      "metricType": "spanner.googleapis.com/instance/cpu/utilization_by_priority",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Storage limit by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "spanner_instance"
      ],
      "groupBys": [ "resource.label.instance_id" ],
      "metricKind": "GAUGE",
      "metricType": "spanner.googleapis.com/instance/storage/limit_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Storage used by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "spanner_instance"
      ],
      "groupBys": [ "resource.label.instance_id" ],
      "metricKind": "GAUGE",
      "metricType": "spanner.googleapis.com/instance/storage/used_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Storage utilization by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "spanner_instance"
      ],
      "groupBys": [ "resource.label.instance_id" ],
      "metricKind": "GAUGE",
      "metricType": "spanner.googleapis.com/instance/storage/utilization",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Backup storage used by database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "spanner_instance"
      ],
      "groupBys": [ "metric.label.database" ],
      "metricKind": "GAUGE",
      "metricType": "spanner.googleapis.com/instance/backup/used_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}