{
 "title": "TCP/SSL Load Balancer Monitoring",
 "tags": [
  "Networking",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "TCP/SSL Load Balancer Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 6 charts for the related [TCP/SSL load balancer metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-loadbalancing), including `Frontend RTT`, `Open connections`, `New connections opened`, `Closed connections`, `Ingress bytes`, and `Egress bytes`."
   }
  },
  {
   "title": "Frontend RTT [95/50/5 PERCENTILE]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "tcp_ssl_proxy_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/tcp_ssl_proxy/frontend_tcp_rtt",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "tcp_ssl_proxy_rule"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/tcp_ssl_proxy/frontend_tcp_rtt",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "tcp_ssl_proxy_rule"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/tcp_ssl_proxy/frontend_tcp_rtt",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Open connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "tcp_ssl_proxy_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "GAUGE",
      "metricType": "loadbalancing.googleapis.com/tcp_ssl_proxy/open_connections",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "New connections opened",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "tcp_ssl_proxy_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/tcp_ssl_proxy/new_connections",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Closed connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "tcp_ssl_proxy_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/tcp_ssl_proxy/closed_connections",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Ingress bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "tcp_ssl_proxy_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/tcp_ssl_proxy/ingress_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Egress bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "tcp_ssl_proxy_rule"
      ],
      "groupBys": [ "resource.label.url_map_name" ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/tcp_ssl_proxy/egress_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}