{
 "title": "UseCase(payment) Monitoring",
 "tags": [
  "Microservices",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Load Balancer Ingress - RTT latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule",
       "AND",
       "resource.label.load_balancer_name",
       "=",
       "afd16f301889611eaab8242010a80007"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/l3/external/rtt_latencies",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Load Balancer - Egress packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule",
       "AND",
       "resource.label.load_balancer_name",
       "=",
       "afd16f301889611eaab8242010a80007"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/l3/external/egress_packets_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Client Request Count from Loadgenerator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "loadgenerator"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/client/request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Client Roundtrip Latencies from Loadgenerator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "loadgenerator"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/client/roundtrip_latencies",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Server Request Count received by Frontend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "frontend"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/server/request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Server Response Latencies by Frontend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "frontend"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/server/response_latencies",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Server Response Bytes by Frontend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "frontend"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/server/response_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Client Request Count from Frontend to CheckoutService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "frontend",
       "AND",
       "metric.label.destination_service_name",
       "=",
       "checkoutservice"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/client/request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Server Request Count received by CheckoutService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "checkoutservice"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/server/request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Server Response Latencies by CheckoutService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "checkoutservice"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/server/response_latencies",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Server Response Bytes by CheckoutService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "checkoutservice"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/server/response_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Client Request Count from CheckoutService to PaymentService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_pod",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "checkoutservice",
       "AND",
       "metric.label.destination_service_name",
       "=",
       "paymentservice"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/client/request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Server Request Count received by PaymentService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "paymentservice"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/server/request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Server Response Latencies by PaymentService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "paymentservice"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/server/response_latencies",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Server Response Bytes by PaymentService",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "paymentservice"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/server/response_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "logging/user/AppErrors for demo, paymentservice",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "k8s_container",
       "AND",
       "resource.label.cluster_name",
       "=",
       "demo",
       "AND",
       "metadata.user_labels.app",
       "=",
       "paymentservice"
      ],
      "groupBys": [],
      "metricKind": "",
      "metricType": "logging.googleapis.com/user/AppErrors",
      "projectName": "$project",
      "unit": "",
      "valueType": ""
     }
    }
   ]
  }
 ]
}