{
 "title": "VPC Connector Access Monitoring",
 "tags": [
  "Networking",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "VPC Connector Access Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 4 charts for the related [VPC connector access metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-vpc%20access), including `Bytes received delta`, `Bytes sent delta`, `Packets received delta`, and `Packets sent delta`."
   }
  },
  {
   "title": "Bytes received delta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "vpc_access_connector"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpcaccess.googleapis.com/connector/received_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Bytes sent delta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "vpc_access_connector"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpcaccess.googleapis.com/connector/sent_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packets received delta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "vpc_access_connector"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpcaccess.googleapis.com/connector/received_packets_count",
      "projectName": "$project",
      "unit": "{packet}",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Packets sent delta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "vpc_access_connector"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "vpcaccess.googleapis.com/connector/sent_packets_count",
      "projectName": "$project",
      "unit": "{packet}",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}