{
 "title": "VPC Flow Logs Monitoring",
 "tags": [
  "Networking",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "VPC Flow Logs Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 6 charts for the related [VPC flow logs metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-networking), including `Ingested log volume`, `log counts`, estimated `VPC Flow logs` counts and volume."
   }
  },
  {
   "title": "Ingested log volume",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "options": {
    "content": "These charts represent the volume of logs ingested for VPC Flow logs. The chart below provides the total volume of logs ingested for reference."
   }
  },
  {
   "title": "Log counts",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "options": {
    "content": "These 2 charts represent the count of log entries for VPC Flow logs. The chart below provides the total count of log entries for reference."
   }
  },
  {
   "title": "Log bytes ingested for gce_subnetwork by label.resource_type [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "global",
       "AND",
       "metric.label.resource_type",
       "=",
       "gce_subnetwork"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "logging.googleapis.com/billing/bytes_ingested",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "gce_subnetwork log entries count [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "gce_subnetwork"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "logging.googleapis.com/log_entry_count",
      "perSeriesAligner": "ALIGN_SUM",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Log bytes ingested by label.resource_type [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "filters": [
       "resource.type",
       "=",
       "global"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "logging.googleapis.com/billing/bytes_ingested",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Log entries count [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "global"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "logging.googleapis.com/log_entry_count",
      "perSeriesAligner": "ALIGN_SUM",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "VPC Flow logs predicted count",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
   "options": {
    "content": "The metric predicted_max_vpc_flow_logs_count is used for the two charts below. They can be used to help estimate VPC Flow log counts and volume. For more details see the metric [vpc_flow/predicted_max_vpc_flow_logs_count ](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-networking)."
   }
  },
  {
   "title": "VPC Flow Logs Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "mqlQuery": {
      "aliasBy": "",
      "expression": "fetch gce_subnetwork\n| metric 'networking.googleapis.com/vpc_flow/predicted_max_vpc_flow_logs_count'\n| align mean_aligner(1w)\n| every 1w\n| group_by [],\n    [value_predicted_max_vpc_flow_logs_count_aggregate:\n       aggregate(value.predicted_max_vpc_flow_logs_count)]\n| value\n    [value_predicted_max_vpc_flow_logs_count_aggregate_mul:\n       mul(value_predicted_max_vpc_flow_logs_count_aggregate, 1080)]\n| value\n    [value_predicted_max_vpc_flow_logs_count_aggregate_mul_cast_units:\n       cast_units(value_predicted_max_vpc_flow_logs_count_aggregate_mul, 'By')]\n| value\n    [value_predicted_max_vpc_flow_logs_count_aggregate_mul_cast_units_mul:\n       mul(value_predicted_max_vpc_flow_logs_count_aggregate_mul_cast_units,\n         60 * 24 * 30)]\n| value\n    [value_predicted_max_vpc_flow_logs_count_aggregate_mul_cast_units_mul_mul:\n       mul(\n         value_predicted_max_vpc_flow_logs_count_aggregate_mul_cast_units_mul,\n         1.0)]",
      "projectName": "$project",
      "query": "fetch gce_subnetwork\n| metric 'networking.googleapis.com/vpc_flow/predicted_max_vpc_flow_logs_count'\n| align mean_aligner(1w)\n| every 1w\n| group_by [],\n    [value_predicted_max_vpc_flow_logs_count_aggregate:\n       aggregate(value.predicted_max_vpc_flow_logs_count)]\n| value\n    [value_predicted_max_vpc_flow_logs_count_aggregate_mul:\n       mul(value_predicted_max_vpc_flow_logs_count_aggregate, 1080)]\n| value\n    [value_predicted_max_vpc_flow_logs_count_aggregate_mul_cast_units:\n       cast_units(value_predicted_max_vpc_flow_logs_count_aggregate_mul, 'By')]\n| value\n    [value_predicted_max_vpc_flow_logs_count_aggregate_mul_cast_units_mul:\n       mul(value_predicted_max_vpc_flow_logs_count_aggregate_mul_cast_units,\n         60 * 24 * 30)]\n| value\n    [value_predicted_max_vpc_flow_logs_count_aggregate_mul_cast_units_mul_mul:\n       mul(\n         value_predicted_max_vpc_flow_logs_count_aggregate_mul_cast_units_mul,\n         1.0)]"
     }
    }
   ]
  },
  {
   "title": "Predicted Max VPC Flow Logs Count [SUM]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "gce_subnetwork"
      ],
      "groupBys": [ "resource.label.project_id" ],
      "metricKind": "DELTA",
      "metricType": "networking.googleapis.com/vpc_flow/predicted_max_vpc_flow_logs_count",
      "perSeriesAligner": "ALIGN_SUM",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}