{
 "title": "Windows Server Monitoring",
 "tags": [
  "Windows",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Windows Server Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 11 charts to display the Cloud Monitoring metrics for Windows servers. Please make sure the [Cloud Monitoring Windows agent](https://cloud.google.com/monitoring/agent/install-agent#agent-install-windows) is installed and configured. The metrics include VM resource usage, IIS, and SQL server status."
   }
  },
  {
   "title": "IIS connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "agent.googleapis.com/iis/new_connection_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "IIS open connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "agent.googleapis.com/iis/current_connections",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "IIS requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "agent.googleapis.com/iis/request_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "IIS transferred bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "agent.googleapis.com/iis/network/transferred_bytes_count",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "SQL Server open connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "agent.googleapis.com/mssql/connections/user",
      "projectName": "$project",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "SQL Server transaction rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "agent.googleapis.com/mssql/transaction_rate",
      "projectName": "$project",
      "unit": "1/s",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "SQL Server write transaction rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "agent.googleapis.com/mssql/write_transaction_rate",
      "projectName": "$project",
      "unit": "1/s",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Pagefile utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "agent.googleapis.com/pagefile/percent_used",
      "projectName": "$project",
      "unit": "%",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "VM Instance - CPU utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "agent.googleapis.com/cpu/utilization",
      "projectName": "$project",
      "unit": "%",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "VM Instance - Disk utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "agent.googleapis.com/disk/percent_used",
      "projectName": "$project",
      "unit": "%",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "VM Instance - Memory utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "gce_instance"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "agent.googleapis.com/memory/percent_used",
      "projectName": "$project",
      "unit": "%",
      "valueType": "DOUBLE"
     }
    }
   ]
  }
 ]
}