const CODEOWNERS_MANIFEST_DIR = 'codeowners-manifest';

module.exports = {
  CODEOWNERS_FILE_PATH: '.github/CODEOWNERS',
  CODEOWNERS_MANIFEST_DIR,
  RAW_AUDIT_JSONL_PATH: `${CODEOWNERS_MANIFEST_DIR}/audit-raw.jsonl`,
  TEAMS_JSON_PATH: `${CODEOWNERS_MANIFEST_DIR}/teams.json`,
  TEAMS_BY_FILENAME_JSON_PATH: `${CODEOWNERS_MANIFEST_DIR}/teams-by-filename.json`,
  FILENAMES_BY_TEAM_JSON_PATH: `${CODEOWNERS_MANIFEST_DIR}/filenames-by-team.json`,
  METADATA_JSON_PATH: `${CODEOWNERS_MANIFEST_DIR}/metadata.json`
};
