{
 "title": "Azure / Insights / Applications - Failures - 3. Exceptions",
 "description": "The dashboard provides insights of exceptions through Application Insights.",
 "tags": [ "Azure-AppInsights-Failures" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {}
   },
   { "name": "res", "label": "Resource", "query": "ResourceNames($sub, $rg, $ns)" },
   {
    "name": "exception_type",
    "label": "Exception Type",
    "query": {}
   },
   {
    "name": "exception",
    "label": "Exception",
    "query": {}
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Failures - Exceptions" } },
  {
   "title": "Application Insights - Failures - Exceptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Exceptions (count)",
   "type": "timeseries",
   "description": "The resource path for this panel uses multiple template variables which requires modifying the dashboard JSON directly. If you would like to do something similar please go to Settings > JSON Model. Edit as you'd like in your new copy by going to Settings > Save as.",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 3 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "\nexceptions\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where type in ($exception_type)\n| summarize FailedCount=sum(itemCount) by bin(timestamp, $__interval)\n| order by timestamp asc\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top 10 exception types (count)",
   "type": "table",
   "description": "The resource path for this panel uses multiple template variables which requires modifying the dashboard JSON directly. If you would like to do something similar please go to Settings > JSON Model. Edit as you'd like in your new copy by going to Settings > Save as.",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 3 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "\nexceptions\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| summarize Count=sum(itemCount) by type\n| top 10 by Count desc\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Server Requests (count)",
   "type": "timeseries",
   "description": "The resource path for this panel uses multiple template variables which requires modifying the dashboard JSON directly. If you would like to do something similar please go to Settings > JSON Model. Edit as you'd like in your new copy by going to Settings > Save as.",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 10 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "requests\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n// calculate average request duration for all requests\n| summarize Count = count() by bin(timestamp, $__interval)\n| order by timestamp asc\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "All Exceptions (Count)",
   "type": "stat",
   "description": "The resource path for this panel uses multiple template variables which requires modifying the dashboard JSON directly. If you would like to do something similar please go to Settings > JSON Model. Edit as you'd like in your new copy by going to Settings > Save as.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "exceptions\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| summarize failedCount=sum(itemCount)\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Number of exceptions matching exception type $exception_type and exception $exception",
   "type": "stat",
   "description": "The resource path for this panel uses multiple template variables which requires modifying the dashboard JSON directly. If you would like to do something similar please go to Settings > JSON Model. Edit as you'd like in your new copy by going to Settings > Save as.",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "exceptions\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| where problemId in ($exception)\n| where type in ($exception_type)\n| summarize failedCount=sum(itemCount)\n\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top Dependencies by Avg Duration",
   "type": "table",
   "description": "The resource path for this panel uses multiple template variables which requires modifying the dashboard JSON directly. If you would like to do something similar please go to Settings > JSON Model. Edit as you'd like in your new copy by going to Settings > Save as.",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let m = exceptions\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| where type in ($exception_type)\n| project itemCount, user_Id, problemId;\nm\n| summarize Count=sum(itemCount), impactedUsers=dcount(user_Id)\n| project Exception=\"All\", Count, impactedUsers\n| union(\nm\n| summarize Count=sum(itemCount), impactedUsers=dcount(user_Id) by problemId\n| sort by Count desc\n| project Exception=problemId, Count, impactedUsers)\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top 20 exceptions level matching $exception by Relevance",
   "type": "table",
   "description": "The resource path for this panel uses multiple template variables which requires modifying the dashboard JSON directly. If you would like to do something similar please go to Settings > JSON Model. Edit as you'd like in your new copy by going to Settings > Save as.",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 19 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let min_length_8 = (s: string) {\n    let len = strlen(s);\n    case(len == 1, strcat(s, s, s, s, s, s, s, s),\n        len == 2 or len == 3, strcat(s, s, s, s),\n        len == 4 or len == 5 or len == 6 or len == 7, strcat(s, s),\n        s)\n};\nlet ai_hash = (s: string) {\n    abs(toint(__hash_djb2(min_length_8(s))))\n};\n\nexceptions\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where type in ($exception_type)\n| where problemId in ($exception)\n| where isnotempty(operation_Id)\n| project Exception=problemId, OperationID=operation_Id, Score=ai_hash(operation_Id)\n| top 20 by Score asc\n\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}