{
 "title": "Azure / Infrastructure / Network Monitoring",
 "description": "This dashboard displays traffic-light indicators to show the health of your Azure infrastructure resources based on key performance indicators and thresholds defined for each infrastructure resource type.  The KPIs and thresholds come from Azure Monitor Baseline Alerts (https://azure.github.io/azure-monitor-baseline-alerts/).  \n\nPrerequisites:\nThe queries used in the dashboard require that you have resource metrics being sent to a Log Analytics Workspace. The AzureMetrics table is required.  This can be achieved through a resource’s diagnostic settings. For detailed instructions, refer to Azure Monitor Essentials: Diagnostic Settings:  https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/diagnostic-settings#metrics\n\nInstallation and Configuration:\nThis dashboard requires the JSON API Grafana plugin and a configured data source for Azure Monitor Baseline Alerts.  Follow these steps to install and configure the JSON API plugin:\n\n1.  Navigate to Connections->Connect Data.\n2.  Search for “JSON API” and then select the JSON API data source.\n3.  Install the plugin if it is not already installed.\n4.  On the JSON API plugin page, click “Create a JSON API data source\".\n5.  On the create JSON API page, give it the name “AMBA” and for the URL, give it the value:  https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/main/visualizations/grafana/infra-monitoring-amba-thresholds.json \n6.  Click the Save & test button. You should see a green checkbox and Success message if configured correctly.\n\nThis is one of a collection of dashboards linked together via dashboard links and the \"azure-infra-monitor\" tag.  Other dashboards in the collection include:\nAzure / Infrastructure / Apps Monitoring\nAzure / Infrastructure / Storage and Key Vaults Monitoring\nAzure / Infrastructure / Compute Monitoring\nAzure / Infrastructure / Data Monitoring\n\nThe other dashboards in this collection can be found in the Azure Monitor Team Grafana library here:  https://grafana.com/orgs/azuremonitorteam/dashboards.  Once imported, you will be able to access these dashboards using the Azure Infra Monitoring Dashboards tab. ",
 "tags": [ "azure-infra-monitor" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "amba", "label": "Azure Monitor Baseline Alerts", "query": "marcusolsson-json-datasource" },
   {
    "name": "subsWSScope",
    "label": "Workspace Scope",
    "query": {}
   },
   {
    "name": "laws",
    "label": "Workspaces",
    "query": {}
   },
   {
    "name": "subsRESScope",
    "label": "Resource Scope",
    "query": {}
   },
   {
    "name": "healthy_color",
    "query": "\"rgb(45\\,161\\,55)\""
   },
   {
    "name": "warning_color",
    "query": "\"rgb(222\\,210\\,38)\""
   },
   {
    "name": "unhealthy_color",
    "query": "\"rgb(255\\,31\\,46)\""
   },
   {
    "name": "amba_lb_DipAvailability",
    "query": {}
   },
   {
    "name": "amba_lb_VipAvailability",
    "query": {}
   },
   {
    "name": "amba_lb_UsedSNATPorts",
    "query": {}
   },
   {
    "name": "amba_tm_PACESByPR",
    "query": {}
   },
   {
    "name": "amba_tm_QpsByEndpoint",
    "query": {}
   },
   {
    "name": "amba_appgw_UnhealthyHostCount",
    "query": {}
   },
   {
    "name": "amba_appgw_FailedRequests",
    "query": {}
   },
   {
    "name": "amba_appgw_HealthyHostCount",
    "query": {}
   },
   {
    "name": "amba_fd_TotalLatency",
    "query": {}
   },
   {
    "name": "amba_fd_RequestCount",
    "query": {}
   },
   {
    "name": "amba_fd_OriginHealthPercentage",
    "query": {}
   },
   {
    "name": "amba_ip_IfUnderDDoSAttack",
    "query": {}
   },
   {
    "name": "amba_ip_PacketsInDDoS",
    "query": {}
   },
   {
    "name": "amba_ip_VipAvailability",
    "query": {}
   },
   {
    "name": "amba_fw_FirewallHealth",
    "query": {}
   },
   {
    "name": "amba_fw_SNATPortUtilization",
    "query": {}
   },
   {
    "name": "amba_vnet_IfUnderDDoSAttack",
    "query": {}
   },
   {
    "name": "amba_vnet_PacketsInDDoS",
    "query": {}
   },
   {
    "name": "amba_vnet_PacketsForwardedDDoS",
    "query": {}
   },
   {
    "name": "amba_vnetgw_TunnelAverageBandwidth",
    "query": {}
   },
   {
    "name": "amba_vnetgw_TunnelEgressBytes",
    "query": {}
   },
   {
    "name": "amba_vnetgw_TunnelIngressBytes",
    "query": {}
   },
   {
    "name": "amba_vnetgw_ExpressRouteGatewayCpuUtil",
    "query": {}
   },
   {
    "name": "amba_vnetgw_ExpressRouteGatewayBitsPerSec",
    "query": {}
   },
   {
    "name": "amba_vnetgw_ExpressRouteGatewayPacketsPerSec",
    "query": {}
   },
   {
    "name": "amba_exprcircuit_ArpAvailability",
    "query": {}
   },
   {
    "name": "amba_exprcircuit_BgpAvailability",
    "query": {}
   },
   {
    "name": "amba_exprcircuit_QosDropBitsInPerSecond",
    "query": {}
   },
   {
    "name": "amba_exprcircuit_QosDropBitsOutPerSecond",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"font-size:24px;color:rgb(87, 148, 242);\">Azure Infrastructure Monitoring Dashboard (Networking)</p>\r\n\r\nSelect a data source, workspace scope, workspace(s) and resource scope.   \r\nExamine the key performance indicators for your resources by expanding the row for a resource type.  \r\nRecommended KPIs and thresholds used in this dashboard come from [Azure Monitor Baseline Alerts](https://azure.github.io/azure-monitor-baseline-alerts/).  \r\nSee dashboard description for more details on linking to other Infrastructure Monitor dashboards.\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<br>\r\n\r\nKey:\r\n- Green\\Healthy &nbsp;- None of the resources of that resource type have KPIs that are exceeding thresholds.\r\n- Yellow\\Warning - At least one resource of that resource type has one KPI exceeding a threshold.\r\n- Red\\Unhealthy &nbsp;- At least one resource of that resource type has two or more KPIs exceeding a threshold."
   }
  },
  {
   "title": "Load Balancers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/loadbalancers/'\r\n| where SubscriptionId has_any ($subsRESScope)\r\n| where MetricName in('UsedSnatPorts', 'DipAvailability', 'VipAvailability')\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'UsedSnatPorts'),\r\n  kpi2 = avgif(Average, MetricName == 'DipAvailability'),\r\n  kpi3 = avgif(Average, MetricName == 'VipAvailability') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)  \r\n|extend health1 = iff(kpi1>$amba_lb_UsedSNATPorts, 1, 0)\r\n|extend health2 = iff(kpi2<$amba_lb_DipAvailability, 1, 0)\r\n|extend health3 = iff(kpi3<$amba_lb_VipAvailability, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2 + health3\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Application Gateways",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/applicationgateways/'\r\n| where SubscriptionId has_any ($subsRESScope)\r\n| where MetricName in('UnhealthyHostCount', 'FailedRequests', 'HealthyHostCount')\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'UnhealthyHostCount'),\r\n  kpi2 = sumif(Total, MetricName == 'FailedRequests'),\r\n  kpi3 = avgif(Average, MetricName == 'HealthyHostCount') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)  \r\n|extend health1 = iff(kpi1>=$amba_appgw_UnhealthyHostCount, 1, 0)\r\n|extend health2 = iff(kpi2>$amba_appgw_FailedRequests, 1, 0)\r\n|extend health3 = iff(kpi3<=$amba_appgw_HealthyHostCount, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2 + health3\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Public IPs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/publicipaddresses/'\r\n| where SubscriptionId has_any ($subsRESScope)\r\n| where MetricName in('VipAvailability', 'IfUnderDDoSAttack', 'PacketsInDDoS')\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'VipAvailability'),\r\n  kpi2 = avgif(Maximum, MetricName == 'IfUnderDDoSAttack'),\r\n  kpi3 = avgif(Total, MetricName == 'PacketsInDDoS') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2)\r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)\r\n|extend health1 = iff(kpi1<$amba_ip_VipAvailability, 1, 0)\r\n|extend health2 = iff(kpi2>$amba_ip_IfUnderDDoSAttack, 1, 0)\r\n|extend health3 = iff(kpi3>$amba_ip_PacketsInDDoS, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2 + health3\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Virtual Networks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/virtualnetworks/'\r\n| where SubscriptionId has_any ($subsRESScope)\r\n| where MetricName in('IfUnderDDoSAttack', 'PacketsInDDoS', 'PacketsForwardedDDoS')\r\n| summarize\r\n  kpi1 = avgif(Maximum, MetricName == 'IfUnderDDoSAttack'),\r\n  kpi2 = avgif(Maximum, MetricName == 'PacketsInDDoS'),\r\n  kpi3 = avgif(Maximum, MetricName == 'PacketsForwardedDDoS') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)\r\n|extend health1 = iff(kpi1>$amba_vnet_IfUnderDDoSAttack, 1, 0)\r\n|extend health2 = iff(kpi2>$amba_vnet_PacketsInDDoS, 1, 0)\r\n|extend health3 = iff(kpi3>$amba_vnet_PacketsForwardedDDoS, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2 + health3\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "ExpressRoute Circuits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/expressroutecircuits/'\r\n| where SubscriptionId has_any ($subsRESScope)\r\n| where MetricName in('BgpAvailability', 'ArpAvailability', 'QosDropBitsInPerSecond', 'QosDropBitsOutPerSecond' )\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'BgpAvailability'),\r\n  kpi2 = avgif(Average, MetricName == 'ArpAvailability'),\r\n  kpi3 = avgif(Average, MetricName == 'QosDropBitsInPerSecond'),\r\n  kpi4 = avgif(Total, MetricName == 'QosDropBitsOutPerSecond') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3) \r\n|extend kpi4 = iff(isnan(kpi4), 0.0, kpi4)\r\n|extend health1 = iff(kpi1<$amba_exprcircuit_BgpAvailability, 1, 0)\r\n|extend health2 = iff(kpi2<$amba_exprcircuit_ArpAvailability, 1, 0)\r\n|extend health3 = iff(kpi3>$amba_exprcircuit_QosDropBitsInPerSecond, 1, 0)\r\n|extend health4 = iff(kpi4>$amba_exprcircuit_QosDropBitsOutPerSecond, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\r\n|extend h4color = iff(tobool(health4), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2 + health3 + health4\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc\r\n",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Traffic Managers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/trafficmanagerprofiles/'\r\n| where SubscriptionId has_any ($subsRESScope)\r\n| where MetricName in('ProbeAgentCurrentEndpointStateByProfileResourceId', 'QpsByEndpoint')\r\n| summarize\r\n  kpi1 = avgif(Maximum, MetricName == 'ProbeAgentCurrentEndpointStateByProfileResourceId'),\r\n  kpi2 = avgif(Total, MetricName == 'QpsByEndpoint') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend health1 = iff(kpi1<=$amba_tm_PACESByPR, 1, 0)\r\n|extend health2 = iff(kpi2<=$amba_tm_QpsByEndpoint, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Front Doors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.cdn/profiles/'\r\n| where SubscriptionId has_any ($subsRESScope)\r\n| where MetricName in('TotalLatency', 'RequestCount', 'OriginHealthPercentage')\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'TotalLatency'),\r\n  kpi2 = avgif(Average, MetricName == 'RequestCount'),\r\n  kpi3 = avgif(Average, MetricName == 'OriginHealthPercentage')*100 by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)\r\n|extend health1 = iff(kpi1>$amba_fd_TotalLatency, 1, 0)\r\n|extend health2 = iff(kpi2<$amba_fd_RequestCount, 1, 0)\r\n|extend health3 = iff(kpi3<$amba_fd_OriginHealthPercentage, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2 + health3\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Firewalls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/azurefirewalls/'\r\n| where SubscriptionId has_any ($subsRESScope)\r\n| where MetricName in('FirewallHealth', 'SNATPortUtilization') \r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'FirewallHealth'),\r\n  kpi2 = avgif(Average, MetricName == 'SNATPortUtilization') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2)\r\n|extend health1 = iff(kpi1<$amba_fw_FirewallHealth, 1, 0)\r\n|extend health2 = iff(kpi2>$amba_fw_SNATPortUtilization, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "VPN Gateways",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/virtualnetworkgateways/'\r\n| where SubscriptionId has_any ($subsRESScope)\r\n| where MetricName in('TunnelAverageBandwidth', 'TunnelEgressBytes', 'TunnelIngressBytes' )\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'TunnelAverageBandwidth'),\r\n  kpi2 = avgif(Average, MetricName == 'TunnelEgressBytes'),\r\n  kpi3 = avgif(Total, MetricName == 'TunnelIngressBytes') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)\r\n|extend health1 = iff(kpi1<$amba_vnetgw_TunnelAverageBandwidth, 1, 0)\r\n|extend health2 = iff(kpi2<=$amba_vnetgw_TunnelEgressBytes, 1, 0)\r\n|extend health3 = iff(kpi3<=$amba_vnetgw_TunnelIngressBytes, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2 + health3\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "ExpressRoute Gateways",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/virtualnetworkgateways/'\r\n| where SubscriptionId has_any ($subsRESScope)\r\n| where MetricName in('ExpressRouteGatewayCpuUtilization', 'ExpressRouteGatewayBitsPerSecond', 'ExpressRouteGatewayPacketsPerSecond' )\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'ExpressRouteGatewayCpuUtilization'),\r\n  kpi2 = avgif(Average, MetricName == 'ExpressRouteGatewayBitsPerSecond'),\r\n  kpi3 = avgif(Total, MetricName == 'ExpressRouteGatewayPacketsPerSecond') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)\r\n|extend health1 = iff(kpi1>$amba_vnetgw_ExpressRouteGatewayCpuUtil, 1, 0)\r\n|extend health2 = iff(kpi2<=$amba_vnetgw_ExpressRouteGatewayBitsPerSec, 1, 0)\r\n|extend health3 = iff(kpi3<=$amba_vnetgw_ExpressRouteGatewayPacketsPerSec, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2 + health3\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Load Balancers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Balancer Used SNAT Ports",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 36 }
     ]
    },
    {
     "title": "Load Balancer Health Probe Status",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 36 }
     ]
    },
    {
     "title": "Load Balancer Data Path Availability",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 36 }
     ]
    }
   ]
  },
  {
   "title": "Traffic Managers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic Manager Endpoint Status by Endpoint",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 46 }
     ]
    },
    {
     "title": "Traffic Manager Queries by Endpoint Returned",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 46 }
     ]
    }
   ]
  },
  {
   "title": "Application Gateways",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Gateway Unhealthy Host Count",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 41 }
     ]
    },
    {
     "title": "Application Gateway Failed Requests",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 41 }
     ]
    },
    {
     "title": "Application Gateway Healthy Host Count",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 41 }
     ]
    }
   ]
  },
  {
   "title": "Front Doors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front Door Total Latency",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 53 }
     ]
    },
    {
     "title": "Front Door Request Count",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 53 }
     ]
    },
    {
     "title": "Front Door Origin Health Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 53 }
     ]
    }
   ]
  },
  {
   "title": "Public IPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Public IP Availability",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 50 }
     ]
    },
    {
     "title": "Public IP Under DDoS Attack",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 50 }
     ]
    },
    {
     "title": "Public IP Inbound Packets DDoS",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 50 }
     ]
    }
   ]
  },
  {
   "title": "Firewalls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Firewall Health",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 59 }
     ]
    },
    {
     "title": "Firewall SNAT Port Utilization",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 59 }
     ]
    }
   ]
  },
  {
   "title": "Virtual Networks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Network Under DDoS Attack",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 54 }
     ]
    },
    {
     "title": "Virtual Network Inbound Packets DDoS",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 54 }
     ]
    },
    {
     "title": "Virtual Network Packets Forwarded DDoS",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 54 }
     ]
    }
   ]
  },
  {
   "title": "VPN Gateways",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "VPN Gateway Tunnel Bandwidth",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 57 }
     ]
    },
    {
     "title": "VPN Gateway Tunnel Egress Bytes",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 57 }
     ]
    },
    {
     "title": "VPN Gateway Tunnel Ingress Bytes",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 57 }
     ]
    }
   ]
  },
  {
   "title": "ExpressRoute Circuits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Express Route Circuit BGP Availability",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 68 }
     ]
    },
    {
     "title": "Express Route Circuit ARP Availability",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 68 }
     ]
    },
    {
     "title": "Express Route QoS Drop Bits In Per Second",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 68 }
     ]
    },
    {
     "title": "Express Route QoS Drop Bits Out Per Second",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 68 }
     ]
    }
   ]
  },
  {
   "title": "ExpressRoute Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Express Route Gateway CPU Utilization",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "Express Route Gateway Bits Per Second",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "Express Route Gateway Packets Per Second",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 66 }
     ]
    }
   ]
  }
 ]
}