{
 "title": "Azure / Infrastructure / Data Monitoring",
 "description": "This dashboard displays traffic-light indicators to show the health of your Azure infrastructure resources based on key performance indicators and thresholds defined for each infrastructure resource type.  The KPIs and thresholds come from Azure Monitor Baseline Alerts (https://azure.github.io/azure-monitor-baseline-alerts/).  \n\nPrerequisites:\nThe queries used in the dashboard require that you have resource metrics being sent to a Log Analytics Workspace. The AzureMetrics and AzureDiagnostics tables are required.  This can be achieved through a resource’s diagnostic settings. For detailed instructions, refer to Azure Monitor Essentials: Diagnostic Settings:  https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/diagnostic-settings#metrics\n\nInstallation and Configuration:\nThis dashboard requires the JSON API Grafana plugin and a configured data source for Azure Monitor Baseline Alerts.  Follow these steps to install and configure the JSON API plugin:\n\n1.  Navigate to Connections->Connect Data.\n2.  Search for “JSON API” and then select the JSON API data source.\n3.  Install the plugin if it is not already installed.\n4.  On the JSON API plugin page, click “Create a JSON API data source\".\n5.  On the create JSON API page, give it the name “AMBA” and for the URL, give it the value:  https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/main/visualizations/grafana/infra-monitoring-amba-thresholds.json \n6.  Click the Save & test button. You should see a green checkbox and Success message if configured correctly.\n\nThis is one of a collection of dashboards linked together via dashboard links and the \"azure-infra-monitor\" tag.  Other dashboards in the collection include:\nAzure / Infrastructure / Network Monitoring\nAzure / Infrastructure / Storage and Key Vaults Monitoring\nAzure / Infrastructure / Compute Monitoring\nAzure / Infrastructure / Apps Monitoring\n\nThe other dashboards in this collection can be found in the Azure Monitor Team Grafana library here:  https://grafana.com/orgs/azuremonitorteam/dashboards.  Once imported, you will be able to access these dashboards using the Azure Infra Monitoring Dashboards tab. ",
 "tags": [ "azure-infra-monitor" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "amba", "label": "Azure Monitor Baseline Alerts", "query": "marcusolsson-json-datasource" },
   {
    "name": "subsWSScope",
    "label": "Workspace Scope",
    "query": {}
   },
   {
    "name": "laws",
    "label": "Workspaces",
    "query": {}
   },
   {
    "name": "subsRESScope",
    "label": "Resource Scope",
    "query": {}
   },
   {
    "name": "healthy_color",
    "query": "\"rgb(45\\,161\\,55)\""
   },
   {
    "name": "warning_color",
    "query": "\"rgb(222\\,210\\,38)\""
   },
   {
    "name": "unhealthy_color",
    "query": "\"rgb(255\\,31\\,46)\""
   },
   {
    "name": "amba_eventhub_UserErrors",
    "query": {}
   },
   {
    "name": "amba_eventhub_ServerErrors",
    "query": {}
   },
   {
    "name": "amba_eventhub_ThrottledRequests",
    "query": {}
   },
   {
    "name": "amba_cosmosDB_ServerSideLatency",
    "query": {}
   },
   {
    "name": "amba_cosmosDB_ReplicationLatency",
    "query": {}
   },
   {
    "name": "amba_cosmosDB_ServiceAvailability",
    "query": {}
   },
   {
    "name": "amba_cosmosDB_OfflineRegion",
    "query": {}
   },
   {
    "name": "amba_SQL_cpu_percent",
    "query": {}
   },
   {
    "name": "amba_SQL_sqlserver_process_memory_percent",
    "query": {}
   },
   {
    "name": "amba_SQL_storage_percent",
    "query": {}
   },
   {
    "name": "amba_SQL_physical_data_read_percent",
    "query": {}
   },
   {
    "name": "amba_MySQL_cpu_percent",
    "query": {}
   },
   {
    "name": "amba_MySQL_memory_percent",
    "query": {}
   },
   {
    "name": "amba_MySQL_storage_percent",
    "query": {}
   },
   {
    "name": "amba_MySQL_replication_lag",
    "query": {}
   },
   {
    "name": "amba_PostgreSQL_cpu_percent",
    "query": {}
   },
   {
    "name": "amba_PostgreSQL_memory_percent",
    "query": {}
   },
   {
    "name": "amba_PostgreSQL_storage_percent",
    "query": {}
   },
   {
    "name": "amba_PostgreSQL_is_db_alive",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"font-size:24px;color:rgb(87, 148, 242);\">Azure Infrastructure Monitoring Dashboard (Data)</p>\r\n\r\nSelect a data source, workspace scope, workspace(s) and resource scope.   \r\nExamine the key performance indicators for your resources by expanding the row for a resource type.  \r\nRecommended KPIs and thresholds used in this dashboard come from [Azure Monitor Baseline Alerts](https://azure.github.io/azure-monitor-baseline-alerts/).  \r\nSee dashboard description for more details on linking to other Infrastructure Monitor dashboards.\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<br>\r\n\r\nKey:\r\n- Green\\Healthy &nbsp;- None of the resources of that resource type have KPIs that are exceeding thresholds.\r\n- Yellow\\Warning - At least one resource of that resource type has one KPI exceeding a threshold.\r\n- Red\\Unhealthy &nbsp;- At least one resource of that resource type has two or more KPIs exceeding a threshold."
   }
  },
  {
   "title": "CosmosDB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.documentdb/databaseaccounts/'\r\n| where SubscriptionId has_any ($subsRESScope)\r\n| where MetricName in('ServerSideLatency', 'ReplicationLatency', 'ServiceAvailability', 'OfflineRegion' )\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'ServerSideLatency'),\r\n  kpi2 = avgif(Average, MetricName == 'ReplicationLatency'),\r\n  kpi3 = avgif(Average, MetricName == 'ServiceAvailability'),\r\n  kpi4 = avgif(Count, MetricName == 'OfflineRegion') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3) \r\n|extend kpi4 = iff(isnan(kpi4), 0.0, kpi4)\r\n|extend health1 = iff(kpi1>$amba_cosmosDB_ServerSideLatency, 1, 0)\r\n|extend health2 = iff(kpi2>$amba_cosmosDB_ReplicationLatency, 1, 0)\r\n|extend health3 = iff(kpi3<$amba_cosmosDB_ServiceAvailability, 1, 0)\r\n|extend health4 = iff(kpi4>$amba_cosmosDB_OfflineRegion, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\r\n|extend h4color = iff(tobool(health4), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2 + health3 + health4\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "SQL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.sql/servers/'\r\n| where SubscriptionId has_any ($subsRESScope)\r\n| where MetricName in('cpu_percent', 'sqlserver_process_memory_percent', 'storage_percent', 'physical_data_read_percent' )\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'cpu_percent'),\r\n  kpi2 = avgif(Average, MetricName == 'sqlserver_process_memory_percent'),\r\n  kpi3 = avgif(Average, MetricName == 'storage_percent'),\r\n  kpi4 = avgif(Average, MetricName == 'physical_data_read_percent') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3) \r\n|extend kpi4 = iff(isnan(kpi4), 0.0, kpi4)\r\n|extend health1 = iff(kpi1>$amba_SQL_cpu_percent, 1, 0)\r\n|extend health2 = iff(kpi2>$amba_SQL_sqlserver_process_memory_percent, 1, 0)\r\n|extend health3 = iff(kpi3>$amba_SQL_storage_percent, 1, 0)\r\n|extend health4 = iff(kpi4>$amba_SQL_physical_data_read_percent, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\r\n|extend h4color = iff(tobool(health4), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2 + health3 + health4\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.dbformysql/flexibleservers/'\r\n| where SubscriptionId has_any ($subsRESScope)\r\n| where MetricName in('cpu_percent', 'memory_percent', 'storage_percent', 'replication_lag' )\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'cpu_percent'),\r\n  kpi2 = avgif(Average, MetricName == 'memory_percent'),\r\n  kpi3 = avgif(Average, MetricName == 'storage_percent'),\r\n  kpi4 = avgif(Maximum, MetricName == 'replication_lag') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3) \r\n|extend kpi4 = iff(isnan(kpi4), 0.0, kpi4)\r\n|extend health1 = iff(kpi1>$amba_MySQL_cpu_percent, 1, 0)\r\n|extend health2 = iff(kpi2>$amba_MySQL_memory_percent, 1, 0)\r\n|extend health3 = iff(kpi3>$amba_MySQL_storage_percent, 1, 0)\r\n|extend health4 = iff(kpi4>$amba_MySQL_replication_lag, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\r\n|extend h4color = iff(tobool(health4), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2 + health3 + health4\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.dbforpostgresql/flexibleservers/'\r\n| where SubscriptionId has_any ($subsRESScope)\r\n| where MetricName in('cpu_percent', 'memory_percent', 'storage_percent', 'is_db_alive' )\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'cpu_percent'),\r\n  kpi2 = avgif(Average, MetricName == 'memory_percent'),\r\n  kpi3 = avgif(Average, MetricName == 'storage_percent'),\r\n  kpi4 = avgif(Maximum, MetricName == 'is_db_alive') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3) \r\n|extend kpi4 = iff(isnan(kpi4), 0.0, kpi4)\r\n|extend health1 = iff(kpi1>$amba_PostgreSQL_cpu_percent, 1, 0)\r\n|extend health2 = iff(kpi2>$amba_PostgreSQL_memory_percent, 1, 0)\r\n|extend health3 = iff(kpi3>$amba_PostgreSQL_storage_percent, 1, 0)\r\n|extend health4 = iff(kpi4<$amba_PostgreSQL_is_db_alive, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\r\n|extend h4color = iff(tobool(health4), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2 + health3 + health4\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Event Hubs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureDiagnostics\r\n| where _ResourceId has '/microsoft.eventhub/namespaces/'\r\n| where SubscriptionId has_any ($subsRESScope)\r\n| where Category == \"DiagnosticErrorLogs\"\r\n| summarize\r\n  kpi1 = countif(OperationResult_s =~ \"ClientError\"), \r\n  kpi2 = countif(OperationResult_s =~ \"ServerBusy\"),\r\n  kpi3 = countif(OperationResult_s =~ \"QuotaExceeded\") by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(toreal(kpi1)), 0.0, toreal(kpi1))\r\n|extend kpi2 = iff(isnan(toreal(kpi2)), 0.0, toreal(kpi2)) \r\n|extend kpi3 = iff(isnan(toreal(kpi3)), 0.0, toreal(kpi3))\r\n|extend health1 = iff(kpi1>$amba_eventhub_UserErrors, 1, 0)\r\n|extend health2 = iff(kpi2>$amba_eventhub_ServerErrors, 1, 0)\r\n|extend health3 = iff(kpi3>$amba_eventhub_ThrottledRequests, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2 + health3\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CosmosDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CosmosDB Server Side Latency",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 107 }
     ]
    },
    {
     "title": "CosmosDB Replication Latency",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 107 }
     ]
    },
    {
     "title": "CosmosDB Service Availability",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 107 }
     ]
    },
    {
     "title": "CosmosDB Offline Regions",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 107 }
     ]
    }
   ]
  },
  {
   "title": "SQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL CPU Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 104 }
     ]
    },
    {
     "title": "SQL Memory Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 104 }
     ]
    },
    {
     "title": "SQL Storage Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 104 }
     ]
    },
    {
     "title": "SQL Physical Data Read Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 104 }
     ]
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL CPU Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 105 }
     ]
    },
    {
     "title": "MySQL Memory Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 105 }
     ]
    },
    {
     "title": "MySQL Storage Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 105 }
     ]
    },
    {
     "title": "MySQL Replication Lag",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 105 }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgreSQL CPU Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 106 }
     ]
    },
    {
     "title": "PostgreSQL Memory Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 106 }
     ]
    },
    {
     "title": "PostgreSQL Storage Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 106 }
     ]
    },
    {
     "title": "PostgreSQL Is DB Alive",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 106 }
     ]
    }
   ]
  },
  {
   "title": "Event Hubs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event Hub User Errors",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 98 }
     ]
    },
    {
     "title": "Event Hub Server Errors",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 98 }
     ]
    },
    {
     "title": "Event Hub Quota Exceeded Errors",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 98 }
     ]
    }
   ]
  }
 ]
}