{
 "title": "Azure / Infrastructure / Infrastructure Monitoring",
 "description": "This dashboard displays traffic-light indicators to show the health of your Azure infrastructure resources based on key performance indicators and thresholds defined for each infrastructure resource type.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"font-size:30px;color:rgb(87, 148, 242);\">Azure Infrastructure - Monitoring Dashboard</p>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 0 },
   "options": {
    "content": "#### Welcome to the Azure Infrastructure Monitoring Dashboard!    Select a data source and subscription to see the current status of your infrastructure resources.  Examine the key performance indicators for your resources by expanding the row for a resource type."
   }
  },
  {
   "title": "Virtual Machines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let insight_table = InsightsMetrics\r\n| where _ResourceId has '/microsoft.compute/virtualmachines/'\r\n| where Origin == \"vm.azm.ms\"\r\n| where Namespace == \"Processor\" and Name == \"UtilizationPercentage\"\r\n| extend Resource = toupper(tostring(split(_ResourceId,'/')[8]));\r\nAzureMetrics\r\n| where _ResourceId has '/microsoft.compute/virtualmachines/'\r\n| where MetricName in('Percentage CPU', 'Available Memory Bytes', 'VmAvailabilityMetric')\r\n| union kind=outer insight_table\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'Percentage CPU'),\r\n  kpi2 = percentile(Val, 95),\r\n  kpi3 = avgif(Average/1000000000, MetricName == 'Available Memory Bytes'),\r\n  kpi4 = avgif(Average*100, MetricName == 'VmAvailabilityMetric') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3) \r\n|extend kpi4 = iff(isnan(kpi4), 0.0, kpi4) \r\n|extend health1 = iff(kpi1>80, 1, 0)\r\n|extend health2 = iff(kpi2>85, 1, 0)\r\n|extend health3 = iff(kpi3<1, 1, 0)\r\n|extend health4 = iff(kpi4<90, 1, 0)\r\n|extend health = health1 + health2 + health3 + health4",
      "resources": [ "/subscriptions/$sub" ]
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let stroage_table = StorageBlobLogs \r\n    | where StatusText != 'Success'\r\n    | extend ErrorCounter = 1\r\n    | extend ResourceName = AccountName\r\n    | extend _ResourceId = trim('/blobservices/default', _ResourceId)\r\n    | extend _ResourceId = trim('/queueservices/default', _ResourceId)\r\n    | extend _ResourceId = trim('/tableservices/default', _ResourceId)\r\n    | extend _ResourceId = trim('/fileservices/default', _ResourceId)\r\n    | project TimeGenerated, ResourceName, StatusText, ErrorCounter, _ResourceId;\r\nAzureMetrics\r\n| where _ResourceId has '/microsoft.storage/'\r\n| where MetricName in('SuccessE2ELatency', 'UsedCapacity', 'Availability')\r\n| extend ResourceName = tostring(split(_ResourceId,'/')[8])\r\n| extend _ResourceId = trim('/blobservices/default', _ResourceId)\r\n| extend _ResourceId = trim('/queueservices/default', _ResourceId)\r\n| extend _ResourceId = trim('/tableservices/default', _ResourceId)\r\n| extend _ResourceId = trim('/fileservices/default', _ResourceId)\r\n| project ResourceName, _ResourceId, MetricName, Average, Total\r\n| union kind=outer stroage_table\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'SuccessE2ELatency'),\r\n  kpi2 = sumif(ErrorCounter, isnotnull(ErrorCounter)),\r\n  kpi3 = avgif(Average, MetricName == 'UsedCapacity'),\r\n  kpi4 = avgif(Average, MetricName == 'Availability') by _ResourceId, ResourceName\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(toreal(kpi2)), 0.0, toreal(kpi2)) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3) \r\n|extend kpi4 = iff(isnan(kpi4), 0.0, kpi4) \r\n|extend health1 = iff(kpi1>5000, 1, 0)\r\n|extend health2 = iff(kpi2>500, 1, 0)\r\n|extend health3 = iff(kpi3>4000000000000000, 1, 0)\r\n|extend health4 = iff(kpi4<90, 1, 0)\r\n|extend health = health1 + health2 + health3 + health4",
      "resources": [ "/subscriptions/$sub" ]
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Load Balancers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/loadbalancers/'\r\n| where MetricName in('UsedSnatPorts', 'DipAvailability', 'VipAvailability')\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'UsedSnatPorts'),\r\n  kpi2 = avgif(Average, MetricName == 'DipAvailability'),\r\n  kpi3 = avgif(Average, MetricName == 'VipAvailability') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)  \r\n|extend health1 = iff(kpi1>900, 1, 0)\r\n|extend health2 = iff(kpi2<=50, 1, 0)\r\n|extend health3 = iff(kpi3<50, 1, 0)\r\n|extend health = health1 + health2 + health3",
      "resources": [ "/subscriptions/$sub" ]
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Application Gateways",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/applicationgateways/'\r\n| where MetricName in('UnhealthyHostCount', 'FailedRequests', 'HealthyHostCount')\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'UnhealthyHostCount'),\r\n  kpi2 = sumif(Total, MetricName == 'FailedRequests'),\r\n  kpi3 = avgif(Average, MetricName == 'HealthyHostCount') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)  \r\n|extend health1 = iff(kpi1>=1, 1, 0)\r\n|extend health2 = iff(kpi2>10, 1, 0)\r\n|extend health3 = iff(kpi3<=0, 1, 0)\r\n|extend health = health1 + health2 + health3",
      "resources": [ "/subscriptions/$sub" ]
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Public IPs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/publicipaddresses/'\r\n| where MetricName in('VipAvailability', 'IfUnderDDoSAttack', 'PacketsInDDoS')\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'VipAvailability'),\r\n  kpi2 = avgif(Maximum, MetricName == 'IfUnderDDoSAttack'),\r\n  kpi3 = avgif(Total, MetricName == 'PacketsInDDoS') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2)\r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)\r\n|extend health1 = iff(kpi1<100, 1, 0)\r\n|extend health2 = iff(kpi2>0, 1, 0)\r\n|extend health3 = iff(kpi3>=1000, 1, 0)\r\n|extend health = health1 + health2 + health3",
      "resources": [ "/subscriptions/$sub" ]
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Virtual Networks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/virtualnetworks/'\r\n| where MetricName in('IfUnderDDoSAttack', 'PacketsInDDoS', 'PacketsForwardedDDoS')\r\n| summarize\r\n  kpi1 = avgif(Maximum, MetricName == 'IfUnderDDoSAttack'),\r\n  kpi2 = avgif(Maximum, MetricName == 'PacketsInDDoS'),\r\n  kpi3 = avgif(Maximum, MetricName == 'PacketsForwardedDDoS') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)\r\n|extend health1 = iff(kpi1>0, 1, 0)\r\n|extend health2 = iff(kpi2>=1000, 1, 0)\r\n|extend health3 = iff(kpi3>1, 1, 0)\r\n|extend health = health1 + health2 + health3",
      "resources": [ "/subscriptions/$sub" ]
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "ExpressRoute Circuits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/expressroutecircuits/'\r\n| where MetricName in('BgpAvailability', 'ArpAvailability', 'QosDropBitsInPerSecond', 'QosDropBitsOutPerSecond' )\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'BgpAvailability'),\r\n  kpi2 = avgif(Average, MetricName == 'ArpAvailability'),\r\n  kpi3 = avgif(Average, MetricName == 'QosDropBitsInPerSecond'),\r\n  kpi4 = avgif(Total, MetricName == 'QosDropBitsOutPerSecond') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3) \r\n|extend kpi4 = iff(isnan(kpi4), 0.0, kpi4)\r\n|extend health1 = iff(kpi1<90, 1, 0)\r\n|extend health2 = iff(kpi1<90, 1, 0)\r\n|extend health3 = iff(kpi2>100, 1, 0)\r\n|extend health4 = iff(kpi3>100, 1, 0)\r\n|extend health = health1 + health2 + health3 + health4\r\n",
      "resources": [ "/subscriptions/$sub" ]
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Virtual Machine Scale Sets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.compute/virtualmachinescalesets/'\r\n| where MetricName in('Percentage CPU', 'OS Disk IOPS Consumed Percentage','Available Memory Bytes', 'VmAvailabilityMetric')\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'Percentage CPU'),\r\n  kpi2 = avgif(Average, MetricName == 'OS Disk IOPS Consumed Percentage'),\r\n  kpi3 = avgif(Average/1000000000, MetricName == 'Available Memory Bytes'),\r\n  kpi4 = avgif(Average*100, MetricName == 'VmAvailabilityMetric') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3) \r\n|extend kpi4 = iff(isnan(kpi4), 0.0, kpi4)\r\n|extend health1 = iff(kpi1>80, 1, 0)\r\n|extend health2 = iff(kpi2>95, 1, 0)\r\n|extend health3 = iff(kpi3<1, 1, 0)\r\n|extend health4 = iff(kpi4<90, 1, 0)\r\n|extend health = health1 + health2 + health3 + health4",
      "resources": [ "/subscriptions/$sub" ]
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Key Vaults",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let diagnostic_table = AzureDiagnostics \r\n    | where _ResourceId has '/microsoft.keyvault/vaults/'\r\n    | where ResultSignature !='OK'\r\n    | extend ErrorCounter = 1\r\n    | project TimeGenerated, Resource, ErrorCounter, _ResourceId;\r\nAzureMetrics\r\n| where _ResourceId has '/microsoft.keyvault/vaults/'\r\n| where MetricName in('ServiceApiLatency', 'Availability')\r\n| project Resource, _ResourceId, MetricName, Average, Total\r\n| union kind=outer diagnostic_table\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'ServiceApiLatency'),\r\n  kpi2 = sumif(ErrorCounter, isnotnull(ErrorCounter)),\r\n  kpi3 = avgif(Average*100, MetricName == 'Availability') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(toreal(kpi2)), 0.0, toreal(kpi2)) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3) \r\n|extend health1 = iff(kpi1>1000, 1, 0)\r\n|extend health2 = iff(kpi2>500, 1, 0)\r\n|extend health3 = iff(kpi3<90, 1, 0)\r\n|extend health = health1 + health2 + health3",
      "resources": [ "/subscriptions/$sub" ]
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Traffic Managers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/trafficmanagerprofiles/'\r\n| where MetricName in('ProbeAgentCurrentEndpointStateByProfileResourceId', 'QpsByEndpoint')\r\n| summarize\r\n  kpi1 = avgif(Maximum, MetricName == 'ProbeAgentCurrentEndpointStateByProfileResourceId'),\r\n  kpi2 = avgif(Total, MetricName == 'QpsByEndpoint') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend health1 = iff(kpi1<=0, 1, 0)\r\n|extend health2 = iff(kpi2<=0, 1, 0)\r\n|extend health = health1 + health2",
      "resources": [ "/subscriptions/$sub" ]
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Front Doors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.cdn/profiles/'\r\n| where MetricName in('TotalLatency', 'ByteHitRatio', 'OriginHealthPercentage')\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'TotalLatency'),\r\n  kpi2 = avgif(Average, MetricName == 'ByteHitRatio'),\r\n  kpi3 = avgif(Average, MetricName == 'OriginHealthPercentage') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)\r\n|extend health1 = iff(kpi1>100, 1, 0)\r\n|extend health2 = iff(kpi2<50, 1, 0)\r\n|extend health3 = iff(kpi3<95, 1, 0)\r\n|extend health = health1 + health2 + health3",
      "resources": [ "/subscriptions/$sub" ]
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Firewalls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/azurefirewalls/'\r\n| where MetricName in('FirewallHealth', 'SNATPortUtilization') \r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'FirewallHealth'),\r\n  kpi2 = avgif(Average, MetricName == 'SNATPortUtilization') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2)\r\n|extend health1 = iff(kpi1<90, 1, 0)\r\n|extend health2 = iff(kpi2>80, 1, 0)\r\n|extend health = health1 + health2",
      "resources": [ "/subscriptions/$sub" ]
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "VPN Gateways",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/virtualnetworkgateways/'\r\n| where MetricName in('TunnelAverageBandwidth', 'AverageBandwidth', 'TunnelIngressBytes' )\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'TunnelAverageBandwidth'),\r\n  kpi2 = avgif(Average, MetricName == 'TunnelEgressBytes'),\r\n  kpi3 = avgif(Total, MetricName == 'TunnelIngressBytes') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)\r\n|extend health1 = iff(kpi1<1, 1, 0)\r\n|extend health2 = iff(kpi2<=1, 1, 0)\r\n|extend health3 = iff(kpi3<=1, 1, 0)\r\n|extend health = health1 + health2 + health3",
      "resources": [ "/subscriptions/$sub" ]
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "ExpressRoute Gateways",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AzureMetrics\r\n| where _ResourceId has '/microsoft.network/virtualnetworkgateways/'\r\n| where MetricName in('ExpressRouteGatewayCpuUtilization', 'ExpressRouteGatewayBitsPerSecond', 'ExpressRouteGatewayPacketsPerSecond' )\r\n| summarize\r\n  kpi1 = avgif(Average, MetricName == 'ExpressRouteGatewayCpuUtilization'),\r\n  kpi2 = avgif(Average, MetricName == 'ExpressRouteGatewayBitsPerSecond'),\r\n  kpi3 = avgif(Total, MetricName == 'ExpressRouteGatewayPacketsPerSecond') by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)\r\n|extend health1 = iff(kpi1>80, 1, 0)\r\n|extend health2 = iff(kpi2<=1, 1, 0)\r\n|extend health3 = iff(kpi3<=1, 1, 0)\r\n|extend health = health1 + health2 + health3",
      "resources": [ "/subscriptions/$sub" ]
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Virtual Machines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Machine CPU Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 2 }
     ]
    },
    {
     "title": "Virtual Machine CPU Utilization 95th Percentile",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 2 }
     ]
    },
    {
     "title": "Virtual Machine Available Memory GB",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 2 }
     ]
    },
    {
     "title": "Virtual Machine Availability",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 2 }
     ]
    }
   ]
  },
  {
   "title": "Virtual Machine Scale Sets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Machine Scale Set CPU Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 26 }
     ]
    },
    {
     "title": "Virtual Machine Scale Set OS Disk IOPS Consumed Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 26 }
     ]
    },
    {
     "title": "Virtual Machine Scale Set Available Memory GB",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 26 }
     ]
    },
    {
     "title": "Virtual Machine Scale Set Availability",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 26 }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Success End to End Latency",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 27 }
     ]
    },
    {
     "title": "Storage Failing Transactions",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 27 }
     ]
    },
    {
     "title": "Storage Used Capacity",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 27 }
     ]
    },
    {
     "title": "Storage Availability",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 27 }
     ]
    }
   ]
  },
  {
   "title": "Key Vaults",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Key Vault Service API Latency",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 28 }
     ]
    },
    {
     "title": "Key Vault Failing Transactions",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 28 }
     ]
    },
    {
     "title": "Key Vault Availability",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 28 }
     ]
    }
   ]
  },
  {
   "title": "Load Balancers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Balancer Used SNAT Ports",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 63 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 36 }
     ]
    },
    {
     "title": "Load Balancer Health Probe Status",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 63 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 36 }
     ]
    },
    {
     "title": "Load Balancer Data Path Availability",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 63 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 36 }
     ]
    }
   ]
  },
  {
   "title": "Traffic Managers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic Manager Endpoint Status by Endpoint",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 46 }
     ]
    },
    {
     "title": "Traffic Manager Queries by Endpoint Returned",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 46 }
     ]
    }
   ]
  },
  {
   "title": "Application Gateways",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Gateway Unhealthy Host Count",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 89 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 41 }
     ]
    },
    {
     "title": "Application Gateway Failed Requests",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 89 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 41 }
     ]
    },
    {
     "title": "Application Gateway Healthy Host Count",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 89 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 41 }
     ]
    }
   ]
  },
  {
   "title": "Front Doors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front Door Total Latency",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 102 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 53 }
     ]
    },
    {
     "title": "Front Door Byte Hit Ratio",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 102 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 53 }
     ]
    },
    {
     "title": "Front Door Origin Health Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 102 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 53 }
     ]
    }
   ]
  },
  {
   "title": "Public IPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Public IP Availability",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 115 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 50 }
     ]
    },
    {
     "title": "Virtual Network Under DDoS Attack",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 115 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 50 }
     ]
    },
    {
     "title": "Virtual Network Inbound Packets DDoS",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 115 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 50 }
     ]
    }
   ]
  },
  {
   "title": "Firewalls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Firewall Health",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 128 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 59 }
     ]
    },
    {
     "title": "Firewall SNAT Port Utilization",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 128 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 59 }
     ]
    }
   ]
  },
  {
   "title": "Virtual Networks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Network Under DDoS Attack",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 54 }
     ]
    },
    {
     "title": "Virtual Network Inbound Packets DDoS",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 54 }
     ]
    },
    {
     "title": "Virtual Network Packets Forwarded DDoS",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 141 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 54 }
     ]
    }
   ]
  },
  {
   "title": "VPN Gateways",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "VPN Gateway Tunnel Bandwidth",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 154 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 57 }
     ]
    },
    {
     "title": "VPN Gateway Tunnel Egress Bytes",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 154 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 57 }
     ]
    },
    {
     "title": "VPN Gateway Tunnel Ingress Bytes",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 154 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 57 }
     ]
    }
   ]
  },
  {
   "title": "ExpressRoute Circuits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Express Route Circuit BGP Availability",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 167 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 68 }
     ]
    },
    {
     "title": "Express Route Circuit ARP Availability",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 167 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 68 }
     ]
    },
    {
     "title": "Express Route QoS Drop Bits In Per Second",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 167 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 68 }
     ]
    },
    {
     "title": "Express Route QoS Drop Bits Out Per Second",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 167 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 68 }
     ]
    }
   ]
  },
  {
   "title": "ExpressRoute Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Express Route Gateway CPU Utilization",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 180 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "Express Route Gateway Bits Per Second",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 180 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 66 }
     ]
    },
    {
     "title": "Express Route Gateway Packets Per Second",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 180 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 66 }
     ]
    }
   ]
  }
 ]
}