#!/bin/bash
set -xeo pipefail

. e2e/variables

HOST=${HOST:-$DEFAULT_HOST}
PORT=${PORT:-$DEFAULT_PORT}

echo -e "Starting Cypress scenarios"

CMD="start"
PARAMS=""
SLOWMO=0
URL=${BASE_URL:-"http://$HOST:$PORT"}
SUITE=${SUITE:-$DEFAULT_SUITE}

if [ "$1" == "debug" ]; then
    echo -e "Debug mode"
    SLOWMO=1
    PARAMS="--headed --no-exit"
fi

if [ "$1" == "dev" ]; then
    echo "Dev mode"
    CMD="open"
fi

cd packages/grafana-e2e

yarn $CMD --env BASE_URL=$URL,SLOWMO=$SLOWMO \
  --config integrationFolder=../../e2e/$SUITE/specs,screenshotsFolder=../../e2e/$SUITE/screenshots,videosFolder=../../e2e/$SUITE/videos,fileServerFolder=./cypress,viewportWidth=1920,viewportHeight=1080,trashAssetsBeforeRuns=false \
  $PARAMS
