#!/bin/bash
trap "exit" INT TERM
trap "kill 0" EXIT

# start storybook in the background and wait for it to respond
yarn storybook &
HOST=localhost PORT=9001 ./scripts/grafana-server/wait-for-grafana

HOST=localhost PORT=9001 ./e2e/run-suite storybook true
