#!/bin/bash
set -eo pipefail
trap "exit" INT TERM
trap "kill 0" EXIT

. scripts/grafana-server/variables

# start storybook in the background and wait for it to respond
yarn storybook &

PORT=9001 ./e2e/run-suite storybook true
