#!/bin/bash

. e2e/variables

PORT=${PORT:-$DEFAULT_PORT}

echo -e "Starting Grafana Server port $PORT"

$RUNDIR/bin/grafana-server \
  --homepath=$RUNDIR \
  --pidfile=$RUNDIR/pid \
  cfg:server.http_port=$PORT \
  cfg:app_mode=development

# 2>&1 > $RUNDIR/output.log &
# cfg:log.level=debug \
