#!/bin/bash

. e2e/variables

echo -e "Starting Grafana Server E2E Scenario"

./e2e/kill-server

mkdir $RUNDIR

echo -e "Copying grafana backend files to temp dir..."

ls dist/*

if [ -f dist/grafana-latest.linux-x64.tar.gz ]; then
  echo "Found built tar file"
  tar zxf dist/grafana-latest.linux-x64.tar.gz -C $RUNDIR
  mv $RUNDIR/grafana-*/**/* $RUNDIR
else
  echo "Copying local dev files"

  cp -r ./bin/grafana-server $RUNDIR
  cp -r ./public $RUNDIR
fi

mkdir $RUNDIR/conf
cp ./conf/defaults.ini $RUNDIR/conf/defaults.ini
cp ./e2e/conf/scenario1.ini $RUNDIR/conf/custom.ini

$RUNDIR/grafana-server \
  --homepath=$RUNDIR \
  --pidfile=$RUNDIR/pid \
  cfg:server.http_port=$PORT \
  2>&1 > $RUNDIR/output.log &

