package contracts

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	common "github.com/grafana/grafana/pkg/apimachinery/apis/common/v0alpha1"
)

// MockInlineSecureValueStore is NOT YET autogenerated mock type...
type MockInlineSecureValueStore struct {
	mock.Mock
}

var _ InlineSecureValueStore = (*MockInlineSecureValueStore)(nil)

// CanReference implements InlineSecureValueStore.
func (m *MockInlineSecureValueStore) CanReference(ctx context.Context, owner common.ResourceReference, names ...string) (bool, error) {
	return true, nil
}

// CreateSecureValue implements InlineSecureValueStore.
func (m *MockInlineSecureValueStore) CreateSecureValue(ctx context.Context, owner common.ResourceReference, value common.RawSecretValue) (string, error) {
	return "TODO", nil
}

// DeleteValuesForOwner implements InlineSecureValueStore.
func (m *MockInlineSecureValueStore) DeleteValuesForOwner(ctx context.Context, owner common.ResourceReference, names ...string) error {
	return nil
}
