config:
  keysDir: /app/data/keys
  tokenExpiry: 43200
  cfgPollInterval: 30
services:
  - name: access-policy:error-tracking
    token: ThisIsMySecretToken
    scopes:
      - access-token:sign
      - grafana-id-token:sign
    namespaces:
      - stacks-11
      - stacks-22
      - default
      - "*"
    audiences:
      - error-tracking.grafana.app
      - authzService
      - grafana
      - cloudAppPlatformDiscovery
    permissions:
      - "error-tracking.grafana.app/events:read"
      - "error-tracking.grafana.app/events:create"
      - "error-tracking.grafana.app:*"
      - "folders:read"
    delegatedPermissions:
      - "error-tracking.grafana.app/events:read"
      - "error-tracking.grafana.app/events:create"
      - "error-tracking.grafana.app:*"
      - "folders:read"
  - name: access-policy:authz
    token: AuthzServiceToken
    scopes:
      - access-token:sign
      - grafana-id-token:sign
    namespaces:
      - default
      - stacks-11
      - "*"
    audiences:
      - folder.grafana.app
      - resourceStore
    permissions:
      - "folder.grafana.app/folders:*"
      - "folders:read"
    delegatedPermissions:
      - "folder.grafana.app/folders:*"
      - "folders:read"
