define([
  './dashboardCtrl',
  './dashboardNavCtrl',
  './playlistCtrl',
  './rowCtrl',
  './sharePanelCtrl',
  './submenuCtrl',
  './dashboardSrv',
  './keybindings',
  './viewStateSrv',
  './playlistSrv',
  './soloPanelCtrl',
  './timeSrv',
  './unsavedChangesSrv',
], function () {});
