define([
  './dashboardCtrl',
  './dashboardNavCtrl',
  './saveDashboardAsCtrl',
  './playlistCtrl',
  './rowCtrl',
  './sharePanelCtrl',
  './submenuCtrl',
  './dashboardSrv',
  './keybindings',
  './viewStateSrv',
  './playlistSrv',
  './timeSrv',
  './unsavedChangesSrv',
  './directives/dashSearchView',
  './graphiteImportCtrl',
  './importCtrl',
], function () {});
