name: 'Setup Grafana Enterprise'
description: 'Clones and sets up Grafana Enterprise repository for testing'

inputs:
  token:
    description: 'GitHub token for cloning grafana-enterprise'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Enterprise
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        git clone https://x-access-token:${GH_TOKEN}@github.com/grafana/grafana-enterprise.git ../grafana-enterprise;

        cd ../grafana-enterprise

        if git checkout ${GITHUB_HEAD_REF}; then
          echo "checked out ${GITHUB_HEAD_REF}"
        elif git checkout ${GITHUB_BASE_REF}; then
          echo "checked out ${GITHUB_BASE_REF}"
        else
          git checkout main
        fi

        QUIET=1 ./build.sh
