import { Token } from 'monaco-editor/esm/vs/editor/editor.api';

import { LogsTokenTypes } from '../../language/logs/completion/types';
import { CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID } from '../../language/logs/definition';

export const multiLineFullQuery = {
  query: `fields @timestamp, unmask(@message) as msg, @memorySize
  | filter (@message like /error/ and bytes > 1000)
  | parse @message /(?<NetworkInterface>eni-.*?)/
  | stats count(NetworkInterface), max(@memorySize / 1000 / 1000) as provisonedMemoryMB by bin(1m)
  # this is a comment with the next line left being intentionally blank

  | limit 20`,
  tokens: [
    [
      new Token(0, LogsTokenTypes.Keyword, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(6, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(7, LogsTokenTypes.Identifier, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(17, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(18, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(19, LogsTokenTypes.Function, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(25, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(26, LogsTokenTypes.Identifier, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(34, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(35, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(36, LogsTokenTypes.Keyword, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(38, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(39, LogsTokenTypes.Identifier, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(42, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(43, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(44, LogsTokenTypes.Identifier, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
    ],
    [
      new Token(0, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(1, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(2, LogsTokenTypes.Keyword, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(8, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(9, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(10, LogsTokenTypes.Identifier, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(18, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(19, LogsTokenTypes.Keyword, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(26, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(27, LogsTokenTypes.Regexp, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(31, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(32, LogsTokenTypes.Operator, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(35, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(36, LogsTokenTypes.Identifier, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(41, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(42, LogsTokenTypes.Operator, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(43, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(44, LogsTokenTypes.Number, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(48, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
    ],
    [
      new Token(0, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(1, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(2, LogsTokenTypes.Keyword, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(7, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(8, LogsTokenTypes.Identifier, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(16, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(17, LogsTokenTypes.Regexp, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
    ],
    [
      new Token(0, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(1, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(2, LogsTokenTypes.Keyword, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(7, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(8, LogsTokenTypes.Function, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(13, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(14, LogsTokenTypes.Identifier, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(30, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(31, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(32, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(33, LogsTokenTypes.Function, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(36, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(37, LogsTokenTypes.Identifier, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(48, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(49, LogsTokenTypes.Operator, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(50, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(51, LogsTokenTypes.Number, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(55, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(56, LogsTokenTypes.Operator, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(57, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(58, LogsTokenTypes.Number, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(62, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(63, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(64, LogsTokenTypes.Keyword, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(66, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(67, LogsTokenTypes.Identifier, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(85, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(86, LogsTokenTypes.Keyword, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(88, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(89, LogsTokenTypes.Function, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(92, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(93, LogsTokenTypes.Number, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(94, LogsTokenTypes.Identifier, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(95, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
    ],
    [new Token(0, LogsTokenTypes.Comment, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID)],
    [new Token(0, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID)],
    [
      new Token(0, LogsTokenTypes.Delimiter, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(1, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(2, LogsTokenTypes.Keyword, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(7, LogsTokenTypes.Whitespace, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
      new Token(8, LogsTokenTypes.Number, CLOUDWATCH_LOGS_LANGUAGE_DEFINITION_ID),
    ],
  ],
};
