export const LOCATION_DISPLAY_NAMES = {
  eastus: 'East US',
  eastus2: 'East US 2',
  southcentralus: 'South Central US',
  westus2: 'West US 2',
  westus3: 'West US 3',
  australiaeast: 'Australia East',
  southeastasia: 'Southeast Asia',
  northeurope: 'North Europe',
  uksouth: 'UK South',
  westeurope: 'West Europe',
  centralus: 'Central US',
  northcentralus: 'North Central US',
  westus: 'West US',
  southafricanorth: 'South Africa North',
  centralindia: 'Central India',
  eastasia: 'East Asia',
  japaneast: 'Japan East',
  jioindiawest: 'Jio India West',
  koreacentral: 'Korea Central',
  canadacentral: 'Canada Central',
  francecentral: 'France Central',
  germanywestcentral: 'Germany West Central',
  norwayeast: 'Norway East',
  switzerlandnorth: 'Switzerland North',
  uaenorth: 'UAE North',
  brazilsouth: 'Brazil South',
  centralusstage: 'Central US (Stage)',
  eastusstage: 'East US (Stage)',
  eastus2stage: 'East US 2 (Stage)',
  northcentralusstage: 'North Central US (Stage)',
  southcentralusstage: 'South Central US (Stage)',
  westusstage: 'West US (Stage)',
  westus2stage: 'West US 2 (Stage)',
  asia: 'Asia',
  asiapacific: 'Asia Pacific',
  australia: 'Australia',
  brazil: 'Brazil',
  canada: 'Canada',
  europe: 'Europe',
  global: 'Global',
  india: 'India',
  japan: 'Japan',
  uk: 'United Kingdom',
  unitedstates: 'United States',
  eastasiastage: 'East Asia (Stage)',
  southeastasiastage: 'Southeast Asia (Stage)',
  westcentralus: 'West Central US',
  southafricawest: 'South Africa West',
  australiacentral: 'Australia Central',
  australiacentral2: 'Australia Central 2',
  australiasoutheast: 'Australia Southeast',
  japanwest: 'Japan West',
  koreasouth: 'Korea South',
  southindia: 'South India',
  westindia: 'West India',
  canadaeast: 'Canada East',
  francesouth: 'France South',
  germanynorth: 'Germany North',
  norwaywest: 'Norway West',
  switzerlandwest: 'Switzerland West',
  ukwest: 'UK West',
  uaecentral: 'UAE Central',
  brazilsoutheast: 'Brazil Southeast',
};
