import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { ImportDashboardState } from '../../../types';

const initialImportDashboardState: ImportDashboardState = {
  dashboard: {
    id: 9777,
    status: 1,
    orgId: 232931,
    orgSlug: 'threedotslabs',
    orgName: 'threedotslabs',
    slug: 'watermill',
    downloads: 2253,
    revisionId: 13631,
    revision: 7,
    name: '1.0 Watermill',
    description:
      'Watermill is a Go library for working efficiently with message streams. It is intended for building event driven applications, enabling event sourcing, RPC over messages, sagas and basically whatever else comes to your mind. You can use conventional pub/sub implementations like Kafka or RabbitMQ, but also HTTP or MySQL binlog if that fits your use case.',
    readme:
      'GitHub: [https://github.com/ThreeDotsLabs/watermill/](https://github.com/ThreeDotsLabs/watermill/)\n\nWatermill Docs: [https://watermill.io/](https://watermill.io/)\n\nWatermill metrics Docs: [https://watermill.io/docs/metrics](https://watermill.io/docs/metrics)',
    collectorType: 'Other',
    collectorConfig: null,
    privacy: 'public',
    createdAt: '2019-02-07T15:36:53.000Z',
    updatedAt: '2019-05-09T21:15:08.000Z',
    isEditor: false,
    screenshots: [
      {
        id: 6137,
        dashboardId: 9777,
        name: '',
        filename: 'grafana_dashboard.png',
        mainScreenshot: false,
        createdAt: '2019-02-13T09:12:03.000Z',
        updatedAt: null,
        links: [
          {
            rel: 'self',
            href: '/dashboards/9777/images/6137',
          },
          {
            rel: 'image',
            href: '/dashboards/9777/images/6137/image',
          },
          {
            rel: 'thumbnail',
            href: '/dashboards/9777/images/6137/thumbnail',
          },
          {
            rel: 'dashboard',
            href: '/dashboards/9777',
          },
        ],
      },
    ],
    dependencies: {
      items: [
        {
          id: 54096,
          dashboardId: 9777,
          dashboardName: '1.0 Watermill',
          revisionId: 13631,
          revision: 7,
          pluginSlug: 'grafana',
          pluginName: 'Grafana',
          pluginId: 55,
          pluginVersion: '5.2.4',
          pluginTypeId: 2,
          pluginTypeName: 'Data Source',
          pluginTypeCode: 'datasource',
          orgId: 232931,
          orgName: 'threedotslabs',
          orgSlug: 'threedotslabs',
          createdAt: '2019-02-13T11:49:08.000Z',
          updatedAt: null,
          links: [
            {
              rel: 'revision',
              href: '/dashboards/9777/revisions/7',
            },
            {
              rel: 'dashboard',
              href: '/dashboards/9777',
            },
            {
              rel: 'org',
              href: '/orgs/threedotslabs',
            },
            {
              rel: 'plugin',
              href: '/plugins/undefined',
            },
          ],
        },
        {
          id: 54097,
          dashboardId: 9777,
          dashboardName: '1.0 Watermill',
          revisionId: 13631,
          revision: 7,
          pluginSlug: 'graph',
          pluginName: 'Graph',
          pluginId: 37,
          pluginVersion: '5.0.0',
          pluginTypeId: 3,
          pluginTypeName: 'Panel',
          pluginTypeCode: 'panel',
          orgId: 232931,
          orgName: 'threedotslabs',
          orgSlug: 'threedotslabs',
          createdAt: '2019-02-13T11:49:08.000Z',
          updatedAt: null,
          links: [
            {
              rel: 'revision',
              href: '/dashboards/9777/revisions/7',
            },
            {
              rel: 'dashboard',
              href: '/dashboards/9777',
            },
            {
              rel: 'org',
              href: '/orgs/threedotslabs',
            },
            {
              rel: 'plugin',
              href: '/plugins/undefined',
            },
          ],
        },
        {
          id: 54098,
          dashboardId: 9777,
          dashboardName: '1.0 Watermill',
          revisionId: 13631,
          revision: 7,
          pluginSlug: 'prometheus',
          pluginName: 'Prometheus',
          pluginId: 70,
          pluginVersion: '5.0.0',
          pluginTypeId: 2,
          pluginTypeName: 'Data Source',
          pluginTypeCode: 'datasource',
          orgId: 232931,
          orgName: 'threedotslabs',
          orgSlug: 'threedotslabs',
          createdAt: '2019-02-13T11:49:08.000Z',
          updatedAt: null,
          links: [
            {
              rel: 'revision',
              href: '/dashboards/9777/revisions/7',
            },
            {
              rel: 'dashboard',
              href: '/dashboards/9777',
            },
            {
              rel: 'org',
              href: '/orgs/threedotslabs',
            },
            {
              rel: 'plugin',
              href: '/plugins/undefined',
            },
          ],
        },
        {
          id: 54099,
          dashboardId: 9777,
          dashboardName: '1.0 Watermill',
          revisionId: 13631,
          revision: 7,
          pluginSlug: 'singlestat',
          pluginName: 'Singlestat',
          pluginId: 40,
          pluginVersion: '5.0.0',
          pluginTypeId: 3,
          pluginTypeName: 'Panel',
          pluginTypeCode: 'panel',
          orgId: 232931,
          orgName: 'threedotslabs',
          orgSlug: 'threedotslabs',
          createdAt: '2019-02-13T11:49:08.000Z',
          updatedAt: null,
          links: [
            {
              rel: 'revision',
              href: '/dashboards/9777/revisions/7',
            },
            {
              rel: 'dashboard',
              href: '/dashboards/9777',
            },
            {
              rel: 'org',
              href: '/orgs/threedotslabs',
            },
            {
              rel: 'plugin',
              href: '/plugins/undefined',
            },
          ],
        },
        {
          id: 54100,
          dashboardId: 9777,
          dashboardName: '1.0 Watermill',
          revisionId: 13631,
          revision: 7,
          pluginSlug: 'text',
          pluginName: 'Text',
          pluginId: 34,
          pluginVersion: '5.0.0',
          pluginTypeId: 3,
          pluginTypeName: 'Panel',
          pluginTypeCode: 'panel',
          orgId: 232931,
          orgName: 'threedotslabs',
          orgSlug: 'threedotslabs',
          createdAt: '2019-02-13T11:49:08.000Z',
          updatedAt: null,
          links: [
            {
              rel: 'revision',
              href: '/dashboards/9777/revisions/7',
            },
            {
              rel: 'dashboard',
              href: '/dashboards/9777',
            },
            {
              rel: 'org',
              href: '/orgs/threedotslabs',
            },
            {
              rel: 'plugin',
              href: '/plugins/undefined',
            },
          ],
        },
      ],
      orderBy: 'name',
      direction: 'asc',
      links: [],
    },
    categories: {
      items: [],
      orderBy: 'categoryName',
      direction: 'asc',
      links: [],
    },
    collectorPlugins: {
      items: [],
      orderBy: 'name',
      direction: 'asc',
      links: [],
    },
    hasLogo: true,
    reviewsCount: 3,
    reviewsAvgRating: 3.33,
    links: [
      {
        rel: 'self',
        href: '/dashboards/9777',
      },
      {
        rel: 'revisions',
        href: '/dashboards/9777/revisions',
      },
      {
        rel: 'revision',
        href: '/dashboards/9777/revisions/7',
      },
      {
        rel: 'download',
        href: '/dashboards/9777/revisions/7/download',
      },
      {
        rel: 'org',
        href: '/orgs/threedotslabs',
      },
      {
        rel: 'images',
        href: '/dashboards/9777/images',
      },
      {
        rel: 'thumbnails',
        href: '/dashboards/9777/thumbnails',
      },
    ],
    json: {
      __inputs: [
        {
          name: 'DS_PROMETHEUS',
          label: 'prometheus',
          description: '',
          type: 'datasource',
          pluginId: 'prometheus',
          pluginName: 'Prometheus',
        },
      ],
      __requires: [
        {
          type: 'grafana',
          id: 'grafana',
          name: 'Grafana',
          version: '5.2.4',
        },
        {
          type: 'panel',
          id: 'graph',
          name: 'Graph',
          version: '5.0.0',
        },
        {
          type: 'datasource',
          id: 'prometheus',
          name: 'Prometheus',
          version: '5.0.0',
        },
        {
          type: 'panel',
          id: 'singlestat',
          name: 'Singlestat',
          version: '5.0.0',
        },
        {
          type: 'panel',
          id: 'text',
          name: 'Text',
          version: '5.0.0',
        },
      ],
      annotations: {
        list: [
          {
            builtIn: 1,
            datasource: '-- Grafana --',
            enable: true,
            hide: true,
            iconColor: 'rgba(0, 211, 255, 1)',
            name: 'Annotations & Alerts',
            type: 'dashboard',
          },
        ],
      },
      description:
        'Watermill is a Go library for working efficiently with message streams. It is intended for building event driven applications, enabling event sourcing, RPC over messages, sagas and basically whatever else comes to your mind. You can use conventional pub/sub implementations like Kafka or RabbitMQ, but also HTTP or MySQL binlog if that fits your use case.',
      editable: true,
      gnetId: 9777,
      graphTooltip: 0,
      id: null,
      iteration: 1550057756355,
      links: [],
      panels: [
        {
          collapsed: false,
          gridPos: {
            h: 1,
            w: 24,
            x: 0,
            y: 0,
          },
          id: 12,
          panels: [],
          title: 'Current stats',
          type: 'row',
        },
        {
          cacheTimeout: null,
          colorBackground: false,
          colorValue: false,
          colors: ['#299c46', 'rgba(237, 129, 40, 0.89)', '#d44a3a'],
          datasource: '${DS_PROMETHEUS}',
          decimals: 0,
          description:
            'Counts the messages received within the selected interval. The graph shows the historical trend of this value, also measured over the selected interval.',
          format: 'none',
          gauge: {
            maxValue: 100,
            minValue: 0,
            show: false,
            thresholdLabels: false,
            thresholdMarkers: true,
          },
          gridPos: {
            h: 4,
            w: 3,
            x: 0,
            y: 1,
          },
          id: 14,
          interval: null,
          links: [],
          mappingType: 1,
          mappingTypes: [
            {
              name: 'value to text',
              value: 1,
            },
            {
              name: 'range to text',
              value: 2,
            },
          ],
          maxDataPoints: 100,
          nullPointMode: 'connected',
          nullText: null,
          postfix: '',
          postfixFontSize: '50%',
          prefix: '',
          prefixFontSize: '50%',
          rangeMaps: [
            {
              from: 'null',
              text: 'N/A',
              to: 'null',
            },
          ],
          sparkline: {
            fillColor: 'rgba(31, 118, 189, 0.18)',
            full: true,
            lineColor: 'rgb(31, 120, 193)',
            show: true,
          },
          tableColumn: 'Value',
          targets: [
            {
              expr:
                'sum(increase(subscriber_messages_received_total{instance=~"$node", handler_name=~"$handler"}[$interval]))',
              format: 'time_series',
              instant: false,
              intervalFactor: 1,
              refId: 'A',
            },
          ],
          thresholds: '',
          title: 'Messages received',
          type: 'singlestat',
          valueFontSize: '80%',
          valueMaps: [
            {
              op: '=',
              text: 'N/A',
              value: 'null',
            },
          ],
          valueName: 'current',
        },
        {
          cacheTimeout: null,
          colorBackground: false,
          colorValue: false,
          colors: ['#299c46', 'rgba(237, 129, 40, 0.89)', '#d44a3a'],
          datasource: '${DS_PROMETHEUS}',
          decimals: 0,
          description:
            'Counts the handler errors within the selected interval. The graph shows the historical trend of this value, also measured over the selected interval.',
          format: 'none',
          gauge: {
            maxValue: 100,
            minValue: 0,
            show: false,
            thresholdLabels: false,
            thresholdMarkers: true,
          },
          gridPos: {
            h: 4,
            w: 3,
            x: 3,
            y: 1,
          },
          id: 16,
          interval: null,
          links: [],
          mappingType: 1,
          mappingTypes: [
            {
              name: 'value to text',
              value: 1,
            },
            {
              name: 'range to text',
              value: 2,
            },
          ],
          maxDataPoints: 100,
          nullPointMode: 'connected',
          nullText: null,
          postfix: '',
          postfixFontSize: '50%',
          prefix: '',
          prefixFontSize: '50%',
          rangeMaps: [
            {
              from: 'null',
              text: 'N/A',
              to: 'null',
            },
          ],
          sparkline: {
            fillColor: 'rgba(191, 27, 0, 0.33)',
            full: false,
            lineColor: '#bf1b00',
            show: true,
          },
          tableColumn: 'Value',
          targets: [
            {
              expr:
                'sum(increase(handler_execution_time_seconds_count{instance=~"$node", handler_name=~"$handler", success="false"}[$interval]))',
              format: 'time_series',
              instant: false,
              intervalFactor: 1,
              refId: 'A',
            },
          ],
          thresholds: '',
          title: 'Handler errors',
          type: 'singlestat',
          valueFontSize: '80%',
          valueMaps: [
            {
              op: '=',
              text: '0',
              value: 'null',
            },
          ],
          valueName: 'current',
        },
        {
          cacheTimeout: null,
          colorBackground: false,
          colorValue: false,
          colors: ['#299c46', 'rgba(237, 129, 40, 0.89)', '#d44a3a'],
          datasource: '${DS_PROMETHEUS}',
          decimals: 0,
          description:
            'Counts the messages publisher within the selected interval. The graph shows the historical trend of this value, also measured over the selected interval.',
          format: 'none',
          gauge: {
            maxValue: 100,
            minValue: 0,
            show: false,
            thresholdLabels: false,
            thresholdMarkers: true,
          },
          gridPos: {
            h: 4,
            w: 3,
            x: 6,
            y: 1,
          },
          id: 15,
          interval: null,
          links: [],
          mappingType: 1,
          mappingTypes: [
            {
              name: 'value to text',
              value: 1,
            },
            {
              name: 'range to text',
              value: 2,
            },
          ],
          maxDataPoints: 100,
          nullPointMode: 'connected',
          nullText: null,
          postfix: '',
          postfixFontSize: '50%',
          prefix: '',
          prefixFontSize: '50%',
          rangeMaps: [
            {
              from: 'null',
              text: 'N/A',
              to: 'null',
            },
          ],
          sparkline: {
            fillColor: 'rgba(31, 118, 189, 0.18)',
            full: false,
            lineColor: 'rgb(31, 120, 193)',
            show: true,
          },
          tableColumn: '',
          targets: [
            {
              expr:
                'sum(increase(publish_time_seconds_count{instance=~"$node", handler_name=~"$handler", success="true"}[$interval]))',
              format: 'time_series',
              interval: '',
              intervalFactor: 1,
              refId: 'A',
            },
          ],
          thresholds: '',
          title: 'Messages published',
          type: 'singlestat',
          valueFontSize: '80%',
          valueMaps: [
            {
              op: '=',
              text: 'N/A',
              value: 'null',
            },
          ],
          valueName: 'current',
        },
        {
          cacheTimeout: null,
          colorBackground: false,
          colorValue: false,
          colors: ['#299c46', 'rgba(237, 129, 40, 0.89)', '#d44a3a'],
          datasource: '${DS_PROMETHEUS}',
          decimals: 0,
          description:
            'Counts the publisher errors within the selected interval. The graph shows the historical trend of this value, also measured over the selected interval.',
          format: 'none',
          gauge: {
            maxValue: 100,
            minValue: 0,
            show: false,
            thresholdLabels: false,
            thresholdMarkers: true,
          },
          gridPos: {
            h: 4,
            w: 3,
            x: 9,
            y: 1,
          },
          id: 17,
          interval: null,
          links: [],
          mappingType: 1,
          mappingTypes: [
            {
              name: 'value to text',
              value: 1,
            },
            {
              name: 'range to text',
              value: 2,
            },
          ],
          maxDataPoints: 100,
          nullPointMode: 'connected',
          nullText: null,
          postfix: '',
          postfixFontSize: '50%',
          prefix: '',
          prefixFontSize: '50%',
          rangeMaps: [
            {
              from: 'null',
              text: 'N/A',
              to: 'null',
            },
          ],
          sparkline: {
            fillColor: 'rgba(191, 27, 0, 0.33)',
            full: false,
            lineColor: '#bf1b00',
            show: true,
          },
          tableColumn: '',
          targets: [
            {
              expr:
                'sum(increase(publish_time_seconds_count{instance=~"$node", handler_name=~"$handler", success="false"}[$interval]))',
              format: 'time_series',
              intervalFactor: 1,
              refId: 'A',
            },
          ],
          thresholds: '',
          title: 'Publisher errors',
          type: 'singlestat',
          valueFontSize: '80%',
          valueMaps: [
            {
              op: '=',
              text: '0',
              value: 'null',
            },
          ],
          valueName: 'current',
        },
        {
          cacheTimeout: null,
          colorBackground: false,
          colorValue: true,
          colors: ['#d44a3a', 'rgba(237, 129, 40, 0.89)', '#299c46'],
          datasource: '${DS_PROMETHEUS}',
          format: 'none',
          gauge: {
            maxValue: 100,
            minValue: 0,
            show: false,
            thresholdLabels: false,
            thresholdMarkers: true,
          },
          gridPos: {
            h: 4,
            w: 3,
            x: 12,
            y: 1,
          },
          id: 18,
          interval: null,
          links: [],
          mappingType: 1,
          mappingTypes: [
            {
              name: 'value to text',
              value: 1,
            },
            {
              name: 'range to text',
              value: 2,
            },
          ],
          maxDataPoints: 100,
          nullPointMode: 'connected',
          nullText: null,
          postfix: '',
          postfixFontSize: '50%',
          prefix: '',
          prefixFontSize: '50%',
          rangeMaps: [
            {
              from: 'null',
              text: 'N/A',
              to: 'null',
            },
          ],
          sparkline: {
            fillColor: 'rgba(57, 232, 0, 0.5)',
            full: false,
            lineColor: 'rgba(57, 232, 0, 1)',
            show: true,
          },
          tableColumn: '',
          targets: [
            {
              expr: 'sum(count(subscriber_messages_received_total{acked="acked"}) by (instance))',
              format: 'time_series',
              intervalFactor: 1,
              refId: 'A',
            },
          ],
          thresholds: '-1, 0',
          title: 'Subscriber count',
          type: 'singlestat',
          valueFontSize: '80%',
          valueMaps: [
            {
              op: '=',
              text: '0',
              value: 'null',
            },
          ],
          valueName: 'current',
        },
        {
          cacheTimeout: null,
          colorBackground: false,
          colorValue: true,
          colors: ['#d44a3a', 'rgba(237, 129, 40, 0.89)', '#299c46'],
          datasource: '${DS_PROMETHEUS}',
          format: 'none',
          gauge: {
            maxValue: 100,
            minValue: 0,
            show: false,
            thresholdLabels: false,
            thresholdMarkers: true,
          },
          gridPos: {
            h: 4,
            w: 3,
            x: 15,
            y: 1,
          },
          id: 19,
          interval: null,
          links: [],
          mappingType: 1,
          mappingTypes: [
            {
              name: 'value to text',
              value: 1,
            },
            {
              name: 'range to text',
              value: 2,
            },
          ],
          maxDataPoints: 100,
          nullPointMode: 'connected',
          nullText: null,
          postfix: '',
          postfixFontSize: '50%',
          prefix: '',
          prefixFontSize: '50%',
          rangeMaps: [
            {
              from: 'null',
              text: 'N/A',
              to: 'null',
            },
          ],
          sparkline: {
            fillColor: 'rgba(57, 232, 0, 0.5)',
            full: false,
            lineColor: 'rgba(57, 232, 0, 1)',
            show: true,
          },
          tableColumn: '',
          targets: [
            {
              expr: 'sum(count(handler_execution_time_seconds_count{success="true"}) by (instance))',
              format: 'time_series',
              intervalFactor: 1,
              refId: 'A',
            },
          ],
          thresholds: '-1, 0',
          title: 'Handler count',
          type: 'singlestat',
          valueFontSize: '80%',
          valueMaps: [
            {
              op: '=',
              text: '0',
              value: 'null',
            },
          ],
          valueName: 'current',
        },
        {
          cacheTimeout: null,
          colorBackground: false,
          colorValue: true,
          colors: ['#d44a3a', 'rgba(237, 129, 40, 0.89)', '#299c46'],
          datasource: '${DS_PROMETHEUS}',
          format: 'none',
          gauge: {
            maxValue: 100,
            minValue: 0,
            show: false,
            thresholdLabels: false,
            thresholdMarkers: true,
          },
          gridPos: {
            h: 4,
            w: 3,
            x: 18,
            y: 1,
          },
          id: 20,
          interval: null,
          links: [],
          mappingType: 1,
          mappingTypes: [
            {
              name: 'value to text',
              value: 1,
            },
            {
              name: 'range to text',
              value: 2,
            },
          ],
          maxDataPoints: 100,
          nullPointMode: 'connected',
          nullText: null,
          postfix: '',
          postfixFontSize: '50%',
          prefix: '',
          prefixFontSize: '50%',
          rangeMaps: [
            {
              from: 'null',
              text: 'N/A',
              to: 'null',
            },
          ],
          sparkline: {
            fillColor: 'rgba(57, 232, 0, 0.5)',
            full: false,
            lineColor: 'rgba(57, 232, 0, 1)',
            show: true,
          },
          tableColumn: '',
          targets: [
            {
              expr: 'sum(count(publish_time_seconds_count{success="true"}) by (instance))',
              format: 'time_series',
              intervalFactor: 1,
              refId: 'A',
            },
          ],
          thresholds: '-1, 0',
          title: 'Publisher count',
          type: 'singlestat',
          valueFontSize: '80%',
          valueMaps: [
            {
              op: '=',
              text: '0',
              value: 'null',
            },
          ],
          valueName: 'current',
        },
        {
          content:
            '<center>\n  <a href="https://threedotslabs.com/">\n    <svg\n       xmlns:svg="http://www.w3.org/2000/svg"\n       xmlns="http://www.w3.org/2000/svg"\n       version="1.1"\n       width="100"\n       height="100"\n       viewBox="0 0 100 100">\n      <path\n         style="fill:#ffffff;stroke-width:0.02"\n         d="M 31.778916,99.930604 C 27.39576,98.858563 24.621347,94.358696 24.578653,90.0029 c 2.563799,-5.722986 5.686344,-11.211293 8.464703,-16.845645 2.189261,-4.353403 4.539058,-8.631413 6.597006,-13.047655 0.199946,-5.171341 0.130598,-10.398628 0.0614,-15.561986 -3.468387,-1.361218 -3.351144,-7.231458 0.360804,-8.127289 6.697684,0.0085 13.395999,-0.03612 20.093198,0.01846 3.542089,1.183583 3.529953,6.766248 0.126526,8.149373 -0.06596,5.182609 -0.02588,10.36833 0.02191,15.551439 4.9877,9.923535 10.225735,19.73149 15.112875,29.698952 0.15367,4.962538 -3.855901,10.637711 -9.203144,10.129645 -11.478179,-0.0167 -22.958055,0.0411 -34.435015,-0.0376 z M 49.517004,33.681892 c -3.49539,-0.396964 -4.085406,-5.770645 -0.677353,-6.812398 4.786757,-1.80492 6.567596,6.435435 1.505626,6.809576 l -0.828245,0.0028 z m -8.749692,-15.57129 c -3.725896,-0.337231 -5.108816,-5.824382 -1.760886,-7.723699 3.008247,-2.2390459 7.553323,1.193141 6.317934,4.699865 -0.576937,1.913074 -2.561064,3.267086 -4.557048,3.023834 z m 18.929333,-2.199243 c -4.161672,-0.05674 -6.64547,-5.620071 -3.852212,-8.7465156 2.570378,-3.6222675 8.909217,-2.0678395 9.554451,2.3324255 0.718338,3.3455981 -2.27107,6.7899561 -5.702239,6.4140901 z">\n      </path>\n    </svg>\n  </a>\n</center>',
          gridPos: {
            h: 4,
            w: 3,
            x: 21,
            y: 1,
          },
          id: 22,
          links: [],
          mode: 'html',
          title: 'Made by',
          type: 'text',
        },
        {
          collapsed: false,
          gridPos: {
            h: 1,
            w: 24,
            x: 0,
            y: 5,
          },
          id: 10,
          panels: [],
          title: 'Handler & publisher operations',
          type: 'row',
        },
        {
          aliasColors: {},
          bars: false,
          dashLength: 10,
          dashes: false,
          datasource: '${DS_PROMETHEUS}',
          fill: 1,
          gridPos: {
            h: 8,
            w: 12,
            x: 0,
            y: 6,
          },
          id: 2,
          legend: {
            avg: false,
            current: false,
            max: false,
            min: false,
            show: true,
            total: false,
            values: false,
          },
          lines: true,
          linewidth: 1,
          links: [],
          nullPointMode: 'null',
          percentage: false,
          pointradius: 5,
          points: false,
          renderer: 'flot',
          seriesOverrides: [],
          spaceLength: 10,
          stack: false,
          steppedLine: false,
          targets: [
            {
              expr:
                'sum(irate(handler_execution_time_seconds_count{instance=~"$node", handler_name=~"$handler"}[$interval])) by (handler_name, instance)',
              format: 'time_series',
              intervalFactor: 1,
              legendFormat: '{{handler_name}}@{{instance}}',
              refId: 'A',
            },
          ],
          thresholds: [],
          timeFrom: null,
          timeShift: null,
          title: 'Handler op/s',
          tooltip: {
            shared: true,
            sort: 0,
            value_type: 'individual',
          },
          transparent: false,
          type: 'graph',
          xaxis: {
            buckets: null,
            mode: 'time',
            name: null,
            show: true,
            values: [],
          },
          yaxes: [
            {
              format: 'ops',
              label: null,
              logBase: 1,
              max: null,
              min: null,
              show: true,
            },
            {
              format: 'short',
              label: null,
              logBase: 1,
              max: null,
              min: null,
              show: true,
            },
          ],
          yaxis: {
            align: false,
            alignLevel: null,
          },
        },
        {
          aliasColors: {},
          bars: false,
          dashLength: 10,
          dashes: false,
          datasource: '${DS_PROMETHEUS}',
          fill: 1,
          gridPos: {
            h: 8,
            w: 12,
            x: 12,
            y: 6,
          },
          id: 8,
          legend: {
            avg: false,
            current: false,
            max: false,
            min: false,
            show: true,
            total: false,
            values: false,
          },
          lines: true,
          linewidth: 1,
          links: [],
          nullPointMode: 'null',
          percentage: false,
          pointradius: 5,
          points: false,
          renderer: 'flot',
          seriesOverrides: [],
          spaceLength: 10,
          stack: false,
          steppedLine: false,
          targets: [
            {
              expr:
                'sum(irate(publish_time_seconds_count{instance=~"$node", handler_name=~"$handler", publisher_name=~"$publisher"}[$interval])) by (handler_name, instance, publisher_name)',
              format: 'time_series',
              intervalFactor: 1,
              legendFormat: '{{publisher_name}}@{{instance}}',
              refId: 'A',
            },
          ],
          thresholds: [],
          timeFrom: null,
          timeShift: null,
          title: 'Publish op/s',
          tooltip: {
            shared: true,
            sort: 0,
            value_type: 'individual',
          },
          transparent: false,
          type: 'graph',
          xaxis: {
            buckets: null,
            mode: 'time',
            name: null,
            show: true,
            values: [],
          },
          yaxes: [
            {
              format: 'ops',
              label: null,
              logBase: 1,
              max: null,
              min: null,
              show: true,
            },
            {
              format: 'short',
              label: null,
              logBase: 1,
              max: null,
              min: null,
              show: true,
            },
          ],
          yaxis: {
            align: false,
            alignLevel: null,
          },
        },
        {
          aliasColors: {},
          bars: false,
          dashLength: 10,
          dashes: false,
          datasource: '${DS_PROMETHEUS}',
          fill: 3,
          gridPos: {
            h: 9,
            w: 12,
            x: 0,
            y: 14,
          },
          id: 5,
          legend: {
            alignAsTable: false,
            avg: false,
            current: false,
            max: true,
            min: false,
            rightSide: false,
            show: true,
            total: false,
            values: true,
          },
          lines: true,
          linewidth: 1,
          links: [],
          nullPointMode: 'null',
          percentage: false,
          pointradius: 5,
          points: false,
          renderer: 'flot',
          repeat: null,
          repeatDirection: 'h',
          seriesOverrides: [],
          spaceLength: 10,
          stack: false,
          steppedLine: false,
          targets: [
            {
              expr:
                'histogram_quantile(0.99, sum(rate(handler_execution_time_seconds_bucket{instance=~"$node", handler_name=~"$handler"}[$interval])) by (le))',
              format: 'time_series',
              interval: '',
              intervalFactor: 1,
              legendFormat: 'p99',
              refId: 'A',
            },
            {
              expr:
                'histogram_quantile(0.90, sum(rate(handler_execution_time_seconds_bucket{instance=~"$node", handler_name=~"$handler"}[$interval])) by ( le))',
              format: 'time_series',
              intervalFactor: 1,
              legendFormat: 'p90',
              refId: 'B',
            },
            {
              expr:
                'histogram_quantile(0.50, sum(rate(handler_execution_time_seconds_bucket{instance=~"$node", handler_name=~"$handler"}[$interval])) by (le))',
              format: 'time_series',
              intervalFactor: 1,
              legendFormat: 'p50',
              refId: 'C',
            },
          ],
          thresholds: [],
          timeFrom: null,
          timeShift: null,
          title: 'Handler duration @ $node nodes',
          tooltip: {
            shared: true,
            sort: 0,
            value_type: 'individual',
          },
          transparent: false,
          type: 'graph',
          xaxis: {
            buckets: null,
            mode: 'time',
            name: null,
            show: true,
            values: [],
          },
          yaxes: [
            {
              format: 's',
              label: null,
              logBase: 1,
              max: null,
              min: null,
              show: true,
            },
            {
              format: 'short',
              label: null,
              logBase: 1,
              max: null,
              min: null,
              show: true,
            },
          ],
          yaxis: {
            align: false,
            alignLevel: null,
          },
        },
        {
          aliasColors: {},
          bars: false,
          dashLength: 10,
          dashes: false,
          datasource: '${DS_PROMETHEUS}',
          decimals: 1,
          fill: 3,
          gridPos: {
            h: 9,
            w: 12,
            x: 12,
            y: 14,
          },
          id: 6,
          legend: {
            alignAsTable: false,
            avg: false,
            current: false,
            max: true,
            min: false,
            rightSide: false,
            show: true,
            total: false,
            values: true,
          },
          lines: true,
          linewidth: 1,
          links: [],
          nullPointMode: 'null',
          percentage: false,
          pointradius: 5,
          points: false,
          renderer: 'flot',
          seriesOverrides: [],
          spaceLength: 10,
          stack: false,
          steppedLine: false,
          targets: [
            {
              expr:
                'histogram_quantile(0.99, sum(rate(publish_time_seconds_bucket{instance=~"$node", handler_name=~"$handler", publisher_name=~"$publisher"}[$interval])) by (handler_name, le, publisher_name))',
              format: 'time_series',
              intervalFactor: 1,
              legendFormat: 'p99 {{handler_name}}→{{publisher_name}}',
              refId: 'A',
            },
            {
              expr:
                'histogram_quantile(0.90, sum(rate(publish_time_seconds_bucket{instance=~"$node", handler_name=~"$handler", publisher_name=~"$publisher"}[$interval])) by (handler_name, le, publisher_name))',
              format: 'time_series',
              intervalFactor: 1,
              legendFormat: 'p90 {{handler_name}}→{{publisher_name}}',
              refId: 'B',
            },
            {
              expr:
                'histogram_quantile(0.50, sum(rate(publish_time_seconds_bucket{instance=~"$node", handler_name=~"$handler", publisher_name=~"$publisher"}[$interval])) by (handler_name, le, publisher_name))',
              format: 'time_series',
              intervalFactor: 1,
              legendFormat: 'p50 {{handler_name}}→{{publisher_name}}',
              refId: 'C',
            },
          ],
          thresholds: [],
          timeFrom: null,
          timeShift: null,
          title: 'Publish duration @ $node nodes',
          tooltip: {
            shared: true,
            sort: 0,
            value_type: 'individual',
          },
          transparent: false,
          type: 'graph',
          xaxis: {
            buckets: null,
            mode: 'time',
            name: null,
            show: true,
            values: [],
          },
          yaxes: [
            {
              format: 's',
              label: null,
              logBase: 1,
              max: null,
              min: null,
              show: true,
            },
            {
              format: 'short',
              label: null,
              logBase: 1,
              max: null,
              min: null,
              show: true,
            },
          ],
          yaxis: {
            align: false,
            alignLevel: null,
          },
        },
        {
          aliasColors: {},
          bars: false,
          dashLength: 10,
          dashes: false,
          datasource: '${DS_PROMETHEUS}',
          fill: 1,
          gridPos: {
            h: 8,
            w: 12,
            x: 0,
            y: 23,
          },
          id: 3,
          legend: {
            avg: false,
            current: false,
            max: false,
            min: false,
            show: true,
            total: false,
            values: false,
          },
          lines: true,
          linewidth: 1,
          links: [],
          nullPointMode: 'null',
          percentage: false,
          pointradius: 5,
          points: false,
          renderer: 'flot',
          seriesOverrides: [],
          spaceLength: 10,
          stack: false,
          steppedLine: false,
          targets: [
            {
              expr:
                'sum(irate(handler_execution_time_seconds_count{instance=~"$node", handler_name=~"$handler", success="false"}[$interval])) by (handler_name, instance)',
              format: 'time_series',
              intervalFactor: 1,
              legendFormat: '{{handler_name}}@{{instance}}',
              refId: 'A',
            },
          ],
          thresholds: [],
          timeFrom: null,
          timeShift: null,
          title: 'Handler failed op/s',
          tooltip: {
            shared: true,
            sort: 0,
            value_type: 'individual',
          },
          transparent: false,
          type: 'graph',
          xaxis: {
            buckets: null,
            mode: 'time',
            name: null,
            show: true,
            values: [],
          },
          yaxes: [
            {
              format: 'ops',
              label: null,
              logBase: 1,
              max: null,
              min: null,
              show: true,
            },
            {
              format: 'short',
              label: null,
              logBase: 1,
              max: null,
              min: null,
              show: true,
            },
          ],
          yaxis: {
            align: false,
            alignLevel: null,
          },
        },
        {
          aliasColors: {},
          bars: false,
          dashLength: 10,
          dashes: false,
          datasource: '${DS_PROMETHEUS}',
          fill: 1,
          gridPos: {
            h: 8,
            w: 12,
            x: 12,
            y: 23,
          },
          id: 7,
          legend: {
            avg: false,
            current: false,
            max: false,
            min: false,
            show: true,
            total: false,
            values: false,
          },
          lines: true,
          linewidth: 1,
          links: [],
          nullPointMode: 'null',
          percentage: false,
          pointradius: 5,
          points: false,
          renderer: 'flot',
          seriesOverrides: [],
          spaceLength: 10,
          stack: false,
          steppedLine: false,
          targets: [
            {
              expr:
                'sum(irate(publish_time_seconds_count{instance=~"$node", handler_name=~"$handler", success="false", publisher_name=~"$publisher"}[$interval])) by (handler_name, instance)',
              format: 'time_series',
              intervalFactor: 1,
              legendFormat: '{{handler_name}}@{{instance}}',
              refId: 'A',
            },
          ],
          thresholds: [],
          timeFrom: null,
          timeShift: null,
          title: 'Publish failed op/s',
          tooltip: {
            shared: true,
            sort: 0,
            value_type: 'individual',
          },
          transparent: false,
          type: 'graph',
          xaxis: {
            buckets: null,
            mode: 'time',
            name: null,
            show: true,
            values: [],
          },
          yaxes: [
            {
              format: 'ops',
              label: null,
              logBase: 1,
              max: null,
              min: null,
              show: true,
            },
            {
              format: 'short',
              label: null,
              logBase: 1,
              max: null,
              min: '0',
              show: true,
            },
          ],
          yaxis: {
            align: false,
            alignLevel: null,
          },
        },
      ],
      refresh: '5s',
      schemaVersion: 16,
      style: 'dark',
      tags: ['go', 'golang', 'cqrs', 'kafka', 'event-driven'],
      templating: {
        list: [
          {
            auto: false,
            auto_count: 30,
            auto_min: '15s',
            current: {
              text: '1m',
              value: '1m',
            },
            hide: 0,
            label: null,
            name: 'interval',
            options: [
              {
                selected: false,
                text: '15s',
                value: '15s',
              },
              {
                selected: false,
                text: '30s',
                value: '30s',
              },
              {
                selected: true,
                text: '1m',
                value: '1m',
              },
              {
                selected: false,
                text: '10m',
                value: '10m',
              },
              {
                selected: false,
                text: '30m',
                value: '30m',
              },
              {
                selected: false,
                text: '1h',
                value: '1h',
              },
              {
                selected: false,
                text: '6h',
                value: '6h',
              },
              {
                selected: false,
                text: '12h',
                value: '12h',
              },
              {
                selected: false,
                text: '1d',
                value: '1d',
              },
            ],
            query: '15s, 30s, 1m,10m,30m,1h,6h,12h,1d',
            refresh: 2,
            type: 'interval',
          },
          {
            allValue: '',
            current: {},
            datasource: '${DS_PROMETHEUS}',
            hide: 0,
            includeAll: true,
            label: null,
            multi: true,
            name: 'node',
            options: [],
            query: 'label_values(instance)',
            refresh: 2,
            regex: '',
            sort: 5,
            tagValuesQuery: '',
            tags: [],
            tagsQuery: '',
            type: 'query',
            useTags: false,
          },
          {
            allValue: null,
            current: {},
            datasource: '${DS_PROMETHEUS}',
            hide: 0,
            includeAll: true,
            label: 'handler',
            multi: true,
            name: 'handler',
            options: [],
            query: 'label_values(handler_name)',
            refresh: 2,
            regex: '',
            sort: 5,
            tagValuesQuery: '',
            tags: [],
            tagsQuery: '',
            type: 'query',
            useTags: false,
          },
          {
            allValue: null,
            current: {},
            datasource: '${DS_PROMETHEUS}',
            hide: 0,
            includeAll: true,
            label: null,
            multi: true,
            name: 'publisher',
            options: [],
            query: 'label_values(publisher_name)',
            refresh: 1,
            regex: '',
            sort: 0,
            tagValuesQuery: '',
            tags: [],
            tagsQuery: '',
            type: 'query',
            useTags: false,
          },
        ],
      },
      time: {
        from: 'now-15m',
        to: 'now',
      },
      timepicker: {
        refresh_intervals: ['5s', '10s', '30s', '1m', '5m', '15m', '30m', '1h', '2h', '1d'],
        time_options: ['5m', '15m', '1h', '6h', '12h', '24h', '2d', '7d', '30d'],
      },
      timezone: '',
      title: '1.0 Watermill',
      uid: 'kAO_4xlmk',
      version: 1,
    },
  },
  gcomError: '',
};

const importDashboardSlice = createSlice({
  name: 'manageDashboards',
  initialState: initialImportDashboardState,
  reducers: {
    setGcomDashboard: (state, action: PayloadAction<any>): ImportDashboardState => {
      return {
        ...state,
        dashboard: action.payload,
      };
    },
    setGcomError: (state, action: PayloadAction<string>): ImportDashboardState => ({
      ...state,
      gcomError: action.payload,
    }),
  },
});

export const { setGcomDashboard, setGcomError } = importDashboardSlice.actions;

export const importDashboardReducer = importDashboardSlice.reducer;

export default {
  importDashboard: importDashboardReducer,
};
