export const alignOptions = [
  { text: 'none', value: 'ALIGN_NONE' },
  { text: 'delta', value: 'ALIGN_DELTA' },
  { text: 'rate', value: 'ALIGN_RATE' },
  { text: 'interpolate', value: 'ALIGN_INTERPOLATE' },
  { text: 'next older', value: 'ALIGN_NEXT_OLDER' },
  { text: 'min', value: 'ALIGN_MIN' },
  { text: 'max', value: 'ALIGN_MAX' },
  { text: 'mean', value: 'ALIGN_MEAN' },
  { text: 'count', value: 'ALIGN_COUNT' },
  { text: 'sum', value: 'ALIGN_SUM' },
  { text: 'stddev', value: 'ALIGN_STDDEV' },
  { text: 'count true', value: 'ALIGN_COUNT_TRUE' },
  { text: 'count false', value: 'ALIGN_COUNT_FALSE' },
  { text: 'fraction true', value: 'ALIGN_FRACTION_TRUE' },
  { text: 'percentile 99', value: 'ALIGN_PERCENTILE_99' },
  { text: 'percentile 95', value: 'ALIGN_PERCENTILE_95' },
  { text: 'percentile 50', value: 'ALIGN_PERCENTILE_50' },
  { text: 'percentile 05', value: 'ALIGN_PERCENTILE_05' },
  { text: 'percent change', value: 'ALIGN_PERCENT_CHANGE' },
];

export const aggOptions = [
  { text: 'none', value: 'REDUCE_NONE' },
  { text: 'mean', value: 'REDUCE_MEAN' },
  { text: 'min', value: 'REDUCE_MIN' },
  { text: 'max', value: 'REDUCE_MAX' },
  { text: 'sum', value: 'REDUCE_SUM' },
  { text: 'std. dev.', value: 'REDUCE_STDDEV' },
  { text: 'count', value: 'REDUCE_COUNT' },
  { text: '99th percentile', value: 'REDUCE_PERCENTILE_99' },
  { text: '95th percentile', value: 'REDUCE_PERCENTILE_95' },
  { text: '50th percentile', value: 'REDUCE_PERCENTILE_50' },
  { text: '5th percentile', value: 'REDUCE_PERCENTILE_05' },
];

export const alignmentPeriods = [
  { text: 'auto', value: 'auto' },
  { text: '1m', value: '+60s' },
  { text: '5m', value: '+300s' },
  { text: '30m', value: '+1800s' },
  { text: '1h', value: '+3600s' },
  { text: '6h', value: '+21600s' },
  { text: '1d', value: '+86400s' },
  { text: '1w', value: '+604800s' },
  { text: '1m', value: '+18748800s' },
];
