// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     public/app/plugins/gen.go
// Using jennies:
//     TSTypesJenny
//     PluginTsTypesJenny
//
// Run 'make gen-cue' from repository root to regenerate.

// Generated from public/app/plugins/panel/logstable/panelcfg.cue file.

export interface Options {
  buildLinkToLogLine?: unknown;
  displayedFields?: Array<string>;
  fieldSelectorWidth?: number;
  setDisplayedFields?: unknown;
  showCopyLogLink?: boolean;
  showInspectLogLine?: boolean;
}

export const defaultOptions: Partial<Options> = {
  displayedFields: [],
  showCopyLogLink: false,
  showInspectLogLine: true,
};
