// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     public/app/plugins/gen.go
// Using jennies:
//     TSTypesJenny
//     LatestMajorsOrXJenny
//
// Run 'make gen-cue' from repository root to regenerate.

export type PhlareQueryType = ('metrics' | 'profile' | 'both');

export const defaultPhlareQueryType: PhlareQueryType = 'both';

export interface PhlareDataQuery extends common.DataQuery {
  /**
   * Allows to group the results.
   */
  groupBy: Array<string>;
  /**
   * Specifies the query label selectors.
   */
  labelSelector: string;
  /**
   * Specifies the type of profile to query.
   */
  profileTypeId: string;
}

export const defaultPhlareDataQuery: Partial<PhlareDataQuery> = {
  groupBy: [],
  labelSelector: '{}',
};
