import { createTheme } from './createTheme';

describe('createTheme', () => {
  it('create default theme', () => {
    const theme = createTheme();
    expect(theme).toMatchInlineSnapshot(`
      Object {
        "breakpoints": Object {
          "down": [Function],
          "keys": Array [
            "xs",
            "sm",
            "md",
            "lg",
            "xl",
            "xxl",
          ],
          "unit": "px",
          "up": [Function],
          "values": Object {
            "lg": 992,
            "md": 769,
            "sm": 544,
            "xl": 1200,
            "xs": 0,
            "xxl": 1440,
          },
        },
        "components": Object {
          "height": Object {
            "lg": 6,
            "md": 4,
            "sm": 3,
          },
          "panel": Object {
            "headerHeight": 4,
            "padding": 1,
          },
        },
        "isDark": true,
        "isLight": false,
        "name": "Dark",
        "palette": Object {
          "action": Object {
            "focus": "rgba(255, 255, 255, 0.12)",
            "hover": "rgba(255, 255, 255, 0.08)",
            "hoverOpacity": 0.08,
            "selected": "rgba(255, 255, 255, 0.16)",
          },
          "border0": "#202226",
          "border1": "#2c3235",
          "border2": "#464c54",
          "contrastThreshold": 3,
          "error": Object {
            "contrastText": "#fff",
            "main": "#D10E5C",
            "name": "error",
            "shade": "rgb(215, 50, 116)",
            "text": "#FF5286",
          },
          "formComponent": Object {
            "background": "#0b0c0e",
            "border": "#2c3235",
            "disabledBackground": "rgba(255,255,255,0.07)",
            "disabledText": "rgba(255, 255, 255, 0.35)",
            "text": "rgba(255, 255, 255, 0.75)",
          },
          "getContrastText": [Function],
          "getHoverColor": [Function],
          "hoverFactor": 0.03,
          "info": Object {
            "contrastText": "#fff",
            "main": "#3658E2",
            "name": "info",
            "shade": "rgb(84, 113, 230)",
            "text": "#5B93FF",
          },
          "layer0": "#0b0c0e",
          "layer1": "#141619",
          "layer2": "#202226",
          "mode": "dark",
          "primary": Object {
            "contrastText": "#fff",
            "main": "#3658E2",
            "name": "primary",
            "shade": "rgb(84, 113, 230)",
            "text": "#5B93FF",
          },
          "secondary": Object {
            "contrastText": "rgba(255, 255, 255, 0.8)",
            "main": "rgba(255,255,255,0.1)",
            "name": "secondary",
            "shade": "rgba(255,255,255,0.15)",
            "text": "rgba(255,255,255,0.13)",
          },
          "success": Object {
            "contrastText": "#fff",
            "main": "#13875D",
            "name": "success",
            "shade": "rgb(54, 153, 117)",
            "text": "#6CCF8E",
          },
          "text": Object {
            "disabled": "rgba(255, 255, 255, 0.35)",
            "link": "#5B93FF",
            "maxContrast": "#fff",
            "primary": "rgba(255, 255, 255, 0.75)",
            "secondary": "rgba(255, 255, 255, 0.50)",
          },
          "tonalOffset": 0.15,
          "warning": Object {
            "contrastText": "#000",
            "main": "#eb7b18",
            "name": "warning",
            "shade": "rgb(238, 142, 58)",
            "text": "#eb7b18",
          },
        },
        "shadows": Object {
          "z1": "0px 3px 1px -2px rgba(0,0,0,0.5),0px 2px 2px 0px rgba(0,0,0,0.4),0px 1px 5px 0px rgba(0,0,0,0.3)",
          "z2": "0px 2px 4px -1px rgba(0,0,0,0.5),0px 4px 5px 0px rgba(0,0,0,0.4),0px 1px 10px 0px rgba(0,0,0,0.3)",
          "z3": "0px 5px 5px -3px rgba(0,0,0,0.5),0px 8px 10px 1px rgba(0,0,0,0.4),0px 3px 14px 2px rgba(0,0,0,0.3)",
        },
        "shape": Object {
          "borderRadius": [Function],
        },
        "spacing": [Function],
        "transitions": Object {
          "create": [Function],
          "duration": Object {
            "complex": 375,
            "enteringScreen": 225,
            "leavingScreen": 195,
            "short": 250,
            "shorter": 200,
            "shortest": 150,
            "standard": 300,
          },
          "easing": Object {
            "easeIn": "cubic-bezier(0.4, 0, 1, 1)",
            "easeInOut": "cubic-bezier(0.4, 0, 0.2, 1)",
            "easeOut": "cubic-bezier(0.0, 0, 0.2, 1)",
            "sharp": "cubic-bezier(0.4, 0, 0.6, 1)",
          },
          "getAutoHeightDuration": [Function],
        },
        "typography": Object {
          "body": Object {
            "fontFamily": "\\"Roboto\\", \\"Helvetica\\", \\"Arial\\", sans-serif",
            "fontSize": "1rem",
            "fontWeight": 400,
            "letterSpacing": "0.01071em",
            "lineHeight": 1.5,
          },
          "fontFamily": "\\"Roboto\\", \\"Helvetica\\", \\"Arial\\", sans-serif",
          "fontFamilyMonospace": "Menlo, Monaco, Consolas, 'Courier New', monospace",
          "fontSize": 14,
          "fontWeightBold": 700,
          "fontWeightLight": 300,
          "fontWeightMedium": 500,
          "fontWeightRegular": 400,
          "h1": Object {
            "fontFamily": "\\"Roboto\\", \\"Helvetica\\", \\"Arial\\", sans-serif",
            "fontSize": "2rem",
            "fontWeight": 300,
            "letterSpacing": "-0.05357em",
            "lineHeight": 1.167,
          },
          "h2": Object {
            "fontFamily": "\\"Roboto\\", \\"Helvetica\\", \\"Arial\\", sans-serif",
            "fontSize": "1.7142857142857142rem",
            "fontWeight": 300,
            "letterSpacing": "-0.02083em",
            "lineHeight": 1.2,
          },
          "h3": Object {
            "fontFamily": "\\"Roboto\\", \\"Helvetica\\", \\"Arial\\", sans-serif",
            "fontSize": "1.5rem",
            "fontWeight": 400,
            "letterSpacing": "0em",
            "lineHeight": 1.167,
          },
          "h4": Object {
            "fontFamily": "\\"Roboto\\", \\"Helvetica\\", \\"Arial\\", sans-serif",
            "fontSize": "1.2857142857142858rem",
            "fontWeight": 400,
            "letterSpacing": "0.01389em",
            "lineHeight": 1.235,
          },
          "h5": Object {
            "fontFamily": "\\"Roboto\\", \\"Helvetica\\", \\"Arial\\", sans-serif",
            "fontSize": "1.1428571428571428rem",
            "fontWeight": 400,
            "letterSpacing": "0em",
            "lineHeight": 1.334,
          },
          "h6": Object {
            "fontFamily": "\\"Roboto\\", \\"Helvetica\\", \\"Arial\\", sans-serif",
            "fontSize": "1rem",
            "fontWeight": 500,
            "letterSpacing": "0.01071em",
            "lineHeight": 1.6,
          },
          "htmlFontSize": 14,
          "pxToRem": [Function],
          "size": Object {
            "base": "14px",
            "lg": "18px",
            "md": "14px",
            "sm": "12px",
            "xs": "10px",
          },
        },
        "zIndex": Object {
          "dropdown": 1030,
          "modal": 1060,
          "modalBackdrop": 1050,
          "navbarFixed": 1000,
          "sidemenu": 1020,
          "tooltip": 1040,
          "typeahead": 1030,
        },
      }
    `);
  });
});
