import { NewThemeOptions } from './createTheme';

export function getDarkTheme(): NewThemeOptions {
  return {
    name: 'Dark',
    colors: {
      mode: 'dark',
      border: {
        weak: 'rgba(204, 204, 220, 0.12)',
        medium: 'rgba(204, 204, 220, 0.20)',
        strong: 'rgba(204, 204, 220, 0.30)',
      },
      text: {
        primary: 'rgb(204, 204, 220)',
        secondary: 'rgba(204, 204, 220, 0.65)',
        disabled: 'rgba(204, 204, 220, 0.6)',
        link: '#6E9FFF',
        maxContrast: '#FFFFFF',
      },
      primary: {
        main: '#3D71D9',
        text: '#6E9FFF',
        border: '#6E9FFF',
        name: 'primary',
        shade: 'rgb(90, 134, 222)',
        transparent: '#3D71D926',
        contrastText: '#FFFFFF',
        borderTransparent: '#6E9FFF40',
      },
      secondary: {
        main: 'rgba(204, 204, 220, 0.10)',
        shade: 'rgba(204, 204, 220, 0.14)',
        transparent: 'rgba(204, 204, 220, 0.08)',
        text: 'rgb(204, 204, 220)',
        contrastText: 'rgb(204, 204, 220)',
        border: 'rgba(204, 204, 220, 0.08)',
        name: 'secondary',
        borderTransparent: 'rgba(204, 204, 220, 0.25)',
      },
      info: {
        main: '#3D71D9',
        text: '#6E9FFF',
        border: '#6E9FFF',
        name: 'info',
        shade: 'rgb(90, 134, 222)',
        transparent: '#3D71D926',
        contrastText: '#FFFFFF',
        borderTransparent: '#6E9FFF40',
      },
      error: {
        main: '#D10E5C',
        text: '#FF5286',
        name: 'error',
        border: '#FF5286',
        shade: 'rgb(215, 50, 116)',
        transparent: '#D10E5C26',
        contrastText: '#FFFFFF',
        borderTransparent: '#FF528640',
      },
      success: {
        main: '#1A7F4B',
        text: '#6CCF8E',
        name: 'success',
        border: '#6CCF8E',
        shade: 'rgb(60, 146, 102)',
        transparent: '#1A7F4B26',
        contrastText: '#FFFFFF',
        borderTransparent: '#6CCF8E40',
      },
      warning: {
        main: '#FF9900',
        text: '#fbad37',
        name: 'warning',
        border: '#fbad37',
        shade: 'rgb(255, 168, 38)',
        transparent: '#FF990026',
        contrastText: '#000000',
        borderTransparent: '#fbad3740',
      },
      background: {
        canvas: '#111217',
        primary: '#181b1f',
        secondary: '#22252b',
      },
      action: {
        hover: 'rgba(204, 204, 220, 0.16)',
        selected: 'rgba(204, 204, 220, 0.12)',
        selectedBorder: '#FF9900',
        focus: 'rgba(204, 204, 220, 0.16)',
        hoverOpacity: 0.08,
        disabledText: 'rgba(204, 204, 220, 0.6)',
        disabledBackground: 'rgba(204, 204, 220, 0.04)',
        disabledOpacity: 0.38,
      },
      gradients: {
        brandHorizontal: 'linear-gradient(270deg, #F55F3E 0%, #FF8833 100%)',
        brandVertical: 'linear-gradient(0.01deg, #F55F3E 0.01%, #FF8833 99.99%)',
      },
      contrastThreshold: 3,
      hoverFactor: 0.03,
      tonalOffset: 0.15,
    },
    breakpoints: {
      values: {
        xs: 0,
        sm: 544,
        md: 769,
        lg: 992,
        xl: 1200,
        xxl: 1440,
      },
      keys: ['xs', 'sm', 'md', 'lg', 'xl', 'xxl'],
      unit: 'px',
    },
    shape: {
      radius: {
        default: '2px',
        pill: '9999px',
        circle: '100%',
      },
    },
    typography: {
      htmlFontSize: 14,
      fontFamily: '"Inter", "Helvetica", "Arial", sans-serif',
      fontFamilyMonospace: "'Roboto Mono', monospace",
      fontSize: 14,
      fontWeightLight: 300,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 500,
      h1: {
        fontFamily: '"Inter", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: '2rem',
        lineHeight: 1.1428571428571428,
        letterSpacing: '-0.00893em',
      },
      h2: {
        fontFamily: '"Inter", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: '1.7142857142857142rem',
        lineHeight: 1.1666666666666667,
        letterSpacing: '0em',
      },
      h3: {
        fontFamily: '"Inter", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: '1.5714285714285714rem',
        lineHeight: 1.0909090909090908,
        letterSpacing: '0em',
      },
      h4: {
        fontFamily: '"Inter", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: '1.2857142857142858rem',
        lineHeight: 1.2222222222222223,
        letterSpacing: '0.01389em',
      },
      h5: {
        fontFamily: '"Inter", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: '1.1428571428571428rem',
        lineHeight: 1.375,
        letterSpacing: '0em',
      },
      h6: {
        fontFamily: '"Inter", "Helvetica", "Arial", sans-serif',
        fontWeight: 500,
        fontSize: '1rem',
        lineHeight: 1.5714285714285714,
        letterSpacing: '0.01071em',
      },
      body: {
        fontFamily: '"Inter", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: '1rem',
        lineHeight: 1.5714285714285714,
        letterSpacing: '0.01071em',
      },
      bodySmall: {
        fontFamily: '"Inter", "Helvetica", "Arial", sans-serif',
        fontWeight: 400,
        fontSize: '0.8571428571428571rem',
        lineHeight: 1.5,
        letterSpacing: '0.0125em',
      },
      code: {
        fontFamily: "'Roboto Mono', monospace",
        fontWeight: 400,
        fontSize: '1rem',
        lineHeight: 1.1428571428571428,
        letterSpacing: '0.01071em',
      },
    },
    shadows: {
      z1: '0px 1px 2px rgba(1, 4, 9, 0.75)',
      z2: '0px 4px 8px rgba(1, 4, 9, 0.75)',
      z3: '0px 8px 24px rgb(1, 4, 9)',
    },
    transitions: {
      duration: {
        shortest: 150,
        shorter: 200,
        short: 250,
        standard: 300,
        complex: 375,
        enteringScreen: 225,
        leavingScreen: 195,
      },
      easing: {
        easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
        easeOut: 'cubic-bezier(0.0, 0, 0.2, 1)',
        easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
        sharp: 'cubic-bezier(0.4, 0, 0.6, 1)',
      },
    },
    visualization: {
      hues: [
        {
          name: 'red',
          shades: [
            {
              color: '#FFA6B0',
              name: 'super-light-red',
            },
            {
              color: '#FF7383',
              name: 'light-red',
            },
            {
              color: '#F2495C',
              name: 'red',
              primary: true,
            },
            {
              color: '#E02F44',
              name: 'semi-dark-red',
            },
            {
              color: '#C4162A',
              name: 'dark-red',
            },
          ],
        },
        {
          name: 'orange',
          shades: [
            {
              color: '#FFCB7D',
              name: 'super-light-orange',
              aliases: [],
            },
            {
              color: '#FFB357',
              name: 'light-orange',
              aliases: [],
            },
            {
              color: '#FF9830',
              name: 'orange',
              aliases: [],
              primary: true,
            },
            {
              color: '#FF780A',
              name: 'semi-dark-orange',
              aliases: [],
            },
            {
              color: '#FA6400',
              name: 'dark-orange',
              aliases: [],
            },
          ],
        },
        {
          name: 'yellow',
          shades: [
            {
              color: '#FFF899',
              name: 'super-light-yellow',
              aliases: [],
            },
            {
              color: '#FFEE52',
              name: 'light-yellow',
              aliases: [],
            },
            {
              color: '#FADE2A',
              name: 'yellow',
              aliases: [],
              primary: true,
            },
            {
              color: '#F2CC0C',
              name: 'semi-dark-yellow',
              aliases: [],
            },
            {
              color: '#E0B400',
              name: 'dark-yellow',
              aliases: [],
            },
          ],
        },
        {
          name: 'green',
          shades: [
            {
              color: '#C8F2C2',
              name: 'super-light-green',
              aliases: [],
            },
            {
              color: '#96D98D',
              name: 'light-green',
              aliases: [],
            },
            {
              color: '#73BF69',
              name: 'green',
              aliases: [],
              primary: true,
            },
            {
              color: '#56A64B',
              name: 'semi-dark-green',
              aliases: [],
            },
            {
              color: '#37872D',
              name: 'dark-green',
              aliases: [],
            },
          ],
        },
        {
          name: 'blue',
          shades: [
            {
              color: '#C0D8FF',
              name: 'super-light-blue',
              aliases: [],
            },
            {
              color: '#8AB8FF',
              name: 'light-blue',
              aliases: [],
            },
            {
              color: '#5794F2',
              name: 'blue',
              aliases: [],
              primary: true,
            },
            {
              color: '#3274D9',
              name: 'semi-dark-blue',
              aliases: [],
            },
            {
              color: '#1F60C4',
              name: 'dark-blue',
              aliases: [],
            },
          ],
        },
        {
          name: 'purple',
          shades: [
            {
              color: '#DEB6F2',
              name: 'super-light-purple',
              aliases: [],
            },
            {
              color: '#CA95E5',
              name: 'light-purple',
              aliases: [],
            },
            {
              color: '#B877D9',
              name: 'purple',
              aliases: [],
              primary: true,
            },
            {
              color: '#A352CC',
              name: 'semi-dark-purple',
              aliases: [],
            },
            {
              color: '#8F3BB8',
              name: 'dark-purple',
              aliases: [],
            },
          ],
        },
      ],
      palette: [
        'green',
        'semi-dark-yellow',
        'light-blue',
        'semi-dark-orange',
        'red',
        'blue',
        'purple',
        '#705DA0',
        'dark-green',
        'yellow',
        '#447EBC',
        '#C15C17',
        '#890F02',
        '#0A437C',
        '#6D1F62',
        '#584477',
        '#B7DBAB',
        '#F4D598',
        '#70DBED',
        '#F9BA8F',
        '#F29191',
        '#82B5D8',
        '#E5A8E2',
        '#AEA2E0',
        '#629E51',
        '#E5AC0E',
        '#64B0C8',
        '#E0752D',
        '#BF1B00',
        '#0A50A1',
        '#962D82',
        '#614D93',
        '#9AC48A',
        '#F2C96D',
        '#65C5DB',
        '#F9934E',
        '#EA6460',
        '#5195CE',
        '#D683CE',
        '#806EB7',
        '#3F6833',
        '#967302',
        '#2F575E',
        '#99440A',
        '#58140C',
        '#052B51',
        '#511749',
        '#3F2B5B',
        '#E0F9D7',
        '#FCEACA',
        '#CFFAFF',
        '#F9E2D2',
        '#FCE2DE',
        '#BADFF4',
        '#F9D9F9',
        '#DEDAF7',
      ],
    },
    zIndex: {
      activePanel: 999,
      navbarFixed: 1000,
      sidemenu: 1020,
      dropdown: 1030,
      typeahead: 1030,
      tooltip: 1040,
      modalBackdrop: 1050,
      modal: 1060,
      portal: 1061,
    },
  };
}
