[common]
logfile = ""
logLevel = "info"
maxCPU = 1
graphPrefix = "carbon.agents.{host}"
metricEndpoint = ""
metricInterval = "1m0s"

[whisper]
data-dir = "/var/lib/graphite/whisper"
schemas-file = "/etc/go-carbon/storage-schemas.conf"
aggregation-file = ""
workers = 1
max-updates-per-second = 0
max-creates-per-second = 0
sparse-create = false
enabled = true

[cache]
max-size = 1000000
write-strategy = "max"

[udp]
listen = ":2003"
enabled = false
log-incomplete = false

[tcp]
listen = ":2003"
enabled = true

[pickle]
listen = ":2004"
enabled = true
max-message-size = 67108864

[carbonserver]
listen = ":8080"
enabled = false

[dump]
enabled = false

[pprof]
listen = "localhost:7007"
enabled = false
