// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     GoTypesJenny
//     LatestJenny
//
// Run 'make gen-cue' from repository root to regenerate.

package preferences

// QueryHistoryPreference defines model for QueryHistoryPreference.
type QueryHistoryPreference struct {
	// one of: '' | 'query' | 'starred';
	HomeTab *string `json:"homeTab,omitempty"`
}

// Preferences defines model for preferences.
type Preferences struct {
	// UID for the home dashboard
	HomeDashboardUID *string `json:"homeDashboardUID,omitempty"`

	// Selected language (beta)
	Language     *string                 `json:"language,omitempty"`
	QueryHistory *QueryHistoryPreference `json:"queryHistory,omitempty"`

	// light, dark, empty is default
	Theme *string `json:"theme,omitempty"`

	// The timezone selection
	Timezone *string `json:"timezone,omitempty"`

	// day of the week (sunday, monday, etc)
	WeekStart *string `json:"weekStart,omitempty"`
}
