#!/bin/sh

# Ignore husky hooks if no frontend code has been changed
git diff --cached --name-only | grep -v --quiet "^pkg/" || exit 0

echo "\n\e[1mImportant:\e[0m Precommit hooks are now opt-in. Precommit hooks *will not run* for this commit, and it will succeed even if you have lint errors."
echo "Run \e[32mmake lefthook-install\e[0m to install precommit hooks for the future."
echo "See https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md#configure-precommit-hooks for more info\n"

