// Code generated by mockery v2.53.4. DO NOT EDIT.

package repository

import (
	context "context"
	http "net/http"

	v0alpha1 "github.com/grafana/grafana/apps/provisioning/pkg/apis/provisioning/v0alpha1"
	mock "github.com/stretchr/testify/mock"
)

// MockWebhookRepository is an autogenerated mock type for the WebhookRepository type
type MockWebhookRepository struct {
	mock.Mock
}

type MockWebhookRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebhookRepository) EXPECT() *MockWebhookRepository_Expecter {
	return &MockWebhookRepository_Expecter{mock: &_m.Mock}
}

// Config provides a mock function with no fields
func (_m *MockWebhookRepository) Config() *v0alpha1.Repository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *v0alpha1.Repository
	if rf, ok := ret.Get(0).(func() *v0alpha1.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v0alpha1.Repository)
		}
	}

	return r0
}

// MockWebhookRepository_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockWebhookRepository_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockWebhookRepository_Expecter) Config() *MockWebhookRepository_Config_Call {
	return &MockWebhookRepository_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockWebhookRepository_Config_Call) Run(run func()) *MockWebhookRepository_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebhookRepository_Config_Call) Return(_a0 *v0alpha1.Repository) *MockWebhookRepository_Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookRepository_Config_Call) RunAndReturn(run func() *v0alpha1.Repository) *MockWebhookRepository_Config_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessRequest provides a mock function with given fields: ctx, req
func (_m *MockWebhookRepository) ProcessRequest(ctx context.Context, req *VerifiedWebhookRequest) (WebhookEvent, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ProcessRequest")
	}

	var r0 WebhookEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *VerifiedWebhookRequest) (WebhookEvent, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *VerifiedWebhookRequest) WebhookEvent); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(WebhookEvent)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *VerifiedWebhookRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebhookRepository_ProcessRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessRequest'
type MockWebhookRepository_ProcessRequest_Call struct {
	*mock.Call
}

// ProcessRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req *VerifiedWebhookRequest
func (_e *MockWebhookRepository_Expecter) ProcessRequest(ctx interface{}, req interface{}) *MockWebhookRepository_ProcessRequest_Call {
	return &MockWebhookRepository_ProcessRequest_Call{Call: _e.mock.On("ProcessRequest", ctx, req)}
}

func (_c *MockWebhookRepository_ProcessRequest_Call) Run(run func(ctx context.Context, req *VerifiedWebhookRequest)) *MockWebhookRepository_ProcessRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*VerifiedWebhookRequest))
	})
	return _c
}

func (_c *MockWebhookRepository_ProcessRequest_Call) Return(_a0 WebhookEvent, _a1 error) *MockWebhookRepository_ProcessRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebhookRepository_ProcessRequest_Call) RunAndReturn(run func(context.Context, *VerifiedWebhookRequest) (WebhookEvent, error)) *MockWebhookRepository_ProcessRequest_Call {
	_c.Call.Return(run)
	return _c
}

// Slug provides a mock function with no fields
func (_m *MockWebhookRepository) Slug() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Slug")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockWebhookRepository_Slug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Slug'
type MockWebhookRepository_Slug_Call struct {
	*mock.Call
}

// Slug is a helper method to define mock.On call
func (_e *MockWebhookRepository_Expecter) Slug() *MockWebhookRepository_Slug_Call {
	return &MockWebhookRepository_Slug_Call{Call: _e.mock.On("Slug")}
}

func (_c *MockWebhookRepository_Slug_Call) Run(run func()) *MockWebhookRepository_Slug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebhookRepository_Slug_Call) Return(_a0 string) *MockWebhookRepository_Slug_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookRepository_Slug_Call) RunAndReturn(run func() string) *MockWebhookRepository_Slug_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribedEvents provides a mock function with no fields
func (_m *MockWebhookRepository) SubscribedEvents() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SubscribedEvents")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockWebhookRepository_SubscribedEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribedEvents'
type MockWebhookRepository_SubscribedEvents_Call struct {
	*mock.Call
}

// SubscribedEvents is a helper method to define mock.On call
func (_e *MockWebhookRepository_Expecter) SubscribedEvents() *MockWebhookRepository_SubscribedEvents_Call {
	return &MockWebhookRepository_SubscribedEvents_Call{Call: _e.mock.On("SubscribedEvents")}
}

func (_c *MockWebhookRepository_SubscribedEvents_Call) Run(run func()) *MockWebhookRepository_SubscribedEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebhookRepository_SubscribedEvents_Call) Return(_a0 []string) *MockWebhookRepository_SubscribedEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookRepository_SubscribedEvents_Call) RunAndReturn(run func() []string) *MockWebhookRepository_SubscribedEvents_Call {
	_c.Call.Return(run)
	return _c
}

// Test provides a mock function with given fields: ctx
func (_m *MockWebhookRepository) Test(ctx context.Context) (*v0alpha1.TestResults, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Test")
	}

	var r0 *v0alpha1.TestResults
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*v0alpha1.TestResults, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *v0alpha1.TestResults); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v0alpha1.TestResults)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebhookRepository_Test_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Test'
type MockWebhookRepository_Test_Call struct {
	*mock.Call
}

// Test is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWebhookRepository_Expecter) Test(ctx interface{}) *MockWebhookRepository_Test_Call {
	return &MockWebhookRepository_Test_Call{Call: _e.mock.On("Test", ctx)}
}

func (_c *MockWebhookRepository_Test_Call) Run(run func(ctx context.Context)) *MockWebhookRepository_Test_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWebhookRepository_Test_Call) Return(_a0 *v0alpha1.TestResults, _a1 error) *MockWebhookRepository_Test_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebhookRepository_Test_Call) RunAndReturn(run func(context.Context) (*v0alpha1.TestResults, error)) *MockWebhookRepository_Test_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyRequest provides a mock function with given fields: req
func (_m *MockWebhookRepository) VerifyRequest(req *http.Request) (*VerifiedWebhookRequest, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for VerifyRequest")
	}

	var r0 *VerifiedWebhookRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (*VerifiedWebhookRequest, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) *VerifiedWebhookRequest); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VerifiedWebhookRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebhookRepository_VerifyRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyRequest'
type MockWebhookRepository_VerifyRequest_Call struct {
	*mock.Call
}

// VerifyRequest is a helper method to define mock.On call
//   - req *http.Request
func (_e *MockWebhookRepository_Expecter) VerifyRequest(req interface{}) *MockWebhookRepository_VerifyRequest_Call {
	return &MockWebhookRepository_VerifyRequest_Call{Call: _e.mock.On("VerifyRequest", req)}
}

func (_c *MockWebhookRepository_VerifyRequest_Call) Run(run func(req *http.Request)) *MockWebhookRepository_VerifyRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *MockWebhookRepository_VerifyRequest_Call) Return(_a0 *VerifiedWebhookRequest, _a1 error) *MockWebhookRepository_VerifyRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebhookRepository_VerifyRequest_Call) RunAndReturn(run func(*http.Request) (*VerifiedWebhookRequest, error)) *MockWebhookRepository_VerifyRequest_Call {
	_c.Call.Return(run)
	return _c
}

// WebhookClient provides a mock function with no fields
func (_m *MockWebhookRepository) WebhookClient() WebhookClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WebhookClient")
	}

	var r0 WebhookClient
	if rf, ok := ret.Get(0).(func() WebhookClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(WebhookClient)
		}
	}

	return r0
}

// MockWebhookRepository_WebhookClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WebhookClient'
type MockWebhookRepository_WebhookClient_Call struct {
	*mock.Call
}

// WebhookClient is a helper method to define mock.On call
func (_e *MockWebhookRepository_Expecter) WebhookClient() *MockWebhookRepository_WebhookClient_Call {
	return &MockWebhookRepository_WebhookClient_Call{Call: _e.mock.On("WebhookClient")}
}

func (_c *MockWebhookRepository_WebhookClient_Call) Run(run func()) *MockWebhookRepository_WebhookClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebhookRepository_WebhookClient_Call) Return(_a0 WebhookClient) *MockWebhookRepository_WebhookClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookRepository_WebhookClient_Call) RunAndReturn(run func() WebhookClient) *MockWebhookRepository_WebhookClient_Call {
	_c.Call.Return(run)
	return _c
}

// WebhookURL provides a mock function with no fields
func (_m *MockWebhookRepository) WebhookURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WebhookURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockWebhookRepository_WebhookURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WebhookURL'
type MockWebhookRepository_WebhookURL_Call struct {
	*mock.Call
}

// WebhookURL is a helper method to define mock.On call
func (_e *MockWebhookRepository_Expecter) WebhookURL() *MockWebhookRepository_WebhookURL_Call {
	return &MockWebhookRepository_WebhookURL_Call{Call: _e.mock.On("WebhookURL")}
}

func (_c *MockWebhookRepository_WebhookURL_Call) Run(run func()) *MockWebhookRepository_WebhookURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebhookRepository_WebhookURL_Call) Return(_a0 string) *MockWebhookRepository_WebhookURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookRepository_WebhookURL_Call) RunAndReturn(run func() string) *MockWebhookRepository_WebhookURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebhookRepository creates a new instance of MockWebhookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebhookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebhookRepository {
	mock := &MockWebhookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
