import { css, keyframes } from '@emotion/css';

import { type GrafanaTheme2 } from '@grafana/data';

const surfaceEnter = keyframes({
  from: { opacity: 0, transform: 'translateY(-2px) scale(0.98)' },
  to: { opacity: 1, transform: 'translateY(0) scale(1)' },
});

const groupEnter = keyframes({
  from: { opacity: 0, transform: 'translateY(-4px) scale(0.98)' },
  to: { opacity: 1, transform: 'translateY(0) scale(1)' },
});

const statusPulse = keyframes({
  '0%, 100%': { opacity: 0.55 },
  '50%': { opacity: 1 },
});

const contextSweep = keyframes({
  from: { backgroundPosition: '100% 0' },
  to: { backgroundPosition: '-100% 0' },
});

export function getQueryCoauthoringStyles(theme: GrafanaTheme2) {
  const compactButton = {
    height: theme.spacing(3),
    minHeight: theme.spacing(3),
    paddingInline: theme.spacing(1),
  };

  return {
    container: css({
      boxSizing: 'border-box',
      display: 'flex',
      flexDirection: 'column',
      gap: theme.spacing(1),
      width: `min(${theme.spacing(52.875)}, calc(100vw - ${theme.spacing(2)}))`,
      minHeight: 0,
      padding: theme.spacing(0.5),
      color: theme.colors.text.primary,
      background: theme.colors.background.elevated,
      border: `1px solid ${theme.colors.border.weak}`,
      borderRadius: theme.shape.radius.default,
      boxShadow: theme.shadows.z2,
      overflow: 'hidden',
      transformOrigin: 'top center',
      [theme.transitions.handleMotion('no-preference')]: {
        animation: `${surfaceEnter} 140ms ${theme.transitions.easing.easeOut}`,
        transition: theme.transitions.create('max-height', {
          duration: theme.transitions.duration.short,
          easing: theme.transitions.easing.easeOut,
        }),
      },
    }),
    hidden: css({ display: 'none' }),
    proposalGroup: css({
      position: 'relative',
      zIndex: theme.zIndex.dropdown,
      background: 'transparent',
      borderColor: 'transparent',
      boxShadow: 'none',
      paddingTop: theme.spacing(2),
      overflow: 'visible',
      '&:hover': { background: theme.colors.background.secondary },
      '&:hover [data-proposal-drag-handle]': { opacity: 1 },
      [theme.transitions.handleMotion('no-preference')]: {
        animation: `${groupEnter} 140ms ${theme.transitions.easing.easeOut}`,
      },
    }),
    dragHandle: css({
      position: 'absolute',
      top: 0,
      left: '50%',
      transform: 'translateX(-50%)',
      height: theme.spacing(2),
      cursor: 'grab',
      opacity: 0,
    }),
    resizeHandle: css({
      position: 'absolute',
      top: 0,
      bottom: 0,
      width: 8,
      cursor: 'ew-resize',
      zIndex: 1,
      '&:hover': { background: theme.colors.action.hover },
    }),
    resizeLeft: css({ left: 0 }),
    resizeRight: css({ right: 0 }),
    resizeActive: css({ background: theme.colors.action.hover }),
    explanationCard: css({
      display: 'flex',
      flexDirection: 'column',
      minHeight: 0,
      background: theme.colors.background.elevated,
      border: `1px solid ${theme.colors.border.weak}`,
      borderRadius: theme.shape.radius.default,
      boxShadow: theme.shadows.z2,
      overflow: 'hidden',
    }),
    narrowExplanationCard: css({ padding: theme.spacing(1.5) }),
    tinyExplanationCard: css({ padding: theme.spacing(0.5) }),
    actionsCard: css({ border: `1px solid ${theme.colors.border.weak}`, boxShadow: theme.shadows.z2 }),
    tinyActionsCard: css({
      alignSelf: 'flex-end',
      width: 'fit-content',
      minHeight: 0,
      padding: theme.spacing(0.5, 1.5),
    }),
    tinyActionsRow: css({ gap: theme.spacing(1.5) }),
    tinyIconAction: css({
      width: theme.spacing(3.5),
      height: theme.spacing(3.5),
      gap: 0,
      padding: theme.spacing(0.75),
    }),
    dimmed: css({ opacity: 0.04, [theme.transitions.handleMotion('no-preference')]: { animation: 'none' } }),
    frozenGroup: css({ [theme.transitions.handleMotion('no-preference')]: { animation: 'none' } }),
    header: css({
      display: 'flex',
      flex: '0 0 auto',
      alignItems: 'flex-start',
      gap: theme.spacing(1),
      minHeight: 0,
      minWidth: 0,
      padding: theme.spacing(1),
    }),
    headerContent: css({
      display: 'flex',
      flex: '1 1 auto',
      alignItems: 'center',
      gap: theme.spacing(1),
      minWidth: 0,
    }),
    headerCopy: css({
      display: 'flex',
      flex: '1 1 auto',
      flexDirection: 'column',
      minWidth: 0,
    }),
    close: css({ flex: '0 0 auto' }),
    pulsingStatus: css({
      [theme.transitions.handleMotion('no-preference')]: {
        animation: `${statusPulse} 900ms ease-in-out infinite`,
      },
    }),
    promptRow: css({
      display: 'grid',
      flex: '0 0 auto',
      gridTemplateColumns: 'minmax(0, 1fr) auto',
      alignItems: 'center',
      gap: theme.spacing(0.5),
      minHeight: theme.spacing(7),
      padding: theme.spacing(1.5),
      background: theme.colors.background.primary,
      borderRadius: theme.shape.radius.default,
    }),
    promptInput: css({
      height: theme.spacing(4),
      minHeight: theme.spacing(4),
      paddingInline: theme.spacing(1),
      background: 'transparent',
      border: 0,
      boxShadow: 'none',
      resize: 'none',
      '&:focus': { boxShadow: 'none' },
    }),
    promptSubmit: css({
      width: theme.spacing(3.5),
      height: theme.spacing(3.5),
      margin: 0,
      padding: theme.spacing(0.75),
    }),
    mentionMenu: css({
      display: 'flex',
      flexDirection: 'column',
      minWidth: theme.spacing(28),
      maxWidth: 'calc(100vw - 16px)',
      padding: theme.spacing(0.5),
      color: theme.colors.text.primary,
      background: theme.colors.background.elevated,
      border: `1px solid ${theme.colors.border.weak}`,
      borderRadius: theme.shape.radius.default,
      boxShadow: theme.shadows.z2,
      zIndex: theme.zIndex.typeahead,
    }),
    mentionOption: css({
      display: 'flex',
      alignItems: 'center',
      gap: theme.spacing(1),
      padding: theme.spacing(0.75, 1),
      color: theme.colors.text.primary,
      background: 'transparent',
      border: 0,
      borderRadius: theme.shape.radius.default,
      textAlign: 'left',
      overflowWrap: 'anywhere',
      '&:hover': { background: theme.colors.action.hover },
    }),
    mentionSelected: css({ background: theme.colors.action.selected }),
    clarificationAction: css({
      display: 'flex',
      flex: '0 0 auto',
      justifyContent: 'flex-end',
      paddingInline: theme.spacing(1),
    }),
    quickActions: css({
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'flex-start',
      gap: theme.spacing(0.5),
      padding: theme.spacing(0, 1, 0.5),
      button: { maxWidth: '100%', whiteSpace: 'normal', height: 'auto', textAlign: 'left' },
    }),
    status: css({
      display: 'flex',
      alignItems: 'center',
      gap: theme.spacing(1),
      minWidth: 0,
    }),
    body: css({
      display: 'flex',
      flex: '1 1 auto',
      flexDirection: 'column',
      gap: theme.spacing(0.5),
      minHeight: 0,
      padding: theme.spacing(0, 1.5, 1),
      overflowY: 'auto',
      scrollbarGutter: 'stable',
    }),
    scrollBody: css({
      display: 'flex',
      flex: '1 1 auto',
      flexDirection: 'column',
      gap: theme.spacing(1),
      minHeight: 0,
      overflowY: 'auto',
      scrollbarGutter: 'stable',
    }),
    contextError: css({
      background: theme.colors.background.primary,
      borderRadius: theme.shape.radius.default,
    }),
    workingStatus: css({ display: 'flex', flexDirection: 'column', gap: theme.spacing(1), minWidth: 0 }),
    workingChips: css({ display: 'flex', alignItems: 'center', gap: theme.spacing(0.5), minWidth: 0 }),
    workingChip: css({
      display: 'flex',
      alignItems: 'center',
      gap: theme.spacing(0.5),
      minWidth: 0,
      padding: theme.spacing(0.5, 0.75),
      background: theme.colors.background.secondary,
      border: `1px solid ${theme.colors.border.weak}`,
      borderRadius: theme.shape.radius.default,
      code: {
        minWidth: 0,
        overflow: 'hidden',
        color: theme.colors.text.secondary,
        fontFamily: theme.typography.fontFamilyMonospace,
        fontSize: theme.typography.bodySmall.fontSize,
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
      },
    }),
    workingSweep: css({
      flex: '0 0 auto',
      width: theme.spacing(2),
      height: 2,
      background: `linear-gradient(90deg, transparent, ${theme.colors.text.secondary}, transparent)`,
      backgroundSize: '200% 100%',
      [theme.transitions.handleMotion('no-preference')]: { animation: `${contextSweep} 1400ms ease-in-out infinite` },
    }),
    optionTabs: css({
      display: 'flex',
      flex: '0 0 auto',
      alignItems: 'center',
      gap: theme.spacing(0.5),
      padding: theme.spacing(0.5, 1),
      overflowX: 'auto',
    }),
    narrowOptionTabs: css({ padding: 0 }),
    tinyOptionTabs: css({ justifyContent: 'center', gap: theme.spacing(1), padding: theme.spacing(1) }),
    compactOptionPill: css({
      height: theme.spacing(3),
      minHeight: theme.spacing(3),
      borderRadius: theme.spacing(2),
      padding: theme.spacing(0.125, 0.75),
      fontSize: theme.typography.bodySmall.fontSize,
      background: theme.colors.action.disabledBackground,
      borderColor: theme.colors.secondary.border,
      color: theme.colors.text.secondary,
      '&[aria-selected="true"]': {
        background: theme.colors.info.transparent,
        borderColor: theme.colors.info.border,
        color: theme.colors.info.text,
      },
    }),
    compactPreviewResult: css({
      display: 'flex',
      alignItems: 'center',
      gap: theme.spacing(0.5),
      whiteSpace: 'nowrap',
      '&[data-kind="error"]': { color: theme.colors.error.text },
      '&[data-kind="no-data"]': { color: theme.colors.warning.text },
      svg: { flexShrink: 0 },
      span: { overflow: 'hidden', textOverflow: 'ellipsis' },
    }),
    unconfirmedValue: css({ display: 'flex', alignItems: 'baseline', gap: theme.spacing(0.5) }),
    inlineDiff: css({
      flex: '0 0 auto',
      margin: 0,
      padding: theme.spacing(1),
      borderRadius: theme.shape.radius.default,
      background: theme.colors.background.primary,
      whiteSpace: 'pre-wrap',
      overflowWrap: 'anywhere',
      fontFamily: theme.typography.fontFamilyMonospace,
    }),
    diffRemoved: css({ background: theme.colors.error.transparent, color: theme.colors.error.text }),
    diffAdded: css({ background: theme.colors.success.transparent, color: theme.colors.success.text }),
    outsideFocus: css({ borderBottom: '2px dashed ' + theme.colors.warning.border }),
    proposal: css({
      display: 'flex',
      flexDirection: 'column',
      gap: theme.spacing(1),
      minHeight: 0,
      overflow: 'hidden',
    }),
    proposalBody: css({
      display: 'flex',
      flex: '0 0 auto',
      flexDirection: 'column',
      gap: theme.spacing(0.5),
      minHeight: 0,
      padding: theme.spacing(0, 1.5, 1),
    }),
    compactProposalBody: css({ padding: 0, paddingTop: theme.spacing(1.5) }),
    footer: css({
      display: 'flex',
      flex: '0 0 auto',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: theme.spacing(1),
      minHeight: theme.spacing(6.5),
      padding: theme.spacing(1.5),
      background: theme.colors.background.primary,
      borderRadius: theme.shape.radius.default,
    }),
    footerActions: css({
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: theme.spacing(0.5),
      minWidth: 0,
    }),
    compactButton: css(compactButton),
    iteration: css({
      display: 'flex',
      flexDirection: 'column',
      gap: theme.spacing(1),
      paddingTop: theme.spacing(1),
    }),
    iterationCopy: css({ padding: theme.spacing(1, 1.5) }),
    handoff: css({
      display: 'flex',
      flexDirection: 'column',
      gap: theme.spacing(2),
      padding: theme.spacing(1, 1.5, 0),
    }),
  };
}
