//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v0alpha1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// schema is unexported to prevent accidental overwrites
var (
	schemaClusterRole = resource.NewSimpleSchema("authz.grafana.app", "v0alpha1", &ClusterRole{}, &ClusterRoleList{}, resource.WithKind("ClusterRole"),
		resource.WithPlural("clusterroles"), resource.WithScope(resource.NamespacedScope))
	kindClusterRole = resource.Kind{
		Schema: schemaClusterRole,
		Codecs: map[resource.KindEncoding]resource.Codec{
			resource.KindEncodingJSON: &ClusterRoleJSONCodec{},
		},
	}
)

// Kind returns a resource.Kind for this Schema with a JSON codec
func ClusterRoleKind() resource.Kind {
	return kindClusterRole
}

// Schema returns a resource.SimpleSchema representation of ClusterRole
func ClusterRoleSchema() *resource.SimpleSchema {
	return schemaClusterRole
}

// Interface compliance checks
var _ resource.Schema = kindClusterRole
