name: Build and sign docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_version_number:
    name: Generate image version
    runs-on: ubuntu-latest
    outputs:
      image_version: ${{ steps.build_version.outputs.image_version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build version string
        id: build_version
        run: |
          tag_number=$(node -p "require('./package.json').version")
          
          short_hash=$(git rev-parse --short ${{ github.sha }})
          branch_name="${GITHUB_REF#refs/heads/}"
          
          if [ "$branch_name" = "main" ]; then
            image_version="$tag_number-ni"
          else
            sanitized_branch=$(echo "$branch_name" | sed 's/[/_]/-/g' | cut -c1-20)
            image_version="$tag_number-$short_hash-$sanitized_branch-ni"
          fi
          
          echo "::set-output name=image_version::$(echo $image_version)"

  determine_registry:
    name: Determine target registry and environment
    runs-on: ubuntu-latest
    outputs:
      registry_path: ${{ steps.set_config.outputs.registry_path }}
      environment: ${{ steps.set_config.outputs.environment }}
    steps:
      - name: Set configuration based on trigger
        id: set_config
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            environment="jfrog-ci"
            registry_path="niartifacts.jfrog.io/rnd-docker-ci/ni/systemlink/ni-grafana"
          else
            environment="jfrog-pre"
            registry_path="niartifacts.jfrog.io/rnd-docker-pre/ni/systemlink/ni-grafana"
          fi
          
          echo "::set-output name=environment::$environment"
          echo "::set-output name=registry_path::$registry_path"

  build_docker_image:
    name: Build Docker Image
    needs: [generate_version_number, determine_registry]
    runs-on: ubuntu-latest
    environment: ${{ needs.determine_registry.outputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: niartifacts.jfrog.io
          username: ${{ vars.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_ACCESS_TOKEN }}
      - name: Docker build and push (with latest)
        if: needs.determine_registry.outputs.environment == 'jfrog-ci'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ needs.determine_registry.outputs.registry_path }}:latest
            ${{ needs.determine_registry.outputs.registry_path }}:${{ needs.generate_version_number.outputs.image_version }}
      - name: Docker build and push (version only)
        if: needs.determine_registry.outputs.environment == 'jfrog-pre'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ needs.determine_registry.outputs.registry_path }}:${{ needs.generate_version_number.outputs.image_version }}
  
  sign_docker_image:
    name: Sign Docker Image
    needs: [generate_version_number, determine_registry, build_docker_image]
    runs-on: ubuntu-latest
    environment: ${{ needs.determine_registry.outputs.environment }}
    steps:
      - name: Log into registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ vars.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_ACCESS_TOKEN }}
          registry: niartifacts.jfrog.io
      - name: Create signature staging directory
        run: mkdir ${{ runner.temp }}/sigstore
      - name: Create gnupghome directory
        run: mkdir ${{ runner.temp }}/gpg && chmod 700 ${{ runner.temp }}/gpg
      - name: Import private key
        run: echo "${{ secrets.NI_PGP_RELEASE_SECRING }}" | base64 --decode | gpg --import
        env:
          GNUPGHOME: ${{ runner.temp }}/gpg
      - name: Sign image
        run: podman image sign --sign-by security@ni.com -d ${{ runner.temp }}/sigstore docker://${{ needs.determine_registry.outputs.registry_path }}:${{ needs.generate_version_number.outputs.image_version }}
        env:
          GNUPGHOME: ${{ runner.temp }}/gpg
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_VERIFY_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_VERIFY_DEV }}
          aws-region: us-east-1
      - name: Sync signatures to S3
        run: aws s3 sync ${{ runner.temp }}/sigstore s3://signing-web-demo-bucket-1neyh347t53dt
