# This workflow builds the Go binaries for the different architectures and operating systems to ensure that
# incoming pull requests are able to be compiled for all supported architectures and operating systems.
name: Build Go (matrix)

on:
  pull_request:
  push:
    branches:
      - main
      - release-*.*.*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  contents: read

jobs:
  build-go:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux/amd64
            goos: linux
            goarch: amd64
          - name: linux/arm64
            goos: linux
            goarch: arm64
          - name: linux/s390x
            goos: linux
            goarch: s390x
          - name: linux/armv6
            goos: linux
            goarch: arm
            goarm: "6"
          - name: linux/armv7
            goos: linux
            goarch: arm
            goarm: "7"
          - name: darwin/arm64
            goos: darwin
            goarch: arm64
          - name: darwin/amd64
            goos: darwin
            goarch: amd64
          - name: windows/arm64
            goos: windows
            goarch: arm64
          - name: windows/armv7
            goos: windows
            goarch: arm
            goarm: "7"
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - name: Build Go (${{ matrix.name }})
        env:
          CGO_ENABLED: "0"
          GO_BUILD_OS: ${{ matrix.goos }}
          GO_BUILD_ARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
        run: make build-go
