name: Clean up orphaned branches
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"



# Prevent concurrent runs of the same workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  cleanup-branches:
    timeout-minutes: 15
    runs-on: ubuntu-arm64-small
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v5
      - uses: grafana/shared-workflows/actions/cleanup-branches@cleanup-branches/v0.2.1
        with:
          dry-run: false
          max-date: "1 month ago"
