# Owned by grafana-backend-services-squad
# Intended to be dropped into the base repo (Ex: grafana/grafana) for use in the security mirror.
name: Create security patch
run-name: create-security-patch
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "main"
      - "v*.*.*"
      - "release-*.*.*"

# This is run before the pull request has been merged, so we'll run against the src branch
jobs:
  trigger_downstream_create_security_patch:
    concurrency: create-patch-${{ github.ref_name }}
    uses: grafana/security-patch-actions/.github/workflows/create-patch.yml@main # zizmor: ignore[unpinned-uses]
    if: github.repository == 'grafana/grafana-security-mirror'
    with:
      repo: "${{ github.repository }}"
      src_ref: "${{ github.head_ref }}" # this is the source branch name, Ex: "feature/newthing"
      patch_ref: "${{ github.base_ref }}" # this is the target branch name, Ex: "main"
      patch_repo: "grafana/grafana-security-patches"
      patch_prefix: "${{ github.event.pull_request.number }}"
      sender: "${{ github.event.pull_request.user.login }}"
      comment: "Closes: ${{ github.repository }}#${{ github.event.pull_request.number }}"
    secrets: inherit # zizmor: ignore[secrets-inherit]

  # Policy-Bot gets confused when no job is ever scheduled.
  # Because ubuntu-latest is free for open-source repos, and this is still faster than any test suite, we'll just add an
  #   always OK check to this workflow. Other workflows aren't affected, because they're run on the OSS repo.
  always_ok:
    name: No security patch
    # Inverse of trigger_downstream_create_security_patch
    if: github.repository != 'grafana/grafana-security-mirror'
    runs-on: ubuntu-latest
    # We need no permissions.
    permissions: {}
    steps:
      - name: No patch detected
        run: echo This is an OSS repository PR, and as such, no patch will be created.
