name: Feature toggles CI

on:
  workflow_call:
    inputs:
      backend:
        description: Whether backend code changed.
        required: true
        type: string
      docs:
        description: Whether docs changed.
        required: true
        type: string

permissions: {}

jobs:

  test:
    if: inputs.backend == 'true' || inputs.docs == 'true'

    name: Feature toggles documentation is in sync with source

    runs-on: ubuntu-x64

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Go
        uses: ./.github/actions/setup-go
        with:
          remote-cache: 'true'

      - name: Run feature toggle tests
        run: go test -v -run TestFeatureToggleFiles ./pkg/services/featuremgmt/
