name: Crowdin automatic task management

on:
  workflow_dispatch:
  # once a month on the first day of the month at midnight
  schedule:
    - cron: "0 0 1 * *"

jobs:
  create-tasks-in-crowdin:
    runs-on: ubuntu-x64
    permissions:
      contents: read
      id-token: write
    steps:
      - name: 'Get vault secrets'
        id: vault-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
            # Vault secret paths:
            # - ci/repo/grafana/grafana/grafana-frontend-crowdin-token
            repo_secrets: |
                CROWDIN_TOKEN=grafana-frontend-crowdin-token:access_token
      - name: Create tasks in Crowdin
        uses: grafana/grafana-github-actions/crowdin-create-tasks@main
        with:
          crowdin_token: ${{ env.CROWDIN_TOKEN }}
          crowdin_project_id: 5
