name: Crowdin Download Action

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  download-sources-from-crowdin:
    if: github.repository == 'grafana/grafana'
    runs-on: ubuntu-x64
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Get GitHub App token
        id: get-github-app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@259ba21cb3ff07724f331e26d926d655d24b317b # create-github-app-token/v0.2.3
        with:
          github_app: grafana-pr-automation
      - name: Get GitHub App token
        id: get-github-approver-token
        uses: grafana/shared-workflows/actions/create-github-app-token@259ba21cb3ff07724f331e26d926d655d24b317b # create-github-app-token/v0.2.3
        with:
          github_app: grafana-pr-approver
      - name: 'Get vault secrets'
        id: vault-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
            # Vault secret paths:
            # - ci/repo/grafana/grafana/grafana-frontend-crowdin-token
            repo_secrets: |
                CROWDIN_TOKEN=grafana-frontend-crowdin-token:access_token
      - name: Download from Crowdin
        uses: grafana/grafana-github-actions/crowdin-download@main
        with:
          crowdin_token: ${{ fromJSON(steps.vault-secrets.outputs.secrets).CROWDIN_TOKEN }}
          crowdin_project_id: 5
          pr_labels: 'area/frontend, area/internationalization, no-changelog, no-backport'
          github_board_id: 78 # Frontend Platform project
          en_paths: public/locales/en-US/grafana.json, public/app/plugins/datasource/azuremonitor/locales/en-US/grafana-azure-monitor-datasource.json, public/app/plugins/datasource/mssql/locales/en-US/mssql.json, packages/grafana-sql/src/locales/en-US/grafana-sql.json
          github_repo_token: ${{ steps.get-github-app-token.outputs.token }}
          github_pr_approver_token: ${{ steps.get-github-approver-token.outputs.token }}
