name: Crowdin Upload Action

on:
  workflow_dispatch:
  push:
    paths:
      - 'public/locales/en-US/grafana.json'
      - 'public/app/plugins/datasource/azuremonitor/locales/en-US/grafana-azure-monitor-datasource.json'
      - 'public/app/plugins/datasource/mssql/locales/en-US/mssql.json'
      - 'packages/grafana-sql/src/locales/en-US/grafana-sql.json'
    branches:
      - main



# Prevent concurrent runs of the same workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  upload-sources-to-crowdin:
    timeout-minutes: 15
    if: github.repository == 'grafana/grafana'
    runs-on: ubuntu-x64
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: 'Get vault secrets'
        id: vault-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
            # Vault secret paths:
            # - ci/repo/grafana/grafana/grafana-frontend-crowdin-token
            repo_secrets: |
                CROWDIN_TOKEN=grafana-frontend-crowdin-token:access_token
      - name: Upload to Crowdin
        uses: grafana/grafana-github-actions/crowdin-upload@main
        with:
          crowdin_token: ${{ fromJSON(steps.vault-secrets.outputs.secrets).CROWDIN_TOKEN }}
          crowdin_project_id: 5

