name: Verify i18n

permissions:
  contents: read

on:
  pull_request:
    paths:
      - 'public/**/*.tsx'
      - 'public/**/*.ts'
      - 'packages/**/*.tsx'
      - 'packages/**/*.ts'
      - '**/locales/**'
      - '**/i18next.config.ts'
      - '.nvmrc'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/i18n-verify.yml'
  push:
    branches:
      - main
      - release-*.*.*
    paths:
      - 'public/**/*.tsx'
      - 'public/**/*.ts'
      - 'packages/**/*.tsx'
      - 'packages/**/*.ts'
      - '**/locales/**'
      - '**/i18next.config.ts'
      - '.nvmrc'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/i18n-verify.yml'

jobs:
  verify-i18n:
    # Run on `grafana/grafana` main branch, or on pull requests to prevent double-running on mirrors
    if: (github.event_name == 'pull_request' || (github.event_name == 'push' && github.repository == 'grafana/grafana'))
    uses: grafana/grafana-github-actions/.github/workflows/verify-i18n.yml@main
