name: Meticulous
on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

permissions:
  actions: write
  contents: read
  issues: write
  pull-requests: write
  statuses: read

jobs:
  test:
    name: Meticulous
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Grafana Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.meticulous
          platforms: linux/amd64
          tags: grafana:${{ github.sha }}
          push: false
          load: true

      - name: Run Meticulous tests
        uses: alwaysmeticulous/report-diffs-action/upload-container@v1
        with:
          api-token: ${{ secrets.METICULOUS_API_TOKEN }}
          image-tag: grafana:${{ github.sha }}
          container-port: 3000
