name: PR Checks
on:
  pull_request:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled
      - unlabeled
      - edited
      - auto_merge_enabled
  issues:
    types:
      - milestoned
      - demilestoned

concurrency:
  group: pr-checks-${{ github.event.number }}

permissions:
  statuses: write
  checks: write
  actions: write
  contents: read
  pull-requests: read

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Run PR Checks
        uses: grafana/grafana-github-actions/pr-checks@jh/pr-checks-refactor
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          configPath: pr-checks
