name: PR automation
on:
  pull_request_target:  # zizmor: ignore[dangerous-triggers] action uses GITHUB_TOKEN only, does not check out fork code
    types:
      - labeled
      - opened
      - synchronize

concurrency:
  group: pr-commands-${{ github.event.number }}

permissions: {}

jobs:
  main:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-arm64-small
    steps:
      - name: Run PR Commands
        uses: grafana/grafana-github-actions/commands@3c62d35c5a66e730186a338e45aeb8fa784e2d56 # main
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          configPath: pr-commands
