name: PR automation
on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize

concurrency:
  group: pr-commands-${{ github.event.number }}

permissions: {}

jobs:
  main:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Run PR Commands
        uses: grafana/grafana-github-actions/commands@main
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          configPath: pr-commands
