name: Test Dockerfile

on:
  pull_request:
    paths:
      - Makefile
      - Dockerfile
      - public/**
      - packages/**
      - apps/**
      - '**/go.mod'
      - '**/go.sum'
      - '**/go.work'
      - '**/go.work.sum'
      - '**/package.json'
      - '**/nx.json'
      - '**/project.json'
      - '**/yarn.lock'
      - conf/**
      - .yarnrc.yml
      - .yarn/**
      - tsconfig.json
      - '**.js'
      # We only want the top directory here.
      - '*.ts'
      # But this one we want all
      - '**.config.ts'
      - scripts/**
      - emails/**
      - .citools/**
      - kinds/**
      - kindsv2/**
      - embed.go
      - packaging/docker/**
      - .github/workflows/pr-test-docker.yml

jobs:
  build-dockerfile:
    runs-on: ubuntu-x64-large-io
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: docker/setup-docker-action@b2189fbf2a6592b51fee7cdd93ee2bfaeba733db # v4
      - name: Build Dockerfile
        run: make build-docker-full
