name: Run dashboard schema v2 e2e

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  dashboard-schema-v2-e2e:
    runs-on: ubuntu-x64-large
    continue-on-error: true
    if: github.event.pull_request.draft == false
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Go
        uses: ./.github/actions/setup-go
      - run: go version
      - name: Setup Node
        uses: ./.github/actions/setup-node
      - name: Install yarn dependencies
        uses: ./.github/actions/yarn-install
      - name: Install Playwright browsers
        run: yarn playwright install --with-deps chromium
      - name: Build Grafana backend
        run: make build-go
      - name: Build Grafana frontend
        env:
          NO_SOURCEMAP: '1' # Don't generate sourcemaps for CI builds to speed up webpack + packaging
        run: make build-js
      - name: Run dashboard scenes e2e
        run: yarn e2e:schema-v2 || echo "Test failed but marking as success since schema V2 is behind a feature flag and should not block PRs"

      - name: Always succeed # This is a workaround to make the job pass even if the previous step fails
        if: failure()
        run: exit 0
