name: Update Schema Types

on:
  push:
    branches:
      - main
    paths:
      - docs/sources/developers/plugins/plugin.schema.json
  workflow_dispatch:

permissions: {}

jobs:
  bundle-schema-types:
    runs-on: ubuntu-arm64-small
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Install yarn dependencies
        uses: ./.github/actions/yarn-install

      - uses: ./.github/actions/bundle-schema-types
