// Code generated by mockery v2.53.4. DO NOT EDIT.

package controller

import (
	context "context"

	v0alpha1 "github.com/grafana/grafana/apps/provisioning/pkg/apis/provisioning/v0alpha1"
	mock "github.com/stretchr/testify/mock"
)

// MockConnectionHealthChecker is an autogenerated mock type for the ConnectionHealthCheckerInterface type
type MockConnectionHealthChecker struct {
	mock.Mock
}

type MockConnectionHealthChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionHealthChecker) EXPECT() *MockConnectionHealthChecker_Expecter {
	return &MockConnectionHealthChecker_Expecter{mock: &_m.Mock}
}

// RefreshHealthWithPatchOps provides a mock function with given fields: ctx, conn
func (_m *MockConnectionHealthChecker) RefreshHealthWithPatchOps(ctx context.Context, conn *v0alpha1.Connection) (*v0alpha1.TestResults, v0alpha1.HealthStatus, []map[string]interface{}, error) {
	ret := _m.Called(ctx, conn)

	if len(ret) == 0 {
		panic("no return value specified for RefreshHealthWithPatchOps")
	}

	var r0 *v0alpha1.TestResults
	var r1 v0alpha1.HealthStatus
	var r2 []map[string]interface{}
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, *v0alpha1.Connection) (*v0alpha1.TestResults, v0alpha1.HealthStatus, []map[string]interface{}, error)); ok {
		return rf(ctx, conn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v0alpha1.Connection) *v0alpha1.TestResults); ok {
		r0 = rf(ctx, conn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v0alpha1.TestResults)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v0alpha1.Connection) v0alpha1.HealthStatus); ok {
		r1 = rf(ctx, conn)
	} else {
		r1 = ret.Get(1).(v0alpha1.HealthStatus)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *v0alpha1.Connection) []map[string]interface{}); ok {
		r2 = rf(ctx, conn)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, *v0alpha1.Connection) error); ok {
		r3 = rf(ctx, conn)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockConnectionHealthChecker_RefreshHealthWithPatchOps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshHealthWithPatchOps'
type MockConnectionHealthChecker_RefreshHealthWithPatchOps_Call struct {
	*mock.Call
}

// RefreshHealthWithPatchOps is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *v0alpha1.Connection
func (_e *MockConnectionHealthChecker_Expecter) RefreshHealthWithPatchOps(ctx interface{}, conn interface{}) *MockConnectionHealthChecker_RefreshHealthWithPatchOps_Call {
	return &MockConnectionHealthChecker_RefreshHealthWithPatchOps_Call{Call: _e.mock.On("RefreshHealthWithPatchOps", ctx, conn)}
}

func (_c *MockConnectionHealthChecker_RefreshHealthWithPatchOps_Call) Run(run func(ctx context.Context, conn *v0alpha1.Connection)) *MockConnectionHealthChecker_RefreshHealthWithPatchOps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v0alpha1.Connection))
	})
	return _c
}

func (_c *MockConnectionHealthChecker_RefreshHealthWithPatchOps_Call) Return(_a0 *v0alpha1.TestResults, _a1 v0alpha1.HealthStatus, _a2 []map[string]interface{}, _a3 error) *MockConnectionHealthChecker_RefreshHealthWithPatchOps_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockConnectionHealthChecker_RefreshHealthWithPatchOps_Call) RunAndReturn(run func(context.Context, *v0alpha1.Connection) (*v0alpha1.TestResults, v0alpha1.HealthStatus, []map[string]interface{}, error)) *MockConnectionHealthChecker_RefreshHealthWithPatchOps_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldCheckHealth provides a mock function with given fields: conn
func (_m *MockConnectionHealthChecker) ShouldCheckHealth(conn *v0alpha1.Connection) bool {
	ret := _m.Called(conn)

	if len(ret) == 0 {
		panic("no return value specified for ShouldCheckHealth")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*v0alpha1.Connection) bool); ok {
		r0 = rf(conn)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockConnectionHealthChecker_ShouldCheckHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldCheckHealth'
type MockConnectionHealthChecker_ShouldCheckHealth_Call struct {
	*mock.Call
}

// ShouldCheckHealth is a helper method to define mock.On call
//   - conn *v0alpha1.Connection
func (_e *MockConnectionHealthChecker_Expecter) ShouldCheckHealth(conn interface{}) *MockConnectionHealthChecker_ShouldCheckHealth_Call {
	return &MockConnectionHealthChecker_ShouldCheckHealth_Call{Call: _e.mock.On("ShouldCheckHealth", conn)}
}

func (_c *MockConnectionHealthChecker_ShouldCheckHealth_Call) Run(run func(conn *v0alpha1.Connection)) *MockConnectionHealthChecker_ShouldCheckHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v0alpha1.Connection))
	})
	return _c
}

func (_c *MockConnectionHealthChecker_ShouldCheckHealth_Call) Return(_a0 bool) *MockConnectionHealthChecker_ShouldCheckHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnectionHealthChecker_ShouldCheckHealth_Call) RunAndReturn(run func(*v0alpha1.Connection) bool) *MockConnectionHealthChecker_ShouldCheckHealth_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnectionHealthChecker creates a new instance of MockConnectionHealthChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionHealthChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionHealthChecker {
	mock := &MockConnectionHealthChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
