// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     public/app/plugins/gen.go
// Using jennies:
//     TSTypesJenny
//     PluginTsTypesJenny
//
// Run 'make gen-cue' from repository root to regenerate.

import * as common from '@grafana/schema';

export interface Options {
  dedupStrategy: common.LogsDedupStrategy;
  enableInfiniteScrolling?: boolean;
  enableLogDetails: boolean;
  grammar?: unknown;
  onLogOptionsChange?: unknown;
  onNewLogsReceived?: unknown;
  showControls: boolean;
  showTime: boolean;
  sortOrder: common.LogsSortOrder;
  syntaxHighlighting: boolean;
  wrapLogMessage: boolean;
}
